// Tokenised chapters of 七階のペットシッター. Prose-first draft and scene map:
// ../nanakai-no-petto-shittaa-draft.md. Each chapter is a list of paragraphs;
// each paragraph a list of [tokens, English] pairs.

export const CHAPTERS = [
  // 1. 夏休みの約束
  [
    [
      ['夏[なつ]休[やす]み|の|最[さい]初[しょ]|の|日[ひ]|、|はやと|は|朝[あさ]|から|犬[いぬ]|の|本[ほん]|を|読[よ]んでいた|。', 'On the first day of the summer holidays, Hayato had been reading a book about dogs since breakfast.'],
      ['はやと|は|八[はっ]歳[さい]|で#and|、|ことね|の|弟[おとうと]|だ|。', 'Hayato is eight, and he is Kotone’s little brother.'],
      ['ことね|は|十[じゅう]二[に]歳[さい]|で#and|、|小[しょう]学[がく]六[ろく]年[ねん]生[せい]|だ|。', 'Kotone is twelve, and in her last year of primary school.'],
      ['二[ふた]人[り]|は|、|大[おお]きな|マンション|の|七[なな]階[かい]|に|住[す]んでいる|。', 'The two of them live on the seventh floor of a big block of flats.'],
    ],
    [
      ['「|お母[かあ]さん|、|犬[いぬ]|が|ほしい|！|」|と|はやと|が|言[い]った|。', '“Mum, I want a dog!” said Hayato.'],
      ['「|小[ちい]さくて|、|かわいい|子[こ]犬[いぬ]|が|いい|」|。', '“A small, cute puppy.”'],
      ['お母[かあ]さん|は|台[だい]所[どころ]|で|お皿[さら]|を|洗[あら]っていた|。', 'Mum was washing the dishes in the kitchen.'],
      ['「|だめ|。|犬[いぬ]|の|世[せ]話[わ]|は|毎[まい]日[にち]|だ|よ|」|。', '“No. A dog needs looking after every single day.”'],
      ['「|去[きょ]年[ねん]|の|金[きん]魚[ぎょ]|は|、|だれ|が|世[せ]話[わ]をした|の#question|」|。', '“Last year’s goldfish — who looked after that?”'],
      ['はやと|は|何[なに]も|言[い]わなかった|。', 'Hayato said nothing.'],
      ['金[きん]魚[ぎょ]|に|えさ|を|あげていた|の#one|は|、|いつも|お母[かあ]さん|だった|。', 'It had always been Mum who fed the goldfish.'],
    ],
    [
      ['ことね|も|、|本[ほん]当[とう]は|犬[いぬ]|が|ほしかった|。', 'The truth was, Kotone wanted a dog too.'],
      ['だから|、|少[すこ]し|考[かんが]えてから|言[い]った|。', 'So she thought for a moment, then said:'],
      ['「|じゃあ|、|夏[なつ]休[やす]み|の|間[あいだ]|、|ほか|の|人[ひと]|の|ペット|の|世[せ]話[わ]|を|する|」|。', '“Then over the summer holidays, we’ll look after other people’s pets.”'],
      ['「|最[さい]後[ご]|の|日[ひ]|まで|、|毎[まい]日[にち]|ちゃんと|やる|」|。', '“Properly, every day, right up to the last day.”'],
      ['「|それ|を|見[み]て|、|もう一[いち]度[ど]|考[かんが]えて|」|。', '“Watch us do it, and then think about it again.”'],
      ['お母[かあ]さん|は|手[て]を止[と]めて|、|二[ふた]人[り]|の|顔[かお]|を|見[み]た|。', 'Mum stopped what she was doing and looked at the two of them.'],
      ['「|いい#ok|よ|。|でも|、|約[やく]束[そく]|が|二[ふた]つ|ある|」|。', '“All right. But there are two rules.”'],
      ['「|お金[かね]|は|もらわない|こと#rule|。|宿[しゅく]題[だい]|も|毎[まい]日[にち]|する|こと#rule|」|。', '“You don’t take any money. And you do your homework every day as well.”'],
      ['「|やった|！|」|と|はやと|が|手[て]|を|上[あ]げた|。', '“Yes!” cried Hayato, throwing his hands in the air.'],
    ],
    [
      ['その|日[ひ]|の|午[ご]後[ご]|、|ことね|は|大[おお]きな|紙[かみ]|に|お知[し]らせ|を|書[か]いた|。', 'That afternoon, Kotone wrote a notice on a big sheet of paper.'],
      ['「|ペット|の|お世[せ]話[わ]|を|します|。|お金[かね]|は|いりません|。|七[なな]階[かい]|の|ことね|と|はやと|」|。', '“We look after pets. No money needed. Kotone and Hayato, seventh floor.”'],
      ['はやと|は|、|その|下[した]|に|犬[いぬ]|と|猫[ねこ]|の|絵[え]|を|かいた|。', 'Underneath, Hayato drew a dog and a cat.'],
      ['二[ふた]人[り]|は|管[かん]理[り]人[にん]さん|に|聞[き]いてから|、|エレベーター|の|横[よこ]|に|紙[かみ]|を|貼[は]った|。', 'After checking with the building manager, they put the paper up beside the lift.'],
    ],
    [
      ['一[いち]日[にち]目[め]|も|、|二[ふつ]日[か]目[め]|も|、|だれ|も|来[こ]なかった|。', 'Nobody came on the first day, or on the second.'],
      ['はやと|は|何[なん]回[かい]も|エレベーター|の|前[まえ]|まで|見[み]に行[い]った|。', 'Hayato went down to check by the lift again and again.'],
      ['三[みっ]日[か]目[め]|の|朝[あさ]|、|「|ピンポーン|」|と|音[おと]がした|。', 'On the morning of the third day, there was a “ding-dong” at the door.'],
      ['ドア|の|前[まえ]|に|は|、|三[さん]階[がい]|の|野[の]村[むら]さん|が|立[た]っていた|。', 'Mrs Nomura from the third floor was standing outside.'],
      ['野[の]村[むら]さん|は|、|小[ちい]さな|鳥[とり]かご|を|持[も]っていた|。', 'She was holding a small birdcage.'],
      ['中[なか]|に|は|、|青[あお]い|インコ|が|いた|。', 'Inside was a blue budgie.'],
      ['「|明[あし]日[た]|から|三[みっ]日[か]間[かん]|、|友[とも]達[だち]|と|温[おん]泉[せん]|に|行[い]く|の#explain|」|。', '“I’m going to a hot spring with my friends for three days, starting tomorrow.”'],
      ['「|この|子[こ]|は|ピーちゃん|。|お世[せ]話[わ]|を|お願[ねが]いできる|かしら|」|。', '“This is Pii-chan. Could I ask you to look after her?”'],
      ['ことね|と|はやと|は|顔[かお]を見[み]合[あ]わせた|。', 'Kotone and Hayato looked at each other.'],
      ['「|はい|！|任[まか]せて|ください|！|」|と|二[ふた]人[り]|は|声[こえ]をそろえた|。', '“Yes! Leave it to us!” they said together.'],
    ],
  ],

  // 2. しゃべるピーちゃん
  [
    [
      ['ピーちゃん|の|鳥[とり]かご|は|、|ことね|の|部[へ]屋[や]|の|机[つくえ]|に|置[お]いた|。', 'They put Pii-chan’s cage on the desk in Kotone’s room.'],
      ['野[の]村[むら]さん|は|、|大[だい]事[じ]な|こと#things|を|紙[かみ]|に|書[か]いてくれた|。', 'Mrs Nomura had written down the important things on a sheet of paper for them.'],
      ['「|朝[あさ]|と|夕[ゆう]方[がた]|に|、|えさ|と|水[みず]|を|替[か]える|」|。', '“Change the food and water morning and evening.”'],
      ['「|ピーちゃん|は|話[はな]す|の#ing|が|大[だい]好[す]き|。|たくさん|話[はな]しかけて|ね|」|。', '“Pii-chan loves to talk. Talk to her lots.”'],
      ['「|外[そと]|に|出[で]た|時[とき]|は|、|えさ|の|箱[はこ]|を|振[ふ]る|こと#rule|」|。', '“If she ever gets out, shake her food box.”'],
      ['「|すぐに|戻[もど]ってくる|から|」|。', '“She’ll come straight back.”'],
    ],
    [
      ['ピーちゃん|は|、|本[ほん]当[とう]に|よく|しゃべった|。', 'Pii-chan really did chatter a lot.'],
      ['「|おはよう|」|や|「|ピーちゃん|、|かわいい|」|と|、|一[いち]日[にち]|に|何[なん]回[かい]も|言[い]った|。', 'She said “Good morning” and “Pii-chan is cute” many times a day.'],
      ['はやと|は|、|ピーちゃん|に|自[じ]分[ぶん]|の|名[な]前[まえ]|を|教[おし]えたかった|。', 'Hayato wanted to teach Pii-chan his name.'],
      ['「|ぼく|は|はやと|。|はやと|だ|よ|」|と|、|はやと|は|何[なん]回[かい]も|言[い]った|。', '“I’m Hayato. Hay-a-to,” he told her, over and over.'],
      ['でも|、|ピーちゃん|は|首[くび]をかしげる|だけ|だった|。', 'But Pii-chan only tilted her head.'],
      ['はやと|は|、|かご|を|指[ゆび]|で|トントン|と|たたいた|。', 'Hayato tapped on the cage with his finger.'],
      ['えさ|も|、|一[いち]度[ど]|に|たくさん|入[い]れすぎた|。', 'He also put far too much food in at once.'],
      ['その|たびに|、|ことね|は|「|はやと|、|だめ|！|」|と|言[い]った|。', 'Each time, Kotone said, “Hayato, no!”'],
    ],
    [
      ['二[ふつ]日[か]目[め]|の|夕[ゆう]方[がた]|、|はやと|は|一[ひと]人[り]|で|水[みず]|を|替[か]えた|。', 'On the evening of the second day, Hayato changed the water on his own.'],
      ['その|時[とき]|、|かご|の|戸[と]|を|少[すこ]し|開[あ]けたままにした|。', 'When he did, he left the cage door a little open.'],
      ['ピーちゃん|は|、|その|すき間[ま]|から|外[そと]|へ|飛[と]び出[だ]した|。', 'Pii-chan shot out through the gap.'],
      ['そして|、|部[へ]屋[や]|の|中[なか]|を|ぐるぐる|飛[と]んで|、|カーテン|の|上[うえ]|に|止[と]まった|。', 'She flew round and round the room and landed on top of the curtain.'],
      ['はやと|は|手[て]|を|伸[の]ばした|。', 'Hayato reached up for her.'],
      ['でも|、|ピーちゃん|は|もっと|高[たか]い|所[ところ]|へ|逃[に]げた|。', 'But Pii-chan fled even higher.'],
      ['「|ことね|！|ピーちゃん|が|！|」|と|はやと|が|叫[さけ]んだ|。', '“Kotone! Pii-chan’s—!” Hayato yelled.'],
    ],
    [
      ['ことね|が|走[はし]ってきて|、|カーテン|を|見[み]上[あ]げた|。', 'Kotone came running and looked up at the curtain.'],
      ['「|はやと|、|だめ|！|追[お]いかけないで|」|。', '“Hayato, no! Don’t chase her.”'],
      ['それから|、|ことね|は|野[の]村[むら]さん|の|紙[かみ]|を|思[おも]い出[だ]した|。', 'Then Kotone remembered Mrs Nomura’s note.'],
      ['ことね|は|えさ|の|箱[はこ]|を|取[と]って|、|そっと|振[ふ]った|。', 'She picked up the food box and shook it gently.'],
      ['カサカサ|と|、|小[ちい]さな|音[おと]|が|した#sound|。', 'It made a soft rattling sound.'],
      ['ピーちゃん|は|首[くび]|を|動[うご]かして|、|ことね|を|見[み]た|。', 'Pii-chan turned her head and looked at Kotone.'],
      ['そして|、|ぱっと|ことね|の|手[て]|の|上[うえ]|に|下[お]りてきた|。', 'Then, all at once, she flew down onto Kotone’s hand.'],
      ['今[こん]度[ど]|は|、|はやと|が|かご|の|戸[と]|を|しっかり|閉[し]めた|。', 'This time, Hayato shut the cage door firmly.'],
    ],
    [
      ['三[みっ]日[か]後[ご]|、|野[の]村[むら]さん|が|ピーちゃん|を|迎[むか]えに来[き]た|。', 'Three days later, Mrs Nomura came to collect Pii-chan.'],
      ['はやと|は|、|カーテン|の|こと#matter|を|正[しょう]直[じき]に|話[はな]した|。', 'Hayato owned up about the curtain.'],
      ['野[の]村[むら]さん|は|「|えさ|の|箱[はこ]|、|役[やく]に立[た]った|ね|」|と|笑[わら]った|。', '“So the food box came in handy,” Mrs Nomura laughed.'],
      ['その|時[とき]|、|ピーちゃん|が|「|ハヤト|、|ダメ|！|」|と|大[おお]きな|声[こえ]|で|言[い]った|。', 'Just then, Pii-chan squawked, “Hayato, no!”'],
      ['みんな|は|おなかをかかえて|笑[わら]った|。', 'Everyone doubled up laughing.'],
      ['野[の]村[むら]さん|は|、|この|話[はなし]|を|マンション|の|みんな|に|話[はな]した|。', 'Mrs Nomura told the story to everyone in the building.'],
    ],
  ],

  // 3. ゆっくり歩くゴロー
  [
    [
      ['次[つぎ]|の|お客[きゃく]さん|は|、|五[ご]階[かい]|の|大[おお]川[かわ]さん|だった|。', 'The next customer was Mr Ōkawa on the fifth floor.'],
      ['大[おお]川[かわ]さん|は|八[はち]十[じゅっ]歳[さい]|の|おじいさん|で#and|、|足[あし]|を|けがしていた|。', 'Mr Ōkawa was eighty years old, and he had hurt his leg.'],
      ['「|一[いっ]週[しゅう]間[かん]|、|ゴロー|の|散[さん]歩[ぽ]|を|頼[たの]める|かな|」|。', '“Could I ask you to walk Gorō for a week?”'],
      ['ゴロー|は|、|茶[ちゃ]色[いろ]|の|大[おお]きな|犬[いぬ]|だった|。', 'Gorō was a big brown dog.'],
      ['顔[かお]|の|毛[け]|は|少[すこ]し|白[しろ]くて|、|目[め]|は|優[やさ]しかった|。', 'The fur on his face had gone a little white, and his eyes were kind.'],
      ['「|ゴロー|も|、|もう|おじいさん|なんだ|よ|」|と|大[おお]川[かわ]さん|は|笑[わら]った|。', '“Gorō’s an old man too, these days,” Mr Ōkawa said with a smile.'],
    ],
    [
      ['夕[ゆう]方[がた]|、|二[ふた]人[り]|は|ゴロー|を|外[そと]|に|連[つ]れ出[だ]した|。', 'That evening, the two of them took Gorō outside.'],
      ['はやと|は|リード|を|持[も]って|、|元[げん]気[き]に|走[はし]り出[だ]した|。', 'Hayato took the lead and set off at a run.'],
      ['「|行[い]く|よ|、|ゴロー|！|公[こう]園[えん]|まで|競[きょう]走[そう]|だ|」|。', '“Come on, Gorō! Race you to the park!”'],
      ['でも|、|ゴロー|は|動[うご]かなかった|。', 'But Gorō didn’t move.'],
      ['マンション|の|前[まえ]|に|座[すわ]って|、|じっとしていた|。', 'He sat down in front of the building and stayed put.'],
      ['はやと|は|リード|を|引[ひ]っ張[ぱ]った|。', 'Hayato tugged on the lead.'],
      ['でも|、|ゴロー|は|座[すわ]った|まま|だった|。', 'But Gorō stayed sitting.'],
      ['ことね|は|、|ポケット|から|犬[いぬ]|の|おやつ|を|出[だ]した|。', 'Kotone took a dog treat out of her pocket.'],
      ['ゴロー|は|おやつ|を|食[た]べた|。', 'Gorō ate the treat.'],
      ['でも|、|やっぱり|歩[ある]かなかった|。', 'But he still wouldn’t walk.'],
    ],
    [
      ['次[つぎ]|の|日[ひ]|も|、|その|次[つぎ]|の|日[ひ]|も|、|同[おな]じ|だった|。', 'It was the same the next day, and the day after that.'],
      ['ゴロー|は|少[すこ]し|だけ|歩[ある]いて|、|すぐに|座[すわ]った|。', 'Gorō walked a few steps and sat straight back down.'],
      ['「|ゴロー|は|、|ぼくたち|が|嫌[きら]い|なんだ|」|と|はやと|が|言[い]った|。', '“Gorō doesn’t like us,” said Hayato.'],
      ['ことね|も|、|だんだん|自[じ]信[しん]|が|なくなった|。', 'Kotone was starting to lose heart too.'],
    ],
    [
      ['四[よっ]日[か]目[め]|の|夕[ゆう]方[がた]|、|ことね|は|五[ご]階[かい]|の|ベランダ|を|見[み]上[あ]げた|。', 'On the fourth evening, Kotone looked up at the fifth-floor balcony.'],
      ['大[おお]川[かわ]さん|が|、|そこ|から|二[ふた]人[り]|を|見[み]ていた|。', 'Mr Ōkawa was watching them from up there.'],
      ['ことね|は|、|前[まえ]#before|に|見[み]た|大[おお]川[かわ]さん|と|ゴロー|の|散[さん]歩[ぽ]|を|思[おも]い出[だ]した|。', 'Kotone remembered seeing Mr Ōkawa and Gorō out on their walks before.'],
      ['大[おお]川[かわ]さん|は|、|いつも|とても|ゆっくり|歩[ある]いていた|。', 'Mr Ōkawa had always walked very slowly.'],
      ['何[なん]度[ど]も|止[と]まって|、|ゴロー|と|一[いっ]緒[しょ]に|花[はな]|や|ほか|の|犬[いぬ]|を|見[み]ていた|。', 'He stopped again and again to look at flowers and other dogs with Gorō.'],
      ['「|はやと|、|走[はし]る|の#ing|は|やめよう|」|と|ことね|が|言[い]った|。', '“Hayato, let’s stop running,” said Kotone.'],
      ['「|ゴロー|は|おじいさん|なんだ|よ|」|。', '“Gorō is an old man.”'],
      ['二[ふた]人[り]|は|ゴロー|の|横[よこ]|に|立[た]って|、|ゆっくり|一[いっ]歩[ぽ]|前[まえ]に出[で]た|。', 'The two of them stood beside Gorō and slowly took one step forward.'],
      ['すると|、|ゴロー|も|立[た]ち上[あ]がって|、|一[いっ]歩[ぽ]|歩[ある]いた|。', 'Then Gorō got up too, and took a step.'],
    ],
    [
      ['その|日[ひ]|、|二[ふた]人[り]|と|ゴロー|は|、|カメ|のように|ゆっくり|公[こう]園[えん]|まで|歩[ある]いた|。', 'That day, the two of them and Gorō walked to the park as slowly as tortoises.'],
      ['ゴロー|は|、|木[き]|の|においをかいだり|、|ほか|の|犬[いぬ]|に|あいさつしたり|した|。', 'Gorō sniffed at the trees and said hello to other dogs.'],
      ['公[こう]園[えん]|に|着[つ]く|まで|、|三[さん]十[じゅっ]分[ぷん]|も|かかった|。', 'It took them a whole thirty minutes to reach the park.'],
      ['でも|、|はやと|は|もう#anymore|文[もん]句[く]を言[い]わなかった|。', 'But Hayato didn’t complain any more.'],
      ['帰[かえ]り道[みち]|、|ベランダ|の|大[おお]川[かわ]さん|が|手[て]|を|振[ふ]っていた|。', 'On the way home, Mr Ōkawa was waving from his balcony.'],
      ['ゴロー|は|大[おお]川[かわ]さん|を|見[み]上[あ]げて|、|しっぽ|を|大[おお]きく|振[ふ]った|。', 'Gorō looked up at him and wagged his tail hard.'],
    ],
    [
      ['一[いっ]週[しゅう]間[かん]|が|たった|。', 'A week went by.'],
      ['大[おお]川[かわ]さん|は|「|これからも|、|ゴロー|と|歩[ある]いてくれる|かな|」|と|二[ふた]人[り]|に|聞[き]いた|。', '“Will you keep walking with Gorō from now on?” Mr Ōkawa asked them.'],
      ['「|はい|！|」|と|、|はやと|が|すぐに|答[こた]えた|。', '“Yes!” Hayato answered at once.'],
    ],
  ],

  // 4. もちはどこ？
  [
    [
      ['八[はち]月[がつ]|に|入[はい]って|、|二[ふた]人[り]|の|仕[し]事[ごと]|は|どんどん|増[ふ]えた|。', 'August came, and the two of them got busier and busier.'],
      ['四[よん]階[かい]|の|金[きん]魚[ぎょ]|、|六[ろっ]階[かい]|の|カメ|、|そして|毎[まい]日[にち]|の|ゴロー|の|散[さん]歩[ぽ]|。', 'Goldfish on the fourth floor, a tortoise on the sixth, and Gorō’s walk every day.'],
      ['はやと|は|、|全[ぜん]部[ぶ]|を|カレンダー|に|書[か]いた|。', 'Hayato wrote it all on the calendar.'],
      ['宿[しゅく]題[だい]|も|、|毎[まい]日[にち]|少[すこ]し|ずつ|やった|。', 'They did a little homework every day, too.'],
      ['ある日[ひ]|、|二[に]階[かい]|に|住[す]む|大[だい]学[がく]生[せい]|の|ちひろさん|が|来[き]た|。', 'One day, Chihiro, a university student who lived on the second floor, came round.'],
      ['「|週[しゅう]末[まつ]|、|家[か]族[ぞく]|に|会[あ]いに行[い]く|の#explain|」|。', '“I’m going to see my family this weekend.”'],
      ['「|もち|に|、|ご飯[はん]|を|あげてくれる|かな|」|。', '“Could you feed Mochi for me?”'],
      ['もち|は|、|白[しろ]くて|丸[まる]い|猫[ねこ]|だった|。', 'Mochi was a round white cat.'],
      ['ちひろさん|は|、|お母[かあ]さん|に|部[へ]屋[や]|の|鍵[かぎ]|を|渡[わた]した|。', 'Chihiro gave Mum the key to her flat.'],
    ],
    [
      ['土[ど]曜[よう]日[び]|の|朝[あさ]|、|三[さん]人[にん]|は|二[に]階[かい]|の|部[へ]屋[や]|に|入[はい]った|。', 'On Saturday morning, the three of them let themselves into the second-floor flat.'],
      ['「|もち|、|ご飯[はん]|だ|よ|」|と|はやと|が|呼[よ]んだ|。', '“Mochi, breakfast!” called Hayato.'],
      ['でも|、|もち|は|出[で]てこなかった|。', 'But Mochi didn’t come out.'],
      ['ベッド|の|下[した]|に|も|、|本[ほん]棚[だな]|の|上[うえ]|に|も|、|いなかった|。', 'She wasn’t under the bed, or on top of the bookcase.'],
      ['お風[ふ]呂[ろ]|に|も|、|トイレ|に|も|、|いなかった|。', 'She wasn’t in the bathroom or the toilet either.'],
      ['はやと|の|顔[かお]|が|、|だんだん|青[あお]くなった|。', 'Hayato’s face slowly went pale.'],
      ['「|ドア|を|開[あ]けた|時[とき]|、|外[そと]|に|出[で]た|のかな|」|。', '“Did she get out when we opened the door?”'],
      ['三[さん]人[にん]|は|、|廊[ろう]下[か]|や|階[かい]段[だん]|も|探[さが]した|。', 'The three of them searched the corridor and the stairs as well.'],
      ['はやと|は|「|もち|！|もち|！|」|と|大[おお]きな|声[こえ]|で|呼[よ]び続[つづ]けた|。', 'Hayato kept shouting at the top of his voice, “Mochi! Mochi!”'],
      ['でも|、|もち|は|どこ|に|も|いなかった|。', 'But Mochi was nowhere to be found.'],
    ],
    [
      ['お母[かあ]さん|は|、|管[かん]理[り]人[にん]さん|に|話[はな]しに行[い]った|。', 'Mum went to tell the building manager.'],
      ['部[へ]屋[や]|に|戻[もど]って|、|ことね|は|ソファ|に|座[すわ]った|。', 'Back in the flat, Kotone sat down on the sofa.'],
      ['その|時[とき]|、|ふと|ゴロー|の|こと#about|を|思[おも]い出[だ]した|。', 'Just then, she found herself thinking about Gorō.'],
      ['ゴロー|は|、|急[いそ]ぐ|人[ひと]|と|は|歩[ある]かなかった|。', 'Gorō wouldn’t walk with people who were in a hurry.'],
      ['「|もち|も|同[おな]じ|だ|。|私[わたし]たち|が|騒[さわ]いだ|から|、|隠[かく]れている|んだ|」|。', '“Mochi’s the same. She’s hiding because we were making a fuss.”'],
      ['「|はやと|、|ここ|に|座[すわ]って|。|静[しず]かに|待[ま]とう|」|。', '“Hayato, sit here. Let’s wait quietly.”'],
      ['二[ふた]人[り]|は|、|何[なに]も|言[い]わずに|待[ま]った|。', 'The two of them waited without a word.'],
      ['五[ご]分[ふん]|たった|。', 'Five minutes passed.'],
      ['十[じゅっ]分[ぷん]|たった|。', 'Ten minutes passed.'],
      ['その|時[とき]|、|上[うえ]|の|方[ほう]|から|「|にゃあ|」|と|小[ちい]さな|声[こえ]|が|した#sound|。', 'Then, from somewhere up high, came a small “miaow.”'],
      ['台[だい]所[どころ]|の|高[たか]い|棚[たな]|の|上[うえ]|から|、|丸[まる]い|顔[かお]|が|のぞいていた|。', 'A round face was peeping down from the top of a high kitchen shelf.'],
      ['もち|は|ゆっくり|下[お]りてきて|、|ご飯[はん]|を|食[た]べ始[はじ]めた|。', 'Mochi came slowly down and began to eat.'],
      ['はやと|は|ほっとして|、|床[ゆか]|に|寝[ね]転[ころ]んだ|。', 'Hayato flopped onto the floor in relief.'],
    ],
    [
      ['その|日[ひ]|の|夕[ゆう]方[がた]|、|散[さん]歩[ぽ]|の|後[あと]|で|、|大[おお]川[かわ]さん|が|二[ふた]人[り]|を|呼[よ]んだ|。', 'That evening, after the walk, Mr Ōkawa called the two of them over.'],
      ['大[おお]川[かわ]さん|の|足[あし]|は|、|もう|治[なお]っていた|。', 'His leg had healed by now.'],
      ['でも|、|大[おお]川[かわ]さん|は|あまり|笑[わら]わなかった|。', 'But he wasn’t smiling much.'],
      ['「|来[らい]月[げつ]|、|娘[むすめ]|の|ところ|に|引[ひ]っ越[こ]す|んだ|」|。', '“I’m moving in with my daughter next month.”'],
      ['「|でも|、|娘[むすめ]|の|マンション|は|、|犬[いぬ]|が|だめ|なんだ|よ|」|。', '“But dogs aren’t allowed in her building.”'],
      ['ゴロー|は|、|大[おお]川[かわ]さん|の|足[あし]元[もと]|で|目[め]|を|閉[と]じていた|。', 'Gorō lay at Mr Ōkawa’s feet with his eyes closed.'],
    ],
  ],

  // 5. 七階の新しい家族
  [
    [
      ['その|夜[よる]|、|ことね|も|はやと|も|、|なかなか|眠[ねむ]れなかった|。', 'That night, neither Kotone nor Hayato could get to sleep.'],
      ['「|ゴロー|は|、|どこ|に|行[い]く|の#question|」|と|はやと|が|聞[き]いた|。', '“Where will Gorō go?” asked Hayato.'],
      ['「|分[わ]からない|。|大[おお]川[かわ]さん|は|、|新[あたら]しい|家[いえ]|を|探[さが]す|って|」|。', '“I don’t know. Mr Ōkawa says he’ll find him a new home.”'],
      ['ことね|は|、|知[し]らない|家[いえ]|に|いる|ゴロー|の|こと#about|を|考[かんが]えた|。', 'Kotone thought about Gorō in a stranger’s house.'],
      ['その|家[いえ]|の|人[ひと]|は|、|ゴロー|の|歩[ある]き方[かた]|を|知[し]らない|。', 'The people there wouldn’t know how Gorō liked to walk.'],
      ['きっと|、|リード|を|引[ひ]っ張[ぱ]る|だろう|。', 'They would be sure to tug on his lead.'],
    ],
    [
      ['次[つぎ]|の|朝[あさ]|、|先[さき]|に|口[くち]を開[ひら]いた|の#one|は|はやと|だった|。', 'The next morning, it was Hayato who spoke first.'],
      ['「|お母[かあ]さん|、|ぼく|、|子[こ]犬[いぬ]|じゃなくていい|」|。', '“Mum, it doesn’t have to be a puppy.”'],
      ['「|ゴロー|が|いい|」|。', '“I want Gorō.”'],
      ['ことね|も|、|お母[かあ]さん|の|顔[かお]|を|じっと|見[み]た|。', 'Kotone looked steadily at Mum, too.'],
      ['お母[かあ]さん|は|、|何[なに]も|言[い]わずに|カレンダー|を|見[み]た|。', 'Without a word, Mum looked at the calendar.'],
      ['そこ|に|は|、|夏[なつ]休[やす]み|の|毎[まい]日[にち]|の|仕[し]事[ごと]|が|書[か]いてあった|。', 'Every day of the summer’s jobs was written there.'],
      ['ピーちゃん|、|ゴロー|、|もち|、|金[きん]魚[ぎょ]|、|カメ|。', 'Pii-chan, Gorō, Mochi, the goldfish, the tortoise.'],
      ['宿[しゅく]題[だい]|の|ところ#spot|に|も|、|毎[まい]日[にち]|丸[まる]|が|ついていた|。', 'And every day, the homework had a circle next to it, too.'],
      ['「|ゴロー|は|、|もう|おじいさん|だ|よ|」|と|お母[かあ]さん|は|言[い]った|。', '“Gorō is an old dog, you know,” said Mum.'],
      ['「|動[どう]物[ぶつ]病[びょう]院[いん]|に|も|よく|行[い]く|し|、|散[さん]歩[ぽ]|も|ゆっくり|だ|よ|」|。', '“He’ll need the vet a lot, and his walks are slow.”'],
      ['「|知[し]ってる|」|と|、|二[ふた]人[り]|は|声[こえ]をそろえた|。', '“We know,” they said together.'],
      ['お母[かあ]さん|は|、|やっと|笑[わら]った|。', 'At last, Mum smiled.'],
      ['「|じゃあ|、|大[おお]川[かわ]さん|に|話[はな]しに行[い]こう|」|。', '“Well then, let’s go and talk to Mr Ōkawa.”'],
    ],
    [
      ['大[おお]川[かわ]さん|は|話[はなし]|を|聞[き]いて|、|長[なが]い|間[あいだ]|黙[だま]っていた|。', 'Mr Ōkawa listened, and for a long time he said nothing.'],
      ['それから|、|ゴロー|の|頭[あたま]|を|なでて|言[い]った|。', 'Then he stroked Gorō’s head and said:'],
      ['「|ゴロー|、|よかった|な|」|。', '“Well, Gorō. Aren’t you lucky.”'],
      ['「|娘[むすめ]|の|ところ|は|隣[となり]|の|町[まち]|だ|から|、|日[にち]曜[よう]日[び]|に|会[あ]いに来[く]る|よ|」|。', '“My daughter’s place is only in the next town, so I’ll come and see you on Sundays.”'],
    ],
    [
      ['九[く]月[がつ]|の|初[はじ]め|、|大[おお]川[かわ]さん|は|引[ひ]っ越[こ]していった|。', 'At the start of September, Mr Ōkawa moved away.'],
      ['ゴロー|は|、|車[くるま]|が|見[み]えなくなる|まで|、|じっと|道[みち]|を|見[み]ていた|。', 'Gorō watched the road without moving until the car was out of sight.'],
      ['ことね|は|ゴロー|の|横[よこ]|に|しゃがんで|、|待[ま]った|。', 'Kotone crouched down beside Gorō and waited.'],
      ['しばらくして|、|ゴロー|は|立[た]ち上[あ]がって|、|ことね|の|手[て]|を|なめた|。', 'After a while, Gorō got up and licked Kotone’s hand.'],
      ['「|さあ|、|帰[かえ]ろう|。|ゆっくり|ね|」|。', '“Come on, let’s go home. Nice and slow.”'],
      ['二[ふた]人[り]|と|ゴロー|は|、|一[いっ]歩[ぽ]|ずつ|マンション|に|入[はい]った|。', 'The two of them and Gorō went into the building one step at a time.'],
    ],
    [
      ['エレベーター|の|横[よこ]|に|は|、|まだ|あの|お知[し]らせ|が|貼[は]ってあった|。', 'Their notice was still up beside the lift.'],
      ['その|下[した]|に|、|だれか|が|何[なに]か|書[か]き足[た]していた|。', 'Underneath it, someone had added something.'],
      ['「|ゴロー|、|七[なな]階[かい]|へ|ようこそ|。|野[の]村[むら]|」|。', '“Welcome to the seventh floor, Gorō. — Nomura”'],
      ['エレベーター|が|三[さん]階[がい]|で|止[と]まって|、|ドア|が|開[あ]いた|。', 'The lift stopped at the third floor, and the doors opened.'],
      ['野[の]村[むら]さん|が|、|ピーちゃん|の|かご|を|持[も]って|立[た]っていた|。', 'There stood Mrs Nomura, holding Pii-chan’s cage.'],
      ['ゴロー|は|、|かご|に|鼻[はな]|を|近[ちか]づけた|。', 'Gorō put his nose up to the cage.'],
      ['「|ハヤト|、|ダメ|！|」|と|ピーちゃん|が|言[い]った|。', '“Hayato, no!” said Pii-chan.'],
      ['「|ぼく|、|何[なに]も|してない|よ|！|」|と|はやと|が|言[い]って|、|みんな|が|笑[わら]った|。', '“I didn’t do anything!” said Hayato, and everyone laughed.'],
    ],
  ],
];
