import { expandStory, lexicon, line } from './helpers.mjs';

const SOL_SOURCE = (text, notes, licence = 'Public domain (traditional tale). This retelling and its English translation are original to Kana Quest.') => ({
  kind: 'adapted', text, by: 'Sol 5.6', credit: 'Retold by', notes, licence,
});

const ariToHato = expandStory({
  id: 'ari-to-hato',
  title: { ja: 'ありとはと', en: 'The Ant and the Dove' },
  series: null, level: 'L1', gram: 'G1',
  blurb: 'A dove helps a tiny ant, and the ant soon finds a way to return the kindness.',
  source: SOL_SOURCE('Aesop’s fable (The Ant and the Dove)', 'An original graded retelling with short, single-clause sentences and no wording from a published edition.'),
  nw: ['あり', 'はと', '葉', '助けます'],
  lexicon: lexicon({
    'ある日[ひ]': ['one day', 'adv'], 'あり': ['ant', 'n'], '川[かわ]': ['river', 'n'], '水[みず]': ['water', 'n'],
    '水[みず]を飲[の]みに行[い]きました': ['went to drink water', 'v', { df: '水を飲みに行く', cf: 'polite past' }],
    '足[あし]': ['foot', 'n'], 'すべりました': ['slipped', 'v', { df: 'すべる', cf: 'polite past' }],
    '落[お]ちました': ['fell', 'v', { df: '落ちる', cf: 'polite past' }],
    '流[なが]されました': ['was swept away', 'v', { df: '流される', cf: 'polite past passive' }],
    'はと': ['dove', 'n'], '木[き]': ['tree', 'n'], '見[み]ていました': ['was watching', 'v', { df: '見る', cf: 'polite past progressive' }],
    '葉[は]': ['leaf', 'n'], '落[お]としました': ['dropped', 'v', { df: '落とす', cf: 'polite past' }],
    'つかまりました': ['held on', 'v', { df: 'つかまる', cf: 'polite past' }],
    '岸[きし]': ['bank, shore', 'n'], '着[つ]きました': ['reached', 'v', { df: '着く', cf: 'polite past' }],
    'すぐ': ['soon', 'adv'], '男[おとこ]': ['man', 'n'], '来[き]ました': ['came', 'v', { df: '来る', cf: 'polite past' }],
    '弓[ゆみ]': ['bow', 'n'], 'ねらいました': ['aimed at', 'v', { df: 'ねらう', cf: 'polite past' }],
    'かみました': ['bit', 'v', { df: 'かむ', cf: 'polite past' }],
    '矢[や]': ['arrow', 'n'], '外[はず]れました': ['missed', 'v', { df: '外れる', cf: 'polite past' }],
    '空[そら]': ['sky', 'n'], '飛[と]びました': ['flew', 'v', { df: '飛ぶ', cf: 'polite past' }],
    '二[ふた]人[り]': ['the two', 'n'], '助[たす]け合[あ]いました': ['helped each other', 'v', { df: '助け合う', cf: 'polite past' }],
  }),
  body: [[
    line('ある日[ひ]|、|あり|は|川[かわ]|へ|水[みず]を飲[の]みに行[い]きました|。', 'One day, an ant went to the river to drink.'),
    line('あり|は|足[あし]|を|すべりました|。', 'The ant slipped.'),
    line('川[かわ]|に|落[お]ちました|。', 'It fell into the river.'),
    line('水[みず]|に|流[なが]されました|。', 'It was swept along by the water.'),
    line('はと|は|木[き]|から|見[み]ていました|。', 'A dove was watching from a tree.'),
    line('はと|は|葉[は]|を|落[お]としました|。', 'The dove dropped a leaf.'),
    line('あり|は|葉[は]|に|つかまりました|。', 'The ant held on to the leaf.'),
    line('岸[きし]|に|着[つ]きました|。', 'It reached the bank.'),
    line('すぐ|、|男[おとこ]|が|弓[ゆみ]|で|はと|を|ねらいました|。', 'Soon, a man aimed a bow at the dove.'),
    line('あり|は|男[おとこ]|の|足[あし]|を|かみました|。', 'The ant bit the man’s foot.'),
    line('矢[や]|は|外[はず]れました|。', 'The arrow missed.'),
    line('はと|は|空[そら]|へ|飛[と]びました|。', 'The dove flew into the sky.'),
    line('二[ふた]人[り]|は|助[たす]け合[あ]いました|。', 'The two had helped each other.'),
  ]],
});

const ookamiGaKita = expandStory({
  id: 'ookami-ga-kita',
  title: { ja: 'おおかみが来た', en: 'The Boy Who Cried Wolf' },
  series: null, level: 'L2', gram: 'G2',
  blurb: 'A bored shepherd boy learns why a true warning needs the trust of its listeners.',
  source: SOL_SOURCE('Aesop’s fable (The Boy Who Cried Wolf)', 'An original graded retelling with a non-violent ending and no wording from a published edition.'),
  nw: ['羊飼い', 'おおかみ', 'うそ', '信じる'],
  lexicon: lexicon({
    '山[やま]': ['mountain', 'n'], '近[ちか]い': ['near', 'adj'], '村[むら]': ['village', 'n'], 'として': ['as; in the role of', 'part'], '日[ひ]': ['day', 'n'],
    '少[しょう]年[ねん]': ['boy', 'n'], '羊[ひつじ]飼[か]い': ['shepherd', 'n'], '働[はたら]いていました': ['was working', 'v', { df: '働く', cf: 'polite past progressive' }],
    '毎[まい]日[にち]': ['every day', 'adv'], '丘[おか]': ['hill', 'n'], '羊[ひつじ]たち': ['the sheep', 'n'], '連[つ]れていきました': ['took along', 'v', { df: '連れていく', cf: 'polite past' }],
    '一[ひと]人[り]': ['alone', 'adv'], '長[なが]い時[じ]間[かん]': ['a long time', 'n'], 'いる': ['being; staying', 'v'], '退[たい]屈[くつ]でした': ['was bored', 'adj', { df: '退屈だ', cf: 'polite past' }],
    'ある日[ひ]': ['one day', 'adv'], 'いたずら': ['mischief, prank', 'n'], '思[おも]いつきました': ['thought of', 'v', { df: '思いつく', cf: 'polite past' }],
    'おおかみ': ['wolf', 'n'], '来[き]た': ['has come', 'v', { df: '来る', cf: 'plain past' }], '助[たす]けて': ['help me', 'v', { df: '助ける', cf: 'te-form request' }], '叫[さけ]びました': ['shouted', 'v', { df: '叫ぶ', cf: 'polite past' }],
    '村[むら]人[びと]たち': ['the villagers', 'n'], '道[どう]具[ぐ]': ['tools', 'n'], '持[も]って': ['carrying', 'v', { df: '持つ', cf: 'te-form' }], '走[はし]ってきました': ['came running', 'v', { df: '走ってくる', cf: 'polite past' }],
    'どこにも': ['nowhere', 'adv'], 'いませんでした': ['was not there', 'v', { df: 'いる', cf: 'polite past negative' }],
    'だました': ['tricked', 'v', { df: 'だます', cf: 'plain past' }], '笑[わら]いました': ['laughed', 'v', { df: '笑う', cf: 'polite past' }],
    '怒[おこ]って': ['angrily; getting angry', 'v', { df: '怒る', cf: 'te-form' }], '帰[かえ]りました': ['went home', 'v', { df: '帰る', cf: 'polite past' }],
    '次[つぎ]': ['next', 'n'], '同[おな]じ': ['same', 'adj'], 'うそ': ['lie', 'n'], '言[い]いました': ['said, told', 'v', { df: '言う', cf: 'polite past' }],
    'また': ['again', 'adv'], '助[たす]けに来[き]ました': ['came to help', 'v', { df: '助けに来る', cf: 'polite past' }],
    '今[こん]度[ど]': ['this time', 'adv'], '強[つよ]く': ['sternly', 'adv', { df: '強い', cf: 'adverbial form' }], '注[ちゅう]意[い]しました': ['warned', 'v', { df: '注意する', cf: 'polite past' }],
    '何[なん]日[にち]か後[ご]': ['several days later', 'adv'], '本[ほん]当[とう]に': ['really', 'adv'], '森[もり]': ['forest', 'n'], '出[で]てきました': ['came out', 'v', { df: '出てくる', cf: 'polite past' }],
    '声[こえ]': ['voice', 'n'], 'かぎり': ['as much as possible', 'n'], '呼[よ]びました': ['called', 'v', { df: '呼ぶ', cf: 'polite past' }],
    'しかし': ['however', 'adv'], '今[いま]': ['now', 'adv'], '信[しん]じませんでした': ['did not believe', 'v', { df: '信じる', cf: 'polite past negative' }],
    '少[しょう]年[ねん]': ['boy', 'n'], '羊[ひつじ]たち': ['the sheep', 'n'], '小[ちい]さな': ['small', 'adj'], '小[こ]屋[や]': ['hut', 'n'], '入[い]れました': ['put inside', 'v', { df: '入れる', cf: 'polite past' }],
    '戸[と]': ['door', 'n'], '閉[し]めると': ['when he closed', 'v', { df: '閉める', cf: 'plain present conditional 〜と' }],
    '朝[あさ]': ['morning', 'n'], '無[ぶ]事[じ]でした': ['were safe', 'adj', { df: '無事だ', cf: 'polite past' }],
    '村[むら]人[びと]たち': ['the villagers', 'n'], '本[ほん]当[とう]': ['truth', 'n'], '話[はな]しました': ['told', 'v', { df: '話す', cf: 'polite past' }],
    'うそをつくと': ['when one lies', 'v', { df: 'うそをつく', cf: 'plain present conditional 〜と' }], '言[こと]葉[ば]': ['words', 'n'], '力[ちから]': ['power', 'n'], 'なくなる': ['is lost', 'v', { df: 'なくなる', cf: 'plain present' }], '学[まな]びました': ['learned', 'v', { df: '学ぶ', cf: 'polite past' }],
  }),
  body: [
    [
      line('山[やま]|に|近[ちか]い|村[むら]|で|、|少[しょう]年[ねん]|は|羊[ひつじ]飼[か]い|として|働[はたら]いていました|。', 'In a village near the mountains, a boy worked as a shepherd.'),
      line('毎[まい]日[にち]|、|丘[おか]|へ|羊[ひつじ]たち|を|連[つ]れていきました|。', 'Every day, he took the sheep to a hill.'),
      line('一[ひと]人[り]|で|長[なが]い時[じ]間[かん]|いる|ので|、|退[たい]屈[くつ]でした|。', 'He was bored because he stayed alone for a long time.'),
      line('ある日[ひ]|、|いたずら|を|思[おも]いつきました|。', 'One day, he thought of a prank.'),
      line('「|おおかみ|が|来[き]た|。|助[たす]けて|」|と|叫[さけ]びました|。', '“A wolf has come! Help!” he shouted.'),
      line('村[むら]人[びと]たち|は|道[どう]具[ぐ]|を|持[も]って|走[はし]ってきました|。', 'The villagers came running with tools.'),
      line('おおかみ|は|どこにも|いませんでした|。', 'There was no wolf anywhere.'),
      line('少[しょう]年[ねん]|は|「|だました|」|と|笑[わら]いました|。', 'The boy laughed, saying, “I tricked you.”'),
      line('村[むら]人[びと]たち|は|怒[おこ]って|帰[かえ]りました|。', 'The villagers went home angrily.'),
    ],
    [
      line('次[つぎ]|の|日[ひ]|も|、|少[しょう]年[ねん]|は|同[おな]じ|うそ|を|言[い]いました|。', 'The next day, the boy told the same lie.'),
      line('村[むら]人[びと]たち|は|また|助[たす]けに来[き]ました|。', 'The villagers came to help again.'),
      line('今[こん]度[ど]|は|少[しょう]年[ねん]|を|強[つよ]く|注[ちゅう]意[い]しました|。', 'This time, they sternly warned the boy.'),
      line('何[なん]日[にち]か後[ご]|、|本[ほん]当[とう]に|おおかみ|が|森[もり]|から|出[で]てきました|。', 'Several days later, a wolf really came out of the forest.'),
      line('少[しょう]年[ねん]|は|声[こえ]|の|かぎり|「|助[たす]けて|」|と|呼[よ]びました|。', 'The boy called “Help!” as loudly as he could.'),
      line('しかし|、|村[むら]人[びと]たち|は|今[いま]|の|言[こと]葉[ば]|も|信[しん]じませんでした|。', 'But the villagers did not believe his words now.'),
      line('少[しょう]年[ねん]|は|羊[ひつじ]たち|を|小[ちい]さな|小[こ]屋[や]|に|入[い]れました|。', 'The boy put the sheep into a small hut.'),
      line('戸[と]|を|閉[し]めると|、|おおかみ|は|森[もり]|へ|帰[かえ]りました|。', 'When he closed the door, the wolf returned to the forest.'),
      line('朝[あさ]|、|羊[ひつじ]たち|は|無[ぶ]事[じ]でした|。', 'In the morning, the sheep were safe.'),
      line('少[しょう]年[ねん]|は|村[むら]人[びと]たち|に|本[ほん]当[とう]|を|話[はな]しました|。', 'The boy told the villagers the truth.'),
      line('うそをつくと|言[こと]葉[ば]|の|力[ちから]|が|なくなる|と|学[まな]びました|。', 'He learned that lies take the power away from words.'),
    ],
  ],
});

const goldilocks = expandStory({
  id: 'goldilocks',
  title: { ja: 'ゴルディロックスと三びきのくま', en: 'Goldilocks and the Three Bears' },
  series: null, level: 'L3', gram: 'G3',
  blurb: 'Three bears return from a walk to find that a curious visitor has tested everything in their cottage.',
  source: SOL_SOURCE('Traditional British tale (Goldilocks and the Three Bears)', 'An original graded retelling with a gentle ending and no wording from a published edition.'),
  nw: ['ゴルディロックス', 'スープ', 'いす', 'ベッド', 'ぴったり'],
  lexicon: lexicon({
    'ある': ['a certain', 'adj'], 'だった': ['were; was', 'aux', { df: 'だ', cf: 'plain past' }], 'が#but': ['but, although', 'part'],
    'ぼく': ['I, me (used by a boy)', 'pn'], '四[よ]人[にん]': ['four people', 'num'],
    '森[もり]': ['forest', 'n'], '中[なか]': ['inside', 'n'], '三[さん]びき': ['three animals', 'num'], 'くま': ['bear', 'n'], '家[いえ]': ['house', 'n'], '住[す]んでいた': ['lived', 'v', { df: '住む', cf: 'plain past progressive' }],
    '大[おお]きな': ['large', 'adj'], 'お父[とう]さんぐま': ['Father Bear', 'pn'], '中[ちゅう]くらい': ['medium-sized', 'adj'], 'お母[かあ]さんぐま': ['Mother Bear', 'pn'], '小[ちい]さな': ['small', 'adj'], '子[こ]ぐま': ['Baby Bear', 'pn'],
    '朝[あさ]': ['morning', 'n'], '三[さん]つ': ['three things', 'num'], 'スープ': ['soup', 'n'], '作[つく]った': ['made', 'v', { df: '作る', cf: 'plain past' }],
    '熱[あつ]かった': ['was hot', 'adj', { df: '熱い', cf: 'plain past' }], '冷[さ]めるまで': ['until it cooled', 'v', { df: '冷める', cf: 'plain present 〜まで form' }], '散[さん]歩[ぽ]に出[で]た': ['went for a walk', 'v', { df: '散歩に出る', cf: 'plain past' }],
    'その間[あいだ]': ['during that time', 'adv'], 'ゴルディロックス': ['Goldilocks', 'pn'], '女[おんな]の子[こ]': ['girl', 'n'], '見[み]つけた': ['found', 'v', { df: '見つける', cf: 'plain past' }],
    'ドア': ['door', 'n'], 'ノックした': ['knocked', 'v', { df: 'ノックする', cf: 'plain past' }], '返[へん]事[じ]': ['reply', 'n'], 'なかった': ['was not; there was no', 'adj', { df: 'ない', cf: 'plain past' }],
    '少[すこ]し': ['a little', 'adv'], '開[あ]いていた': ['was open', 'v', { df: '開く', cf: 'plain past progressive' }], '入[はい]った': ['entered', 'v', { df: '入る', cf: 'plain past' }],
    'テーブル': ['table', 'n'], '並[なら]んでいた': ['were lined up', 'v', { df: '並ぶ', cf: 'plain past progressive' }],
    '一[いち]番[ばん]': ['number one; first', 'adv'], '皿[さら]': ['bowl, plate', 'n'], '辛[から]すぎた': ['was too spicy', 'adj', { df: '辛い', cf: 'plain past 〜すぎる form' }],
    '二[に]番[ばん]目[め]': ['the second', 'n'], '甘[あま]すぎた': ['was too sweet', 'adj', { df: '甘い', cf: 'plain past 〜すぎる form' }],
    '子[こ]ぐま用[よう]': ['for Baby Bear', 'adj'], 'ちょうどよかった': ['was just right', 'adj', { df: 'ちょうどよい', cf: 'plain past' }], '全[ぜん]部[ぶ]': ['all', 'n'], '食[た]べた': ['ate', 'v', { df: '食べる', cf: 'plain past' }],
    '次[つぎ]に': ['next', 'adv'], 'いす': ['chair', 'n'], '座[すわ]った': ['sat', 'v', { df: '座る', cf: 'plain past' }],
    '固[かた]すぎた': ['was too hard', 'adj', { df: '固い', cf: 'plain past 〜すぎる form' }], '柔[やわ]らかすぎた': ['was too soft', 'adj', { df: '柔らかい', cf: 'plain past 〜すぎる form' }],
    'ぴったりだった': ['was just right', 'adj', { df: 'ぴったりだ', cf: 'plain past' }], 'ところが': ['however', 'adv'], '壊[こわ]れた': ['broke', 'v', { df: '壊れる', cf: 'plain past' }],
    '疲[つか]れて': ['being tired', 'v', { df: '疲れる', cf: 'te-form' }], '二[に]階[かい]': ['upstairs, second floor', 'n'], '上[あ]がった': ['went up', 'v', { df: '上がる', cf: 'plain past' }],
    'ベッド': ['bed', 'n'], '試[ため]した': ['tried', 'v', { df: '試す', cf: 'plain past' }], '高[たか]すぎた': ['was too high', 'adj', { df: '高い', cf: 'plain past 〜すぎる form' }], '広[ひろ]すぎた': ['was too wide', 'adj', { df: '広い', cf: 'plain past 〜すぎる form' }],
    '眠[ねむ]ってしまった': ['fell asleep', 'v', { df: '眠る', cf: 'plain past 〜てしまう form' }],
    'やがて': ['before long', 'adv'], '帰[かえ]ってきた': ['came home', 'v', { df: '帰ってくる', cf: 'plain past' }],
    '誰[だれ]か': ['someone', 'pn'], '飲[の]んだ': ['drank', 'v', { df: '飲む', cf: 'plain past' }], '気[き]づいた': ['noticed', 'v', { df: '気づく', cf: 'plain past' }],
    '食[た]べられている': ['has been eaten', 'v', { df: '食べる', cf: 'plain present perfect passive' }], '泣[な]いた': ['cried', 'v', { df: '泣く', cf: 'plain past' }],
    'いす': ['chair', 'n'], '調[しら]べた': ['examined', 'v', { df: '調べる', cf: 'plain past' }], '座[すわ]った': ['sat on', 'v', { df: '座る', cf: 'plain past' }], '壊[こわ]されている': ['has been broken', 'v', { df: '壊す', cf: 'plain present perfect passive' }],
    '寝[しん]室[しつ]': ['bedroom', 'n'], '行[い]くと': ['when they went', 'v', { df: '行く', cf: 'plain present conditional 〜と' }], '枕[まくら]': ['pillow', 'n'], 'くぼみ': ['hollow, dent', 'n'], '見[み]えた': ['could be seen', 'v', { df: '見える', cf: 'plain past' }],
    '眠[ねむ]っている': ['is sleeping', 'v', { df: '眠る', cf: 'plain present progressive' }], '叫[さけ]んだ': ['cried out', 'v', { df: '叫ぶ', cf: 'plain past' }],
    '目[め]を覚[さ]まして': ['waking up; woke and', 'v', { df: '目を覚ます', cf: 'te-form' }], '見[み]て': ['seeing; saw and', 'v', { df: '見る', cf: 'te-form' }], '驚[おどろ]いた': ['was startled', 'v', { df: '驚く', cf: 'plain past' }],
    '窓[まど]': ['window', 'n'], '逃[に]げようとした': ['tried to escape', 'v', { df: '逃げる', cf: 'plain volitional 〜ようとする past' }],
    '待[ま]って': ['wait', 'v', { df: '待つ', cf: 'te-form request' }], '怖[こわ]くない': ['not frightening', 'adj', { df: '怖い', cf: 'plain negative' }], '言[い]った': ['said', 'v', { df: '言う', cf: 'plain past' }],
    'ゴルディロックス': ['Goldilocks', 'pn'], '勝[かっ]手[て]に': ['without permission', 'adv'], '使[つか]ったこと': ['having used', 'v', { df: '使う', cf: 'plain past nominalised' }], '謝[あやま]った': ['apologised', 'v', { df: '謝る', cf: 'plain past' }],
    '直[なお]す': ['repair', 'v', { df: '直す', cf: 'plain present' }], '約[やく]束[そく]した': ['promised', 'v', { df: '約束する', cf: 'plain past' }],
    '温[あたた]かい': ['warm', 'adj'], '新[あたら]しい': ['new', 'adj'], '一[いっ]緒[しょ]に': ['together', 'adv'], '作[つく]り直[なお]した': ['remade', 'v', { df: '作り直す', cf: 'plain past' }],
    'それから': ['after that', 'adv'], '訪[たず]ねる時[とき]': ['when visiting', 'v', { df: '訪ねる', cf: 'plain present time clause' }], '必[かなら]ず': ['always', 'adv'], '先[さき]に': ['first; beforehand', 'adv'], '聞[き]くようになった': ['came to ask', 'v', { df: '聞く', cf: 'plain past 〜ようになる form' }],
  }),
  body: [
    [
      line('森[もり]|の|中[なか]|に|、|三[さん]びき|の|くま|が|住[す]んでいた|。', 'Three bears lived in the forest.'),
      line('大[おお]きな|お父[とう]さんぐま|、|中[ちゅう]くらい|の|お母[かあ]さんぐま|、|小[ちい]さな|子[こ]ぐま|だった|。', 'They were a large Father Bear, a medium Mother Bear and a small Baby Bear.'),
      line('ある|朝[あさ]|、|三[さん]びき|は|三[さん]つ|の|スープ|を|作[つく]った|。', 'One morning, the three bears made three bowls of soup.'),
      line('スープ|が|熱[あつ]かった|ので|、|冷[さ]めるまで|散[さん]歩[ぽ]に出[で]た|。', 'Because the soup was hot, they went walking until it cooled.'),
      line('その間[あいだ]|に|、|ゴルディロックス|という|女[おんな]の子[こ]|が|家[いえ]|を|見[み]つけた|。', 'Meanwhile, a girl called Goldilocks found the house.'),
      line('ドア|を|ノックした|が#but|、|返[へん]事[じ]|は|なかった|。', 'She knocked on the door, but there was no reply.'),
      line('ドア|が|少[すこ]し|開[あ]いていた|ので|、|中[なか]|へ|入[はい]った|。', 'Because the door was slightly open, she went inside.'),
    ],
    [
      line('テーブル|に|三[さん]つ|の|スープ|が|並[なら]んでいた|。', 'Three bowls of soup stood on the table.'),
      line('一[いち]番[ばん]|大[おお]きな|皿[さら]|の|スープ|は|辛[から]すぎた|。', 'The soup in the largest bowl was too spicy.'),
      line('二[に]番[ばん]目[め]|の|スープ|は|甘[あま]すぎた|。', 'The second soup was too sweet.'),
      line('子[こ]ぐま用[よう]|の|スープ|は|ちょうどよかった|ので|、|全[ぜん]部[ぶ]|食[た]べた|。', 'Baby Bear’s soup was just right, so she ate it all.'),
      line('次[つぎ]に|、|三[さん]つ|の|いす|に|座[すわ]った|。', 'Next, she sat on the three chairs.'),
      line('大[おお]きな|いす|は|固[かた]すぎた|。', 'The large chair was too hard.'),
      line('中[ちゅう]くらい|の|いす|は|柔[やわ]らかすぎた|。', 'The medium chair was too soft.'),
      line('小[ちい]さな|いす|は|ぴったりだった|が#but|、|壊[こわ]れた|。', 'The small chair was just right, but it broke.'),
    ],
    [
      line('疲[つか]れて|、|ゴルディロックス|は|二[に]階[かい]|へ|上[あ]がった|。', 'Tired, Goldilocks went upstairs.'),
      line('三[さん]つ|の|ベッド|を|試[ため]した|。', 'She tried the three beds.'),
      line('一[いち]番[ばん]|の|ベッド|は|高[たか]すぎた|。', 'The first bed was too high.'),
      line('二[に]番[ばん]目[め]|の|ベッド|は|広[ひろ]すぎた|。', 'The second bed was too wide.'),
      line('小[ちい]さな|ベッド|は|ぴったりだった|ので|、|眠[ねむ]ってしまった|。', 'The small bed was just right, so she fell asleep.'),
      line('やがて|、|三[さん]びき|の|くま|が|帰[かえ]ってきた|。', 'Before long, the three bears came home.'),
      line('誰[だれ]か|が|スープ|を|飲[の]んだ|と|気[き]づいた|。', 'They noticed that someone had tasted the soup.'),
      line('「|ぼく|の|スープ|は|全[ぜん]部[ぶ]|食[た]べられている|」|と|子[こ]ぐま|は|泣[な]いた|。', '“All my soup has been eaten,” Baby Bear cried.'),
    ],
    [
      line('三[さん]びき|は|いす|を|調[しら]べた|。', 'The three bears examined their chairs.'),
      line('「|誰[だれ]か|が|ぼく|の|いす|に|座[すわ]った|。|壊[こわ]されている|」|と|子[こ]ぐま|は|言[い]った|。', '“Someone sat in my chair. It has been broken,” Baby Bear said.'),
      line('寝[しん]室[しつ]|へ|行[い]くと|、|枕[まくら]|に|小[ちい]さな|くぼみ|が|見[み]えた|。', 'When they went to the bedroom, they saw a small hollow in a pillow.'),
      line('「|女[おんな]の子[こ]|が|眠[ねむ]っている|」|と|子[こ]ぐま|が|叫[さけ]んだ|。', '“A girl is sleeping here!” Baby Bear cried.'),
      line('ゴルディロックス|は|目[め]を覚[さ]まして|、|三[さん]びき|を|見[み]て|驚[おどろ]いた|。', 'Goldilocks woke, saw the three bears and was startled.'),
      line('窓[まど]|から|逃[に]げようとした|が#but|、|お母[かあ]さんぐま|が|「|待[ま]って|。|怖[こわ]くない|」|と|言[い]った|。', 'She tried to flee through the window, but Mother Bear said, “Wait. We will not hurt you.”'),
      line('ゴルディロックス|は|勝[かっ]手[て]に|家[いえ]|を|使[つか]ったこと|を|謝[あやま]った|。', 'Goldilocks apologised for using the house without permission.'),
      line('子[こ]ぐま|の|いす|を|直[なお]す|と|約[やく]束[そく]した|。', 'She promised to repair Baby Bear’s chair.'),
      line('四[よ]人[にん]|は|温[あたた]かい|スープ|を|新[あたら]しい|いす|で|一[いっ]緒[しょ]に|食[た]べた|。', 'The four ate warm soup together on the repaired chair.'),
      line('それから|、|ゴルディロックス|は|訪[たず]ねる時[とき]|、|必[かなら]ず|先[さき]に|聞[き]くようになった|。', 'After that, Goldilocks always asked before visiting.'),
    ],
  ],
});

const shirayukihime = expandStory({
  id: 'shirayukihime', title: { ja: '白雪姫', en: 'Snow White' }, series: null,
  level: 'L4', gram: 'G4',
  blurb: 'A princess escapes a jealous queen and finds an unexpected home beyond the forest.',
  source: SOL_SOURCE('Traditional European tale (Snow White)', 'An original graded retelling with a gentle resolution and no wording from a published edition.'),
  nw: ['白雪姫', 'マジックミラー', 'ドワーフ', 'りんご', '嫉妬'],
  lexicon: lexicon({
    'そこ': ['there', 'n'], 'です': ['is', 'aux'], 'では': ['as for; by means of', 'part'], 'ミラー': ['mirror', 'n'],
    '人[ひと]': ['person', 'n'], '全[ぜん]部[ぶ]': ['everything', 'n'], '道[みち]': ['road', 'n'],
    'ドワーフたち': ['the dwarfs', 'n'], '自[じ]分[ぶん]': ['oneself', 'pn'], '行[おこな]い': ['conduct, actions', 'n'],
    '願[ねが]った': ['wished', 'v', { df: '願う', cf: 'plain past' }], '美[うつく]しい': ['beautiful', 'adj'], '美[うつく]しさ': ['beauty', 'n'],
    '受[う]け取[と]った': ['accepted', 'v', { df: '受け取る', cf: 'plain past' }], '呼[よ]んでも': ['even when they called', 'v', { df: '呼ぶ', cf: 'te-form concessive 〜ても' }],
    '申[もう]し出[で]た': ['offered', 'v', { df: '申し出る', cf: 'plain past' }], '話[はな]した': ['told', 'v', { df: '話す', cf: 'plain past' }],
    '落[お]ちた': ['fell', 'v', { df: '落ちる', cf: 'plain past' }], '送[おく]られた': ['was sent', 'v', { df: '送る', cf: 'plain past passive' }],
    '遠[とお]い': ['distant', 'adj'], '考[かんが]えることになった': ['was made to reflect', 'v', { df: '考える', cf: 'plain past 〜ことになる form' }],
    '本[ほん]当[とう]の': ['true, real', 'adj'],
    '昔[むかし]': ['long ago', 'adv'], '雪[ゆき]': ['snow', 'n'], '白[しろ]い': ['white', 'adj'], '肌[はだ]': ['skin', 'n'], '姫[ひめ]': ['princess', 'n'], '白[しら]雪[ゆき]姫[ひめ]': ['Snow White', 'pn'], '呼[よ]ばれていた': ['was called', 'v', { df: '呼ぶ', cf: 'plain past passive progressive' }],
    '母[はは]': ['mother', 'n'], '亡[な]くなった後[あと]': ['after she died', 'v', { df: '亡くなる', cf: 'plain past time clause' }], '王[おう]': ['king', 'n'], '新[あたら]しい': ['new', 'adj'], '王[おう]妃[ひ]': ['queen', 'n'], '迎[むか]えた': ['welcomed; married', 'v', { df: '迎える', cf: 'plain past' }],
    '美[うつく]しかった': ['was beautiful', 'adj', { df: '美しい', cf: 'plain past' }], 'が#but': ['but, although', 'part'], '誰[だれ]よりも': ['more than anyone', 'adv'], '美[うつく]しくありたい': ['wanted to be beautiful', 'adj', { df: '美しい', cf: 'desiderative 〜くありたい form' }],
    '毎[まい]朝[あさ]': ['every morning', 'adv'], 'マジックミラー': ['magic mirror', 'n'], '国[くに]': ['country, kingdom', 'n'], '一[いち]番[ばん]': ['most; number one', 'adv'], '尋[たず]ねた': ['asked', 'v', { df: '尋ねる', cf: 'plain past' }],
    '初[はじ]め': ['at first', 'adv'], 'あなた': ['you', 'pn'], '答[こた]えていた': ['kept answering', 'v', { df: '答える', cf: 'plain past progressive' }], 'ある日[ひ]': ['one day', 'adv'], '成[せい]長[ちょう]した': ['grown', 'v', { df: '成長する', cf: 'plain past' }], '名[な]前[まえ]': ['name', 'n'], '告[つ]げた': ['announced', 'v', { df: '告げる', cf: 'plain past' }],
    '嫉[しっ]妬[と]した': ['became jealous', 'v', { df: '嫉妬する', cf: 'plain past' }], '狩[か]人[りゅうど]': ['huntsman', 'n'], '森[もり]': ['forest', 'n'], '連[つ]れていくよう命[めい]じた': ['ordered to take away', 'v', { df: '連れていくよう命じる', cf: 'plain past' }],
    'しかし': ['however', 'adv'], '優[やさ]しい': ['kind', 'adj'], '傷[きず]つけられなかった': ['could not hurt', 'v', { df: '傷つける', cf: 'plain past potential negative' }], '遠[とお]く': ['far away', 'adv'], '逃[に]げるよう勧[すす]めた': ['urged her to flee', 'v', { df: '逃げるよう勧める', cf: 'plain past' }],
    '一[ひと]人[り]で': ['alone', 'adv'], '奥[おく]': ['depths', 'n'], '歩[ある]き続[つづ]けた': ['kept walking', 'v', { df: '歩き続ける', cf: 'plain past' }], '夜[よる]': ['night', 'n'], '小[ちい]さな': ['small', 'adj'], 'コテージ': ['cottage', 'n'], '見[み]つけた': ['found', 'v', { df: '見つける', cf: 'plain past' }],
    '中[なか]': ['inside', 'n'], '七[なな]つ': ['seven things', 'num'], 'ベッド': ['beds', 'n'], 'カップ': ['cups', 'n'], '並[なら]んでいた': ['were lined up', 'v', { df: '並ぶ', cf: 'plain past progressive' }], '疲[つか]れ果[は]てていた': ['was exhausted', 'v', { df: '疲れ果てる', cf: 'plain past progressive' }], '眠[ねむ]った': ['slept', 'v', { df: '眠る', cf: 'plain past' }],
    '住[す]んでいた': ['lived', 'v', { df: '住む', cf: 'plain past progressive' }], '七[なな]人[にん]': ['seven people', 'num'], 'ドワーフ': ['dwarfs', 'n'], '鉱[こう]山[ざん]': ['mine', 'n'], '帰[かえ]ってきた': ['returned', 'v', { df: '帰ってくる', cf: 'plain past' }],
    '驚[おどろ]いた': ['were surprised', 'v', { df: '驚く', cf: 'plain past' }], '事[じ]情[じょう]': ['circumstances', 'n'], '聞[き]いて': ['hearing; heard and', 'v', { df: '聞く', cf: 'te-form' }], '一[いっ]緒[しょ]に': ['together', 'adv'], '暮[く]らしてもよい': ['may live', 'v', { df: '暮らす', cf: 'plain permission 〜てもよい form' }], '言[い]った': ['said', 'v', { df: '言う', cf: 'plain past' }],
    '白[しら]雪[ゆき]姫[ひめ]': ['Snow White', 'pn'], '料[りょう]理[り]': ['cooking', 'n'], '掃[そう]除[じ]': ['cleaning', 'n'], '手[て]伝[つだ]い': ['helping; helped and', 'v', { df: '手伝う', cf: 'continuative form' }], '楽[たの]しく': ['happily', 'adv', { df: '楽しい', cf: 'adverbial form' }], '過[す]ごした': ['spent time', 'v', { df: '過ごす', cf: 'plain past' }],
    '一[いっ]方[ぽう]': ['meanwhile', 'adv'], '生[い]きている': ['is alive', 'v', { df: '生きる', cf: 'plain present progressive' }], '知[し]った': ['learned', 'v', { df: '知る', cf: 'plain past' }], '老[ろう]婆[ば]': ['old woman', 'n'], '姿[すがた]': ['appearance', 'n'], '変[か]え': ['changing; changed and', 'v', { df: '変える', cf: 'continuative form' }], 'コルセット': ['corset', 'n'], '売[う]りに来[き]た': ['came to sell', 'v', { df: '売りに来る', cf: 'plain past' }],
    '留[る]守[す]番[ばん]をしていた': ['was minding the house', 'v', { df: '留守番をする', cf: 'plain past progressive' }], 'ドア': ['door', 'n'], '開[あ]けてしまった': ['opened despite herself', 'v', { df: '開ける', cf: 'plain past 〜てしまう form' }], '強[つよ]く': ['tightly', 'adv'], '締[し]められ': ['was tightened', 'v', { df: '締める', cf: 'continuative passive' }], '倒[たお]れた': ['collapsed', 'v', { df: '倒れる', cf: 'plain past' }],
    '夕[ゆう]方[がた]': ['evening', 'n'], 'ひも': ['cord', 'n'], '切[き]って': ['cutting; cut and', 'v', { df: '切る', cf: 'te-form' }], '助[たす]けた': ['rescued', 'v', { df: '助ける', cf: 'plain past' }], '知[し]らない人[ひと]': ['stranger', 'n'], '入[い]れてはいけない': ['must not let in', 'v', { df: '入れる', cf: 'plain prohibition 〜てはいけない' }], '警[けい]告[こく]した': ['warned', 'v', { df: '警告する', cf: 'plain past' }],
    '二[に]度[ど]目[め]': ['second time', 'n'], '毒[どく]': ['poison', 'n'], '入[はい]った': ['containing; entered', 'v', { df: '入る', cf: 'plain past' }], 'くし': ['comb', 'n'], '持[も]ってきた': ['brought', 'v', { df: '持ってくる', cf: 'plain past' }], '窓[まど]': ['window', 'n'], '閉[し]めたまま': ['kept closed', 'v', { df: '閉める', cf: 'plain past 〜たまま form' }], '断[ことわ]った': ['refused', 'v', { df: '断る', cf: 'plain past' }],
    '王[おう]妃[ひ]': ['queen', 'n'], 'あきらめず': ['without giving up', 'v', { df: 'あきらめる', cf: 'negative continuative 〜ず form' }], '赤[あか]い': ['red', 'adj'], 'りんご': ['apple', 'n'], '半[はん]分[ぶん]': ['half', 'n'], '毒[どく]入[い]り': ['poisoned', 'adj'], '作[つく]った': ['made', 'v', { df: '作る', cf: 'plain past' }],
    '安[あん]全[ぜん]な': ['safe', 'adj'], '側[がわ]': ['side', 'n'], '食[た]べて見[み]せた': ['ate to demonstrate', 'v', { df: '食べて見せる', cf: 'plain past' }], '疑[うたが]わず': ['without suspecting', 'v', { df: '疑う', cf: 'negative continuative 〜ず form' }], '毒[どく]入[い]りの側[がわ]': ['poisoned side', 'n'], 'かじった': ['bit into', 'v', { df: 'かじる', cf: 'plain past' }],
    '深[ふか]い': ['deep', 'adj'], '眠[ねむ]り': ['sleep', 'n'], '目[め]を覚[さ]まさなかった': ['did not wake', 'v', { df: '目を覚ます', cf: 'plain past negative' }], 'ガラス': ['glass', 'n'], '箱[はこ]': ['case, box', 'n'], '寝[ね]かせ': ['laying; laid and', 'v', { df: '寝かせる', cf: 'continuative form' }], 'そば': ['beside', 'n'], '見[み]守[まも]った': ['watched over', 'v', { df: '見守る', cf: 'plain past' }],
    '数[すう]日[じつ]後[ご]': ['several days later', 'adv'], '旅[たび]': ['journey', 'n'], '王[おう]子[じ]': ['prince', 'n'], '通[とお]りかかった': ['happened to pass', 'v', { df: '通りかかる', cf: 'plain past' }], '運[はこ]ぶ': ['carry', 'v'], '手[て]伝[つだ]った': ['helped', 'v', { df: '手伝う', cf: 'plain past' }], '段[だん]差[さ]': ['bump, step', 'n'], '揺[ゆ]れた': ['shook', 'v', { df: '揺れる', cf: 'plain past' }], 'かけら': ['piece', 'n'], '喉[のど]': ['throat', 'n'], '飛[と]び出[だ]した': ['flew out', 'v', { df: '飛び出す', cf: 'plain past' }],
    '目[め]を開[あ]けた': ['opened her eyes', 'v', { df: '目を開ける', cf: 'plain past' }], '再[さい]会[かい]': ['reunion', 'n'], '喜[よろこ]んだ': ['rejoiced', 'v', { df: '喜ぶ', cf: 'plain past' }], '城[しろ]': ['castle', 'n'], '戻[もど]り': ['returning; returned and', 'v', { df: '戻る', cf: 'continuative form' }], '鏡[かがみ]': ['mirror', 'n'], '見[み]ることをやめた': ['stopped looking at', 'v', { df: '見る', cf: 'plain past 〜ことをやめる form' }], '幸[しあわ]せ': ['happiness', 'n'], '測[はか]れない': ['cannot be measured', 'v', { df: '測る', cf: 'plain present potential negative' }], '気[き]づいた': ['realised', 'v', { df: '気づく', cf: 'plain past' }],
  }),
  body: [
    [line('昔[むかし]|、|雪[ゆき]|のように|白[しろ]い|肌[はだ]|の|姫[ひめ]|が|白[しら]雪[ゆき]姫[ひめ]|と|呼[よ]ばれていた|。','Long ago, a princess with skin white as snow was called Snow White.'),line('母[はは]|が|亡[な]くなった後[あと]|、|王[おう]|は|新[あたら]しい|王[おう]妃[ひ]|を|迎[むか]えた|。','After her mother died, the king married a new queen.'),line('王[おう]妃[ひ]|は|美[うつく]しかった|が#but|、|誰[だれ]よりも|美[うつく]しくありたい|と|願[ねが]った|。','The queen was beautiful, but wished to be more beautiful than anyone.'),line('毎[まい]朝[あさ]|、|マジックミラー|に|国[くに]|で|一[いち]番[ばん]|美[うつく]しい|人[ひと]|を|尋[たず]ねた|。','Every morning she asked her magic mirror who was fairest in the kingdom.'),line('初[はじ]め|、|ミラー|は|「|あなた|です|」|と|答[こた]えていた|。','At first, the mirror answered, “You are.”'),line('ある日[ひ]|、|ミラー|は|成[せい]長[ちょう]した|白[しら]雪[ゆき]姫[ひめ]|の|名[な]前[まえ]|を|告[つ]げた|。','One day, the mirror named the now-grown Snow White.'),line('嫉[しっ]妬[と]した|王[おう]妃[ひ]|は|、|狩[か]人[りゅうど]|に|姫[ひめ]|を|森[もり]|へ|連[つ]れていくよう命[めい]じた|。','Jealous, the queen ordered a huntsman to take the princess into the forest.'),line('しかし|、|優[やさ]しい|狩[か]人[りゅうど]|は|白[しら]雪[ゆき]姫[ひめ]|を|傷[きず]つけられなかった|。','But the kind huntsman could not hurt her.'),line('遠[とお]く|へ|逃[に]げるよう勧[すす]めた|。','He urged her to flee far away.'),line('白[しら]雪[ゆき]姫[ひめ]|は|一[ひと]人[り]で|森[もり]|の|奥[おく]|を|歩[ある]き続[つづ]けた|。','Snow White walked alone into the forest.')],
    [line('夜[よる]|、|小[ちい]さな|コテージ|を|見[み]つけた|。','At night, she found a small cottage.'),line('中[なか]|に|七[なな]つ|の|ベッド|と|カップ|が|並[なら]んでいた|。','Inside were seven beds and seven cups.'),line('疲[つか]れ果[は]てていた|ので|、|一[いち]番[ばん]|小[ちい]さな|ベッド|で|眠[ねむ]った|。','Exhausted, she slept in the smallest bed.'),line('そこ|に|住[す]んでいた|七[なな]人[にん]|の|ドワーフ|が|鉱[こう]山[ざん]|から|帰[かえ]ってきた|。','The seven dwarfs who lived there returned from the mine.'),line('ドワーフたち|は|驚[おどろ]いた|が#but|、|事[じ]情[じょう]|を|聞[き]いて|一[いっ]緒[しょ]に|暮[く]らしてもよい|と|言[い]った|。','They were surprised, but heard her story and invited her to stay.'),line('白[しら]雪[ゆき]姫[ひめ]|は|料[りょう]理[り]|と|掃[そう]除[じ]|を|手[て]伝[つだ]い|、|楽[たの]しく|過[す]ごした|。','Snow White helped cook and clean and lived happily.'),line('一[いっ]方[ぽう]|、|王[おう]妃[ひ]|は|ミラー|から|姫[ひめ]|が|生[い]きている|と|知[し]った|。','Meanwhile, the mirror told the queen the princess still lived.'),line('老[ろう]婆[ば]|に|姿[すがた]|を|変[か]え|、|コルセット|を|売[う]りに来[き]た|。','Disguised as an old woman, she came selling a corset.'),line('留[る]守[す]番[ばん]をしていた|姫[ひめ]|は|ドア|を|開[あ]けてしまった|。','Snow White, minding the house, opened the door.'),line('コルセット|を|強[つよ]く|締[し]められ|、|姫[ひめ]|は|倒[たお]れた|。','The corset was pulled tight and she collapsed.')],
    [line('夕[ゆう]方[がた]|、|ドワーフたち|が|ひも|を|切[き]って|助[たす]けた|。','That evening, the dwarfs cut the cord and saved her.'),line('「|知[し]らない人[ひと]|を|入[い]れてはいけない|」|と|警[けい]告[こく]した|。','They warned her not to admit strangers.'),line('二[に]度[ど]目[め]|、|王[おう]妃[ひ]|は|毒[どく]|の|入[はい]った|くし|を|持[も]ってきた|。','The second time, the queen brought a poisoned comb.'),line('白[しら]雪[ゆき]姫[ひめ]|は|窓[まど]|を|閉[し]めたまま|断[ことわ]った|。','Snow White kept the window shut and refused.'),line('王[おう]妃[ひ]|は|あきらめず|、|赤[あか]い|りんご|を|半[はん]分[ぶん]|だけ|毒[どく]入[い]り|に|作[つく]った|。','The queen persisted, poisoning just half a red apple.'),line('安[あん]全[ぜん]な|側[がわ]|を|食[た]べて見[み]せた|ので|、|姫[ひめ]|は|疑[うたが]わず|受[う]け取[と]った|。','She ate the safe side, so the princess accepted it.'),line('毒[どく]入[い]りの側[がわ]|を|かじった|白[しら]雪[ゆき]姫[ひめ]|は|、|深[ふか]い|眠[ねむ]り|に|落[お]ちた|。','Snow White bit the poisoned side and fell into deep sleep.'),line('ドワーフたち|が|呼[よ]んでも|、|目[め]を覚[さ]まさなかった|。','She did not wake when the dwarfs called.'),line('七[なな]人[にん]|は|姫[ひめ]|を|ガラス|の|箱[はこ]|に|寝[ね]かせ|、|そば|で|見[み]守[まも]った|。','They laid her in a glass case and watched beside her.'),line('数[すう]日[じつ]後[ご]|、|旅[たび]|の|王[おう]子[じ]|が|通[とお]りかかった|。','Several days later, a travelling prince passed by.')],
    [line('王[おう]子[じ]|は|ガラス|の|箱[はこ]|を|城[しろ]|へ|運[はこ]ぶ|手[て]伝[つだ]い|を|申[もう]し出[で]た|。','The prince offered to help carry the glass case to the castle.'),line('道[みち]|の|段[だん]差[さ]|で|箱[はこ]|が|揺[ゆ]れた|。','The case jolted at a bump in the road.'),line('りんご|の|かけら|が|白[しら]雪[ゆき]姫[ひめ]|の|喉[のど]|から|飛[と]び出[だ]した|。','The piece of apple flew from Snow White’s throat.'),line('姫[ひめ]|は|目[め]を開[あ]けた|。','The princess opened her eyes.'),line('ドワーフたち|は|再[さい]会[かい]|を|喜[よろこ]んだ|。','The dwarfs rejoiced at their reunion.'),line('白[しら]雪[ゆき]姫[ひめ]|は|城[しろ]|へ|戻[もど]り|、|王[おう]|に|全[ぜん]部[ぶ]|を|話[はな]した|。','Snow White returned to the castle and told the king everything.'),line('王[おう]妃[ひ]|は|遠[とお]い|国[くに]|へ|送[おく]られた|。','The queen was sent to a distant country.'),line('そこ|で|自[じ]分[ぶん]|の|行[おこな]い|を|考[かんが]えることになった|。','There she had to reflect on her actions.'),line('白[しら]雪[ゆき]姫[ひめ]|は|マジックミラー|を|見[み]ることをやめた|。','Snow White stopped consulting the magic mirror.'),line('本[ほん]当[とう]の|幸[しあわ]せ|は|美[うつく]しさ|では|測[はか]れない|と|気[き]づいた|。','She realised true happiness cannot be measured by beauty.')],
  ],
});

export const STORY_SOURCES = [ariToHato, ookamiGaKita, goldilocks, shirayukihime];
