import { expandStory, lexicon, line } from './helpers.mjs';

const SOL_SOURCE = (text, notes, licence) => ({
  kind: 'adapted', text, by: 'Sol 5.6', credit: 'Retold by', notes, licence,
});

const aladdin = expandStory({
  id: 'aladdin-to-mahou-no-lamp',
  title: { ja: 'アラジンと魔法のランプ', en: 'Aladdin and the Magic Lamp' },
  series: null,
  level: 'L5',
  gram: 'G5',
  blurb: 'A poor market worker finds a lamp of impossible power and must outwit the magician who buried it.',
  source: SOL_SOURCE(
    'Traditional tale associated with One Thousand and One Nights (Aladdin and the Magic Lamp)',
    'An original retelling assembled from long-established public-domain plot elements, not translated from a particular edition.',
    'Public domain (traditional tale). This retelling and its English translation are original to Kana Quest.',
  ),
  nw: ['アラジン', 'ランプ', '精霊', '魔術師', '宝石'],
  lexicon: lexicon({
    '遠[とお]い': ['faraway, distant', 'adj'],
    '国[くに]': ['country, land', 'n'],
    'にぎやかな': ['lively, bustling', 'adj', { df: 'にぎやかだ', cf: 'na-adjective form' }],
    '町[まち]': ['town, city', 'n'],
    'アラジン': ['Aladdin', 'pn'],
    '若[わか]者[もの]': ['young man', 'n'],
    '母[はは]親[おや]': ['mother', 'n'],
    '暮[く]らしていた': ['was living', 'v', { df: '暮らす', cf: 'plain past progressive' }],
    'バザール': ['bazaar, marketplace', 'n'],
    '荷[に]物[もつ]': ['loads, luggage', 'n'],
    '運[はこ]び': ['carrying; carried and', 'v', { df: '運ぶ', cf: 'continuative form' }],
    '少[すこ]しずつ': ['little by little', 'adv'],
    '家[か]計[けい]': ['household finances', 'n'],
    '助[たす]けていた': ['was helping', 'v', { df: '助ける', cf: 'plain past progressive' }],
    '二[ふた]人[り]': ['the two of them', 'num'],
    '生[せい]活[かつ]': ['life, living', 'n'],
    '苦[くる]しかった': ['was difficult, hard', 'adj', { df: '苦しい', cf: 'plain past' }],
    'ある日[ひ]': ['one day', 'adv'],
    '黒[くろ]い': ['black', 'adj'],
    'マント': ['cloak', 'n'],
    '着[き]た': ['wearing', 'v', { df: '着る', cf: 'plain past (modifying a noun)' }],
    '魔[ま]術[じゅつ]師[し]': ['magician, sorcerer', 'n'],
    '訪[たず]ねてきた': ['came to visit', 'v', { df: '訪ねる', cf: 'plain past 〜てくる form' }],
    '父[ちち]親[おや]': ['father', 'n'],
    '古[ふる]い': ['old, long-time', 'adj'],
    '友[ゆう]人[じん]': ['friend', 'n'],
    '名[な]乗[の]った': ['introduced himself as; claimed to be', 'v', { df: '名乗る', cf: 'plain past' }],
    '簡[かん]単[たん]な': ['simple, easy', 'adj', { df: '簡単だ', cf: 'na-adjective form' }],
    '仕[し]事[ごと]': ['work, job', 'n'],
    '報[ほう]酬[しゅう]': ['payment, reward', 'n'],
    '払[はら]う': ['will pay', 'v', { df: '払う', cf: 'plain present' }],
    '約[やく]束[そく]した': ['promised', 'v', { df: '約束する', cf: 'plain past' }],
    '疑[うたが]った': ['doubted, was suspicious', 'v', { df: '疑う', cf: 'plain past' }],
    '家[いえ]': ['home, house', 'n'],
    '楽[らく]にしたかった': ['wanted to make life easier', 'v', { df: '楽にする', cf: 'plain past desiderative' }],
    '申[もう]し出[で]': ['offer, proposal', 'n'],
    '受[う]け入[い]れた': ['accepted', 'v', { df: '受け入れる', cf: 'plain past' }],
    '翌[よく]朝[あさ]': ['the following morning', 'adv'],
    '町[まち]外[はず]れ': ['outskirts of town', 'n'],
    '出[で]た': ['left, went out', 'v', { df: '出る', cf: 'plain past' }],
    '岩[いわ]だらけ': ['covered in rocks', 'adj'],
    '谷[たに]': ['valley', 'n'],
    '越[こ]えた': ['crossed', 'v', { df: '越える', cf: 'plain past' }],
    '不[ふ]思[し]議[ぎ]な': ['mysterious, strange', 'adj', { df: '不思議だ', cf: 'na-adjective form' }],
    '粉[こな]': ['powder', 'n'],
    '火[ひ]': ['fire', 'n'],
    '投[な]げ入[い]れた': ['threw into', 'v', { df: '投げ入れる', cf: 'plain past' }],
    '地[じ]面[めん]': ['ground', 'n'],
    '揺[ゆ]れ': ['shook; shaking and', 'v', { df: '揺れる', cf: 'continuative form' }],
    '石[いし]': ['stone', 'n'],
    '扉[とびら]': ['door', 'n'],
    '現[あらわ]れた': ['appeared', 'v', { df: '現れる', cf: 'plain past' }],
    '指[ゆび]輪[わ]': ['ring', 'n'],
    '渡[わた]した': ['handed, gave', 'v', { df: '渡す', cf: 'plain past' }],
    '洞[どう]窟[くつ]': ['cave', 'n'],
    '守[まも]ってくれる': ['will protect', 'v', { df: '守る', cf: 'plain present 〜てくれる form' }],
    '説[せつ]明[めい]した': ['explained', 'v', { df: '説明する', cf: 'plain past' }],
    '中[なか]': ['inside', 'n'],
    '入[はい]れる': ['can enter', 'v', { df: '入る', cf: 'potential form' }],
    '君[きみ]': ['you', 'pn'],
    '言[い]われた': ['was told', 'v', { df: '言う', cf: 'plain past passive' }],
    '一[いち]番[ばん]奥[おく]': ['very back, deepest part', 'n'],
    '古[ふる]い': ['old', 'adj'],
    'ランプ': ['lamp', 'n'],
    '持[も]ってこい': ['bring it here', 'v', { df: '持ってくる', cf: 'plain imperative' }],
    '命[めい]じた': ['ordered, commanded', 'v', { df: '命じる', cf: 'plain past' }],
    '長[なが]い': ['long', 'adj'],
    '階[かい]段[だん]': ['staircase, steps', 'n'],
    '下[お]りていった': ['went down', 'v', { df: '下りていく', cf: 'plain past 〜ていく form' }],
    '地[ち]下[か]': ['underground', 'n'],
    '庭[にわ]': ['garden', 'n'],
    '木[き]': ['trees', 'n'],
    '宝[ほう]石[せき]': ['jewels, gemstones', 'n'],
    '果[くだ]物[もの]': ['fruit', 'n'],
    '実[みの]っていた': ['were growing; bearing fruit', 'v', { df: '実る', cf: 'plain past progressive' }],
    'ルビー': ['ruby', 'n'],
    'サファイア': ['sapphire', 'n'],
    'エメラルド': ['emerald', 'n'],
    '枝[えだ]': ['branches', 'n'],
    '輝[かがや]いていた': ['were sparkling', 'v', { df: '輝く', cf: 'plain past progressive' }],
    '夢[ゆめ]中[ちゅう]で': ['absorbed; eagerly', 'adv', { df: '夢中だ', cf: 'adverbial form' }],
    'ポケット': ['pockets', 'n'],
    '詰[つ]めた': ['filled, stuffed', 'v', { df: '詰める', cf: 'plain past' }],
    '小[ちい]さな': ['small', 'adj'],
    '部[へ]屋[や]': ['room', 'n'],
    '汚[よご]れた': ['dirty, tarnished', 'adj', { df: '汚れる', cf: 'plain past (modifying a noun)' }],
    '見[み]つけた': ['found', 'v', { df: '見つける', cf: 'plain past' }],
    '抱[かか]えて': ['holding in his arms', 'v', { df: '抱える', cf: 'te-form' }],
    '入[い]り口[ぐち]': ['entrance', 'n'],
    '戻[もど]った': ['returned', 'v', { df: '戻る', cf: 'plain past' }],
    '先[さき]に': ['first, before anything else', 'adv'],
    '渡[わた]せ': ['hand it over', 'v', { df: '渡す', cf: 'plain imperative' }],
    '叫[さけ]んだ': ['shouted', 'v', { df: '叫ぶ', cf: 'plain past' }],
    '引[ひ]き上[あ]げてください': ['please pull me up', 'v', { df: '引き上げる', cf: 'polite request form' }],
    '頼[たの]んだ': ['asked, pleaded', 'v', { df: '頼む', cf: 'plain past' }],
    '腹[はら]を立[た]て': ['becoming angry; angered and', 'v', { df: '腹を立てる', cf: 'continuative form' }],
    '呪[じゅ]文[もん]': ['spell, incantation', 'n'],
    '唱[とな]えた': ['chanted, recited', 'v', { df: '唱える', cf: 'plain past' }],
    '閉[と]じられた': ['was sealed, closed', 'v', { df: '閉じる', cf: 'plain past passive' }],
    '暗[くら]闇[やみ]': ['darkness', 'n'],
    '取[と]り残[のこ]された': ['was left trapped', 'v', { df: '取り残す', cf: 'plain past passive' }],
    '恐[おそ]ろしさ': ['fear, terror', 'n'],
    '手[て]': ['hands', 'n'],
    'こすった': ['rubbed', 'v', { df: 'こする', cf: 'plain past' }],
    '突[とつ]然[ぜん]': ['suddenly', 'adv'],
    '青[あお]い': ['blue', 'adj'],
    '煙[けむり]': ['smoke', 'n'],
    '指[ゆび]輪[わ]の精[せい]': ['spirit of the ring', 'n'],
    '現[あらわ]れた': ['appeared', 'v', { df: '現れる', cf: 'plain past' }],
    '望[のぞ]み': ['wish, desire', 'n'],
    '聞[き]いた': ['asked; heard', 'v', { df: '聞く', cf: 'plain past' }],
    '帰[かえ]してほしい': ['want you to send me home', 'v', { df: '帰す', cf: 'plain desiderative 〜てほしい form' }],
    '答[こた]えた': ['answered', 'v', { df: '答える', cf: 'plain past' }],
    '次[つぎ]': ['next moment', 'n'],
    '瞬[しゅん]間[かん]': ['instant, moment', 'n'],
    '家[いえ]': ['home', 'n'],
    '立[た]っていた': ['was standing', 'v', { df: '立つ', cf: 'plain past progressive' }],
    '無[ぶ]事[じ]な': ['safe, unharmed', 'adj', { df: '無事だ', cf: 'na-adjective form' }],
    '姿[すがた]': ['figure, appearance', 'n'],
    '見[み]て': ['seeing; saw and', 'v', { df: '見る', cf: 'te-form' }],
    '涙[なみだ]を流[なが]した': ['shed tears', 'v', { df: '涙を流す', cf: 'plain past' }],
    '数[すう]日[じつ]後[ご]': ['several days later', 'adv'],
    '売[う]ろうとして': ['trying to sell', 'v', { df: '売る', cf: '"try to" form' }],
    '布[ぬの]': ['cloth', 'n'],
    '磨[みが]いた': ['polished', 'v', { df: '磨く', cf: 'plain past' }],
    '巨[きょ]大[だい]な': ['enormous', 'adj', { df: '巨大だ', cf: 'na-adjective form' }],
    'ランプの精[せい]': ['spirit of the lamp', 'n'],
    '呼[よ]び出[だ]された': ['was summoned', 'v', { df: '呼び出す', cf: 'plain past passive' }],
    '主[しゅ]人[じん]': ['master', 'n'],
    '何[なん]なりと': ['anything you wish', 'adv'],
    'ご命[めい]令[れい]ください': ['please command me', 'v', { df: '命令する', cf: 'honorific request form' }],
    '深[ふか]い': ['deep, profound', 'adj'],
    '声[こえ]': ['voice', 'n'],
    '告[つ]げた': ['declared, told', 'v', { df: '告げる', cf: 'plain past' }],
    '温[あたた]かい': ['warm', 'adj'],
    '食[しょく]事[じ]': ['meal', 'n'],
    '願[ねが]った': ['wished for', 'v', { df: '願う', cf: 'plain past' }],
    '銀[ぎん]': ['silver', 'n'],
    'トレー': ['trays', 'n'],
    'スープ': ['soup', 'n'],
    '焼[や]きたて': ['freshly baked', 'adj'],
    'パン': ['bread', 'n'],
    '並[なら]んだ': ['were laid out, appeared', 'v', { df: '並ぶ', cf: 'plain past' }],
    '残[のこ]った': ['remaining', 'adj', { df: '残る', cf: 'plain past (modifying a noun)' }],
    '少[すこ]しずつ': ['little by little', 'adv'],
    '売[う]り': ['selling; sold and', 'v', { df: '売る', cf: 'continuative form' }],
    '穏[おだ]やかに': ['comfortably, peacefully', 'adv', { df: '穏やかだ', cf: 'adverbial form' }],
    '暮[く]らせるようになった': ['became able to live', 'v', { df: '暮らす', cf: 'plain past potential 〜ようになる form' }],
    '王[おう]宮[きゅう]': ['royal palace', 'n'],
    '春[はる]': ['spring', 'n'],
    '祭[まつ]り': ['festival', 'n'],
    '開[ひら]かれる': ['will be held', 'v', { df: '開く', cf: 'plain present passive' }],
    '知[し]らせ': ['announcement, news', 'n'],
    '姫[ひめ]': ['princess', 'n'],
    '町[まち]の人[ひと]たち': ['townspeople', 'n'],
    '公[こう]平[へい]に': ['fairly', 'adv', { df: '公平だ', cf: 'adverbial form' }],
    '話[はな]す': ['speaking; talks', 'v', { df: '話す', cf: 'plain present' }],
    '様[よう]子[す]': ['manner, behaviour', 'n'],
    '見[み]た': ['saw', 'v', { df: '見る', cf: 'plain past' }],
    '美[うつく]しさ': ['beauty', 'n'],
    '思[おも]いやり': ['thoughtfulness, compassion', 'n'],
    '心[こころ]を動[うご]かされた': ['was moved', 'v', { df: '心を動かす', cf: 'plain past passive' }],
    '結[けっ]婚[こん]を申[もう]し込[こ]みたい': ['wanted to propose marriage', 'v', { df: '結婚を申し込む', cf: 'plain desiderative' }],
    '打[う]ち明[あ]けた': ['confided, revealed', 'v', { df: '打ち明ける', cf: 'plain past' }],
    '母[はは]親[おや]': ['mother', 'n'],
    '布[ぬの]袋[ぶくろ]': ['cloth bag', 'n'],
    '詰[つ]め': ['packing; packed and', 'v', { df: '詰める', cf: 'continuative form' }],
    '王[おう]様[さま]': ['king', 'n'],
    '届[とど]けた': ['delivered', 'v', { df: '届ける', cf: 'plain past' }],
    'ダイヤモンド': ['diamonds', 'n'],
    '見[み]たことがありません': ['has never seen', 'v', { df: '見る', cf: 'polite perfect negative' }],
    '驚[おどろ]かれた': ['was astonished', 'v', { df: '驚く', cf: 'honorific past' }],
    '娘[むすめ]': ['daughter', 'n'],
    '迎[むか]える': ['to welcome; marry into the family', 'v', { df: '迎える', cf: 'plain present' }],
    'ふさわしい': ['worthy, suitable', 'adj'],
    '宮[きゅう]殿[でん]': ['palace', 'n'],
    '建[た]てなければならない': ['must build', 'v', { df: '建てる', cf: '〜なければならない form' }],
    '条[じょう]件[けん]': ['condition, requirement', 'n'],
    '出[だ]された': ['was given, imposed', 'v', { df: '出す', cf: 'plain past passive' }],
    '今[こん]度[ど]': ['this time', 'n'],
    '立[りっ]派[ぱ]な': ['splendid, magnificent', 'adj', { df: '立派だ', cf: 'na-adjective form' }],
    '頼[たの]んだ': ['asked for', 'v', { df: '頼む', cf: 'plain past' }],
    '一[いち]夜[や]': ['one night; overnight', 'n'],
    '金[きん]色[いろ]': ['golden', 'adj'],
    'ドーム': ['dome', 'n'],
    'モザイク': ['mosaic', 'n'],
    '床[ゆか]': ['floor', 'n'],
    'カーペット': ['carpets', 'n'],
    '敷[し]かれた': ['were laid', 'v', { df: '敷く', cf: 'plain past passive' }],
    '招[まね]かれた': ['was invited', 'v', { df: '招く', cf: 'plain past passive' }],
    'アラジンと話[はな]し': ['talking with Aladdin; talked and', 'v', { df: '話す', cf: 'continuative form' }],
    '正[しょう]直[じき]さ': ['honesty', 'n'],
    '好[す]きになった': ['came to like', 'v', { df: '好きになる', cf: 'plain past' }],
    '結[けっ]婚[こん]': ['marriage', 'n'],
    '同[どう]意[い]した': ['agreed', 'v', { df: '同意する', cf: 'plain past' }],
    '町[まち]全[ぜん]体[たい]': ['the whole town', 'n'],
    '祝[いわ]った': ['celebrated', 'v', { df: '祝う', cf: 'plain past' }],
    '一[いっ]方[ぽう]': ['meanwhile', 'adv'],
    '遠[とお]く': ['far away', 'adv'],
    'うわさ': ['rumour', 'n'],
    '聞[き]いた': ['heard', 'v', { df: '聞く', cf: 'plain past' }],
    '商[しょう]人[にん]': ['merchant', 'n'],
    '姿[すがた]': ['appearance, guise', 'n'],
    '変[か]えて': ['changing; changed and', 'v', { df: '変える', cf: 'te-form' }],
    '戻[もど]ってきた': ['came back', 'v', { df: '戻る', cf: 'plain past 〜てくる form' }],
    '新[あたら]しい': ['new', 'adj'],
    '交[こう]換[かん]します': ['will exchange', 'v', { df: '交換する', cf: 'polite present/future' }],
    '呼[よ]び歩[ある]いた': ['walked around calling out', 'v', { df: '呼び歩く', cf: 'plain past' }],
    '召[め]し使[つか]い': ['servant', 'n'],
    '価[か]値[ち]': ['value', 'n'],
    '知[し]らず': ['without knowing', 'v', { df: '知る', cf: '"without ...ing" form' }],
    '取[と]り替[か]えた': ['exchanged, swapped', 'v', { df: '取り替える', cf: 'plain past' }],
    '砂[さ]漠[ばく]': ['desert', 'n'],
    '向[む]こう': ['far side, beyond', 'n'],
    '移[うつ]させた': ['made it move', 'v', { df: '移す', cf: 'plain past causative' }],
    '帰[かえ]ると': ['when he returned', 'v', { df: '帰る', cf: 'conditional 〜と form' }],
    '宮[きゅう]殿[でん]': ['palace', 'n'],
    '消[き]えていた': ['had disappeared', 'v', { df: '消える', cf: 'plain past perfect' }],
    '状[じょう]況[きょう]': ['situation', 'n'],
    '指[ゆび]輪[わ]': ['ring', 'n'],
    '再[ふたた]び': ['again', 'adv'],
    'こすった': ['rubbed', 'v', { df: 'こする', cf: 'plain past' }],
    'ランプの精[せい]より': ['than the spirit of the lamp', 'n'],
    '力[ちから]': ['power', 'n'],
    '弱[よわ]い': ['weaker', 'adj'],
    '運[はこ]ぶ': ['can carry, transport', 'v', { df: '運ぶ', cf: 'plain present' }],
    '密[ひそ]かに': ['secretly', 'adv', { df: '密かだ', cf: 'adverbial form' }],
    '再[さい]会[かい]した': ['reunited', 'v', { df: '再会する', cf: 'plain past' }],
    '作[さく]戦[せん]': ['plan, strategy', 'n'],
    '練[ね]った': ['devised, worked out', 'v', { df: '練る', cf: 'plain past' }],
    '姫[ひめ]': ['princess', 'n'],
    '眠[ねむ]り薬[ぐすり]': ['sleeping draught', 'n'],
    '甘[あま]い': ['sweet', 'adj'],
    'シャーベット': ['sherbet drink', 'n'],
    '混[ま]ぜた': ['mixed into', 'v', { df: '混ぜる', cf: 'plain past' }],
    '魔[ま]術[じゅつ]師[し]': ['magician', 'n'],
    '飲[の]み干[ほ]して': ['drinking it all; drank and', 'v', { df: '飲み干す', cf: 'te-form' }],
    '眠[ねむ]り込[こ]んだ': ['fell fast asleep', 'v', { df: '眠り込む', cf: 'plain past' }],
    '取[と]り戻[もど]した': ['recovered, took back', 'v', { df: '取り戻す', cf: 'plain past' }],
    '元[もと]': ['original place, former state', 'n'],
    '戻[もど]すように命[めい]じた': ['ordered it returned', 'v', { df: '戻す', cf: 'plain 〜ように命じる form' }],
    '魔[ま]術[じゅつ]師[し]': ['magician', 'n'],
    '二[に]度[ど]と': ['never again', 'adv'],
    '近[ちか]づけない': ['unable to approach', 'v', { df: '近づく', cf: 'plain potential negative' }],
    '遠[とお]い': ['faraway', 'adj'],
    '送[おく]られた': ['was sent', 'v', { df: '送る', cf: 'plain past passive' }],
    '人[ひと]たち': ['people', 'n'],
    '無[ぶ]事[じ]': ['safe return, safety', 'n'],
    '喜[よろこ]んだ': ['rejoiced', 'v', { df: '喜ぶ', cf: 'plain past' }],
    '洞[どう]窟[くつ]': ['cave', 'n'],
    '忘[わす]れなかった': ['did not forget', 'v', { df: '忘れる', cf: 'plain past negative' }],
    '魔[ま]法[ほう]': ['magic', 'n'],
    '誰[だれ]か': ['someone, anyone', 'pn'],
    '傷[きず]つけるため': ['in order to hurt', 'v', { df: '傷つける', cf: 'purpose form' }],
    '使[つか]わないと誓[ちか]った': ['swore not to use', 'v', { df: '使う', cf: 'plain negative 〜と誓う form' }],
    '市[いち]場[ば]': ['market', 'n', { d: '市場|いちば' }],
    '病[びょう]院[いん]': ['hospital', 'n'],
    '学[がっ]校[こう]': ['school', 'n'],
    '建[た]てることにも使[つか]った': ['also used it to build', 'v', { df: '使う', cf: 'plain past purpose form' }],
    '長[なが]い': ['long', 'adj'],
    '時[じ]間[かん]': ['time', 'n'],
    '幸[しあわ]せに': ['happily', 'adv', { df: '幸せだ', cf: 'adverbial form' }],
    '暮[く]らした': ['lived', 'v', { df: '暮らす', cf: 'plain past' }],
    'ある': ['located; existing', 'v'],
    'いくつも': ['many; one after another', 'adv'],
    'こと': ['act or fact; nominaliser', 'n'],
    'しかし': ['however, but', 'adv'],
    'できる': ['can do; is possible', 'v'],
    'まず': ['first of all', 'adv'],
    'やがて': ['before long, eventually', 'adv'],
    '完[かん]成[せい]した': ['was completed', 'v', { df: '完成する', cf: 'plain past' }],
    '島[しま]': ['island', 'n'],
    '彼[かれ]': ['he, him', 'pn'],
    '所[ところ]': ['place; where someone is', 'n'],
    '時[とき]': ['when; time', 'n'],
    '気[き]づき': ['realising; realised and', 'v', { df: '気づく', cf: 'continuative form' }],
    '色[いろ]あざやかな': ['vividly coloured', 'adj', { df: '色あざやかだ', cf: 'na-adjective form' }],
    '言[い]った': ['said', 'v', { df: '言う', cf: 'plain past' }],
    '運[はこ]ばれた': ['was carried', 'v', { df: '運ぶ', cf: 'plain past passive' }],
    'が#but': ['but, although', 'part'],
  }),
  body: [
    [
      line('遠[とお]い|国[くに]|の|にぎやかな|町[まち]|に|、|アラジン|という|若[わか]者[もの]|が|母[はは]親[おや]|と|暮[く]らしていた|。', 'In a bustling town in a faraway land, a young man named Aladdin lived with his mother.'),
      line('アラジン|は|バザール|で|荷[に]物[もつ]|を|運[はこ]び|、|少[すこ]しずつ|家[か]計[けい]|を|助[たす]けていた|。', 'Aladdin carried loads in the bazaar and helped with the household money little by little.'),
      line('それでも|二[ふた]人[り]|の|生[せい]活[かつ]|は|苦[くる]しかった|。', 'Even so, life was hard for the two of them.'),
      line('ある日[ひ]|、|黒[くろ]い|マント|を|着[き]た|魔[ま]術[じゅつ]師[し]|が|訪[たず]ねてきた|。', 'One day, a magician in a black cloak came to visit.'),
      line('魔[ま]術[じゅつ]師[し]|は|父[ちち]親[おや]|の|古[ふる]い|友[ゆう]人[じん]|だ|と|名[な]乗[の]った|。', 'The magician claimed to be an old friend of Aladdin’s father.'),
      line('簡[かん]単[たん]な|仕[し]事[ごと]|に|報[ほう]酬[しゅう]|を|払[はら]う|と|約[やく]束[そく]した|。', 'He promised payment for a simple job.'),
      line('母[はは]親[おや]|は|疑[うたが]った|が#but|、|アラジン|は|家[いえ]|を|楽[らく]にしたかった|ので|申[もう]し出[で]|を|受[う]け入[い]れた|。', 'His mother was suspicious, but Aladdin accepted because he wanted to make life easier at home.'),
    ],
    [
      line('翌[よく]朝[あさ]|、|二[ふた]人[り]|は|町[まち]外[はず]れ|へ|出[で]た|。', 'The next morning, the two left the town.'),
      line('岩[いわ]だらけ|の|谷[たに]|を|いくつも|越[こ]えた|。', 'They crossed valley after rocky valley.'),
      line('魔[ま]術[じゅつ]師[し]|は|不[ふ]思[し]議[ぎ]な|粉[こな]|を|火[ひ]|に|投[な]げ入[い]れた|。', 'The magician threw a mysterious powder into a fire.'),
      line('地[じ]面[めん]|が|揺[ゆ]れ|、|石[いし]|の|扉[とびら]|が|現[あらわ]れた|。', 'The ground shook, and a stone door appeared.'),
      line('魔[ま]術[じゅつ]師[し]|は|アラジン|に|指[ゆび]輪[わ]|を|渡[わた]した|。', 'The magician gave Aladdin a ring.'),
      line('「|洞[どう]窟[くつ]|で|この|指[ゆび]輪[わ]|が|守[まも]ってくれる|」|と|説[せつ]明[めい]した|。', '“This ring will protect you in the cave,” he explained.'),
      line('「|中[なか]|に|入[はい]れる|の|は|君[きみ]|だけ|だ|」|と|言[い]われた|。', '“You are the only one who can enter,” Aladdin was told.'),
    ],
    [
      line('「|一[いち]番[ばん]奥[おく]|に|ある|古[ふる]い|ランプ|を|持[も]ってこい|」|と|命[めい]じた|。', '“Bring me the old lamp from the very back,” the magician ordered.'),
      line('アラジン|は|長[なが]い|階[かい]段[だん]|を|下[お]りていった|。', 'Aladdin went down a long staircase.'),
      line('地[ち]下[か]|の|庭[にわ]|で|、|木[き]|に|宝[ほう]石[せき]|の|果[くだ]物[もの]|が|実[みの]っていた|。', 'In an underground garden, gemstone fruit grew on the trees.'),
      line('ルビー|、|サファイア|、|エメラルド|が|枝[えだ]|で|輝[かがや]いていた|。', 'Rubies, sapphires and emeralds glittered on the branches.'),
      line('アラジン|は|夢[ゆめ]中[ちゅう]で|宝[ほう]石[せき]|を|ポケット|に|詰[つ]めた|。', 'Aladdin eagerly filled his pockets with jewels.'),
      line('一[いち]番[ばん]奥[おく]|の|小[ちい]さな|部[へ]屋[や]|で|、|汚[よご]れた|ランプ|を|見[み]つけた|。', 'In a small room at the very back, he found a dirty lamp.'),
      line('ランプ|を|抱[かか]えて|入[い]り口[ぐち]|へ|戻[もど]った|。', 'Holding the lamp, he returned to the entrance.'),
    ],
    [
      line('魔[ま]術[じゅつ]師[し]|は|「|先[さき]に|ランプ|を|渡[わた]せ|」|と|叫[さけ]んだ|。', '“Hand over the lamp first!” shouted the magician.'),
      line('アラジン|は|「|先[さき]に|私[わたし]|を|引[ひ]き上[あ]げてください|」|と|頼[たの]んだ|。', 'Aladdin pleaded, “Please pull me up first.”'),
      line('魔[ま]術[じゅつ]師[し]|は|腹[はら]を立[た]て|、|呪[じゅ]文[もん]|を|唱[とな]えた|。', 'The magician became angry and chanted a spell.'),
      line('石[いし]|の|扉[とびら]|は|閉[と]じられた|。', 'The stone door was sealed.'),
      line('アラジン|は|暗[くら]闇[やみ]|に|取[と]り残[のこ]された|。', 'Aladdin was left trapped in the darkness.'),
      line('恐[おそ]ろしさ|で|手[て]|を|こすった|時[とき]|、|指[ゆび]輪[わ]|も|こすった|。', 'When he rubbed his hands in fear, he rubbed the ring too.'),
      line('突[とつ]然[ぜん]|、|青[あお]い|煙[けむり]|から|指[ゆび]輪[わ]の精[せい]|が|現[あらわ]れた|。', 'Suddenly, the spirit of the ring appeared from blue smoke.'),
    ],
    [
      line('指[ゆび]輪[わ]の精[せい]|は|アラジン|の|望[のぞ]み|を|聞[き]いた|。', 'The spirit of the ring asked Aladdin’s wish.'),
      line('「|母[はは]親[おや]|の|所[ところ]|へ|帰[かえ]してほしい|」|と|アラジン|は|答[こた]えた|。', '“I want to go home to my mother,” Aladdin answered.'),
      line('次[つぎ]|の|瞬[しゅん]間[かん]|、|アラジン|は|家[いえ]|に|立[た]っていた|。', 'The next moment, Aladdin was standing at home.'),
      line('母[はは]親[おや]|は|無[ぶ]事[じ]な|姿[すがた]|を|見[み]て|涙[なみだ]を流[なが]した|。', 'His mother wept when she saw him safe.'),
      line('数[すう]日[じつ]後[ご]|、|母[はは]親[おや]|は|ランプ|を|売[う]ろうとして|布[ぬの]|で|磨[みが]いた|。', 'Several days later, his mother polished the lamp to sell it.'),
      line('巨[きょ]大[だい]な|ランプの精[せい]|が|呼[よ]び出[だ]された|。', 'An enormous spirit of the lamp was summoned.'),
      line('「|主[しゅ]人[じん]|よ|、|何[なん]なりと|ご命[めい]令[れい]ください|」|と|深[ふか]い|声[こえ]|で|告[つ]げた|。', '“Master, command me to do anything,” it declared in a deep voice.'),
    ],
    [
      line('アラジン|は|まず|温[あたた]かい|食[しょく]事[じ]|を|願[ねが]った|。', 'Aladdin first wished for a warm meal.'),
      line('銀[ぎん]|の|トレー|に|スープ|と|焼[や]きたて|の|パン|が|並[なら]んだ|。', 'Soup and freshly baked bread appeared on silver trays.'),
      line('二[ふた]人[り]|は|残[のこ]った|銀[ぎん]|の|トレー|を|少[すこ]しずつ|売[う]り|、|穏[おだ]やかに|暮[く]らせるようになった|。', 'By selling the remaining silver trays little by little, the two could live comfortably.'),
      line('やがて|王[おう]宮[きゅう]|で|春[はる]|の|祭[まつ]り|が|開[ひら]かれる|という|知[し]らせ|が|出[で]た|。', 'Before long, an announcement said a spring festival would be held at the palace.'),
      line('アラジン|は|姫[ひめ]|が|町[まち]の人[ひと]たち|と|公[こう]平[へい]に|話[はな]す|様[よう]子[す]|を|見[み]た|。', 'Aladdin saw the princess speaking fairly with the townspeople.'),
      line('彼[かれ]|は|美[うつく]しさ|より|思[おも]いやり|に|心[こころ]を動[うご]かされた|。', 'He was moved more by her compassion than her beauty.'),
      line('姫[ひめ]|に|結[けっ]婚[こん]を申[もう]し込[こ]みたい|と|母[はは]親[おや]|に|打[う]ち明[あ]けた|。', 'He told his mother that he wanted to ask the princess to marry him.'),
    ],
    [
      line('母[はは]親[おや]|は|宝[ほう]石[せき]|を|布[ぬの]袋[ぶくろ]|に|詰[つ]め|、|王[おう]様[さま]|へ|届[とど]けた|。', 'His mother packed the jewels in a cloth bag and took them to the king.'),
      line('王[おう]様[さま]|は|「|これ|ほど|の|ダイヤモンド|は|見[み]たことがありません|」|と|驚[おどろ]かれた|。', 'The king said in astonishment, “I have never seen diamonds like these.”'),
      line('しかし|、|娘[むすめ]|を|迎[むか]える|のに|ふさわしい|宮[きゅう]殿[でん]|を|建[た]てなければならない|と|条[じょう]件[けん]|を|出[だ]された|。', 'However, he required Aladdin to build a palace worthy of welcoming his daughter.'),
      line('アラジン|は|今[こん]度[ど]|、|ランプの精[せい]|に|立[りっ]派[ぱ]な|宮[きゅう]殿[でん]|を|頼[たの]んだ|。', 'This time, Aladdin asked the lamp spirit for a magnificent palace.'),
      line('一[いち]夜[や]|で|金[きん]色[いろ]|の|ドーム|と|モザイク|の|床[ゆか]|が|完[かん]成[せい]した|。', 'Overnight, golden domes and mosaic floors were completed.'),
      line('部[へ]屋[や]|に|は|色[いろ]あざやかな|カーペット|が|敷[し]かれた|。', 'Colourful carpets were laid in the rooms.'),
      line('姫[ひめ]|は|宮[きゅう]殿[でん]|へ|招[まね]かれた|。', 'The princess was invited to the palace.'),
    ],
    [
      line('姫[ひめ]|は|アラジンと話[はな]し|、|彼[かれ]|の|正[しょう]直[じき]さ|が|好[す]きになった|。', 'The princess talked with Aladdin and came to like his honesty.'),
      line('姫[ひめ]|も|結[けっ]婚[こん]|に|同[どう]意[い]した|。', 'The princess agreed to the marriage too.'),
      line('町[まち]全[ぜん]体[たい]|が|二[ふた]人[り]|を|祝[いわ]った|。', 'The whole town celebrated the couple.'),
      line('一[いっ]方[ぽう]|、|遠[とお]く|で|魔[ま]術[じゅつ]師[し]|が|うわさ|を|聞[き]いた|。', 'Meanwhile, far away, the magician heard the rumours.'),
      line('商[しょう]人[にん]|に|姿[すがた]|を|変[か]えて|町[まち]|へ|戻[もど]ってきた|。', 'Disguised as a merchant, he returned to the town.'),
      line('「|古[ふる]い|ランプ|を|新[あたら]しい|ランプ|と|交[こう]換[かん]します|」|と|呼[よ]び歩[ある]いた|。', 'He walked about calling, “I will exchange new lamps for old ones.”'),
      line('召[め]し使[つか]い|は|価[か]値[ち]|を|知[し]らず|、|汚[よご]れた|ランプ|を|取[と]り替[か]えた|。', 'A servant, not knowing its value, exchanged the dirty lamp.'),
    ],
    [
      line('魔[ま]術[じゅつ]師[し]|は|ランプの精[せい]|に|宮[きゅう]殿[でん]|を|砂[さ]漠[ばく]|の|向[む]こう|へ|移[うつ]させた|。', 'The magician made the lamp spirit move the palace beyond the desert.'),
      line('アラジン|が|帰[かえ]ると|、|宮[きゅう]殿[でん]|は|消[き]えていた|。', 'When Aladdin returned, the palace had disappeared.'),
      line('状[じょう]況[きょう]|に|気[き]づき|、|指[ゆび]輪[わ]|を|再[ふたた]び|こすった|。', 'Realising what had happened, he rubbed the ring again.'),
      line('指[ゆび]輪[わ]の精[せい]|は|「|ランプの精[せい]より|力[ちから]|は|弱[よわ]い|が|、|君[きみ]|を|姫[ひめ]|の|所[ところ]|へ|運[はこ]ぶ|こと|は|できる|」|と|言[い]った|。', 'The ring spirit said, “I am weaker than the lamp spirit, but I can carry you to the princess.”'),
      line('アラジン|は|宮[きゅう]殿[でん]|へ|密[ひそ]かに|運[はこ]ばれた|。', 'Aladdin was secretly carried to the palace.'),
      line('姫[ひめ]|と|再[さい]会[かい]した|二[ふた]人[り]|は|作[さく]戦[せん]|を|練[ね]った|。', 'Reunited, the two worked out a plan.'),
      line('姫[ひめ]|は|眠[ねむ]り薬[ぐすり]|を|甘[あま]い|シャーベット|に|混[ま]ぜた|。', 'The princess mixed a sleeping draught into sweet sherbet.'),
    ],
    [
      line('魔[ま]術[じゅつ]師[し]|は|シャーベット|を|飲[の]み干[ほ]して|眠[ねむ]り込[こ]んだ|。', 'The magician drank the sherbet and fell fast asleep.'),
      line('アラジン|は|ランプ|を|取[と]り戻[もど]した|。', 'Aladdin recovered the lamp.'),
      line('ランプの精[せい]|に|宮[きゅう]殿[でん]|を|元[もと]|の|町[まち]|へ|戻[もど]すように命[めい]じた|。', 'He ordered the lamp spirit to return the palace to its town.'),
      line('魔[ま]術[じゅつ]師[し]|は|二[に]度[ど]と|近[ちか]づけない|遠[とお]い|島[しま]|へ|送[おく]られた|。', 'The magician was sent to a faraway island from which he could never approach them again.'),
      line('町[まち]|の|人[ひと]たち|は|二[ふた]人[り]|の|無[ぶ]事[じ]|を|喜[よろこ]んだ|。', 'The townspeople rejoiced that the two were safe.'),
      line('アラジン|は|洞[どう]窟[くつ]|の|暗[くら]闇[やみ]|を|忘[わす]れなかった|。', 'Aladdin never forgot the darkness of the cave.'),
      line('魔[ま]法[ほう]|を|誰[だれ]か|を|傷[きず]つけるため|に|使[つか]わないと誓[ちか]った|。', 'He swore never to use magic to hurt anyone.'),
    ],
    [
      line('ランプの精[せい]|の|力[ちから]|を|市[いち]場[ば]|、|病[びょう]院[いん]|、|学[がっ]校[こう]|を|建[た]てることにも使[つか]った|。', 'He also used the lamp spirit’s power to build a market, a hospital and a school.'),
      line('アラジン|と|姫[ひめ]|は|長[なが]い|時[じ]間[かん]|、|幸[しあわ]せに|暮[く]らした|。', 'Aladdin and the princess lived happily for a long time.'),
    ],
  ],
});

const pinocchio = expandStory({
  id: 'pinocchio',
  title: { ja: 'ピノキオ', en: 'Pinocchio' },
  series: null,
  level: 'L5',
  gram: 'G5',
  blurb: 'A runaway wooden puppet learns, through costly mistakes, what honesty and responsibility mean.',
  source: SOL_SOURCE(
    'Public-domain novel by Carlo Collodi (The Adventures of Pinocchio, 1883)',
    'An original abridged retelling using familiar episodes from Collodi’s public-domain story, not a translation of its Italian text or a later adaptation.',
    'Public domain (Carlo Collodi d. 1890). This retelling and its English translation are original to Kana Quest.',
  ),
  nw: ['ピノキオ', 'ゼペット', 'サーカス', '妖精', 'クジラ'],
  lexicon: lexicon({
    'イタリア': ['Italy', 'pn'],
    '小[ちい]さな': ['small', 'adj'],
    '町[まち]': ['town', 'n'],
    'ゼペット': ['Geppetto', 'pn'],
    '年[とし]を取[と]った': ['elderly, old', 'adj', { df: '年を取る', cf: 'plain past (modifying a noun)' }],
    '木[き]彫[ぼ]り職[しょく]人[にん]': ['woodcarver', 'n'],
    '暮[く]らしていた': ['was living', 'v', { df: '暮らす', cf: 'plain past progressive' }],
    'ある日[ひ]': ['one day', 'adv'],
    '大[だい]工[く]': ['carpenter', 'n'],
    '変[か]わった': ['unusual, peculiar', 'adj', { df: '変わる', cf: 'plain past (modifying a noun)' }],
    '丸[まる]太[た]': ['log of wood', 'n'],
    '買[か]った': ['bought', 'v', { df: '買う', cf: 'plain past' }],
    '道[どう]具[ぐ]': ['tool', 'n'],
    '当[あ]てると': ['when he placed against', 'v', { df: '当てる', cf: 'conditional 〜と form' }],
    '中[なか]': ['inside', 'n'],
    '笑[わら]い声[ごえ]': ['laughter', 'n'],
    '聞[き]こえた': ['could be heard', 'v', { df: '聞こえる', cf: 'plain past' }],
    '驚[おどろ]いた': ['was surprised', 'v', { df: '驚く', cf: 'plain past' }],
    '息[むす]子[こ]': ['son', 'n'],
    '人[にん]形[ぎょう]': ['puppet, doll', 'n'],
    '作[つく]ることにした': ['decided to make', 'v', { df: '作る', cf: 'plain past decision form' }],
    '目[め]': ['eyes', 'n'],
    '彫[ほ]った': ['carved', 'v', { df: '彫る', cf: 'plain past' }],
    '時[とき]': ['when, time', 'n'],
    '瞬[まばた]きをした': ['blinked', 'v', { df: '瞬きをする', cf: 'plain past' }],
    '鼻[はな]': ['nose', 'n'],
    '口[くち]': ['mouth', 'n'],
    '腕[うで]': ['arms', 'n'],
    '足[あし]': ['legs', 'n'],
    '順[じゅん]番[ばん]に': ['in order, one after another', 'adv'],
    '動[うご]き出[だ]した': ['began to move', 'v', { df: '動き出す', cf: 'plain past' }],
    'ピノキオ': ['Pinocchio', 'pn'],
    '名[な]前[まえ]': ['name', 'n'],
    '付[つ]けた': ['gave, assigned', 'v', { df: '付ける', cf: 'plain past' }],
    '完[かん]成[せい]した': ['was completed', 'v', { df: '完成する', cf: 'plain past' }],
    '途[と]端[たん]': ['very moment', 'n'],
    '窓[まど]': ['window', 'n'],
    '飛[と]び出[だ]した': ['leapt out', 'v', { df: '飛び出す', cf: 'plain past' }],
    '町[まち]中[じゅう]': ['throughout the town', 'n'],
    '走[はし]り回[まわ]った': ['ran around', 'v', { df: '走り回る', cf: 'plain past' }],
    '近[きん]所[じょ]の人[ひと]たち': ['neighbours', 'n'],
    '捕[つか]まえて': ['catching; caught and', 'v', { df: '捕まえる', cf: 'te-form' }],
    '家[いえ]': ['home, house', 'n'],
    '連[つ]れ戻[もど]してくれた': ['brought back for him', 'v', { df: '連れ戻す', cf: 'plain past 〜てくれる form' }],
    '言[こと]葉[ば]': ['words, language', 'n'],
    '礼[れい]儀[ぎ]': ['manners', 'n'],
    '教[おし]えようとした': ['tried to teach', 'v', { df: '教える', cf: 'plain past "try to" form' }],
    '夜[よる]': ['night', 'n'],
    'おしゃべりな': ['talkative', 'adj', { df: 'おしゃべりだ', cf: 'na-adjective form' }],
    'コオロギ': ['cricket (insect)', 'n'],
    '暖[だん]炉[ろ]': ['fireplace', 'n'],
    '現[あらわ]れた': ['appeared', 'v', { df: '現れる', cf: 'plain past' }],
    '本[ほん]当[とう]の': ['real, true', 'adj'],
    '子[こ]ども': ['child', 'n'],
    '正[しょう]直[じき]で': ['honest; honestly and', 'adj', { df: '正直だ', cf: 'te-form of na-adjective' }],
    '我[が]慢[まん]強[づよ]くなければならない': ['must be patient', 'adj', { df: '我慢強い', cf: '〜なければならない form' }],
    '忠[ちゅう]告[こく]した': ['advised, warned', 'v', { df: '忠告する', cf: 'plain past' }],
    '聞[き]こうとしなかった': ['would not listen', 'v', { df: '聞く', cf: 'plain past negative "try to" form' }],
    '上[うわ]着[ぎ]': ['coat', 'n'],
    '売[う]って': ['selling; sold and', 'v', { df: '売る', cf: 'te-form' }],
    '教[きょう]科[か]書[しょ]': ['schoolbook, textbook', 'n'],
    '買[か]ってくれた': ['bought for him', 'v', { df: '買う', cf: 'plain past 〜てくれる form' }],
    '学[がっ]校[こう]': ['school', 'n'],
    '行[い]く': ['will go', 'v', { df: '行く', cf: 'plain present/future' }],
    '約[やく]束[そく]した': ['promised', 'v', { df: '約束する', cf: 'plain past' }],
    '翌[よく]朝[あさ]': ['the next morning', 'adv'],
    '元[げん]気[き]よく': ['cheerfully, energetically', 'adv', { df: '元気だ', cf: 'adverbial form' }],
    '出[で]かけた': ['set out', 'v', { df: '出かける', cf: 'plain past' }],
    '途[と]中[ちゅう]': ['on the way', 'n'],
    'サーカス': ['circus', 'n'],
    '音[おん]楽[がく]': ['music', 'n'],
    '聞[き]こえてきた': ['came drifting to him; could be heard', 'v', { df: '聞こえる', cf: 'plain past 〜てくる form' }],
    'ポスター': ['poster', 'n'],
    '人[にん]形[ぎょう]劇[げき]': ['puppet show', 'n'],
    '書[か]かれていた': ['was written', 'v', { df: '書く', cf: 'plain past passive progressive' }],
    'チケット': ['ticket', 'n'],
    '代[だい]': ['cost, price', 'n'],
    'お金[かね]': ['money', 'n'],
    '足[た]りなかった': ['was not enough', 'v', { df: '足りる', cf: 'plain past negative' }],
    '迷[まよ]った': ['hesitated, was torn', 'v', { df: '迷う', cf: 'plain past' }],
    '末[すえ]': ['after; result of a process', 'n'],
    '売[う]ってしまった': ['ended up selling', 'v', { df: '売る', cf: 'plain past 〜てしまう form' }],
    'テント': ['tent', 'n'],
    '入[はい]ると': ['when he entered', 'v', { df: '入る', cf: 'conditional 〜と form' }],
    '舞[ぶ]台[たい]': ['stage', 'n'],
    '人[にん]形[ぎょう]たち': ['the puppets', 'n'],
    '仲[なか]間[ま]': ['companion, one of their kind', 'n'],
    'として': ['as; in the role of', 'part'],
    '歓[かん]迎[げい]した': ['welcomed', 'v', { df: '歓迎する', cf: 'plain past' }],
    'ステージ': ['stage', 'n'],
    '踊[おど]り始[はじ]めた': ['began to dance', 'v', { df: '踊り始める', cf: 'plain past' }],
    '親[おや]方[かた]': ['show master, director', 'n'],
    'ショー': ['show, performance', 'n'],
    '乱[みだ]された': ['was disrupted', 'v', { df: '乱す', cf: 'plain past passive' }],
    '怒[おこ]った': ['became angry', 'v', { df: '怒る', cf: 'plain past' }],
    '最[さい]後[ご]に': ['in the end', 'adv'],
    '話[はなし]': ['story, account', 'n'],
    '聞[き]いて': ['hearing; listened and', 'v', { df: '聞く', cf: 'te-form' }],
    '同[どう]情[じょう]した': ['felt sympathy', 'v', { df: '同情する', cf: 'plain past' }],
    '金[きん]貨[か]': ['gold coins', 'n'],
    '五[ご]枚[まい]': ['five coins', 'num'],
    '持[も]たせた': ['gave to take with him', 'v', { df: '持つ', cf: 'plain past causative' }],
    '帰[かえ]り道[みち]': ['way home', 'n'],
    'キツネ': ['fox', 'n'],
    'ネコ': ['cat', 'n'],
    '出[で]会[あ]った': ['met, encountered', 'v', { df: '出会う', cf: 'plain past' }],
    '足[あし]が悪[わる]いふり': ['pretence of having a bad leg', 'n'],
    'し': ['doing; and', 'v', { df: 'する', cf: 'continuative form' }],
    '目[め]が見[み]えないふり': ['pretence of being blind', 'n'],
    'していた': ['were doing; were pretending', 'v', { df: 'する', cf: 'plain past progressive' }],
    'ポケット': ['pocket', 'n'],
    'コイン': ['coins', 'n'],
    '音[おと]': ['sound', 'n'],
    '気[き]づいた': ['noticed', 'v', { df: '気づく', cf: 'plain past' }],
    '奇[き]跡[せき]': ['miracles', 'n'],
    '原[はら]っぱ': ['field, open ground', 'n'],
    '埋[う]めれば': ['if you bury', 'v', { df: '埋める', cf: 'conditional 〜ば form' }],
    '木[き]': ['tree, wood', 'n'],
    'なって': ['becoming; become and', 'v', { df: 'なる', cf: 'te-form' }],
    '千[せん]枚[まい]': ['one thousand coins', 'num'],
    'なる': ['will become', 'v', { df: 'なる', cf: 'plain present/future' }],
    '教[おし]えた': ['told, taught', 'v', { df: '教える', cf: 'plain past' }],
    '忘[わす]れ': ['forgetting; forgot and', 'v', { df: '忘れる', cf: 'continuative form' }],
    '二[ふた]人[り]': ['the two of them', 'num'],
    '付[つ]いていった': ['followed along', 'v', { df: '付いていく', cf: 'plain past' }],
    '穴[あな]': ['hole', 'n'],
    '掘[ほ]って': ['digging; dug and', 'v', { df: '掘る', cf: 'te-form' }],
    '埋[う]めた': ['buried', 'v', { df: '埋める', cf: 'plain past' }],
    '育[そだ]つ': ['will grow', 'v', { df: '育つ', cf: 'plain present/future' }],
    '待[ま]ち続[つづ]けた': ['kept waiting', 'v', { df: '待ち続ける', cf: 'plain past' }],
    '眠[ねむ]っている間[あいだ]に': ['while he was asleep', 'v', { df: '眠る', cf: 'plain present progressive 〜間に form' }],
    '掘[ほ]り返[かえ]して': ['digging back up; dug up and', 'v', { df: '掘り返す', cf: 'te-form' }],
    '盗[ぬす]んだ': ['stole', 'v', { df: '盗む', cf: 'plain past' }],
    '朝[あさ]': ['morning', 'n'],
    '空[から]の穴[あな]': ['empty hole', 'n'],
    'だまされた': ['was deceived', 'v', { df: 'だます', cf: 'plain past passive' }],
    '分[わ]かった': ['realised, understood', 'v', { df: '分かる', cf: 'plain past' }],
    '帰[かえ]る': ['return, go home', 'v', { df: '帰る', cf: 'plain present' }],
    '道[みち]': ['road, way', 'n'],
    '見[み]失[うしな]った': ['lost sight of; lost', 'v', { df: '見失う', cf: 'plain past' }],
    '森[もり]': ['forest', 'n'],
    '歩[ある]き続[つづ]け': ['continuing to walk; walked on and', 'v', { df: '歩き続ける', cf: 'continuative form' }],
    '青[あお]い': ['blue', 'adj'],
    'たどり着[つ]いた': ['finally reached', 'v', { df: 'たどり着く', cf: 'plain past' }],
    '青[あお]い髪[かみ]の妖[よう]精[せい]': ['Blue Fairy', 'pn'],
    '迎[むか]え入[い]れた': ['welcomed inside', 'v', { df: '迎え入れる', cf: 'plain past' }],
    '妖[よう]精[せい]': ['fairy', 'n'],
    '学[がっ]校[こう]へ行[い]かなかった理[り]由[ゆう]': ['reason he had not gone to school', 'n'],
    '尋[たず]ねた': ['asked', 'v', { df: '尋ねる', cf: 'plain past' }],
    '川[かわ]': ['river', 'n'],
    '渡[わた]る時[とき]': ['while crossing', 'v', { df: '渡る', cf: 'plain present (modifying 時)' }],
    '落[お]としました': ['dropped, lost', 'v', { df: '落とす', cf: 'polite past' }],
    'うそ': ['lie, falsehood', 'n'],
    '答[こた]えた': ['answered', 'v', { df: '答える', cf: 'plain past' }],
    '瞬[しゅん]間[かん]': ['instant, moment', 'n'],
    '少[すこ]し': ['a little', 'adv'],
    '伸[の]びた': ['grew longer', 'v', { df: '伸びる', cf: 'plain past' }],
    'いいえ': ['no', 'int'],
    '鳥[とり]': ['birds', 'n'],
    '取[と]られました': ['was taken by', 'v', { df: '取る', cf: 'polite past passive' }],
    '続[つづ]けた': ['continued', 'v', { df: '続ける', cf: 'plain past' }],
    'もっと': ['even more', 'adv'],
    '長[なが]くなった': ['became longer', 'v', { df: '長くなる', cf: 'plain past' }],
    '部[へ]屋[や]': ['room', 'n'],
    '隅[すみ]': ['corner', 'n'],
    '悲[かな]しそうに': ['sadly; looking sad', 'adv', { df: '悲しそうだ', cf: 'adverbial form' }],
    '見[み]つめていた': ['was watching, gazing', 'v', { df: '見つめる', cf: 'plain past progressive' }],
    'とうとう': ['at last, finally', 'adv'],
    '本[ほん]当[とう]のこと': ['the truth', 'n'],
    '話[はな]した': ['told, spoke', 'v', { df: '話す', cf: 'plain past' }],
    '正[しょう]直[じき]さ': ['honesty', 'n'],
    '認[みと]め': ['acknowledging; recognised and', 'v', { df: '認める', cf: 'continuative form' }],
    '魔[ま]法[ほう]': ['magic', 'n'],
    '元[もと]': ['original state', 'n'],
    '戻[もど]した': ['returned, restored', 'v', { df: '戻す', cf: 'plain past' }],
    '二[に]度[ど]と': ['never again', 'adv'],
    'つかない': ['will not tell', 'v', { df: 'つく', cf: 'plain negative' }],
    '誓[ちか]った': ['swore, vowed', 'v', { df: '誓う', cf: 'plain past' }],
    '戻[もど]ると': ['when he returned', 'v', { df: '戻る', cf: 'conditional 〜と form' }],
    '空[から]っぽ': ['empty', 'adj'],
    'だった': ['was', 'aux', { df: 'だ', cf: 'plain past' }],
    '近[きん]所[じょ]の人[ひと]': ['neighbour', 'n'],
    '父[とう]さん': ['father', 'n'],
    '海[うみ]': ['sea', 'n'],
    '君[きみ]': ['you', 'pn'],
    '捜[さが]しに行[い]った': ['went to search', 'v', { df: '捜しに行く', cf: 'plain past' }],
    '手[て]紙[がみ]': ['letter, note', 'n'],
    '受[う]け取[と]った': ['received', 'v', { df: '受け取る', cf: 'plain past' }],
    '海[うみ]岸[がん]': ['coast, seashore', 'n'],
    '走[はし]った': ['ran', 'v', { df: '走る', cf: 'plain past' }],
    '嵐[あらし]': ['storm', 'n'],
    '始[はじ]まった': ['began', 'v', { df: '始まる', cf: 'plain past' }],
    '沖[おき]': ['offshore', 'n'],
    '小[こ]舟[ぶね]': ['small boat', 'n'],
    '必[ひっ]死[し]に': ['desperately', 'adv'],
    'こいでいる': ['was rowing', 'v', { df: 'こぐ', cf: 'plain present progressive' }],
    '見[み]えた': ['could see', 'v', { df: '見える', cf: 'plain past' }],
    '大[おお]波[なみ]': ['large wave', 'n'],
    '舟[ふね]': ['boat', 'n'],
    'ひっくり返[かえ]した': ['overturned', 'v', { df: 'ひっくり返す', cf: 'plain past' }],
    '迷[まよ]わず': ['without hesitating', 'v', { df: '迷う', cf: '"without ...ing" form' }],
    '飛[と]び込[こ]んだ': ['jumped into', 'v', { df: '飛び込む', cf: 'plain past' }],
    '体[からだ]': ['body', 'n'],
    '浮[う]いた': ['floated', 'v', { df: '浮く', cf: 'plain past' }],
    '姿[すがた]': ['figure, sight', 'n'],
    '波[なみ]': ['waves', 'n'],
    '向[む]こう': ['beyond, other side', 'n'],
    '消[き]えた': ['disappeared', 'v', { df: '消える', cf: 'plain past' }],
    '泳[およ]ぎ続[つづ]けた': ['kept swimming', 'v', { df: '泳ぎ続ける', cf: 'plain past' }],
    '突[とつ]然[ぜん]': ['suddenly', 'adv'],
    '巨[きょ]大[だい]な': ['enormous', 'adj', { df: '巨大だ', cf: 'na-adjective form' }],
    'クジラ': ['whale', 'n'],
    '飲[の]み込[こ]まれた': ['was swallowed', 'v', { df: '飲み込む', cf: 'plain past passive' }],
    '腹[はら]': ['belly, stomach', 'n'],
    '真[ま]っ暗[くら]だった': ['was pitch-dark', 'adj', { df: '真っ暗だ', cf: 'plain past' }],
    '奥[おく]': ['deep inside', 'n'],
    '弱[よわ]い': ['faint, weak', 'adj'],
    '明[あ]かり': ['light', 'n'],
    '見[み]つけた': ['found', 'v', { df: '見つける', cf: 'plain past' }],
    '古[ふる]い': ['old', 'adj'],
    'ランタン': ['lantern', 'n'],
    '隣[となり]': ['beside, next to', 'n'],
    '座[すわ]っていた': ['was sitting', 'v', { df: '座る', cf: 'plain past progressive' }],
    '抱[だ]き合[あ]って': ['embracing; hugged and', 'v', { df: '抱き合う', cf: 'te-form' }],
    '泣[な]いた': ['cried', 'v', { df: '泣く', cf: 'plain past' }],
    '飲[の]み込[こ]んだ': ['swallowed', 'v', { df: '飲み込む', cf: 'plain past' }],
    '魚[さかな]': ['fish', 'n'],
    '生[い]き延[の]びていた': ['had survived', 'v', { df: '生き延びる', cf: 'plain past progressive' }],
    '逃[に]げる': ['escape', 'v', { df: '逃げる', cf: 'plain present' }],
    '方[ほう]法[ほう]': ['method, way', 'n'],
    '考[かんが]えた': ['thought of', 'v', { df: '考える', cf: 'plain past' }],
    '眠[ねむ]ると': ['when it sleeps', 'v', { df: '眠る', cf: 'conditional 〜と form' }],
    '開[ひら]いたままになる': ['remains open', 'v', { df: '開く', cf: 'plain 〜たままになる form' }],
    '湿[しめ]った': ['damp', 'adj', { df: '湿る', cf: 'plain past (modifying a noun)' }],
    '木[き]切[ぎ]れ': ['scraps of wood', 'n'],
    '集[あつ]め': ['gathering; gathered and', 'v', { df: '集める', cf: 'continuative form' }],
    '火[ひ]': ['fire', 'n'],
    '起[お]こした': ['started, made', 'v', { df: '起こす', cf: 'plain past' }],
    '煙[けむり]': ['smoke', 'n'],
    '吸[す]い込[こ]んだ': ['breathed in', 'v', { df: '吸い込む', cf: 'plain past' }],
    '大[おお]きなくしゃみ': ['enormous sneeze', 'n'],
    'した': ['did, made', 'v', { df: 'する', cf: 'plain past' }],
    '外[そと]': ['outside', 'n'],
    '吹[ふ]き飛[と]ばされた': ['were blown out', 'v', { df: '吹き飛ばす', cf: 'plain past passive' }],
    '弱[よわ]っていて': ['being weak; was weak and', 'v', { df: '弱る', cf: 'te-form progressive' }],
    '泳[およ]げなかった': ['could not swim', 'v', { df: '泳ぐ', cf: 'plain potential past negative' }],
    '背[せ]中[なか]': ['back', 'n'],
    '乗[の]せた': ['put onto; carried', 'v', { df: '乗せる', cf: 'plain past' }],
    'イルカ': ['dolphin', 'n'],
    '岸[きし]': ['shore', 'n'],
    '案[あん]内[ない]してくれた': ['guided them', 'v', { df: '案内する', cf: 'plain past 〜てくれる form' }],
    '夜[よ]明[あ]け': ['dawn', 'n'],
    '浜[はま]辺[べ]': ['beach, shore', 'n'],
    '着[つ]いた': ['arrived', 'v', { df: '着く', cf: 'plain past' }],
    '近[ちか]く': ['nearby', 'adv'],
    '空[あ]き家[や]': ['empty house', 'n'],
    '農[のう]家[か]': ['farmer', 'n'],
    '水[みず]': ['water', 'n'],
    '運[はこ]ぶ': ['carrying', 'v', { df: '運ぶ', cf: 'plain present' }],
    '仕[し]事[ごと]': ['job, work', 'n'],
    '始[はじ]めた': ['began', 'v', { df: '始める', cf: 'plain past' }],
    '代[か]わり': ['in exchange, as compensation', 'n'],
    'ミルク': ['milk', 'n'],
    '食[た]べ物[もの]': ['food', 'n'],
    '昼[ひる]': ['daytime', 'n'],
    '働[はたら]き': ['working; worked and', 'v', { df: '働く', cf: 'continuative form' }],
    '勉[べん]強[きょう]した': ['studied', 'v', { df: '勉強する', cf: 'plain past' }],
    '稼[かせ]いだ': ['earned', 'v', { df: '稼ぐ', cf: 'plain past' }],
    '少[すこ]しずつ': ['little by little', 'adv'],
    '貯[た]めた': ['saved up', 'v', { df: '貯める', cf: 'plain past' }],
    '数[すう]か月[げつ]後[ご]': ['several months later', 'adv'],
    '再[ふたた]び': ['again', 'adv'],
    '訪[たず]ねてきた': ['came to visit', 'v', { df: '訪ねる', cf: 'plain past 〜てくる form' }],
    '前[まえ]': ['before; former', 'n'],
    '違[ちが]う': ['different', 'adj'],
    '成[せい]長[ちょう]': ['growth, development', 'n'],
    '認[みと]めた': ['acknowledged, recognised', 'v', { df: '認める', cf: 'plain past' }],
    '日[ひ]': ['day', 'n'],
    '病[びょう]気[き]': ['ill', 'adj'],
    '知[し]らせ': ['news, message', 'n'],
    '届[とど]いた': ['arrived', 'v', { df: '届く', cf: 'plain past' }],
    '新[あたら]しい': ['new', 'adj'],
    '服[ふく]': ['clothes', 'n'],
    '使[つか]う': ['intended for; use', 'v', { df: '使う', cf: 'plain present' }],
    'はず': ['expectation; intended purpose', 'n'],
    '全[ぜん]部[ぶ]': ['all of it', 'n'],
    '渡[わた]した': ['gave', 'v', { df: '渡す', cf: 'plain past' }],
    '晩[ばん]': ['that night', 'n'],
    '夢[ゆめ]': ['dream', 'n'],
    '勇[ゆう]気[き]': ['courage', 'n'],
    '責[せき]任[にん]感[かん]': ['sense of responsibility', 'n'],
    '身[み]につけた': ['acquired, learned', 'v', { df: '身につける', cf: 'plain past' }],
    '言[い]った': ['said', 'v', { df: '言う', cf: 'plain past' }],
    '目[め]を覚[さ]ますと': ['when he woke', 'v', { df: '目を覚ます', cf: 'conditional 〜と form' }],
    '人[にん]間[げん]': ['human', 'n'],
    '少[しょう]年[ねん]': ['boy', 'n'],
    '変[か]わっていた': ['had changed', 'v', { df: '変わる', cf: 'plain past perfect' }],
    '椅[い]子[す]': ['chair', 'n'],
    '横[よこ]': ['side, beside', 'n'],
    '木[き]の人[にん]形[ぎょう]': ['wooden puppet', 'n'],
    '横[よこ]たわっていた': ['was lying', 'v', { df: '横たわる', cf: 'plain past progressive' }],
    '元[げん]気[き]を取[と]り戻[もど]し': ['recovering; recovered and', 'v', { df: '元気を取り戻す', cf: 'continuative form' }],
    '明[あか]るく': ['brightly; bright', 'adv', { df: '明るい', cf: 'adverbial form' }],
    '暖[あたた]かくなっていた': ['had become warm', 'v', { df: '暖かくなる', cf: 'plain past perfect' }],
    '自[じ]由[ゆう]': ['freedom', 'n'],
    '好[す]き勝[かっ]手[て]': ['doing whatever one pleases', 'n'],
    'ではなく': ['is not; rather than', 'aux', { df: 'だ', cf: 'plain negative continuative form' }],
    '大[たい]切[せつ]な': ['important, precious', 'adj', { df: '大切だ', cf: 'na-adjective form' }],
    '人[ひと]': ['people, person', 'n'],
    '守[まも]ること': ['protecting; keeping', 'n', { df: '守る', cf: 'plain present (modifying こと)' }],
    '語[かた]った': ['told, related', 'v', { df: '語る', cf: 'plain past' }],
    '抱[だ]きしめた': ['hugged tightly', 'v', { df: '抱きしめる', cf: 'plain past' }],
    'が#but': ['but, although', 'part'],
    'のような': ['like; resembling', 'part'],
    'しかし': ['however, but', 'adv'],
    '約[やく]束[そく]': ['promise', 'n'],
    '見[み]て': ['seeing; saw and', 'v', { df: '見る', cf: 'te-form' }],
  }),
  body: [
    [
      line('イタリア|の|小[ちい]さな|町[まち]|に|、|ゼペット|という|年[とし]を取[と]った|木[き]彫[ぼ]り職[しょく]人[にん]|が|暮[く]らしていた|。', 'In a small Italian town lived an elderly woodcarver named Geppetto.'),
      line('ある日[ひ]|、|ゼペット|は|大[だい]工[く]|から|変[か]わった|丸[まる]太[た]|を|買[か]った|。', 'One day, Geppetto bought a peculiar log from a carpenter.'),
      line('道[どう]具[ぐ]|を|当[あ]てると|、|丸[まる]太[た]|の|中[なか]|から|笑[わら]い声[ごえ]|が|聞[き]こえた|。', 'When he put a tool to it, laughter came from inside the log.'),
      line('ゼペット|は|驚[おどろ]いた|が#but|、|息[むす]子[こ]|のような|人[にん]形[ぎょう]|を|作[つく]ることにした|。', 'Geppetto was surprised, but decided to make a puppet like a son.'),
      line('目[め]|を|彫[ほ]った|時[とき]|、|人[にん]形[ぎょう]|は|瞬[まばた]きをした|。', 'When he carved the eyes, the puppet blinked.'),
      line('鼻[はな]|、|口[くち]|、|腕[うで]|、|足[あし]|が|順[じゅん]番[ばん]に|動[うご]き出[だ]した|。', 'Its nose, mouth, arms and legs began to move one after another.'),
      line('ゼペット|は|人[にん]形[ぎょう]|に|ピノキオ|と|名[な]前[まえ]|を|付[つ]けた|。', 'Geppetto named the puppet Pinocchio.'),
      line('完[かん]成[せい]した|途[と]端[たん]|、|ピノキオ|は|窓[まど]|から|飛[と]び出[だ]した|。', 'The moment he was finished, Pinocchio leapt out of the window.'),
    ],
    [
      line('ピノキオ|は|町[まち]中[じゅう]|を|走[はし]り回[まわ]った|。', 'Pinocchio ran all over town.'),
      line('近[きん]所[じょ]の人[ひと]たち|が|捕[つか]まえて|、|家[いえ]|へ|連[つ]れ戻[もど]してくれた|。', 'The neighbours caught him and brought him home.'),
      line('ゼペット|は|言[こと]葉[ば]|と|礼[れい]儀[ぎ]|を|教[おし]えようとした|。', 'Geppetto tried to teach him words and manners.'),
      line('その|夜[よる]|、|おしゃべりな|コオロギ|が|暖[だん]炉[ろ]|から|現[あらわ]れた|。', 'That night, a talkative cricket appeared by the fireplace.'),
      line('「|本[ほん]当[とう]の|子[こ]ども|なら|、|正[しょう]直[じき]で|我[が]慢[まん]強[づよ]くなければならない|」|と|忠[ちゅう]告[こく]した|。', '“A real child must be honest and patient,” the cricket advised.'),
      line('しかし|、|ピノキオ|は|聞[き]こうとしなかった|。', 'But Pinocchio would not listen.'),
      line('ゼペット|は|上[うわ]着[ぎ]|を|売[う]って|、|教[きょう]科[か]書[しょ]|を|買[か]ってくれた|。', 'Geppetto sold his coat and bought him a schoolbook.'),
      line('ピノキオ|は|学[がっ]校[こう]|へ|行[い]く|と|約[やく]束[そく]した|。', 'Pinocchio promised to go to school.'),
    ],
    [
      line('翌[よく]朝[あさ]|、|ピノキオ|は|元[げん]気[き]よく|出[で]かけた|。', 'The next morning, Pinocchio set out cheerfully.'),
      line('途[と]中[ちゅう]|で|サーカス|の|音[おん]楽[がく]|が|聞[き]こえてきた|。', 'On the way, circus music drifted towards him.'),
      line('ポスター|に|「|人[にん]形[ぎょう]劇[げき]|」|と|書[か]かれていた|。', '“Puppet Show” was written on a poster.'),
      line('チケット|代[だい]|に|は|お金[かね]|が|足[た]りなかった|。', 'He did not have enough money for a ticket.'),
      line('ピノキオ|は|迷[まよ]った|末[すえ]|、|教[きょう]科[か]書[しょ]|を|売[う]ってしまった|。', 'After hesitating, Pinocchio ended up selling his schoolbook.'),
      line('テント|に|入[はい]ると|、|舞[ぶ]台[たい]|の|人[にん]形[ぎょう]たち|が|仲[なか]間[ま]|として|歓[かん]迎[げい]した|。', 'When he entered the tent, the stage puppets welcomed him as one of them.'),
      line('ピノキオ|も|ステージ|で|踊[おど]り始[はじ]めた|。', 'Pinocchio began dancing on the stage too.'),
      line('親[おや]方[かた]|は|ショー|を|乱[みだ]された|ので|怒[おこ]った|。', 'The show master was angry because his performance had been disrupted.'),
      line('最[さい]後[ご]に|は|ピノキオ|の|話[はなし]|を|聞[き]いて|同[どう]情[じょう]した|。', 'In the end, he heard Pinocchio’s story and felt sorry for him.'),
      line('親[おや]方[かた]|は|金[きん]貨[か]|を|五[ご]枚[まい]|持[も]たせた|。', 'The show master gave him five gold coins to take home.'),
    ],
    [
      line('帰[かえ]り道[みち]|で|、|ピノキオ|は|キツネ|と|ネコ|に|出[で]会[あ]った|。', 'On the way home, Pinocchio met a fox and a cat.'),
      line('キツネ|は|足[あし]が悪[わる]いふり|を|し|、|ネコ|は|目[め]が見[み]えないふり|を|していた|。', 'The fox pretended to have a bad leg, and the cat pretended to be blind.'),
      line('二[ふた]人[り]|は|ポケット|の|コイン|の|音[おと]|に|気[き]づいた|。', 'The pair noticed the sound of coins in his pocket.'),
      line('「|奇[き]跡[せき]|の|原[はら]っぱ|に|埋[う]めれば|、|金[きん]貨[か]|の|木[き]|に|なって|千[せん]枚[まい]|に|なる|」|と|教[おし]えた|。', '“Bury them in the Field of Miracles and they will grow into a money tree with a thousand coins,” they told him.'),
      line('ピノキオ|は|学[がっ]校[こう]|の|約[やく]束[そく]|を|忘[わす]れ|、|二[ふた]人[り]|に|付[つ]いていった|。', 'Pinocchio forgot his promise about school and followed them.'),
      line('原[はら]っぱ|に|穴[あな]|を|掘[ほ]って|金[きん]貨[か]|を|埋[う]めた|。', 'He dug a hole in the field and buried the coins.'),
      line('木[き]|が|育[そだ]つ|まで|夜[よる]|まで|待[ま]ち続[つづ]けた|。', 'He kept waiting until night for the tree to grow.'),
      line('ピノキオ|が|眠[ねむ]っている間[あいだ]に|、|キツネ|と|ネコ|は|金[きん]貨[か]|を|掘[ほ]り返[かえ]して|盗[ぬす]んだ|。', 'While Pinocchio slept, the fox and cat dug up the coins and stole them.'),
      line('朝[あさ]|、|空[から]の穴[あな]|を|見[み]て|、|だまされた|と|分[わ]かった|。', 'In the morning, he saw the empty hole and realised he had been tricked.'),
    ],
    [
      line('ピノキオ|は|帰[かえ]る|道[みち]|を|見[み]失[うしな]った|。', 'Pinocchio lost the road home.'),
      line('森[もり]|を|歩[ある]き続[つづ]け|、|青[あお]い|家[いえ]|に|たどり着[つ]いた|。', 'He walked on through the forest and reached a blue house.'),
      line('青[あお]い髪[かみ]の妖[よう]精[せい]|が|ピノキオ|を|迎[むか]え入[い]れた|。', 'The Blue Fairy welcomed Pinocchio inside.'),
      line('妖[よう]精[せい]|は|学[がっ]校[こう]へ行[い]かなかった理[り]由[ゆう]|を|尋[たず]ねた|。', 'The fairy asked why he had not gone to school.'),
      line('「|金[きん]貨[か]|は|川[かわ]|を|渡[わた]る時[とき]|に|落[お]としました|」|と|うそ|を|答[こた]えた|。', '“I dropped the coins while crossing a river,” he lied.'),
      line('その|瞬[しゅん]間[かん]|、|鼻[はな]|が|少[すこ]し|伸[の]びた|。', 'At that moment, his nose grew a little.'),
      line('「|いいえ|、|鳥[とり]|に|取[と]られました|」|と|うそ|を|続[つづ]けた|。', '“No, birds took them,” he continued lying.'),
      line('鼻[はな]|は|もっと|長[なが]くなった|。', 'His nose grew even longer.'),
      line('コオロギ|が|部[へ]屋[や]|の|隅[すみ]|から|悲[かな]しそうに|見[み]つめていた|。', 'The cricket watched sadly from the corner of the room.'),
      line('ピノキオ|は|とうとう|本[ほん]当[とう]のこと|を|話[はな]した|。', 'At last, Pinocchio told the truth.'),
      line('妖[よう]精[せい]|は|正[しょう]直[じき]さ|を|認[みと]め|、|魔[ま]法[ほう]|で|鼻[はな]|を|元[もと]|に|戻[もど]した|。', 'The fairy recognised his honesty and magically restored his nose.'),
      line('ピノキオ|は|二[に]度[ど]と|うそ|を|つかない|と|誓[ちか]った|。', 'Pinocchio swore never to lie again.'),
    ],
    [
      line('ゼペット|の|家[いえ]|へ|戻[もど]ると|、|部[へ]屋[や]|は|空[から]っぽ|だった|。', 'When he returned to Geppetto’s house, the room was empty.'),
      line('近[きん]所[じょ]の人[ひと]|から|「|父[とう]さん|は|海[うみ]|へ|君[きみ]|を|捜[さが]しに行[い]った|」|という|手[て]紙[がみ]|を|受[う]け取[と]った|。', 'A neighbour gave him a note saying, “Your father went to sea to look for you.”'),
      line('ピノキオ|は|海[うみ]岸[がん]|へ|走[はし]った|。', 'Pinocchio ran to the coast.'),
      line('その|時[とき]|、|嵐[あらし]|が|始[はじ]まった|。', 'At that moment, a storm began.'),
      line('沖[おき]|で|ゼペット|が|小[こ]舟[ぶね]|を|必[ひっ]死[し]に|こいでいる|の|が|見[み]えた|。', 'Offshore, he saw Geppetto desperately rowing a small boat.'),
      line('大[おお]波[なみ]|が|舟[ふね]|を|ひっくり返[かえ]した|。', 'A huge wave overturned the boat.'),
      line('ピノキオ|は|迷[まよ]わず|海[うみ]|へ|飛[と]び込[こ]んだ|。', 'Without hesitation, Pinocchio jumped into the sea.'),
      line('木[き]|の|体[からだ]|は|浮[う]いた|が#but|、|ゼペット|の|姿[すがた]|は|波[なみ]|の|向[む]こう|へ|消[き]えた|。', 'His wooden body floated, but Geppetto disappeared beyond the waves.'),
      line('ピノキオ|は|夜[よる]|まで|泳[およ]ぎ続[つづ]けた|。', 'Pinocchio kept swimming until night.'),
    ],
    [
      line('突[とつ]然[ぜん]|、|巨[きょ]大[だい]な|クジラ|に|飲[の]み込[こ]まれた|。', 'Suddenly, he was swallowed by an enormous whale.'),
      line('クジラ|の|腹[はら]|の|中[なか]|は|真[ま]っ暗[くら]だった|。', 'Inside the whale’s belly it was pitch-dark.'),
      line('奥[おく]|に|弱[よわ]い|明[あ]かり|を|見[み]つけた|。', 'He found a faint light deep inside.'),
      line('古[ふる]い|ランタン|の|隣[となり]|に|ゼペット|が|座[すわ]っていた|。', 'Geppetto was sitting beside an old lantern.'),
      line('二[ふた]人[り]|は|抱[だ]き合[あ]って|泣[な]いた|。', 'The two embraced and wept.'),
      line('ゼペット|は|クジラ|が|飲[の]み込[こ]んだ|魚[さかな]|を|捕[つか]まえて|生[い]き延[の]びていた|。', 'Geppetto had survived by catching fish swallowed by the whale.'),
      line('ピノキオ|は|逃[に]げる|方[ほう]法[ほう]|を|考[かんが]えた|。', 'Pinocchio thought of a way to escape.'),
      line('クジラ|が|眠[ねむ]ると|、|口[くち]|が|開[ひら]いたままになる|と|気[き]づいた|。', 'He noticed that the whale’s mouth stayed open when it slept.'),
      line('湿[しめ]った|木[き]切[ぎ]れ|を|集[あつ]め|、|小[ちい]さな|火[ひ]|を|起[お]こした|。', 'He gathered damp scraps of wood and started a small fire.'),
      line('煙[けむり]|を|吸[す]い込[こ]んだ|クジラ|は|大[おお]きなくしゃみ|を|した|。', 'The whale breathed in the smoke and gave a tremendous sneeze.'),
      line('ピノキオ|と|ゼペット|は|クジラ|の|口[くち]|から|外[そと]|へ|吹[ふ]き飛[と]ばされた|。', 'Pinocchio and Geppetto were blown out through the whale’s mouth.'),
    ],
    [
      line('ゼペット|は|弱[よわ]っていて|泳[およ]げなかった|。', 'Geppetto was too weak to swim.'),
      line('ピノキオ|は|ゼペット|を|背[せ]中[なか]|に|乗[の]せた|。', 'Pinocchio put Geppetto on his back.'),
      line('イルカ|が|二[ふた]人[り]|を|岸[きし]|まで|案[あん]内[ない]してくれた|。', 'A dolphin guided the two of them to shore.'),
      line('夜[よ]明[あ]け|に|浜[はま]辺[べ]|へ|着[つ]いた|。', 'They reached the beach at dawn.'),
      line('近[ちか]く|に|小[ちい]さな|空[あ]き家[や]|を|見[み]つけた|。', 'They found a small empty house nearby.'),
      line('ピノキオ|は|農[のう]家[か]|で|水[みず]|を|運[はこ]ぶ|仕[し]事[ごと]|を|始[はじ]めた|。', 'Pinocchio began carrying water for a farmer.'),
      line('その|代[か]わり|に|ミルク|と|食[た]べ物[もの]|を|受[う]け取[と]った|。', 'In exchange, he received milk and food.'),
      line('昼[ひる]|は|働[はたら]き|、|夜[よる]|は|勉[べん]強[きょう]した|。', 'He worked by day and studied at night.'),
      line('稼[かせ]いだ|お金[かね]|も|少[すこ]しずつ|貯[た]めた|。', 'He also saved the money he earned little by little.'),
    ],
    [
      line('数[すう]か月[げつ]後[ご]|、|コオロギ|が|再[ふたた]び|訪[たず]ねてきた|。', 'Several months later, the cricket came to visit again.'),
      line('「|前[まえ]|の|君[きみ]|と|は|違[ちが]う|」|と|ピノキオ|の|成[せい]長[ちょう]|を|認[みと]めた|。', '“You are different from before,” he said, recognising Pinocchio’s growth.'),
      line('その|日[ひ]|、|青[あお]い髪[かみ]の妖[よう]精[せい]|が|病[びょう]気[き]|だ|という|知[し]らせ|が|届[とど]いた|。', 'That day, news arrived that the Blue Fairy was ill.'),
      line('ピノキオ|は|新[あたら]しい|服[ふく]|に|使[つか]う|はず|の|お金[かね]|を|全[ぜん]部[ぶ]|渡[わた]した|。', 'Pinocchio gave all the money he had intended for new clothes.'),
      line('その|晩[ばん]|、|妖[よう]精[せい]|が|夢[ゆめ]|に|現[あらわ]れた|。', 'That night, the fairy appeared in his dream.'),
      line('「|正[しょう]直[じき]さ|、|勇[ゆう]気[き]|、|責[せき]任[にん]感[かん]|を|身[み]につけた|」|と|言[い]った|。', '“You have learned honesty, courage and responsibility,” she said.'),
      line('ピノキオ|が|目[め]を覚[さ]ますと|、|木[き]|の|体[からだ]|は|人[にん]間[げん]|の|少[しょう]年[ねん]|に|変[か]わっていた|。', 'When Pinocchio woke, his wooden body had changed into that of a human boy.'),
      line('椅[い]子[す]|の|横[よこ]|に|、|古[ふる]い|木[き]の人[にん]形[ぎょう]|が|横[よこ]たわっていた|。', 'Beside the chair lay the old wooden puppet.'),
      line('ゼペット|も|元[げん]気[き]を取[と]り戻[もど]し|、|部[へ]屋[や]|は|明[あか]るく|暖[あたた]かくなっていた|。', 'Geppetto had recovered, and the room had become bright and warm.'),
      line('ピノキオ|は|「|自[じ]由[ゆう]|は|好[す]き勝[かっ]手[て]|ではなく|、|大[たい]切[せつ]な|人[ひと]|を|守[まも]ること|だ|と|分[わ]かった|」|と|語[かた]った|。', 'Pinocchio said, “I learned that freedom is not doing whatever you please; it is protecting the people you love.”'),
      line('ゼペット|は|本[ほん]当[とう]の|息[むす]子[こ]|を|抱[だ]きしめた|。', 'Geppetto embraced his real son.'),
    ],
  ],
});

export const STORY_SOURCES = [aladdin, pinocchio];
