import { expandStory, lexicon, line } from './helpers.mjs';

const SOL_SOURCE = (text, notes, licence) => ({
  kind: 'adapted',
  text,
  by: 'Sol 5.6',
  credit: 'Retold by',
  notes,
  licence,
});

const giantTurnip = expandStory({
  id: 'ookina-kabu',
  title: { ja: '大きなかぶ', en: 'The Giant Turnip' },
  series: null,
  level: 'L1',
  gram: 'G1',
  blurb: 'A turnip will not come out of the ground until a whole family of helpers pulls together.',
  source: SOL_SOURCE(
    'Traditional cumulative tale (The Giant Turnip)',
    'An original beginner-level retelling, not a transcription or translation of a published edition.',
    'Public domain (traditional tale). This retelling and its English translation are original to Kana Quest.',
  ),
  nw: ['かぶ', '植える', '抜ける', '引く'],
  lexicon: lexicon({
    'おじいさん': ['old man; grandfather', 'n'],
    '小[ちい]さな': ['small', 'adj'],
    'かぶ': ['turnip', 'n'],
    '植[う]えました': ['planted', 'v', { df: '植える', cf: 'polite past' }],
    '毎[まい]日[にち]': ['every day', 'adv'],
    '水[みず]': ['water', 'n'],
    'やりました': ['gave; watered', 'v', { df: 'やる', cf: 'polite past' }],
    '大[おお]きくなりました': ['became big', 'v', { df: '大きくなる', cf: 'polite past' }],
    '引[ひ]きました': ['pulled', 'v', { df: '引く', cf: 'polite past' }],
    'しかし': ['however, but', 'adv'],
    '抜[ぬ]けませんでした': ['did not come out', 'v', { df: '抜ける', cf: 'polite past negative' }],
    'おばあさん': ['old woman; grandmother', 'n'],
    '来[き]ました': ['came', 'v', { df: '来る', cf: 'polite past' }],
    '二[ふた]人[り]': ['two people; the two of them', 'num'],
    'まだ': ['still; not yet', 'adv'],
    '女[おんな]の子[こ]': ['girl', 'n'],
    '犬[いぬ]': ['dog', 'n'],
    '猫[ねこ]': ['cat', 'n'],
    'みんな': ['everyone', 'n'],
    '強[つよ]く': ['strongly, hard', 'adv', { df: '強い', cf: 'adverbial form' }],
    'ぽんと': ['with a pop', 'adv'],
    '抜[ぬ]けました': ['came out; was pulled free', 'v', { df: '抜ける', cf: 'polite past' }],
    '笑[わら]いました': ['laughed, smiled', 'v', { df: '笑う', cf: 'polite past' }],
    '夜[よる]': ['evening, night', 'n'],
    '食[た]べました': ['ate', 'v', { df: '食べる', cf: 'polite past' }],
  }),
  body: [
    [
      line('おじいさん|は|小[ちい]さな|かぶ|を|植[う]えました|。', 'An old man planted a small turnip.'),
      line('毎[まい]日[にち]|、|水[みず]|を|やりました|。', 'Every day, he gave it water.'),
      line('かぶ|は|大[おお]きくなりました|。', 'The turnip grew big.'),
    ],
    [
      line('おじいさん|は|かぶ|を|引[ひ]きました|。', 'The old man pulled the turnip.'),
      line('しかし|、|かぶ|は|抜[ぬ]けませんでした|。', 'But the turnip did not come out.'),
      line('おばあさん|も|来[き]ました|。', 'The old woman came too.'),
      line('二[ふた]人[り]|で|引[ひ]きました|。', 'The two of them pulled.'),
      line('まだ|抜[ぬ]けませんでした|。', 'It still did not come out.'),
    ],
    [
      line('女[おんな]の子[こ]|と|犬[いぬ]|と|猫[ねこ]|も|来[き]ました|。', 'A girl, a dog and a cat came too.'),
      line('みんな|で|強[つよ]く|引[ひ]きました|。', 'Everyone pulled hard together.'),
      line('かぶ|は|ぽんと|抜[ぬ]けました|。', 'The turnip came out with a pop.'),
      line('みんな|は|笑[わら]いました|。', 'Everyone laughed.'),
      line('夜[よる]|、|みんな|で|かぶ|を|食[た]べました|。', 'That evening, everyone ate the turnip together.'),
    ],
  ],
});

const northWindAndSun = expandStory({
  id: 'kitakaze-to-taiyou',
  title: { ja: '北風と太陽', en: 'The North Wind and the Sun' },
  series: null,
  level: 'L1',
  gram: 'G1',
  blurb: 'The North Wind and the Sun each try to make a traveller remove his coat.',
  source: SOL_SOURCE(
    'Traditional fable (The North Wind and the Sun)',
    'An original beginner-level retelling of the ancient fable, written without reference to a specific edition.',
    'Public domain (traditional fable). This retelling and its English translation are original to Kana Quest.',
  ),
  nw: ['北風', '太陽', '上着', '吹く'],
  lexicon: lexicon({
    '北[きた]風[かぜ]': ['North Wind', 'pn'],
    '太[たい]陽[よう]': ['Sun', 'pn'],
    '会[あ]いました': ['met', 'v', { df: '会う', cf: 'polite past' }],
    'とても': ['very', 'adv'],
    '強[つよ]い': ['strong', 'adj'],
    '明[あか]るい': ['bright', 'adj'],
    '下[した]': ['below, underneath', 'n'],
    '男[おとこ]の人[ひと]': ['man', 'n'],
    'いました': ['there was; was present', 'v', { df: 'いる', cf: 'polite past' }],
    '上[うわ]着[ぎ]': ['coat, outerwear', 'n'],
    '着[き]ました': ['put on; wore', 'v', { df: '着る', cf: 'polite past' }],
    '強[つよ]く吹[ふ]きました': ['blew hard', 'v', { df: '強く吹く', cf: 'polite past' }],
    'しっかり': ['firmly, tightly', 'adv'],
    'おさえました': ['held down', 'v', { df: 'おさえる', cf: 'polite past' }],
    'もっと': ['more; even more', 'adv'],
    '次[つぎ]': ['next; next turn', 'n'],
    'です': ['is; it is', 'aux', { df: 'だ', cf: 'polite present' }],
    '暖[あたた]かく照[て]らしました': ['shone warmly', 'v', { df: '暖かく照らす', cf: 'polite past' }],
    '暑[あつ]くなりました': ['became hot', 'v', { df: '暑くなる', cf: 'polite past' }],
    '脱[ぬ]ぎました': ['took off', 'v', { df: '脱ぐ', cf: 'polite past' }],
    'にっこり笑[わら]いました': ['smiled warmly', 'v', { df: 'にっこり笑う', cf: 'polite past' }],
  }),
  body: [
    [
      line('北[きた]風[かぜ]|と|太[たい]陽[よう]|は|会[あ]いました|。', 'The North Wind and the Sun met.'),
      line('北[きた]風[かぜ]|は|とても|強[つよ]い|です|。', 'The North Wind was very strong.'),
      line('太[たい]陽[よう]|は|とても|明[あか]るい|です|。', 'The Sun was very bright.'),
    ],
    [
      line('下[した]|に|男[おとこ]の人[ひと]|が|いました|。', 'Below them, there was a man.'),
      line('男[おとこ]の人[ひと]|は|上[うわ]着[ぎ]|を|着[き]ました|。', 'The man put on a coat.'),
      line('北[きた]風[かぜ]|は|強[つよ]く吹[ふ]きました|。', 'The North Wind blew hard.'),
      line('男[おとこ]の人[ひと]|は|上[うわ]着[ぎ]|を|しっかり|おさえました|。', 'The man held his coat tightly.'),
      line('北[きた]風[かぜ]|は|もっと|強[つよ]く吹[ふ]きました|。', 'The North Wind blew even harder.'),
      line('男[おとこ]の人[ひと]|は|もっと|しっかり|おさえました|。', 'The man held it even more tightly.'),
    ],
    [
      line('次[つぎ]|は|太[たい]陽[よう]|です|。', 'Next it was the Sun’s turn.'),
      line('太[たい]陽[よう]|は|暖[あたた]かく照[て]らしました|。', 'The Sun shone warmly.'),
      line('男[おとこ]の人[ひと]|は|暑[あつ]くなりました|。', 'The man became hot.'),
      line('男[おとこ]の人[ひと]|は|上[うわ]着[ぎ]|を|脱[ぬ]ぎました|。', 'The man took off his coat.'),
      line('太[たい]陽[よう]|は|にっこり笑[わら]いました|。', 'The Sun smiled warmly.'),
    ],
  ],
});

export const STORY_SOURCES = [giantTurnip, northWindAndSun];

