import { expandStory, lexicon, line } from './helpers.mjs';

const SOL_SOURCE = (text, notes, licence) => ({
  kind: 'adapted', text, by: 'Sol 5.6', credit: 'Retold by', notes, licence,
});

const threeLittlePigs = expandStory({
  id: 'sanbiki-no-kobuta',
  title: { ja: '三匹の子ぶた', en: 'The Three Little Pigs' },
  series: null,
  level: 'L3',
  gram: 'G3',
  blurb: 'Three young pigs build very different houses before a hungry wolf arrives from the forest.',
  source: SOL_SOURCE(
    'Traditional European tale (The Three Little Pigs)',
    'An original graded retelling, using a non-violent version of the ending and no wording from a published edition.',
    'Public domain (traditional tale). This retelling and its English translation are original to Kana Quest.',
  ),
  nw: ['子ぶた', 'オオカミ', 'レンガ', '煙突', '頑丈'],
  lexicon: lexicon({
    '昔[むかし]': ['long ago', 'adv'],
    '三[さん]匹[びき]': ['three small animals', 'num'],
    '子[こ]ぶた': ['young pig; piglet', 'n'],
    '母[はは]ぶた': ['mother pig', 'n'],
    '暮[く]らしていた': ['were living', 'v', { df: '暮らす', cf: 'plain past progressive' }],
    'ある日[ひ]': ['one day', 'adv'],
    '自[じ]分[ぶん]': ['oneself; one’s own', 'n'],
    '家[いえ]': ['house, home', 'n'],
    '建[た]てることにした': ['decided to build', 'v', { df: '建てる', cf: 'plain past decision form' }],
    '一[いち]番[ばん]目[め]': ['the first one', 'n'],
    'わら': ['straw', 'n'],
    'すぐ': ['quickly, right away', 'adv'],
    'できると思[おも]った': ['thought it could be made', 'v', { df: 'できると思う', cf: 'plain past' }],
    'あっという間[ま]に': ['in an instant', 'adv'],
    'できた': ['was finished; was made', 'v', { df: 'できる', cf: 'plain past' }],
    '二[に]番[ばん]目[め]': ['the second one', 'n'],
    '木[き]': ['wood; tree', 'n'],
    '枝[えだ]': ['branches', 'n'],
    '集[あつ]めた': ['gathered', 'v', { df: '集める', cf: 'plain past' }],
    '一[いち]日[にち]': ['one day', 'n'],
    '完[かん]成[せい]した': ['was completed', 'v', { df: '完成する', cf: 'plain past' }],
    '三[さん]番[ばん]目[め]': ['the third one', 'n'],
    'レンガ': ['brick', 'n'],
    '一[ひと]つずつ': ['one at a time', 'num'],
    '積[つ]んだ': ['stacked, laid', 'v', { df: '積む', cf: 'plain past' }],
    '兄[あに]たち': ['the older brothers', 'n'],
    'そんな': ['that kind of; such', 'adj'],
    '遅[おそ]い': ['slow', 'adj'],
    '仕[し]事[ごと]': ['work, job', 'n'],
    '笑[わら]った': ['laughed at', 'v', { df: '笑う', cf: 'plain past' }],
    'それでも': ['even so, nevertheless', 'adv'],
    '末[すえ]っ子[こ]': ['youngest child', 'n'],
    '何[なん]日[にち]も': ['for many days', 'adv'],
    '働[はたら]いた': ['worked', 'v', { df: '働く', cf: 'plain past' }],
    'やっと': ['at last, finally', 'adv'],
    '頑[がん]丈[じょう]な': ['sturdy, strong', 'adj', { df: '頑丈だ', cf: 'na-adjective form' }],
    'そこ': ['there; that place', 'n'],
    'お腹[なか]をすかせた': ['hungry', 'adj', { df: 'お腹をすかせる', cf: 'plain past (modifying a noun)' }],
    'オオカミ': ['wolf', 'n'],
    '来[き]た': ['came', 'v', { df: '来る', cf: 'plain past' }],
    'まず': ['first of all', 'adv'],
    '戸[と]': ['door', 'n'],
    'たたいた': ['knocked on', 'v', { df: 'たたく', cf: 'plain past' }],
    '入[い]れてくれ': ['let me in', 'v', { df: '入れる', cf: 'plain imperative 〜てくれる form' }],
    '言[い]った': ['said', 'v', { df: '言う', cf: 'plain past' }],
    'いやだ': ['no; I refuse', 'adj'],
    '答[こた]えた': ['answered', 'v', { df: '答える', cf: 'plain past' }],
    '強[つよ]い': ['strong', 'adj'],
    '息[いき]': ['breath', 'n'],
    '吹[ふ]き飛[と]ばした': ['blew away', 'v', { df: '吹き飛ばす', cf: 'plain past' }],
    '飛[と]んでいった': ['went flying away', 'v', { df: '飛んでいく', cf: 'plain past 〜ていく form' }],
    '空[そら]': ['sky, air', 'n'],
    '逃[に]げた': ['ran away, escaped', 'v', { df: '逃げる', cf: 'plain past' }],
    '壊[こわ]した': ['broke, destroyed', 'v', { df: '壊す', cf: 'plain past' }],
    '二[に]匹[ひき]': ['the two animals', 'num'],
    '走[はし]った': ['ran', 'v', { df: '走る', cf: 'plain past' }],
    '何[なん]度[ど]も': ['many times; again and again', 'adv'],
    '吹[ふ]いた': ['blew', 'v', { df: '吹く', cf: 'plain past' }],
    '壁[かべ]': ['wall', 'n'],
    '少[すこ]しも': ['not at all', 'adv'],
    '動[うご]かなかった': ['did not move', 'v', { df: '動く', cf: 'plain past negative' }],
    '次[つぎ]に': ['next', 'adv'],
    '煙[えん]突[とつ]': ['chimney', 'n'],
    '入[はい]ろうと思[おも]った': ['thought he would enter', 'v', { df: '入る', cf: 'volitional 〜と思う form' }],
    '音[おと]': ['sound', 'n'],
    '聞[き]いて': ['hearing; listened and', 'v', { df: '聞く', cf: 'te-form' }],
    '大[おお]きな': ['large, big', 'adj'],
    '鍋[なべ]': ['cooking pot', 'n'],
    '湯[ゆ]': ['hot water', 'n'],
    '沸[わ]かした': ['boiled', 'v', { df: '沸かす', cf: 'plain past' }],
    '下[お]りてきた': ['came down', 'v', { df: '下りる', cf: 'plain past 〜てくる form' }],
    'しかし': ['however, but', 'adv'],
    '熱[あつ]い': ['hot', 'adj'],
    '湯[ゆ]気[げ]': ['steam', 'n'],
    '見[み]て': ['seeing; looked and', 'v', { df: '見る', cf: 'te-form' }],
    'びっくりした': ['was startled', 'v', { df: 'びっくりする', cf: 'plain past' }],
    '屋[や]根[ね]': ['roof', 'n'],
    '森[もり]': ['forest, woods', 'n'],
    '飛[と]び去[さ]った': ['flew away; bounded off', 'v', { df: '飛び去る', cf: 'plain past' }],
    '謝[あやま]った': ['apologised', 'v', { df: '謝る', cf: 'plain past' }],
    '仲[なか]良[よ]く': ['happily together; on good terms', 'adv', { df: '仲良い', cf: 'adverbial form' }],
    '暮[く]らした': ['lived', 'v', { df: '暮らす', cf: 'plain past' }],
  }),
  body: [
    [
      line('昔[むかし]|、|三[さん]匹[びき]|の|子[こ]ぶた|が|母[はは]ぶた|と|暮[く]らしていた|。', 'Long ago, three little pigs lived with their mother.'),
      line('ある日[ひ]|、|三[さん]匹[びき]|は|自[じ]分[ぶん]|の|家[いえ]|を|建[た]てることにした|。', 'One day, the three of them decided to build homes of their own.'),
    ],
    [
      line('一[いち]番[ばん]目[め]|は|わら|の|家[いえ]|なら|すぐ|できると思[おも]った|。', 'The first pig thought a straw house could be made quickly.'),
      line('あっという間[ま]に|家[いえ]|が|できた|。', 'The house was finished in no time.'),
      line('二[に]番[ばん]目[め]|は|木[き]|の|枝[えだ]|を|集[あつ]めた|。', 'The second pig gathered branches.'),
      line('木[き]|の|家[いえ]|も|一[いち]日[にち]|で|完[かん]成[せい]した|。', 'The wooden house was completed in a day too.'),
      line('三[さん]番[ばん]目[め]|は|レンガ|を|一[ひと]つずつ|積[つ]んだ|。', 'The third pig laid the bricks one at a time.'),
      line('兄[あに]たち|は|そんな|遅[おそ]い|仕[し]事[ごと]|を|笑[わら]った|。', 'His older brothers laughed at such slow work.'),
      line('それでも|末[すえ]っ子[こ]|は|何[なん]日[にち]も|働[はたら]いた|。', 'Even so, the youngest worked for many days.'),
      line('やっと|頑[がん]丈[じょう]な|レンガ|の|家[いえ]|が|できた|。', 'At last, a sturdy brick house was finished.'),
    ],
    [
      line('そこ|へ|お腹[なか]をすかせた|オオカミ|が|来[き]た|。', 'Then a hungry wolf came along.'),
      line('オオカミ|は|まず|わら|の|家[いえ]|の|戸[と]|を|たたいた|。', 'The wolf first knocked on the straw house’s door.'),
      line('「|入[い]れてくれ|」|と|言[い]った|。', '“Let me in,” he said.'),
      line('子[こ]ぶた|は|「|いやだ|」|と|答[こた]えた|。', 'The little pig answered, “No.”'),
      line('オオカミ|は|強[つよ]い|息[いき]|で|家[いえ]|を|吹[ふ]き飛[と]ばした|。', 'The wolf blew the house away with a powerful breath.'),
      line('わら|の|家[いえ]|は|空[そら]|へ|飛[と]んでいった|。', 'The straw house went flying into the air.'),
      line('一[いち]番[ばん]目[め]|は|木[き]|の|家[いえ]|へ|逃[に]げた|。', 'The first pig escaped to the wooden house.'),
      line('オオカミ|は|木[き]|の|家[いえ]|も|壊[こわ]した|。', 'The wolf broke the wooden house too.'),
      line('二[に]匹[ひき]|は|レンガ|の|家[いえ]|へ|走[はし]った|。', 'The two pigs ran to the brick house.'),
    ],
    [
      line('オオカミ|は|何[なん]度[ど]も|息[いき]|を|吹[ふ]いた|。', 'The wolf blew again and again.'),
      line('レンガ|の|壁[かべ]|は|少[すこ]しも|動[うご]かなかった|。', 'The brick walls did not move at all.'),
      line('次[つぎ]に|オオカミ|は|煙[えん]突[とつ]|から|入[はい]ろうと思[おも]った|。', 'Next, the wolf decided to enter through the chimney.'),
      line('末[すえ]っ子[こ]|は|その|音[おと]|を|聞[き]いて|、|大[おお]きな|鍋[なべ]|に|湯[ゆ]|を|沸[わ]かした|。', 'The youngest heard the noise and boiled water in a large pot.'),
      line('オオカミ|は|煙[えん]突[とつ]|を|下[お]りてきた|。', 'The wolf came down the chimney.'),
      line('しかし|、|熱[あつ]い|湯[ゆ]気[げ]|を|見[み]て|びっくりした|。', 'But he saw the hot steam and was startled.'),
      line('オオカミ|は|屋[や]根[ね]|から|森[もり]|へ|飛[と]び去[さ]った|。', 'The wolf bounded from the roof and away into the forest.'),
    ],
    [
      line('兄[あに]たち|は|末[すえ]っ子[こ]|に|謝[あやま]った|。', 'The older brothers apologised to the youngest.'),
      line('三[さん]匹[びき]|は|レンガ|の|家[いえ]|で|仲[なか]良[よ]く|暮[く]らした|。', 'The three pigs lived happily together in the brick house.'),
    ],
  ],
});

const cinderella = expandStory({
  id: 'cinderella',
  title: { ja: 'シンデレラ', en: 'Cinderella' },
  series: null,
  level: 'L3',
  gram: 'G3',
  blurb: 'A mistreated young woman receives one magical night at the palace and leaves a glass slipper behind.',
  source: SOL_SOURCE(
    'Traditional European fairy tale (Cinderella)',
    'An original graded retelling based on familiar public-domain motifs rather than a particular literary edition.',
    'Public domain (traditional fairy tale). This retelling and its English translation are original to Kana Quest.',
  ),
  nw: ['シンデレラ', '魔法', 'ドレス', 'ガラス', 'パーティー'],
  lexicon: lexicon({
    'シンデレラ': ['Cinderella', 'pn'],
    '継[まま]母[はは]': ['stepmother', 'n'],
    '二[ふた]人[り]': ['two people', 'num'],
    '姉[あね]': ['older sisters', 'n'],
    '暮[く]らしていた': ['was living', 'v', { df: '暮らす', cf: 'plain past progressive' }],
    '毎[まい]日[にち]': ['every day', 'adv'],
    '彼[かの]女[じょ]': ['she; her', 'pn'],
    '朝[あさ]': ['morning', 'n'],
    '夜[よる]': ['night', 'n'],
    '働[はたら]いた': ['worked', 'v', { df: '働く', cf: 'plain past' }],
    '古[ふる]い': ['old, worn', 'adj'],
    '服[ふく]': ['clothes', 'n'],
    '灰[はい]': ['ashes', 'n'],
    'いつも': ['always', 'adv'],
    '汚[よご]れていた': ['was dirty', 'v', { df: '汚れる', cf: 'plain past progressive' }],
    'それで': ['and so; because of that', 'adv'],
    '姉[あね]たち': ['the older sisters', 'n'],
    '呼[よ]んだ': ['called, named', 'v', { df: '呼ぶ', cf: 'plain past' }],
    'ある日[ひ]': ['one day', 'adv'],
    '王[おう]宮[きゅう]': ['royal palace', 'n'],
    'パーティー': ['party, ball', 'n'],
    '招[しょう]待[たい]状[じょう]': ['invitation', 'n'],
    '届[とど]いた': ['arrived', 'v', { df: '届く', cf: 'plain past' }],
    '王[おう]子[じ]': ['prince', 'n'],
    '国[くに]中[じゅう]': ['throughout the country', 'n'],
    '若[わか]い': ['young', 'adj'],
    '人[ひと]': ['people; person', 'n'],
    '招[まね]いた': ['invited', 'v', { df: '招く', cf: 'plain past' }],
    '新[あたら]しい': ['new', 'adj'],
    'ドレス': ['dress; gown', 'n'],
    '選[えら]んだ': ['chose', 'v', { df: '選ぶ', cf: 'plain past' }],
    '行[い]きたいと言[い]った': ['said she wanted to go', 'v', { df: '行きたいと言う', cf: 'plain past' }],
    'だが': ['but, however', 'adv'],
    '残[のこ]して': ['leaving behind', 'v', { df: '残す', cf: 'te-form' }],
    '出[で]かけた': ['went out; departed', 'v', { df: '出かける', cf: 'plain past' }],
    '一[ひと]人[り]になった': ['left alone', 'adj', { df: '一人になる', cf: 'plain past (modifying a noun)' }],
    '庭[にわ]': ['garden', 'n'],
    '泣[な]いた': ['cried', 'v', { df: '泣く', cf: 'plain past' }],
    'すると': ['then; thereupon', 'adv'],
    '魔[ま]法[ほう]使[つか]い': ['magician; fairy godmother', 'n'],
    '現[あらわ]れた': ['appeared', 'v', { df: '現れる', cf: 'plain past' }],
    'かぼちゃ': ['pumpkin', 'n'],
    '馬[ば]車[しゃ]': ['carriage', 'n'],
    '変[か]えた': ['changed, transformed', 'v', { df: '変える', cf: 'plain past' }],
    'ネズミ': ['mice', 'n'],
    '白[しろ]い': ['white', 'adj'],
    '馬[うま]': ['horses', 'n'],
    'なった': ['became, turned into', 'v', { df: 'なる', cf: 'plain past' }],
    '青[あお]い': ['blue', 'adj'],
    '変[か]わった': ['changed, was transformed', 'v', { df: '変わる', cf: 'plain past' }],
    '足[あし]': ['feet', 'n'],
    'ガラス': ['glass', 'n'],
    '靴[くつ]': ['shoes; slipper', 'n'],
    '光[ひか]っていた': ['were shining', 'v', { df: '光る', cf: 'plain past progressive' }],
    '魔[ま]法[ほう]': ['magic', 'n'],
    '十[じゅう]二[に]時[じ]': ['twelve o’clock', 'n'],
    '消[き]える': ['will disappear', 'v', { df: '消える', cf: 'plain present' }],
    '言[い]った': ['said', 'v', { df: '言う', cf: 'plain past' }],
    '会[かい]場[じょう]': ['venue; party hall', 'n'],
    '急[いそ]いだ': ['hurried', 'v', { df: '急ぐ', cf: 'plain past' }],
    '見[み]て': ['seeing; saw and', 'v', { df: '見る', cf: 'te-form' }],
    'すぐ': ['at once', 'adv'],
    'ダンス': ['dance', 'n'],
    '誘[さそ]った': ['invited, asked', 'v', { df: '誘う', cf: 'plain past' }],
    '音[おん]楽[がく]': ['music', 'n'],
    '合[あ]わせて': ['in time with; matching', 'v', { df: '合わせる', cf: 'te-form' }],
    '踊[おど]った': ['danced', 'v', { df: '踊る', cf: 'plain past' }],
    '時[じ]間[かん]': ['time', 'n'],
    '忘[わす]れて': ['forgetting', 'v', { df: '忘れる', cf: 'te-form' }],
    '楽[たの]しんだ': ['enjoyed herself', 'v', { df: '楽しむ', cf: 'plain past' }],
    '突[とつ]然[ぜん]': ['suddenly', 'adv'],
    '時[と]計[けい]': ['clock', 'n'],
    '打[う]った': ['struck, chimed', 'v', { df: '打つ', cf: 'plain past' }],
    '階[かい]段[だん]': ['stairs, staircase', 'n'],
    '走[はし]って下[お]りた': ['ran down', 'v', { df: '走って下りる', cf: 'plain past' }],
    '途[と]中[ちゅう]': ['on the way; midway', 'n'],
    '片[かた]方[ほう]': ['one of a pair', 'n'],
    '脱[ぬ]げた': ['came off', 'v', { df: '脱げる', cf: 'plain past' }],
    'しかし': ['however, but', 'adv'],
    '止[と]まらなかった': ['did not stop', 'v', { df: '止まる', cf: 'plain past negative' }],
    '小[ちい]さな': ['small', 'adj'],
    '拾[ひろ]った': ['picked up', 'v', { df: '拾う', cf: 'plain past' }],
    '翌[よく]日[じつ]': ['the next day', 'adv'],
    '持[も]ち主[ぬし]': ['owner', 'n'],
    '捜[さが]した': ['searched for', 'v', { df: '捜す', cf: 'plain past' }],
    'たくさん': ['many; a great many', 'adv'],
    '試[ため]した': ['tried, tested', 'v', { df: '試す', cf: 'plain past' }],
    '最[さい]後[ご]に': ['finally, at the end', 'adv'],
    '入[い]れた': ['put in', 'v', { df: '入れる', cf: 'plain past' }],
    'ぴったり': ['perfectly, exactly', 'adv'],
    '合[あ]った': ['fitted, matched', 'v', { df: '合う', cf: 'plain past' }],
    'あの人[ひと]': ['the person from before', 'n'],
    '分[わ]かった': ['realised, understood', 'v', { df: '分かる', cf: 'plain past' }],
    '再[さい]会[かい]': ['reunion; meeting again', 'n'],
    '喜[よろこ]んだ': ['rejoiced; were delighted', 'v', { df: '喜ぶ', cf: 'plain past' }],
    '新[あたら]しい': ['new', 'adj'],
    '人[じん]生[せい]': ['life', 'n'],
    '自[じ]分[ぶん]': ['herself; her own', 'n'],
    '選[えら]んだ': ['chose', 'v', { df: '選ぶ', cf: 'plain past' }],
  }),
  body: [
    [
      line('シンデレラ|は|継[まま]母[はは]|と|二[ふた]人[り]|の|姉[あね]|と|暮[く]らしていた|。', 'Cinderella lived with her stepmother and two older sisters.'),
      line('毎[まい]日[にち]|、|彼[かの]女[じょ]|は|朝[あさ]|から|夜[よる]|まで|働[はたら]いた|。', 'Every day, she worked from morning until night.'),
      line('古[ふる]い|服[ふく]|は|灰[はい]|で|いつも|汚[よご]れていた|。', 'Her old clothes were always dirty with ash.'),
      line('それで|姉[あね]たち|は|彼[かの]女[じょ]|を|シンデレラ|と|呼[よ]んだ|。', 'That was why the sisters called her Cinderella.'),
    ],
    [
      line('ある日[ひ]|、|王[おう]宮[きゅう]|から|パーティー|の|招[しょう]待[たい]状[じょう]|が|届[とど]いた|。', 'One day, an invitation to a party arrived from the palace.'),
      line('王[おう]子[じ]|は|国[くに]中[じゅう]|の|若[わか]い|人[ひと]|を|招[まね]いた|。', 'The prince invited the young people from across the country.'),
      line('姉[あね]たち|は|新[あたら]しい|ドレス|を|選[えら]んだ|。', 'The sisters chose new dresses.'),
      line('シンデレラ|も|行[い]きたいと言[い]った|。', 'Cinderella said that she wanted to go too.'),
      line('だが|継[まま]母[はは]|は|彼[かの]女[じょ]|を|残[のこ]して|出[で]かけた|。', 'But her stepmother left without her.'),
    ],
    [
      line('一[ひと]人[り]になった|シンデレラ|は|庭[にわ]|で|泣[な]いた|。', 'Left alone, Cinderella cried in the garden.'),
      line('すると|魔[ま]法[ほう]使[つか]い|が|現[あらわ]れた|。', 'Then a fairy godmother appeared.'),
      line('魔[ま]法[ほう]使[つか]い|は|かぼちゃ|を|馬[ば]車[しゃ]|に|変[か]えた|。', 'The fairy godmother changed a pumpkin into a carriage.'),
      line('ネズミ|は|白[しろ]い|馬[うま]|に|なった|。', 'The mice became white horses.'),
      line('シンデレラ|の|古[ふる]い|服[ふく]|は|青[あお]い|ドレス|に|変[か]わった|。', 'Cinderella’s old clothes changed into a blue gown.'),
      line('足[あし]|に|は|ガラス|の|靴[くつ]|が|光[ひか]っていた|。', 'Glass slippers shone on her feet.'),
      line('「|魔[ま]法[ほう]|は|十[じゅう]二[に]時[じ]|に|消[き]える|」|と|魔[ま]法[ほう]使[つか]い|は|言[い]った|。', '“The magic will disappear at twelve,” said the fairy godmother.'),
    ],
    [
      line('シンデレラ|は|パーティー|会[かい]場[じょう]|へ|急[いそ]いだ|。', 'Cinderella hurried to the party.'),
      line('王[おう]子[じ]|は|彼[かの]女[じょ]|を|見[み]て|、|すぐ|ダンス|に|誘[さそ]った|。', 'The prince saw her and immediately asked her to dance.'),
      line('二[ふた]人[り]|は|音[おん]楽[がく]|に|合[あ]わせて|踊[おど]った|。', 'The two danced in time with the music.'),
      line('シンデレラ|は|時[じ]間[かん]|を|忘[わす]れて|楽[たの]しんだ|。', 'Cinderella forgot the time and enjoyed herself.'),
      line('突[とつ]然[ぜん]|、|時[と]計[けい]|が|十[じゅう]二[に]時[じ]|を|打[う]った|。', 'Suddenly, the clock struck twelve.'),
      line('彼[かの]女[じょ]|は|階[かい]段[だん]|を|走[はし]って下[お]りた|。', 'She ran down the stairs.'),
      line('その|途[と]中[ちゅう]|で|ガラス|の|靴[くつ]|が|片[かた]方[ほう]|脱[ぬ]げた|。', 'On the way, one glass slipper came off.'),
      line('しかし|彼[かの]女[じょ]|は|止[と]まらなかった|。', 'But she did not stop.'),
      line('王[おう]子[じ]|は|小[ちい]さな|ガラス|の|靴[くつ]|を|拾[ひろ]った|。', 'The prince picked up the small glass slipper.'),
    ],
    [
      line('翌[よく]日[じつ]|、|王[おう]子[じ]|は|その|靴[くつ]|の|持[も]ち主[ぬし]|を|捜[さが]した|。', 'The next day, the prince searched for the slipper’s owner.'),
      line('たくさん|の|人[ひと]|が|靴[くつ]|を|試[ため]した|。', 'Many people tried on the slipper.'),
      line('最[さい]後[ご]に|シンデレラ|が|足[あし]|を|入[い]れた|。', 'Finally, Cinderella put her foot into it.'),
      line('ガラス|の|靴[くつ]|は|ぴったり|合[あ]った|。', 'The glass slipper fitted perfectly.'),
      line('王[おう]子[じ]|は|彼[かの]女[じょ]|が|あの人[ひと]|だ|と|分[わ]かった|。', 'The prince realised that she was the woman from the party.'),
      line('二[ふた]人[り]|は|再[さい]会[かい]|を|喜[よろこ]んだ|。', 'The two were delighted to meet again.'),
      line('シンデレラ|は|自[じ]分[ぶん]|の|新[あたら]しい|人[じん]生[せい]|を|選[えら]んだ|。', 'Cinderella chose a new life for herself.'),
    ],
  ],
});

export const STORY_SOURCES = [threeLittlePigs, cinderella];
