import { expandStory, lexicon, line } from './helpers.mjs';

const SOL_SOURCE = (text, notes, licence) => ({
  kind: 'adapted', text, by: 'Sol 5.6', credit: 'Retold by', notes, licence,
});

const redRidingHood = expandStory({
  id: 'akazukin',
  title: { ja: '赤ずきん', en: 'Little Red Riding Hood' },
  series: null,
  level: 'L4',
  gram: 'G4',
  blurb: 'A girl carrying food to her grandmother meets a dangerously friendly wolf in the forest.',
  source: SOL_SOURCE(
    'Traditional European fairy tale (Little Red Riding Hood)',
    'An original graded retelling with a non-violent rescue, drawing on common public-domain motifs rather than one edition.',
    'Public domain (traditional fairy tale). This retelling and its English translation are original to Kana Quest.',
  ),
  nw: ['赤ずきん', 'オオカミ', 'バスケット', '猟師', '物置'],
  lexicon: lexicon({
    '小[ちい]さな': ['little, small', 'adj'],
    '村[むら]': ['village', 'n'],
    '赤[あか]ずきん': ['Little Red Riding Hood', 'pn'],
    '女[おんな]の子[こ]': ['girl', 'n'],
    '住[す]んでいました': ['lived', 'v', { df: '住む', cf: 'polite past progressive' }],
    'おばあさん': ['grandmother; old woman', 'n'],
    '赤[あか]い': ['red', 'adj'],
    'ずきん': ['hood, head covering', 'n'],
    '縫[ぬ]ってくれました': ['sewed for her', 'v', { df: '縫う', cf: 'polite past 〜てくれる form' }],
    'いつも': ['always', 'adv'],
    'かぶっていた': ['wore; had on', 'v', { df: 'かぶる', cf: 'plain past progressive' }],
    'ある朝[あさ]': ['one morning', 'adv'],
    'お母[かあ]さん': ['mother', 'n'],
    'パン': ['bread', 'n'],
    'ジャム': ['jam, fruit preserve', 'n'],
    'バスケット': ['basket', 'n'],
    '入[い]れました': ['put in', 'v', { df: '入れる', cf: 'polite past' }],
    '病[びょう]気[き]': ['ill, sick', 'adj'],
    '届[とど]けて': ['take; deliver', 'v', { df: '届ける', cf: 'te-form request' }],
    '道[みち]': ['path, road', 'n'],
    '外[はず]れてはいけません': ['must not leave', 'v', { df: '外れる', cf: 'prohibitive 〜てはいけない form' }],
    '言[い]いました': ['said', 'v', { df: '言う', cf: 'polite past' }],
    '約[やく]束[そく]して': ['promising; promise and', 'v', { df: '約束する', cf: 'te-form' }],
    '森[もり]': ['forest, woods', 'n'],
    '出[で]かけました': ['set out', 'v', { df: '出かける', cf: 'polite past' }],
    '途[と]中[ちゅう]': ['on the way', 'n'],
    '大[おお]きな': ['large, big', 'adj'],
    'オオカミ': ['wolf', 'n'],
    '現[あらわ]れました': ['appeared', 'v', { df: '現れる', cf: 'polite past' }],
    'やさしい': ['gentle, kind', 'adj'],
    '声[こえ]': ['voice', 'n'],
    'こんにちは': ['hello', 'int'],
    '話[はな]しかけました': ['spoke to; addressed', 'v', { df: '話しかける', cf: 'polite past' }],
    'どちら': ['where; which direction', 'n'],
    '行[い]くのですか': ['are you going?', 'v', { df: '行く', cf: 'polite explanatory question form' }],
    '聞[き]きました': ['asked', 'v', { df: '聞く', cf: 'polite past' }],
    '奥[おく]': ['deep inside', 'n'],
    '家[いえ]': ['house, home', 'n'],
    'です': ['is; it is', 'aux', { df: 'だ', cf: 'polite present' }],
    '答[こた]えました': ['answered', 'v', { df: '答える', cf: 'polite past' }],
    '色[いろ]とりどり': ['colourful; of many colours', 'adj'],
    '花[はな]': ['flowers', 'n'],
    '見[み]つけました': ['noticed, found', 'v', { df: '見つける', cf: 'polite past' }],
    'きれいな': ['pretty, beautiful', 'adj', { df: 'きれいだ', cf: 'na-adjective form' }],
    'ブーケ': ['bouquet', 'n'],
    '喜[よろこ]ぶでしょう': ['will probably be pleased', 'v', { df: '喜ぶ', cf: 'plain probable form' }],
    '赤[あか]ずきんちゃん': ['Little Red Riding Hood (affectionate)', 'pn'],
    '作[つく]って': ['make; pick and arrange', 'v', { df: '作る', cf: 'te-form suggestion' }],
    '誘[さそ]いました': ['tempted; suggested', 'v', { df: '誘う', cf: 'polite past' }],
    '少[すこ]し': ['a little', 'adv'],
    '考[かんが]えて': ['thinking; thought and', 'v', { df: '考える', cf: 'te-form' }],
    '花[はな]を摘[つ]み始[はじ]めました': ['began picking flowers', 'v', { df: '花を摘み始める', cf: 'polite past' }],
    'その間[あいだ]に': ['meanwhile; during that time', 'adv'],
    '近[ちか]道[みち]': ['shortcut', 'n'],
    '走[はし]りました': ['ran', 'v', { df: '走る', cf: 'polite past' }],
    '先[さき]に': ['ahead; first', 'adv'],
    '着[つ]きました': ['arrived', 'v', { df: '着く', cf: 'polite past' }],
    'ドア': ['door', 'n'],
    'たたきました': ['knocked on', 'v', { df: 'たたく', cf: 'polite past' }],
    '声[こえ]をまねて': ['imitating the voice', 'v', { df: '声をまねる', cf: 'te-form' }],
    '私[わたし]': ['I, me', 'pn'],
    '入[い]れてください': ['please let me in', 'v', { df: '入れる', cf: 'polite request form' }],
    '弱[よわ]い': ['weak, faint', 'adj'],
    '寝[ね]たまま': ['while remaining in bed', 'v', { df: '寝る', cf: 'plain past 〜たまま form' }],
    '開[あ]けました': ['opened', 'v', { df: '開ける', cf: 'polite past' }],
    'すぐ': ['immediately', 'adv'],
    '物[もの]置[おき]': ['storage cupboard', 'n'],
    '閉[と]じ込[こ]めました': ['shut inside', 'v', { df: '閉じ込める', cf: 'polite past' }],
    'ナイトキャップ': ['nightcap', 'n'],
    'かぶり': ['putting on', 'v', { df: 'かぶる', cf: 'continuative form' }],
    'ベッド': ['bed', 'n'],
    '入[はい]りました': ['got into; entered', 'v', { df: '入る', cf: 'polite past' }],
    'やがて': ['before long', 'adv'],
    '部[へ]屋[や]': ['room', 'n'],
    '暗[くら]い': ['dark', 'adj'],
    'テーブル': ['table', 'n'],
    '置[お]きました': ['put, placed', 'v', { df: '置く', cf: 'polite past' }],
    'そっと': ['quietly, gently', 'adv'],
    '近[ちか]づきました': ['approached', 'v', { df: '近づく', cf: 'polite past' }],
    '耳[みみ]': ['ears', 'n'],
    'どうして': ['why', 'adv'],
    '大[おお]きいの': ['are so big', 'adj', { df: '大きい', cf: 'explanatory question form' }],
    'よく': ['well; clearly', 'adv'],
    '聞[き]くためだよ': ['are for hearing', 'v', { df: '聞く', cf: 'plain purpose explanatory form' }],
    '目[め]': ['eyes', 'n'],
    '見[み]るためだよ': ['are for seeing', 'v', { df: '見る', cf: 'plain purpose explanatory form' }],
    '口[くち]': ['mouth', 'n'],
    '食[た]べるためだ': ['is for eating', 'v', { df: '食べる', cf: 'plain purpose explanatory form' }],
    '飛[と]び起[お]きました': ['sprang up', 'v', { df: '飛び起きる', cf: 'polite past' }],
    '驚[おどろ]きました': ['was startled', 'v', { df: '驚く', cf: 'polite past' }],
    '助[たす]けて': ['help!', 'v', { df: '助ける', cf: 'te-form request' }],
    '叫[さけ]びながら': ['while shouting', 'v', { df: '叫ぶ', cf: '〜ながら form' }],
    '逃[に]げました': ['escaped, ran away', 'v', { df: '逃げる', cf: 'polite past' }],
    '近[ちか]く': ['nearby', 'adv'],
    '猟[りょう]師[し]': ['hunter', 'n'],
    '叫[さけ]び声[ごえ]': ['shout, cry', 'n'],
    '聞[き]きました': ['heard', 'v', { df: '聞く', cf: 'polite past' }],
    '急[いそ]いで': ['in a hurry; hurrying', 'adv', { df: '急ぐ', cf: 'te-form' }],
    '駆[か]けつけました': ['rushed over', 'v', { df: '駆けつける', cf: 'polite past' }],
    '窓[まど]': ['window', 'n'],
    '出[で]ようとしました': ['tried to get out', 'v', { df: '出る', cf: 'polite past "try to" form' }],
    '前[まえ]': ['in front', 'n'],
    '立[た]ちました': ['stood', 'v', { df: '立つ', cf: 'polite past' }],
    '森[もり]の奥[おく]深[ぶか]く': ['deep into the forest', 'adv'],
    '消[き]えました': ['disappeared', 'v', { df: '消える', cf: 'polite past' }],
    '出[だ]しました': ['let out; brought out', 'v', { df: '出す', cf: 'polite past' }],
    '道[みち]を外[はず]れたこと': ['having left the path', 'n'],
    '知[し]らない': ['unknown, unfamiliar', 'adj', { df: '知る', cf: 'plain negative (modifying a noun)' }],
    '人[ひと]': ['person', 'n'],
    '話[はな]したこと': ['having spoken; what she told', 'n', { df: '話す', cf: 'plain past (modifying こと)' }],
    '謝[あやま]りました': ['apologised', 'v', { df: '謝る', cf: 'polite past' }],
    '三[さん]人[にん]': ['the three people', 'num'],
    '一[いっ]緒[しょ]に': ['together', 'adv'],
    '食[た]べました': ['ate', 'v', { df: '食べる', cf: 'polite past' }],
    '二[に]度[ど]と': ['never again', 'adv'],
    '忘[わす]れませんでした': ['did not forget', 'v', { df: '忘れる', cf: 'polite past negative' }],
    '外[そと]': ['outside; off the path', 'n'],
    '約[やく]束[そく]': ['promise', 'n'],
    '続[つづ]けました': ['continued', 'v', { df: '続ける', cf: 'polite past' }],
    '逃[に]げて': ['fleeing; fled and', 'v', { df: '逃げる', cf: 'te-form' }],
  }),
  body: [
    [
      line('小[ちい]さな|村[むら]|に|赤[あか]ずきん|という|女[おんな]の子[こ]|が|住[す]んでいました|。', 'In a small village lived a girl called Little Red Riding Hood.'),
      line('おばあさん|が|赤[あか]い|ずきん|を|縫[ぬ]ってくれました|。', 'Her grandmother had sewn a red hood for her.'),
      line('女[おんな]の子[こ]|は|いつも|その|ずきん|を|かぶっていた|。', 'The girl always wore that hood.'),
    ],
    [
      line('ある朝[あさ]|、|お母[かあ]さん|は|パン|と|ジャム|を|バスケット|に|入[い]れました|。', 'One morning, her mother put bread and jam into a basket.'),
      line('「|病[びょう]気[き]|の|おばあさん|に|届[とど]けて|」|と|言[い]いました|。', '“Take this to your grandmother, who is ill,” she said.'),
      line('「|道[みち]|から|外[はず]れてはいけません|」|と|も|言[い]いました|。', '“You must not leave the path,” she added.'),
      line('赤[あか]ずきん|は|約[やく]束[そく]して|森[もり]|へ|出[で]かけました|。', 'Little Red Riding Hood promised and set out for the forest.'),
    ],
    [
      line('途[と]中[ちゅう]|で|大[おお]きな|オオカミ|が|現[あらわ]れました|。', 'A large wolf appeared on the way.'),
      line('オオカミ|は|やさしい|声[こえ]|で|「|こんにちは|」|と|話[はな]しかけました|。', 'The wolf spoke to her in a gentle voice and said, “Hello.”'),
      line('「|どちら|へ|行[い]くのですか|」|と|聞[き]きました|。', '“Where are you going?” he asked.'),
      line('「|森[もり]|の|奥[おく]|の|おばあさん|の|家[いえ]|です|」|と|答[こた]えました|。', '“To my grandmother’s house deep in the forest,” she answered.'),
      line('オオカミ|は|道[みち]|の|外[そと]|に|色[いろ]とりどり|の|花[はな]|を|見[み]つけました|。', 'The wolf noticed colourful flowers away from the path.'),
      line('「|きれいな|ブーケ|なら|おばあさん|も|喜[よろこ]ぶでしょう|」|と|誘[さそ]いました|。', '“Your grandmother would be pleased with a pretty bouquet,” he suggested.'),
      line('赤[あか]ずきん|は|少[すこ]し|考[かんが]えて|、|花[はな]を摘[つ]み始[はじ]めました|。', 'Little Red Riding Hood thought for a moment and began picking flowers.'),
    ],
    [
      line('その間[あいだ]に|オオカミ|は|近[ちか]道[みち]|を|走[はし]りました|。', 'Meanwhile, the wolf ran along a shortcut.'),
      line('おばあさん|の|家[いえ]|に|先[さき]に|着[つ]きました|。', 'He reached Grandmother’s house first.'),
      line('ドア|を|たたきました|。', 'He knocked on the door.'),
      line('赤[あか]ずきん|の|声[こえ]をまねて|「|私[わたし]|です|、|入[い]れてください|」|と|言[い]いました|。', 'Imitating Little Red Riding Hood, he said, “It’s me. Please let me in.”'),
      line('弱[よわ]い|おばあさん|は|寝[ね]たまま|ドア|を|開[あ]けました|。', 'The weak grandmother opened the door without leaving her bed.'),
      line('オオカミ|は|すぐ|おばあさん|を|物[もの]置[おき]|に|閉[と]じ込[こ]めました|。', 'The wolf quickly shut Grandmother in the storage cupboard.'),
      line('ナイトキャップ|を|かぶり|、|ベッド|に|入[はい]りました|。', 'He put on a nightcap and climbed into bed.'),
    ],
    [
      line('やがて|赤[あか]ずきん|が|着[つ]きました|。', 'Before long, Little Red Riding Hood arrived.'),
      line('部[へ]屋[や]|は|暗[くら]い|まま|でした|。', 'The room was still dark.'),
      line('バスケット|を|テーブル|に|置[お]きました|。', 'She put the basket on the table.'),
      line('そして|ベッド|へ|そっと|近[ちか]づきました|。', 'Then she quietly approached the bed.'),
      line('「|おばあさん|、|どうして|耳[みみ]|が|そんなに|大[おお]きいの|」|と|聞[き]きました|。', '“Grandmother, why are your ears so big?” she asked.'),
      line('「|おまえ|の|声[こえ]|を|よく|聞[き]くためだよ|」|と|オオカミ|は|答[こた]えました|。', '“So I can hear your voice clearly,” the wolf answered.'),
      line('「|どうして|目[め]|が|そんなに|大[おお]きいの|」|と|赤[あか]ずきん|は|続[つづ]けました|。', '“Why are your eyes so big?” Little Red Riding Hood continued.'),
      line('「|おまえ|を|よく|見[み]るためだよ|」|と|オオカミ|は|言[い]いました|。', '“So I can see you clearly,” said the wolf.'),
      line('「|どうして|口[くち]|が|そんなに|大[おお]きいの|」|と|聞[き]きました|。', '“Why is your mouth so big?” she asked.'),
      line('「|おまえ|を|食[た]べるためだ|」|と|オオカミ|は|飛[と]び起[お]きました|。', '“So I can eat you,” said the wolf, springing up.'),
    ],
    [
      line('赤[あか]ずきん|は|驚[おどろ]きました|。', 'Little Red Riding Hood was startled.'),
      line('「|助[たす]けて|」|と|叫[さけ]びながら|ドア|へ|逃[に]げました|。', 'Shouting “Help!” she fled towards the door.'),
      line('近[ちか]く|に|いた|猟[りょう]師[し]|が|叫[さけ]び声[ごえ]|を|聞[き]きました|。', 'A hunter nearby heard her cry.'),
      line('猟[りょう]師[し]|は|急[いそ]いで|家[いえ]|へ|駆[か]けつけました|。', 'The hunter hurried to the house.'),
      line('オオカミ|は|窓[まど]|から|出[で]ようとしました|。', 'The wolf tried to get out through the window.'),
      line('猟[りょう]師[し]|が|窓[まど]|の|前[まえ]|に|立[た]ちました|。', 'The hunter stood in front of the window.'),
      line('オオカミ|は|森[もり]の奥[おく]深[ぶか]く|へ|逃[に]げて|消[き]えました|。', 'The wolf fled deep into the forest and disappeared.'),
      line('猟[りょう]師[し]|は|おばあさん|を|物[もの]置[おき]|から|出[だ]しました|。', 'The hunter let Grandmother out of the cupboard.'),
    ],
    [
      line('赤[あか]ずきん|は|道[みち]を外[はず]れたこと|を|謝[あやま]りました|。', 'Little Red Riding Hood apologised for leaving the path.'),
      line('知[し]らない|人[ひと]|に|話[はな]したこと|も|謝[あやま]りました|。', 'She also apologised for talking to a stranger.'),
      line('三[さん]人[にん]|は|パン|と|ジャム|を|一[いっ]緒[しょ]に|食[た]べました|。', 'The three of them ate the bread and jam together.'),
      line('赤[あか]ずきん|は|約[やく]束[そく]|を|二[に]度[ど]と|忘[わす]れませんでした|。', 'Little Red Riding Hood never forgot her promise again.'),
    ],
  ],
});

const bremenMusicians = expandStory({
  id: 'bremen-no-ongakutai',
  title: { ja: 'ブレーメンの音楽隊', en: 'The Bremen Town Musicians' },
  series: null,
  level: 'L4',
  gram: 'G4',
  blurb: 'Four ageing animals form a band, frighten a houseful of thieves, and discover a home together.',
  source: SOL_SOURCE(
    'Public-domain tale collected by the Brothers Grimm (The Bremen Town Musicians)',
    'An original graded retelling of the familiar plot, not a translation of the Grimms’ German text or a modern edition.',
    'Public domain (original collectors Jacob Grimm d. 1863 and Wilhelm Grimm d. 1859). This retelling and translation are original to Kana Quest.',
  ),
  nw: ['ブレーメン', '音楽隊', 'ロバ', '泥棒', 'バンド'],
  lexicon: lexicon({
    '昔[むかし]': ['long ago', 'adv'],
    '粉[こな]ひき小[ご]屋[や]': ['flour mill', 'n'],
    '年[とし]を取[と]った': ['old, aged', 'adj', { df: '年を取る', cf: 'plain past (modifying a noun)' }],
    'ロバ': ['donkey', 'n'],
    '働[はたら]いていました': ['was working', 'v', { df: '働く', cf: 'polite past progressive' }],
    '重[おも]い': ['heavy', 'adj'],
    '袋[ふくろ]': ['sacks, bags', 'n'],
    '運[はこ]べなくなりました': ['became unable to carry', 'v', { df: '運ぶ', cf: 'polite past potential negative 〜なる form' }],
    '主[しゅ]人[じん]': ['owner, master', 'n'],
    '仕[し]事[ごと]': ['work, job', 'n'],
    'もう': ['any more; already', 'adv'],
    'ない': ['there is none', 'adj', { df: 'ある', cf: 'plain negative' }],
    '言[い]いました': ['said', 'v', { df: '言う', cf: 'polite past' }],
    'そこで': ['so; therefore', 'adv'],
    'ブレーメン': ['Bremen', 'pn'],
    '行[い]って': ['going; go and', 'v', { df: '行く', cf: 'te-form' }],
    '音[おん]楽[がく]隊[たい]': ['musical group; band', 'n'],
    '入[はい]ろうと決[き]めました': ['decided to join', 'v', { df: '入る', cf: 'volitional 〜と決める form' }],
    '道[みち]': ['road, way', 'n'],
    '疲[つか]れた': ['tired', 'adj', { df: '疲れる', cf: 'plain past (modifying a noun)' }],
    '犬[いぬ]': ['dog', 'n'],
    '座[すわ]っていました': ['was sitting', 'v', { df: '座る', cf: 'polite past progressive' }],
    '遠[とお]く': ['far; a long way', 'adv'],
    '歩[ある]けません': ['cannot walk', 'v', { df: '歩く', cf: 'polite potential negative' }],
    '一[いっ]緒[しょ]に': ['together', 'adv'],
    'バンド': ['band', 'n'],
    '作[つく]りませんか': ['shall we form?', 'v', { df: '作る', cf: 'polite negative question invitation' }],
    '誘[さそ]いました': ['invited', 'v', { df: '誘う', cf: 'polite past' }],
    '喜[よろこ]んで': ['gladly; with pleasure', 'adv', { df: '喜ぶ', cf: 'te-form' }],
    '仲[なか]間[ま]': ['companion, member', 'n'],
    '猫[ねこ]': ['cat', 'n'],
    '会[あ]いました': ['met', 'v', { df: '会う', cf: 'polite past' }],
    '家[いえ]': ['home, house', 'n'],
    '追[お]い出[だ]された': ['was driven out', 'v', { df: '追い出す', cf: 'plain past passive' }],
    '元[げん]気[き]がありませんでした': ['had no energy; looked miserable', 'v', { df: '元気がある', cf: 'polite past negative' }],
    '声[こえ]': ['voice', 'n'],
    'すてきな': ['lovely, excellent', 'adj', { df: 'すてきだ', cf: 'na-adjective form' }],
    'メロディー': ['melody', 'n'],
    '歌[うた]える': ['can sing', 'v', { df: '歌う', cf: 'potential form' }],
    '加[くわ]わりました': ['joined', 'v', { df: '加わる', cf: 'polite past' }],
    '門[もん]': ['gate', 'n'],
    '上[うえ]': ['top, above', 'n'],
    '鳴[な]いている': ['was crowing', 'v', { df: '鳴く', cf: 'plain present progressive' }],
    '雄[おん]鶏[どり]': ['rooster', 'n'],
    '見[み]つけました': ['found', 'v', { df: '見つける', cf: 'polite past' }],
    '農[のう]夫[ふ]': ['farmer', 'n'],
    '明[あ]日[した]': ['tomorrow', 'n'],
    '市[いち]場[ば]': ['market', 'n', { d: '市場|いちば' }],
    '売[う]るつもりだ': ['intends to sell', 'v', { df: '売る', cf: 'plain intention form' }],
    '聞[き]きました': ['heard', 'v', { df: '聞く', cf: 'polite past' }],
    'なら': ['if so; in that case', 'part'],
    '高[たか]い': ['high, loud', 'adj'],
    'コーラス': ['chorus', 'n'],
    '言[い]って': ['saying; said and', 'v', { df: '言う', cf: 'te-form' }],
    '四[よん]匹[ひき]': ['four animals', 'num'],
    '出[しゅっ]発[ぱつ]しました': ['set off', 'v', { df: '出発する', cf: 'polite past' }],
    '歩[ある]きながら': ['while walking', 'v', { df: '歩く', cf: '〜ながら form' }],
    '自[じ]分[ぶん]たち': ['themselves; their own', 'pn'],
    '歌[うた]': ['song', 'n'],
    '歌[うた]いました': ['sang', 'v', { df: '歌う', cf: 'polite past' }],
    '日[ひ]': ['sun; daylight', 'n'],
    '暮[く]れても': ['even when night fell', 'v', { df: '暮れる', cf: '"even if" form' }],
    '町[まち]': ['town', 'n'],
    '着[つ]きませんでした': ['did not arrive', 'v', { df: '着く', cf: 'polite past negative' }],
    '森[もり]': ['forest, woods', 'n'],
    '休[やす]むことにしました': ['decided to rest', 'v', { df: '休む', cf: 'polite past decision form' }],
    '屋[や]根[ね]': ['roof', 'n'],
    '登[のぼ]りました': ['climbed', 'v', { df: '登る', cf: 'polite past' }],
    '遠[とお]く': ['in the distance', 'adv'],
    '明[あ]かり': ['light', 'n'],
    '見[み]えました': ['could see; was visible', 'v', { df: '見える', cf: 'polite past' }],
    '近[ちか]づくと': ['when they approached', 'v', { df: '近づく', cf: '"when" form' }],
    '窓[まど]': ['window', 'n'],
    '泥[どろ]棒[ぼう]たち': ['the thieves', 'n'],
    'ごちそう': ['feast, fine food', 'n'],
    '囲[かこ]んでいました': ['were sitting around', 'v', { df: '囲む', cf: 'polite past progressive' }],
    'テーブル': ['table', 'n'],
    'ソーセージ': ['sausages', 'n'],
    'スープ': ['soup', 'n'],
    '並[なら]んでいました': ['were laid out', 'v', { df: '並ぶ', cf: 'polite past progressive' }],
    'お腹[なか]': ['stomachs', 'n'],
    '鳴[な]りました': ['rumbled', 'v', { df: '鳴る', cf: 'polite past' }],
    '作[さく]戦[せん]': ['plan, strategy', 'n'],
    '考[かんが]えました': ['thought up', 'v', { df: '考える', cf: 'polite past' }],
    '前[まえ]足[あし]': ['front legs', 'n'],
    '窓[まど]枠[わく]': ['window frame', 'n'],
    'かけました': ['placed, propped', 'v', { df: 'かける', cf: 'polite past' }],
    '背[せ]中[なか]': ['back', 'n'],
    '乗[の]りました': ['climbed onto, rode', 'v', { df: '乗る', cf: 'polite past' }],
    '猫[ねこ]の上[うえ]': ['on top of the cat', 'n'],
    '積[つ]み重[かさ]なりました': ['stacked themselves up', 'v', { df: '積み重なる', cf: 'polite past' }],
    'いっせいに': ['all at once', 'adv'],
    '大[おお]声[ごえ]': ['loud voices', 'n'],
    '出[だ]しました': ['made, let out', 'v', { df: '出す', cf: 'polite past' }],
    '不[ぶ]気[き]味[み]な': ['eerie, frightening', 'adj', { df: '不気味だ', cf: 'na-adjective form' }],
    'モンスター': ['monster', 'n'],
    '思[おも]いました': ['thought', 'v', { df: '思う', cf: 'polite past' }],
    '驚[おどろ]いて': ['being startled; startled and', 'v', { df: '驚く', cf: 'te-form' }],
    '逃[に]げ出[だ]しました': ['ran away', 'v', { df: '逃げ出す', cf: 'polite past' }],
    '中[なか]': ['inside', 'n'],
    '入[はい]りました': ['entered', 'v', { df: '入る', cf: 'polite past' }],
    '食[た]べました': ['ate', 'v', { df: '食べる', cf: 'polite past' }],
    '寝[ね]床[どこ]': ['place to sleep; bed', 'n'],
    '選[えら]びました': ['chose', 'v', { df: '選ぶ', cf: 'polite past' }],
    '外[そと]': ['outside', 'n'],
    'わら': ['straw', 'n'],
    '上[うえ]': ['on top of', 'n'],
    '玄[げん]関[かん]': ['entrance, doorway', 'n'],
    '暖[だん]炉[ろ]': ['fireplace', 'n'],
    'そば': ['beside, near', 'n'],
    '消[け]しました': ['put out', 'v', { df: '消す', cf: 'polite past' }],
    'しばらくすると': ['after a little while', 'adv'],
    '一[ひと]人[り]': ['one person', 'num'],
    '様[よう]子[す]を見[み]に戻[もど]りました': ['returned to investigate', 'v', { df: '様子を見に戻る', cf: 'polite past' }],
    '暗[くら]い': ['dark', 'adj'],
    '手[て]を伸[の]ばしたら': ['when he reached out', 'v', { df: '手を伸ばす', cf: 'conditional 〜たら form' }],
    '顔[かお]': ['face', 'n'],
    '引[ひ]っかきました': ['scratched', 'v', { df: '引っかく', cf: 'polite past' }],
    'ドア': ['door', 'n'],
    '走[はし]ると': ['when he ran', 'v', { df: '走る', cf: 'conditional 〜と form' }],
    '吠[ほ]えました': ['barked', 'v', { df: '吠える', cf: 'polite past' }],
    'ズボン': ['trousers', 'n'],
    'かみつきました': ['bit into', 'v', { df: 'かみつく', cf: 'polite past' }],
    '蹴[け]りました': ['kicked', 'v', { df: '蹴る', cf: 'polite past' }],
    '道[みち]': ['road', 'n'],
    '転[ころ]がりました': ['tumbled', 'v', { df: '転がる', cf: 'polite past' }],
    '屋[や]根[ね]の上[うえ]': ['on the roof', 'n'],
    '叫[さけ]びました': ['shouted, crowed', 'v', { df: '叫ぶ', cf: 'polite past' }],
    '仲[なか]間[ま]': ['companions', 'n'],
    '戻[もど]って': ['returning; returned and', 'v', { df: '戻る', cf: 'te-form' }],
    '怪[かい]物[ぶつ]': ['monsters', 'n'],
    '報[ほう]告[こく]しました': ['reported', 'v', { df: '報告する', cf: 'polite past' }],
    '二[に]度[ど]と': ['never again', 'adv'],
    '来[き]ませんでした': ['did not come', 'v', { df: '来る', cf: 'polite past negative' }],
    '気[き]に入[い]りました': ['grew fond of; liked', 'v', { df: '気に入る', cf: 'polite past' }],
    '毎[まい]晩[ばん]': ['every evening', 'adv'],
    '練[れん]習[しゅう]しました': ['practised', 'v', { df: '練習する', cf: 'polite past' }],
    '旅[たび]人[びと]': ['travellers', 'n'],
    'コンサート': ['concert', 'n'],
    '聞[き]きました': ['heard, listened to', 'v', { df: '聞く', cf: 'polite past' }],
    '最[さい]後[ご]まで': ['in the end; ever', 'adv'],
    '幸[しあわ]せに': ['happily', 'adv', { df: '幸せだ', cf: 'adverbial form' }],
    '暮[く]らしました': ['lived', 'v', { df: '暮らす', cf: 'polite past' }],
    '二[に]匹[ひき]': ['the two animals', 'num'],
    '加[くわ]わり': ['joining; joined and', 'v', { df: '加わる', cf: 'continuative form' }],
    '歌[うた]って': ['singing; sing and', 'v', { df: '歌う', cf: 'te-form' }],
    '次[つぎ]に': ['next', 'adv'],
    '木[き]': ['tree; wood', 'n'],
    '新[あたら]しい': ['new', 'adj'],
    '泥[どろ]棒[ぼう]': ['thief', 'n'],
    'お腹[なか]いっぱい': ['until full; one’s fill', 'adv'],
    '寝[ね]ました': ['slept', 'v', { df: '寝る', cf: 'polite past' }],
    '眠[ねむ]りました': ['slept', 'v', { df: '眠る', cf: 'polite past' }],
    '来[き]た': ['came', 'v', { df: '来る', cf: 'plain past' }],
    '蹴[け]り': ['kicking; kicked and', 'v', { df: '蹴る', cf: 'continuative form' }],
    '所[ところ]': ['place; where someone was', 'n'],
    '行[い]きませんでした': ['did not go', 'v', { df: '行く', cf: 'polite past negative' }],
    'てっぺん': ['top, crown', 'n'],
  }),
  body: [
    [
      line('昔[むかし]|、|粉[こな]ひき小[ご]屋[や]|で|年[とし]を取[と]った|ロバ|が|働[はたら]いていました|。', 'Long ago, an old donkey worked at a flour mill.'),
      line('ロバ|は|重[おも]い|袋[ふくろ]|を|運[はこ]べなくなりました|。', 'The donkey became unable to carry heavy sacks.'),
      line('主[しゅ]人[じん]|は|「|おまえ|の|仕[し]事[ごと]|は|もう|ない|」|と|言[い]いました|。', 'His owner said, “There is no more work for you.”'),
      line('そこで|ロバ|は|ブレーメン|へ|行[い]って|音[おん]楽[がく]隊[たい]|に|入[はい]ろうと決[き]めました|。', 'So the donkey decided to go to Bremen and join a band.'),
    ],
    [
      line('道[みち]|で|疲[つか]れた|犬[いぬ]|が|座[すわ]っていました|。', 'On the road, a tired dog was sitting down.'),
      line('犬[いぬ]|は|「|もう|遠[とお]く|まで|歩[ある]けません|」|と|言[い]いました|。', 'The dog said, “I cannot walk far any more.”'),
      line('ロバ|は|「|一[いっ]緒[しょ]に|バンド|を|作[つく]りませんか|」|と|誘[さそ]いました|。', 'The donkey asked, “Shall we form a band together?”'),
      line('犬[いぬ]|は|喜[よろこ]んで|仲[なか]間[ま]|に|なりました|。', 'The dog gladly became his companion.'),
      line('次[つぎ]に|二[に]匹[ひき]|は|猫[ねこ]|に|会[あ]いました|。', 'Next, the two animals met a cat.'),
      line('猫[ねこ]|は|家[いえ]|を|追[お]い出[だ]された|ので|元[げん]気[き]がありませんでした|。', 'The cat was miserable because she had been driven from her home.'),
      line('「|その|声[こえ]|なら|すてきな|メロディー|を|歌[うた]える|」|と|ロバ|は|言[い]いました|。', '“With that voice, you can sing a lovely melody,” said the donkey.'),
      line('猫[ねこ]|も|バンド|に|加[くわ]わりました|。', 'The cat joined the band too.'),
    ],
    [
      line('門[もん]|の|上[うえ]|で|鳴[な]いている|雄[おん]鶏[どり]|も|見[み]つけました|。', 'They also found a rooster crowing on top of a gate.'),
      line('雄[おん]鶏[どり]|は|「|農[のう]夫[ふ]|が|明[あ]日[した]|の|市[いち]場[ば]|で|私[わたし]|を|売[う]るつもりだ|」|と|言[い]いました|。', 'The rooster said, “The farmer intends to sell me at tomorrow’s market.”'),
      line('「|それ|なら|高[たか]い|コーラス|を|歌[うた]って|ください|」|と|ロバ|は|言[い]いました|。', '“Then please sing the high chorus,” said the donkey.'),
      line('雄[おん]鶏[どり]|も|加[くわ]わり|、|四[よん]匹[ひき]|は|出[しゅっ]発[ぱつ]しました|。', 'The rooster joined, and the four animals set off.'),
      line('歩[ある]きながら|自[じ]分[ぶん]たち|の|歌[うた]|を|歌[うた]いました|。', 'As they walked, they sang their own song.'),
    ],
    [
      line('日[ひ]|が|暮[く]れても|ブレーメン|の|町[まち]|に|着[つ]きませんでした|。', 'Even when night fell, they had not reached Bremen.'),
      line('四[よん]匹[ひき]|は|森[もり]|で|休[やす]むことにしました|。', 'The four decided to rest in the forest.'),
      line('雄[おん]鶏[どり]|が|木[き]|の|てっぺん|に|登[のぼ]りました|。', 'The rooster climbed to the crown of a tree.'),
      line('遠[とお]く|に|家[いえ]|の|明[あ]かり|が|見[み]えました|。', 'A house light was visible in the distance.'),
      line('近[ちか]づくと|、|窓[まど]|の|中[なか]|で|泥[どろ]棒[ぼう]たち|が|ごちそう|を|囲[かこ]んでいました|。', 'When they approached, thieves were gathered around a feast inside.'),
      line('テーブル|に|ソーセージ|や|スープ|が|並[なら]んでいました|。', 'Sausages, soup and other food were spread across the table.'),
      line('四[よん]匹[ひき]|の|お腹[なか]|が|鳴[な]りました|。', 'All four stomachs rumbled.'),
    ],
    [
      line('ロバ|は|作[さく]戦[せん]|を|考[かんが]えました|。', 'The donkey thought up a plan.'),
      line('ロバ|は|前[まえ]足[あし]|を|窓[まど]枠[わく]|に|かけました|。', 'The donkey put his front legs on the window frame.'),
      line('犬[いぬ]|は|ロバ|の|背[せ]中[なか]|に|乗[の]りました|。', 'The dog climbed onto the donkey’s back.'),
      line('猫[ねこ]|は|犬[いぬ]|の|背[せ]中[なか]|に|乗[の]りました|。', 'The cat climbed onto the dog’s back.'),
      line('雄[おん]鶏[どり]|は|猫[ねこ]の上[うえ]|に|乗[の]りました|。', 'The rooster climbed onto the cat.'),
      line('そして|四[よん]匹[ひき]|は|いっせいに|大[おお]声[ごえ]|を|出[だ]しました|。', 'Then all four made a tremendous noise at once.'),
      line('泥[どろ]棒[ぼう]たち|は|不[ぶ]気[き]味[み]な|モンスター|が|来[き]た|と|思[おも]いました|。', 'The thieves thought an eerie monster had come.'),
      line('驚[おどろ]いて|森[もり]|へ|逃[に]げ出[だ]しました|。', 'Terrified, they ran into the forest.'),
      line('四[よん]匹[ひき]|は|家[いえ]|の|中[なか]|に|入[はい]りました|。', 'The four animals went inside the house.'),
      line('ごちそう|を|お腹[なか]いっぱい|食[た]べました|。', 'They ate their fill of the feast.'),
    ],
    [
      line('それぞれ|が|寝[ね]床[どこ]|を|選[えら]びました|。', 'Each chose a place to sleep.'),
      line('ロバ|は|外[そと]|の|わら|の|上[うえ]|、|犬[いぬ]|は|玄[げん]関[かん]|で|寝[ね]ました|。', 'The donkey slept on straw outside and the dog slept by the entrance.'),
      line('猫[ねこ]|は|暖[だん]炉[ろ]|の|そば|、|雄[おん]鶏[どり]|は|屋[や]根[ね]の上[うえ]|で|眠[ねむ]りました|。', 'The cat slept by the fireplace and the rooster slept on the roof.'),
      line('家[いえ]|の|明[あ]かり|を|消[け]しました|。', 'They put out the house lights.'),
    ],
    [
      line('しばらくすると|、|泥[どろ]棒[ぼう]|の|一[ひと]人[り]|が|様[よう]子[す]を見[み]に戻[もど]りました|。', 'After a while, one thief returned to investigate.'),
      line('暗[くら]い|暖[だん]炉[ろ]|へ|手[て]を伸[の]ばしたら|、|猫[ねこ]|が|顔[かお]|を|引[ひ]っかきました|。', 'When he reached towards the dark fireplace, the cat scratched his face.'),
      line('ドア|へ|走[はし]ると|、|犬[いぬ]|が|吠[ほ]えました|。', 'When he ran for the door, the dog barked.'),
      line('犬[いぬ]|は|泥[どろ]棒[ぼう]|の|ズボン|に|かみつきました|。', 'The dog bit into the thief’s trousers.'),
      line('外[そと]|で|ロバ|が|蹴[け]り|、|泥[どろ]棒[ぼう]|は|道[みち]|へ|転[ころ]がりました|。', 'Outside, the donkey kicked and the thief tumbled onto the road.'),
      line('屋[や]根[ね]の上[うえ]|から|雄[おん]鶏[どり]|が|「|泥[どろ]棒[ぼう]|だ|」|と|叫[さけ]びました|。', 'From the roof, the rooster cried, “Thief!”'),
      line('泥[どろ]棒[ぼう]|は|仲[なか]間[ま]|の|所[ところ]|へ|戻[もど]って|、|家[いえ]|に|怪[かい]物[ぶつ]|が|いる|と|報[ほう]告[こく]しました|。', 'The thief returned to his companions and reported that monsters lived in the house.'),
      line('泥[どろ]棒[ぼう]たち|は|二[に]度[ど]と|来[き]ませんでした|。', 'The thieves never came back.'),
    ],
    [
      line('四[よん]匹[ひき]|は|その|家[いえ]|が|気[き]に入[い]りました|。', 'The four animals grew fond of the house.'),
      line('毎[まい]晩[ばん]|、|バンド|で|練[れん]習[しゅう]しました|。', 'Every evening, they practised as a band.'),
      line('旅[たび]人[びと]|は|森[もり]|の|コンサート|を|聞[き]きました|。', 'Travellers heard their concerts in the forest.'),
      line('四[よん]匹[ひき]|は|最[さい]後[ご]まで|ブレーメン|に|行[い]きませんでした|。', 'In the end, the four never went to Bremen.'),
      line('それでも|新[あたら]しい|家[いえ]|で|幸[しあわ]せに|暮[く]らしました|。', 'Even so, they lived happily in their new home.'),
    ],
  ],
});

export const STORY_SOURCES = [redRidingHood, bremenMusicians];
