import { expandStory, lexicon, line } from './helpers.mjs';

const SOL_SOURCE = (text, notes, licence) => ({
  kind: 'adapted', text, by: 'Sol 5.6', credit: 'Retold by', notes, licence,
});

const alice = expandStory({
  id: 'fushigi-no-kuni-no-alice',
  title: { ja: '不思議の国のアリス', en: 'Alice in Wonderland' },
  series: { id: 'alice', part: 1, of: 1, name: 'Alice in Wonderland' },
  level: 'L6',
  gram: 'G6',
  blurb: 'Alice follows a waistcoated White Rabbit underground, where doors, keys, bottles and cakes refuse to be sensible.',
  source: SOL_SOURCE(
    'Public-domain novel by Lewis Carroll (Alice’s Adventures in Wonderland, 1865), opening episode',
    'An original Japanese retelling and abridgement of the opening episode, not a translation of Carroll’s prose or a modern Japanese edition.',
    'Public domain (Lewis Carroll d. 1898). This retelling and its English translation are original to Kana Quest.',
  ),
  nw: ['アリス', '白ウサギ', 'チョッキ', 'マーマレード', 'ボトル'],
  lexicon: lexicon({
    '夏[なつ]': ['summer', 'n'],
    '午[ご]後[ご]': ['afternoon', 'n'],
    'アリス': ['Alice', 'pn'],
    '姉[あね]': ['older sister', 'n'],
    '川[かわ]岸[ぎし]': ['riverbank', 'n'],
    '座[すわ]っていた': ['was sitting', 'v', { df: '座る', cf: 'plain past progressive' }],
    '姉[あね]': ['sister', 'n'],
    '本[ほん]': ['book', 'n'],
    '読[よ]んでいた': ['was reading', 'v', { df: '読む', cf: 'plain past progressive' }],
    '挿[さし]絵[え]': ['illustrations', 'n'],
    '会[かい]話[わ]': ['dialogue', 'n'],
    '退[たい]屈[くつ]だ': ['is boring', 'adj'],
    '思[おも]った': ['thought', 'v', { df: '思う', cf: 'plain past' }],
    '暑[あつ]さ': ['heat', 'n'],
    '眠[ねむ]気[け]': ['drowsiness', 'n'],
    '頭[あたま]': ['head, mind', 'n'],
    'ぼんやりしていた': ['felt hazy', 'v', { df: 'ぼんやりする', cf: 'plain past progressive' }],
    '花[はな]': ['flowers', 'n'],
    '首[くび]飾[かざ]り': ['garland, necklace', 'n'],
    '作[つく]ろうか': ['whether to make', 'v', { df: '作る', cf: 'volitional question form' }],
    '考[かんが]えていた': ['was considering', 'v', { df: '考える', cf: 'plain past progressive' }],
    '白[しろ]ウサギ': ['White Rabbit', 'pn'],
    '目[め]の前[まえ]': ['before her eyes', 'n'],
    '走[はし]っていった': ['ran past, went running', 'v', { df: '走っていく', cf: 'plain past 〜ていく form' }],
    '最[さい]初[しょ]': ['at first', 'adv'],
    '少[すこ]しも': ['not in the least', 'adv'],
    '不[ふ]思[し]議[ぎ]に思[おも]わなかった': ['did not find strange', 'v', { df: '不思議に思う', cf: 'plain past negative' }],
    'まずい': ['oh dear; this is bad', 'adj'],
    '遅[ち]刻[こく]する': ['will be late', 'v', { df: '遅刻する', cf: 'plain present/future' }],
    '独[ひと]り言[ごと]': ['talking to himself', 'n'],
    '言[い]った': ['said', 'v', { df: '言う', cf: 'plain past' }],
    '耳[みみ]': ['ears', 'n'],
    '赤[あか]い': ['red', 'adj'],
    '目[め]': ['eyes', 'n'],
    'ウサギ': ['rabbit', 'n'],
    '珍[めずら]しくない': ['not unusual', 'adj', { df: '珍しい', cf: 'plain negative' }],
    'しかし': ['however, but', 'adv'],
    'チョッキ': ['waistcoat', 'n'],
    'ポケット': ['pocket', 'n'],
    '懐[かい]中[ちゅう]時[ど]計[けい]': ['pocket watch', 'n'],
    '取[と]り出[だ]した': ['pulled out', 'v', { df: '取り出す', cf: 'plain past' }],
    '見[み]た': ['looked at, saw', 'v', { df: '見る', cf: 'plain past' }],
    '瞬[しゅん]間[かん]': ['moment, instant', 'n'],
    '跳[と]び上[あ]がった': ['sprang up', 'v', { df: '跳び上がる', cf: 'plain past' }],
    '考[かんが]えるより先[さき]に': ['before stopping to think', 'adv'],
    '追[お]いかけていた': ['was chasing after', 'v', { df: '追いかける', cf: 'plain past progressive' }],
    '生[い]け垣[がき]': ['hedge', 'n'],
    '根[ね]元[もと]': ['base, foot', 'n'],
    '穴[あな]': ['hole', 'n'],
    '飛[と]び込[こ]んだ': ['jumped into', 'v', { df: '飛び込む', cf: 'plain past' }],
    '帰[かえ]る': ['return, get home', 'v', { df: '帰る', cf: 'plain present' }],
    '方[ほう]法[ほう]': ['way, method', 'n'],
    '考[かんが]えもしなかった': ['did not even think about', 'v', { df: '考える', cf: 'plain emphatic past negative' }],
    'ウサギ穴[あな]': ['rabbit hole', 'n'],
    '初[はじ]め': ['at first', 'adv'],
    'トンネル': ['tunnel', 'n'],
    '続[つづ]いていた': ['continued', 'v', { df: '続く', cf: 'plain past progressive' }],
    '急[きゅう]に': ['suddenly, steeply', 'adv', { df: '急だ', cf: 'adverbial form' }],
    '井[い]戸[ど]': ['well, shaft', 'n'],
    '落[お]ち始[はじ]めた': ['began falling', 'v', { df: '落ち始める', cf: 'plain past' }],
    '深[ふか]すぎて': ['being too deep; so deep that', 'adj', { df: '深い', cf: 'te-form 〜すぎる form' }],
    '底[そこ]': ['bottom', 'n'],
    '見[み]えなかった': ['could not be seen', 'v', { df: '見える', cf: 'plain past negative' }],
    '落[お]ちながら': ['while falling', 'v', { df: '落ちる', cf: '〜ながら form' }],
    '周[まわ]り': ['surroundings', 'n'],
    '見[み]回[まわ]す': ['look around', 'v', { df: '見回す', cf: 'plain present' }],
    '余[よ]裕[ゆう]': ['composure, leeway', 'n'],
    'あった': ['had, existed', 'v', { df: 'ある', cf: 'plain past' }],
    '壁[かべ]': ['walls', 'n'],
    '本[ほん]棚[だな]': ['bookshelves', 'n'],
    '地[ち]図[ず]': ['maps', 'n'],
    '絵[え]': ['pictures', 'n'],
    '掛[か]けられていた': ['were hung', 'v', { df: '掛ける', cf: 'plain past passive progressive' }],
    '棚[たな]': ['shelf', 'n'],
    'オレンジ': ['orange', 'n'],
    'マーマレード': ['marmalade', 'n'],
    '書[か]かれた': ['labelled; written', 'adj', { df: '書く', cf: 'plain past passive (modifying a noun)' }],
    '瓶[びん]': ['jar', 'n'],
    'つかんだ': ['grabbed', 'v', { df: 'つかむ', cf: 'plain past' }],
    '残[ざん]念[ねん]ながら': ['unfortunately', 'adv', { df: '残念だ', cf: '〜ながら form' }],
    '空[から]だった': ['was empty', 'adj', { df: '空だ', cf: 'plain past' }],
    '下[した]': ['below', 'n'],
    '誰[だれ]か': ['someone', 'pn'],
    '当[あ]たったら危[あぶ]ない': ['would be dangerous if it hit', 'v', { df: '当たる', cf: 'conditional 〜たら form' }],
    '落[お]とさず': ['without dropping', 'v', { df: '落とす', cf: '"without ...ing" form' }],
    '別[べつ]': ['another, different', 'adj'],
    '棚[たな]': ['shelf', 'n'],
    '戻[もど]した': ['put back', 'v', { df: '戻す', cf: 'plain past' }],
    '自[じ]分[ぶん]': ['herself, oneself', 'pn'],
    '勇[ゆう]敢[かん]さ': ['bravery', 'n'],
    '感[かん]心[しん]してくれるだろう': ['would probably admire', 'v', { df: '感心する', cf: 'plain probable 〜てくれる form' }],
    '想[そう]像[ぞう]した': ['imagined', 'v', { df: '想像する', cf: 'plain past' }],
    '家[いえ]': ['home, house', 'n'],
    '階[かい]段[だん]': ['stairs', 'n'],
    '転[ころ]げ落[お]ちても': ['even if she tumbled down', 'v', { df: '転げ落ちる', cf: '"even if" form' }],
    '怖[こわ]くない': ['would not be afraid', 'adj', { df: '怖い', cf: 'plain negative' }],
    '思[おも]った': ['thought', 'v', { df: '思う', cf: 'plain past' }],
    '地[ち]球[きゅう]': ['Earth', 'n'],
    '真[ま]ん中[なか]': ['very centre', 'n'],
    '突[つ]き抜[ぬ]けたら': ['if she passed right through', 'v', { df: '突き抜ける', cf: 'conditional 〜たら form' }],
    '国[くに]': ['country', 'n'],
    '出[で]るのだろう': ['wondered where she would emerge', 'v', { df: '出る', cf: 'plain speculative form' }],
    '緯[い]度[ど]': ['latitude', 'n'],
    '経[けい]度[ど]': ['longitude', 'n'],
    '難[むずか]しい': ['difficult', 'adj'],
    '言[こと]葉[ば]': ['words', 'n'],
    '声[こえ]に出[だ]してみた': ['tried saying aloud', 'v', { df: '声に出す', cf: 'plain past 〜てみる form' }],
    '正[ただ]しい': ['correct', 'adj'],
    '使[つか]い方[かた]': ['use, way of using', 'n'],
    '知[し]らなかった': ['did not know', 'v', { df: '知る', cf: 'plain past negative' }],
    '聞[き]く': ['hearing; ask', 'v', { df: '聞く', cf: 'plain present' }],
    '人[ひと]': ['person', 'n'],
    'いなかった': ['was not there', 'v', { df: 'いる', cf: 'plain past negative' }],
    '飼[か]い猫[ねこ]': ['pet cat', 'n'],
    'ダイナ': ['Dinah', 'pn'],
    '今[いま]': ['now', 'adv'],
    '何[なに]をしているだろう': ['wondered what she was doing', 'v', { df: '何をしている', cf: 'plain speculative form' }],
    '夕[ゆう]食[しょく]': ['supper, evening meal', 'n'],
    'ミルク': ['milk', 'n'],
    '忘[わす]れられていないだろうか': ['wondered whether it had been forgotten', 'v', { df: '忘れる', cf: 'plain passive progressive speculative negative question' }],
    '心[しん]配[ぱい]した': ['worried', 'v', { df: '心配する', cf: 'plain past' }],
    'やがて': ['before long', 'adv'],
    '独[ひと]り言[ごと]': ['talking to herself', 'n'],
    '途[と]切[ぎ]れ': ['trailing off; stopped and', 'v', { df: '途切れる', cf: 'continuative form' }],
    '夢[ゆめ]': ['dream', 'n'],
    '中[なか]': ['inside', 'n'],
    '落[お]ちているような気[き]がした': ['felt as though she were falling', 'v', { df: '落ちる', cf: 'plain progressive simile form' }],
    'どさり': ['with a thump', 'adv'],
    '枯[か]れ葉[は]': ['dry leaves', 'n'],
    '小[こ]枝[えだ]': ['twigs', 'n'],
    '山[やま]': ['pile, heap', 'n'],
    '上[うえ]': ['on top of', 'n'],
    '着[ちゃく]地[ち]した': ['landed', 'v', { df: '着地する', cf: 'plain past' }],
    'けが': ['injury', 'n'],
    'すぐ': ['immediately', 'adv'],
    '立[た]ち上[あ]がった': ['stood up', 'v', { df: '立ち上がる', cf: 'plain past' }],
    '白[しろ]ウサギ': ['White Rabbit', 'pn'],
    '角[かど]': ['corner', 'n'],
    '曲[ま]がる': ['turning', 'v', { df: '曲がる', cf: 'plain present' }],
    'ところ': ['moment, point', 'n'],
    '見[み]えた': ['could see', 'v', { df: '見える', cf: 'plain past' }],
    '追[お]って': ['following; chased and', 'v', { df: '追う', cf: 'te-form' }],
    '走[はし]った': ['ran', 'v', { df: '走る', cf: 'plain past' }],
    '次[つぎ]': ['next', 'n'],
    '角[かど]': ['corner', 'n'],
    '姿[すがた]': ['sight, figure', 'n'],
    '消[き]えていた': ['had disappeared', 'v', { df: '消える', cf: 'plain past perfect' }],
    '代[か]わり': ['in its place', 'n'],
    '長[なが]い': ['long', 'adj'],
    '低[ひく]い': ['low', 'adj'],
    '広[ひろ]間[ま]': ['hall', 'n'],
    '出[で]た': ['came out, emerged', 'v', { df: '出る', cf: 'plain past' }],
    '天[てん]井[じょう]': ['ceiling', 'n'],
    '一[いち]列[れつ]': ['row, line', 'n'],
    'ランプ': ['lamps', 'n'],
    '下[さ]がっていた': ['were hanging', 'v', { df: '下がる', cf: 'plain past progressive' }],
    '周[しゅう]囲[い]': ['all around, surroundings', 'n'],
    'ドア': ['doors', 'n'],
    'あった': ['there were', 'v', { df: 'ある', cf: 'plain past' }],
    '全[ぜん]部[ぶ]': ['all of them', 'n'],
    '鍵[かぎ]': ['locked; lock', 'n'],
    'かかっていた': ['were locked', 'v', { df: 'かかる', cf: 'plain past progressive' }],
    '片[かた]っ端[ぱし]から': ['one after another, from the first onward', 'adv'],
    '開[あ]けようとした': ['tried to open', 'v', { df: '開ける', cf: 'plain past "try to" form' }],
    'どれ': ['none; which one', 'n'],
    '開[あ]かなかった': ['would not open', 'v', { df: '開く', cf: 'plain past negative' }],
    '広[ひろ]間[ま]': ['hall', 'n'],
    '真[ま]ん中[なか]': ['centre', 'n'],
    'ガラス': ['glass', 'n'],
    '三[さん]本[ぼん]脚[あし]': ['three-legged', 'adj'],
    'テーブル': ['table', 'n'],
    '立[た]っていた': ['was standing', 'v', { df: '立つ', cf: 'plain past progressive' }],
    '上[うえ]': ['on top', 'n'],
    '小[ちい]さな': ['tiny, small', 'adj'],
    '金[きん]色[いろ]': ['golden', 'adj'],
    '置[お]かれていた': ['had been placed', 'v', { df: '置く', cf: 'plain past passive progressive' }],
    '試[ため]してみた': ['tried out', 'v', { df: '試す', cf: 'plain past 〜てみる form' }],
    '鍵[かぎ]穴[あな]': ['keyhole', 'n'],
    '合[あ]わなかった': ['did not fit', 'v', { df: '合う', cf: 'plain past negative' }],
    '二[に]度[ど]目[め]': ['second time', 'n'],
    '回[まわ]った': ['went around', 'v', { df: '回る', cf: 'plain past' }],
    'カーテン': ['curtain', 'n'],
    '隠[かく]れた': ['hidden', 'adj', { df: '隠れる', cf: 'plain past (modifying a noun)' }],
    '高[たか]さ': ['height', 'n'],
    '十[じゅう]五[ご]センチ': ['fifteen centimetres', 'num'],
    '小[ちい]さな': ['tiny', 'adj'],
    'ドア': ['door', 'n'],
    '発[はっ]見[けん]した': ['discovered', 'v', { df: '発見する', cf: 'plain past' }],
    '金[きん]色[いろ]': ['golden', 'adj'],
    'ぴったり': ['perfectly', 'adv'],
    '合[あ]った': ['fitted', 'v', { df: '合う', cf: 'plain past' }],
    '向[む]こう': ['other side, beyond', 'n'],
    '明[あか]るい': ['bright', 'adj'],
    '庭[にわ]': ['garden', 'n'],
    '見[み]えた': ['could see', 'v', { df: '見える', cf: 'plain past' }],
    '花[はな]壇[だん]': ['flowerbeds', 'n'],
    '噴[ふん]水[すい]': ['fountains', 'n'],
    '日[ひ]差[ざ]し': ['sunlight', 'n'],
    '輝[かがや]いていた': ['were shining', 'v', { df: '輝く', cf: 'plain past progressive' }],
    '通[とお]り抜[ぬ]ける': ['pass through', 'v', { df: '通り抜ける', cf: 'plain present' }],
    '大[おお]きすぎた': ['was too large', 'adj', { df: '大きい', cf: 'plain past 〜すぎる form' }],
    '頭[あたま]': ['head', 'n'],
    '入[はい]らなかった': ['would not fit', 'v', { df: '入る', cf: 'plain past negative' }],
    '体[からだ]': ['body', 'n'],
    '望[のぞ]み': ['wish, desire', 'n'],
    '置[お]き忘[わす]れてきた': ['had left behind', 'v', { df: '置き忘れる', cf: 'plain past 〜てくる form' }],
    'たたむ': ['folding up', 'v', { df: 'たたむ', cf: 'plain present' }],
    '望[ぼう]遠[えん]鏡[きょう]': ['telescope', 'n'],
    '小[ちい]さくなれたら': ['if she could become small', 'v', { df: '小さくなる', cf: 'conditional potential 〜たら form' }],
    '思[おも]った': ['thought, wished', 'v', { df: '思う', cf: 'plain past' }],
    '戻[もど]ると': ['when she returned', 'v', { df: '戻る', cf: 'conditional 〜と form' }],
    '青[あお]い': ['blue', 'adj'],
    'ボトル': ['bottle', 'n'],
    '置[お]かれていた': ['had been placed', 'v', { df: '置く', cf: 'plain past passive progressive' }],
    '前[まえ]': ['before, previously', 'n'],
    '確[たし]かに': ['certainly', 'adv'],
    'なかった': ['was not there', 'v', { df: 'ある', cf: 'plain past negative' }],
    '首[くび]': ['neck', 'n'],
    '札[ふだ]': ['tag, label', 'n'],
    '飲[の]んで': ['drink me', 'v', { df: '飲む', cf: 'te-form request' }],
    '大[おお]きな': ['large', 'adj'],
    '文[も]字[じ]': ['letters, writing', 'n'],
    '印[いん]刷[さつ]されていた': ['was printed', 'v', { df: '印刷する', cf: 'plain past passive progressive' }],
    '用[よう]心[じん]深[ぶか]く': ['cautiously', 'adv', { df: '用心深い', cf: 'adverbial form' }],
    '毒[どく]': ['poison', 'n'],
    '書[か]いていないか': ['whether it said', 'v', { df: '書く', cf: 'plain progressive negative question' }],
    '調[しら]べた': ['checked, examined', 'v', { df: '調べる', cf: 'plain past' }],
    '何[なに]も': ['nothing', 'n'],
    '警[けい]告[こく]': ['warning', 'n'],
    '香[かお]り': ['aroma', 'n'],
    '試[ため]しに': ['as a test', 'adv'],
    '一[ひと]口[くち]': ['one sip', 'num'],
    '飲[の]んだ': ['drank', 'v', { df: '飲む', cf: 'plain past' }],
    '味[あじ]': ['taste, flavour', 'n'],
    'チェリータルト': ['cherry tart', 'n'],
    'トースト': ['toast', 'n'],
    'キャラメル': ['caramel', 'n'],
    'オレンジ': ['orange', 'n'],
    '混[ま]ぜたようだった': ['seemed mixed together', 'v', { df: '混ぜる', cf: 'plain past simile form' }],
    'おいしさ': ['deliciousness', 'n'],
    '一[いっ]気[き]に': ['all at once', 'adv'],
    '飲[の]み干[ほ]した': ['drank it all', 'v', { df: '飲み干す', cf: 'plain past' }],
    '体[からだ]': ['body', 'n'],
    '縮[ちぢ]み始[はじ]めた': ['began to shrink', 'v', { df: '縮み始める', cf: 'plain past' }],
    '最[さい]後[ご]': ['finally', 'adv'],
    '人[にん]形[ぎょう]': ['doll', 'n'],
    '背[せ]丈[たけ]': ['height, stature', 'n'],
    'これなら': ['at this size; if so', 'adv'],
    '庭[にわ]': ['garden', 'n'],
    '行[い]ける': ['can go', 'v', { df: '行く', cf: 'potential form' }],
    '喜[よろこ]んだ': ['rejoiced', 'v', { df: '喜ぶ', cf: 'plain past' }],
    '直[す]ぐ': ['immediately', 'adv'],
    'テーブル': ['table', 'n'],
    '上[うえ]': ['top', 'n'],
    '鍵[かぎ]': ['key', 'n'],
    '取[と]る': ['take, reach', 'v', { df: '取る', cf: 'plain present' }],
    '手[て]': ['hand', 'n'],
    '届[とど]かなくなっていた': ['could no longer reach', 'v', { df: '届く', cf: 'plain potential negative 〜なる form' }],
    '脚[あし]': ['leg', 'n'],
    '登[のぼ]ろうとした': ['tried to climb', 'v', { df: '登る', cf: 'plain past "try to" form' }],
    'ガラス': ['glass', 'n'],
    '滑[すべ]って': ['slipping; slipped and', 'v', { df: '滑る', cf: 'te-form' }],
    '何[なん]度[ど]': ['many times', 'n'],
    '失[しっ]敗[ぱい]した': ['failed', 'v', { df: '失敗する', cf: 'plain past' }],
    '床[ゆか]': ['floor', 'n'],
    '座[すわ]り込[こ]んだ': ['sat down heavily', 'v', { df: '座り込む', cf: 'plain past' }],
    '泣[な]いても': ['even if you cry', 'v', { df: '泣く', cf: '"even if" form' }],
    '仕[し]方[かた]がない': ['it will not help; there is no point', 'v'],
    '自[じ]分[ぶん]': ['herself', 'pn'],
    '言[い]い聞[き]かせた': ['told herself firmly', 'v', { df: '言い聞かせる', cf: 'plain past causative' }],
    '泣[な]き続[つづ]けた': ['kept crying', 'v', { df: '泣き続ける', cf: 'plain past' }],
    'しばらくして': ['after a while', 'adv'],
    'テーブル': ['table', 'n'],
    '下[した]': ['underneath', 'n'],
    '小[ちい]さな': ['small', 'adj'],
    'ガラス箱[ばこ]': ['glass box', 'n'],
    '見[み]つけた': ['found', 'v', { df: '見つける', cf: 'plain past' }],
    '中[なか]': ['inside', 'n'],
    'ケーキ': ['cake', 'n'],
    '入[はい]っていた': ['was inside', 'v', { df: '入る', cf: 'plain past progressive' }],
    '食[た]べて': ['eat me', 'v', { df: '食べる', cf: 'te-form request' }],
    'レーズン': ['raisins', 'n'],
    '並[なら]べられていた': ['had been arranged', 'v', { df: '並べる', cf: 'plain past passive progressive' }],
    '今[こん]度[ど]': ['this time', 'n'],
    '大[おお]きくなるか': ['whether she would grow', 'v', { df: '大きくなる', cf: 'plain question form' }],
    '小[ちい]さくなるか': ['whether she would shrink', 'v', { df: '小さくなる', cf: 'plain question form' }],
    'どちら': ['whichever; which', 'n'],
    '都[つ]合[ごう]がいい': ['would be useful', 'adj'],
    '一[ひと]口[くち]': ['one bite', 'num'],
    '食[た]べた': ['ate', 'v', { df: '食べる', cf: 'plain past' }],
    '何[なに]も': ['nothing', 'n'],
    '起[お]こらなかった': ['did not happen', 'v', { df: '起こる', cf: 'plain past negative' }],
    '残[のこ]り': ['the rest', 'n'],
    '食[た]べた': ['ate', 'v', { df: '食べる', cf: 'plain past' }],
    '途[と]端[たん]': ['instant, moment', 'n'],
    '頭[あたま]': ['head', 'n'],
    '天[てん]井[じょう]': ['ceiling', 'n'],
    'ぶつかった': ['bumped into', 'v', { df: 'ぶつかる', cf: 'plain past' }],
    '首[くび]': ['neck', 'n'],
    '伸[の]び': ['stretching; grew and', 'v', { df: '伸びる', cf: 'continuative form' }],
    '足[あし]元[もと]': ['feet, area below', 'n'],
    '遠[とお]く': ['far away', 'adv'],
    '望[ぼう]遠[えん]鏡[きょう]': ['telescope', 'n'],
    '逆[ぎゃく]向[む]き': ['in reverse', 'adv'],
    '開[ひら]いたようだった': ['seemed to have opened', 'v', { df: '開く', cf: 'plain past simile form' }],
    '今[いま]': ['now', 'adv'],
    '鍵[かぎ]': ['key', 'n'],
    '簡[かん]単[たん]に': ['easily', 'adv', { df: '簡単だ', cf: 'adverbial form' }],
    '取[と]れた': ['could take', 'v', { df: '取る', cf: 'plain potential past' }],
    '小[ちい]さな': ['tiny', 'adj'],
    'ドア': ['door', 'n'],
    '通[とお]れない': ['cannot pass through', 'v', { df: '通る', cf: 'plain potential negative' }],
    'ひどく': ['terribly', 'adv'],
    '腹[はら]を立[た]てた': ['became angry', 'v', { df: '腹を立てる', cf: 'plain past' }],
    '片[かた]手[て]': ['one hand', 'n'],
    '鍵[かぎ]': ['key', 'n'],
    '握[にぎ]り': ['gripping; held and', 'v', { df: '握る', cf: 'continuative form' }],
    'もう片[かた]方[ほう]': ['the other hand', 'n'],
    '扇[せん]子[す]': ['fan', 'n'],
    '欲[ほ]しい': ['wanted', 'adj'],
    'つぶやいた': ['muttered', 'v', { df: 'つぶやく', cf: 'plain past' }],
    '廊[ろう]下[か]': ['corridor', 'n'],
    '向[む]こう': ['far end', 'n'],
    '足[あし]音[おと]': ['footsteps', 'n'],
    '聞[き]こえた': ['could be heard', 'v', { df: '聞こえる', cf: 'plain past' }],
    '白[しろ]ウサギ': ['White Rabbit', 'pn'],
    '戻[もど]ってきた': ['came back', 'v', { df: '戻る', cf: 'plain past 〜てくる form' }],
    '白[しろ]い': ['white', 'adj'],
    '手[て]袋[ぶくろ]': ['gloves', 'n'],
    '大[おお]きな': ['large', 'adj'],
    '扇[せん]子[す]': ['fan', 'n'],
    '抱[かか]えていた': ['was carrying', 'v', { df: '抱える', cf: 'plain past progressive' }],
    '公[こう]爵[しゃく]夫[ふ]人[じん]': ['Duchess', 'n'],
    'お待[ま]たせしたら': ['if I keep her waiting', 'v', { df: 'お待たせする', cf: 'humble conditional 〜たら form' }],
    '何[なん]と言[い]われることか': ['what she will say to me', 'v', { df: '言う', cf: 'plain passive exclamatory form' }],
    'ぶつぶつ言[い]っていた': ['was muttering', 'v', { df: 'ぶつぶつ言う', cf: 'plain past progressive' }],
    'アリス': ['Alice', 'pn'],
    '姿[すがた]': ['sight, figure', 'n'],
    '気[き]づくと': ['when he noticed', 'v', { df: '気づく', cf: 'conditional 〜と form' }],
    'メアリー・アン': ['Mary Ann', 'pn'],
    'どうして': ['why', 'adv'],
    '命[めい]令[れい]した': ['ordered', 'v', { df: '命令する', cf: 'plain past' }],
    '驚[おどろ]き': ['being startled; startled and', 'v', { df: '驚く', cf: 'continuative form' }],
    '手[て]袋[ぶくろ]': ['gloves', 'n'],
    '扇[せん]子[す]': ['fan', 'n'],
    '落[お]として': ['dropping; dropped and', 'v', { df: '落とす', cf: 'te-form' }],
    '逃[に]げた': ['ran away', 'v', { df: '逃げる', cf: 'plain past' }],
    '拾[ひろ]った': ['picked up', 'v', { df: '拾う', cf: 'plain past' }],
    '暑[あつ]い': ['hot', 'adj'],
    '顔[かお]': ['face', 'n'],
    'あおぎ始[はじ]めた': ['began fanning', 'v', { df: 'あおぎ始める', cf: 'plain past' }],
    '一[いっ]体[たい]': ['on earth; exactly', 'adv'],
    '誰[だれ]なのだろう': ['wondered who she was', 'v', { df: '誰だ', cf: 'plain speculative form' }],
    '朝[あさ]': ['this morning', 'n'],
    '起[お]きた': ['woke up', 'v', { df: '起きる', cf: 'plain past (modifying a noun)' }],
    '時[とき]': ['time', 'n'],
    '同[おな]じ': ['same', 'adj'],
    '確[たし]かめるため': ['in order to check', 'v', { df: '確かめる', cf: 'purpose form' }],
    '暗[あん]唱[しょう]してみた': ['tried reciting', 'v', { df: '暗唱する', cf: 'plain past 〜てみる form' }],
    '詩[し]': ['poem', 'n'],
    '全[まった]く': ['completely', 'adv'],
    '違[ちが]う': ['different, wrong', 'adj'],
    '言[こと]葉[ば]': ['words', 'n'],
    '出[で]てきた': ['came out', 'v', { df: '出る', cf: 'plain past 〜てくる form' }],
    '夢[ゆめ]': ['dream', 'n'],
    '見[み]ているのかもしれない': ['might be dreaming', 'v', { df: '見る', cf: 'plain progressive possibility form' }],
    '思[おも]った': ['thought', 'v', { df: '思う', cf: 'plain past' }],
    'あおぐ': ['fanning', 'v', { df: 'あおぐ', cf: 'plain present' }],
    '体[からだ]': ['body', 'n'],
    '再[ふたた]び': ['again', 'adv'],
    '縮[ちぢ]み始[はじ]めた': ['began shrinking', 'v', { df: '縮み始める', cf: 'plain past' }],
    '危[あぶ]うく': ['nearly, narrowly', 'adv'],
    '消[き]えてしまう': ['would disappear completely', 'v', { df: '消える', cf: 'plain present 〜てしまう form' }],
    '前[まえ]': ['before', 'n'],
    '投[な]げ捨[す]てた': ['threw away', 'v', { df: '投げ捨てる', cf: 'plain past' }],
    '身[しん]長[ちょう]': ['height', 'n'],
    '二[に]十[じゅっ]センチ': ['twenty centimetres', 'num'],
    '落[お]ち着[つ]いた': ['settled, stopped changing', 'v', { df: '落ち着く', cf: 'plain past' }],
    'これで': ['with this; now', 'adv'],
    '庭[にわ]': ['garden', 'n'],
    '入[はい]れる': ['can enter', 'v', { df: '入る', cf: 'potential form' }],
    'ドア': ['door', 'n'],
    '駆[か]け寄[よ]った': ['rushed up to', 'v', { df: '駆け寄る', cf: 'plain past' }],
    '鍵[かぎ]': ['key', 'n'],
    'まだ': ['still', 'adv'],
    'テーブル': ['table', 'n'],
    '上[うえ]': ['top', 'n'],
    '思[おも]い出[だ]した': ['remembered', 'v', { df: '思い出す', cf: 'plain past' }],
    '二[に]度[ど]目[め]': ['second time', 'n'],
    '自[じ]分[ぶん]': ['herself', 'pn'],
    '愚[おろ]かさ': ['foolishness', 'n'],
    '腹[はら]を立[た]てた': ['became angry', 'v', { df: '腹を立てる', cf: 'plain past' }],
    '涙[なみだ]': ['tears', 'n'],
    '止[と]まらなくなった': ['would no longer stop', 'v', { df: '止まる', cf: 'plain negative 〜なる form' }],
    '大[おお]粒[つぶ]': ['large drops', 'n'],
    '床[ゆか]': ['floor', 'n'],
    '落[お]ち': ['falling; fell and', 'v', { df: '落ちる', cf: 'continuative form' }],
    '足[あし]首[くび]': ['ankles', 'n'],
    '深[ふか]さ': ['depth', 'n'],
    '水[みず]たまり': ['pool', 'n'],
    '広[ひろ]がった': ['spread, grew', 'v', { df: '広がる', cf: 'plain past' }],
    '泳[およ]がなければならない': ['would have to swim', 'v', { df: '泳ぐ', cf: '〜なければならない form' }],
    '困[こま]った': ['was in trouble, perplexed', 'v', { df: '困る', cf: 'plain past' }],
    '数[すう]分[ふん]前[まえ]': ['a few minutes earlier', 'adv'],
    '大[おお]きかった': ['had been large', 'adj', { df: '大きい', cf: 'plain past' }],
    '自[じ]分[ぶん]': ['herself', 'pn'],
    '涙[なみだ]': ['tears', 'n'],
    '海[うみ]': ['sea', 'n'],
    '作[つく]った': ['had made', 'v', { df: '作る', cf: 'plain past' }],
    '泣[な]きすぎた': ['had cried too much', 'v', { df: '泣く', cf: 'plain past 〜すぎる form' }],
    '後[こう]悔[かい]しても': ['even if she regretted it', 'v', { df: '後悔する', cf: '"even if" form' }],
    '遅[おそ]かった': ['was too late', 'adj', { df: '遅い', cf: 'plain past' }],
    'が#but': ['but, although', 'part'],
    'ある': ['a certain; located', 'adj'],
    'まず': ['first; oh dear', 'adv'],
    '時[とき]': ['when, time', 'n'],
    'いなければ': ['if there were not', 'v', { df: 'いる', cf: 'conditional negative 〜ば form' }],
    'これほど': ['this much, so greatly', 'adv'],
    'あまり': ['so much that; excess', 'part'],
    'いくつも': ['many', 'adv'],
    'うち': ['while; during', 'n'],
    'ここ': ['here', 'n'],
    'こと': ['act or fact; nominaliser', 'n'],
    'このまま': ['if things stay this way', 'adv'],
    'これから': ['from now on', 'adv'],
    'さえ': ['even', 'part'],
    'した': ['did; gave off', 'v', { df: 'する', cf: 'plain past' }],
    'だった': ['was', 'aux', { df: 'だ', cf: 'plain past' }],
    'でも': ['even; whichever', 'part'],
    'ところが': ['however; instead', 'adv'],
    'どの': ['which; every', 'adj'],
    'ない': ['there is no; without', 'adj'],
    'なく': ['without; not being', 'adj', { df: 'ない', cf: 'continuative form' }],
    'なの': ['is; explanatory form', 'aux', { df: 'だ', cf: 'explanatory form' }],
    'なんて': ['such a thing as; dismissive topic marker', 'part'],
    'になった': ['became', 'v', { df: 'なる', cf: 'plain past' }],
    'のような': ['like; resembling', 'part'],
    'のように': ['like; in the manner of', 'part'],
    'はず': ['expectation; ought to', 'n'],
    'もう': ['already, now', 'adv'],
    'わずか': ['only, merely', 'adv'],
    '並[なら]び': ['lining up; stood in rows', 'v', { df: '並ぶ', cf: 'continuative form' }],
    '後[あと]': ['after; behind', 'n'],
    '摘[つ]んで': ['picking; pick and', 'v', { df: '摘む', cf: 'te-form' }],
    '時[と]計[けい]': ['watch, clock', 'n'],
    '曲[ま]がり': ['turning; turned and', 'v', { df: '曲がる', cf: 'continuative form' }],
    '泣[な]かない': ['not crying', 'v', { df: '泣く', cf: 'plain negative' }],
    '泣[な]けば': ['if she kept crying', 'v', { df: '泣く', cf: 'conditional 〜ば form' }],
    '消[き]えていった': ['receded, disappeared away', 'v', { df: '消えていく', cf: 'plain past 〜ていく form' }],
    '甘[あま]い': ['sweet', 'adj'],
    '考[かんが]えた': ['thought, wondered', 'v', { df: '考える', cf: 'plain past' }],
    '落[お]ちても': ['even after falling', 'v', { df: '落ちる', cf: '"even if" form' }],
    '覚[おぼ]えている': ['remembers', 'v', { df: '覚える', cf: 'plain present progressive' }],
    '誰[だれ]': ['who; anyone', 'pn'],
    '追[お]った': ['followed, chased', 'v', { df: '追う', cf: 'plain past' }],
    '長[なが]く': ['long; in a long shape', 'adv', { df: '長い', cf: 'adverbial form' }],
    'として': ['as; in the role of', 'part'],
  }),
  body: [
    [
      line('夏[なつ]|の|午[ご]後[ご]|、|アリス|は|姉[あね]|と|川[かわ]岸[ぎし]|に|座[すわ]っていた|。', 'One summer afternoon, Alice was sitting with her sister on the riverbank.'),
      line('姉[あね]|は|本[ほん]|を|読[よ]んでいた|。', 'Her sister was reading a book.'),
      line('「|挿[さし]絵[え]|も|会[かい]話[わ]|も|ない|本[ほん]|なんて|退[たい]屈[くつ]だ|」|と|アリス|は|思[おも]った|。', '“A book with no pictures or conversation is boring,” Alice thought.'),
      line('暑[あつ]さ|と|眠[ねむ]気[け]|で|、|頭[あたま]|は|ぼんやりしていた|。', 'The heat and drowsiness had made her mind hazy.'),
      line('花[はな]|を|摘[つ]んで|首[くび]飾[かざ]り|を|作[つく]ろうか|と|考[かんが]えていた|。', 'She was considering picking flowers to make a garland.'),
      line('その|時[とき]|、|白[しろ]ウサギ|が|目[め]の前[まえ]|を|走[はし]っていった|。', 'Just then, a White Rabbit ran past her.'),
      line('最[さい]初[しょ]|、|アリス|は|少[すこ]しも|不[ふ]思[し]議[ぎ]に思[おも]わなかった|。', 'At first, Alice did not find it strange at all.'),
      line('「|まずい|、|遅[ち]刻[こく]する|」|と|ウサギ|が|独[ひと]り言[ごと]|を|言[い]った|。', '“Oh dear, I shall be late,” the Rabbit said to himself.'),
    ],
    [
      line('長[なが]い|耳[みみ]|と|赤[あか]い|目[め]|の|ウサギ|なら|珍[めずら]しくない|。', 'A rabbit with long ears and red eyes was not unusual.'),
      line('しかし|、|チョッキ|の|ポケット|から|懐[かい]中[ちゅう]時[ど]計[けい]|を|取[と]り出[だ]した|の|は|別[べつ]|だった|。', 'But pulling a pocket watch from a waistcoat was another matter.'),
      line('時[と]計[けい]|を|見[み]た|瞬[しゅん]間[かん]|、|アリス|は|跳[と]び上[あ]がった|。', 'The moment she saw the watch, Alice sprang to her feet.'),
      line('考[かんが]えるより先[さき]に|、|白[しろ]ウサギ|を|追[お]いかけていた|。', 'Before she stopped to think, she was chasing the White Rabbit.'),
      line('ウサギ|は|生[い]け垣[がき]|の|根[ね]元[もと]|に|ある|穴[あな]|へ|飛[と]び込[こ]んだ|。', 'The Rabbit jumped into a hole at the foot of the hedge.'),
      line('アリス|も|すぐ|後[あと]|を|追[お]った|。', 'Alice immediately followed.'),
      line('帰[かえ]る|方[ほう]法[ほう]|を|考[かんが]えもしなかった|。', 'She did not even think about how she would get home.'),
      line('ウサギ穴[あな]|は|初[はじ]め|、|長[なが]い|トンネル|のように|続[つづ]いていた|。', 'At first, the rabbit hole continued like a long tunnel.'),
    ],
    [
      line('やがて|急[きゅう]に|下[した]|へ|曲[ま]がり|、|アリス|は|井[い]戸[ど]|のような|穴[あな]|を|落[お]ち始[はじ]めた|。', 'Then it turned sharply down, and Alice began falling through a shaft like a well.'),
      line('穴[あな]|は|深[ふか]すぎて|、|底[そこ]|が|見[み]えなかった|。', 'The hole was so deep that she could not see the bottom.'),
      line('落[お]ちながら|周[まわ]り|を|見[み]回[まわ]す|余[よ]裕[ゆう]|さえ|あった|。', 'As she fell, she even had time to look around.'),
      line('壁[かべ]|に|は|本[ほん]棚[だな]|が|並[なら]び|、|地[ち]図[ず]|や|絵[え]|が|掛[か]けられていた|。', 'Bookshelves lined the walls, with maps and pictures hanging among them.'),
      line('棚[たな]|から|「|オレンジ|・|マーマレード|」|と|書[か]かれた|瓶[びん]|を|つかんだ|。', 'She grabbed a jar labelled “Orange Marmalade” from a shelf.'),
      line('残[ざん]念[ねん]ながら|、|瓶[びん]|は|空[から]だった|。', 'Unfortunately, the jar was empty.'),
      line('下[した]|の|誰[だれ]か|に|当[あ]たったら危[あぶ]ない|ので|、|落[お]とさず|別[べつ]|の|棚[たな]|へ|戻[もど]した|。', 'Since it might hurt someone below, she did not drop it and put it on another shelf.'),
      line('これほど|落[お]ちても|泣[な]かない|自[じ]分[ぶん]|を|家[いえ]|の|人[ひと]|が|感[かん]心[しん]してくれるだろう|と|想[そう]像[ぞう]した|。', 'She imagined that everyone at home would admire her for not crying during such a fall.'),
    ],
    [
      line('これから|は|家[いえ]|の|階[かい]段[だん]|を|転[ころ]げ落[お]ちても|怖[こわ]くない|と|思[おも]った|。', 'She thought she would never fear tumbling down the stairs at home again.'),
      line('地[ち]球[きゅう]|の|真[ま]ん中[なか]|を|突[つ]き抜[ぬ]けたら|、|どの|国[くに]|へ|出[で]るのだろう|。', 'If she passed through the centre of the Earth, what country would she emerge in?'),
      line('「|緯[い]度[ど]|」|や|「|経[けい]度[ど]|」|という|難[むずか]しい|言[こと]葉[ば]|を|声[こえ]に出[だ]してみた|。', 'She tried saying difficult words such as “latitude” and “longitude” aloud.'),
      line('正[ただ]しい|使[つか]い方[かた]|は|知[し]らなかった|が#but|、|聞[き]く|人[ひと]|は|誰[だれ]|も|いなかった|。', 'She did not know their proper use, but nobody was there to hear.'),
      line('飼[か]い猫[ねこ]|の|ダイナ|は|今[いま]|何[なに]をしているだろう|と|考[かんが]えた|。', 'She wondered what her cat Dinah was doing now.'),
      line('夕[ゆう]食[しょく]|の|ミルク|を|忘[わす]れられていないだろうか|と|心[しん]配[ぱい]した|。', 'She worried that Dinah’s supper milk might be forgotten.'),
      line('やがて|独[ひと]り言[ごと]|が|途[と]切[ぎ]れ|、|夢[ゆめ]|の|中[なか]|で|落[お]ちているような気[き]がした|。', 'Before long, her muttering trailed off, and she felt as if she were falling in a dream.'),
      line('どさり|と|枯[か]れ葉[は]|と|小[こ]枝[えだ]|の|山[やま]|の|上[うえ]|に|着[ちゃく]地[ち]した|。', 'With a thump, she landed on a heap of dry leaves and twigs.'),
    ],
    [
      line('けが|は|なく|、|アリス|は|すぐ|立[た]ち上[あ]がった|。', 'She was unhurt and immediately stood up.'),
      line('白[しろ]ウサギ|が|角[かど]|を|曲[ま]がる|ところ|が|見[み]えた|。', 'She saw the White Rabbit turning a corner.'),
      line('追[お]って|走[はし]った|が#but|、|次[つぎ]|の|角[かど]|で|姿[すがた]|は|消[き]えていた|。', 'She ran after him, but he had vanished at the next corner.'),
      line('代[か]わり|に|、|長[なが]く|低[ひく]い|広[ひろ]間[ま]|へ|出[で]た|。', 'Instead, she emerged into a long, low hall.'),
      line('天[てん]井[じょう]|から|一[いち]列[れつ]|の|ランプ|が|下[さ]がっていた|。', 'A row of lamps hung from the ceiling.'),
      line('周[しゅう]囲[い]|に|ドア|が|いくつも|あった|が#but|、|全[ぜん]部[ぶ]|に|鍵[かぎ]|が|かかっていた|。', 'There were many doors around the hall, but every one was locked.'),
      line('アリス|は|片[かた]っ端[ぱし]から|開[あ]けようとした|。', 'Alice tried them one after another.'),
      line('どれ|も|開[あ]かなかった|。', 'None would open.'),
    ],
    [
      line('広[ひろ]間[ま]|の|真[ま]ん中[なか]|に|、|ガラス|の|三[さん]本[ぼん]脚[あし]|の|テーブル|が|立[た]っていた|。', 'In the centre of the hall stood a three-legged glass table.'),
      line('上[うえ]|に|小[ちい]さな|金[きん]色[いろ]|の|鍵[かぎ]|が|置[お]かれていた|。', 'A tiny golden key lay on it.'),
      line('全[ぜん]部[ぶ]|の|ドア|で|試[ため]してみた|が#but|、|どの|鍵[かぎ]穴[あな]|に|も|合[あ]わなかった|。', 'She tried it in every door, but it fitted none of the keyholes.'),
      line('二[に]度[ど]目[め]|に|広[ひろ]間[ま]|を|回[まわ]った|時[とき]|、|カーテン|に|隠[かく]れた|小[ちい]さな|ドア|を|発[はっ]見[けん]した|。', 'On her second circuit of the hall, she discovered a tiny door hidden by a curtain.'),
      line('高[たか]さ|は|わずか|十[じゅう]五[ご]センチ|だった|。', 'It was only fifteen centimetres high.'),
      line('金[きん]色[いろ]|の|鍵[かぎ]|は|ぴったり|合[あ]った|。', 'The golden key fitted perfectly.'),
      line('ドア|の|向[む]こう|に|、|明[あか]るい|庭[にわ]|が|見[み]えた|。', 'Beyond the door, she could see a bright garden.'),
      line('花[はな]壇[だん]|と|噴[ふん]水[すい]|が|日[ひ]差[ざ]し|の|中[なか]|で|輝[かがや]いていた|。', 'Flowerbeds and fountains shone in the sunlight.'),
    ],
    [
      line('アリス|は|通[とお]り抜[ぬ]ける|に|は|大[おお]きすぎた|。', 'Alice was far too large to pass through.'),
      line('頭[あたま]|さえ|入[はい]らなかった|。', 'Even her head would not fit.'),
      line('体[からだ]|を|たたむ|望[ぼう]遠[えん]鏡[きょう]|のように|小[ちい]さくなれたら|と|思[おも]った|。', 'She wished she could shrink like a folding telescope.'),
      line('テーブル|へ|戻[もど]ると|、|青[あお]い|ボトル|が|置[お]かれていた|。', 'When she returned to the table, a blue bottle had appeared.'),
      line('前[まえ]|に|は|確[たし]かに|なかった|。', 'It certainly had not been there before.'),
      line('首[くび]|の|札[ふだ]|に|「|飲[の]んで|」|と|大[おお]きな|文[も]字[じ]|で|印[いん]刷[さつ]されていた|。', 'A tag around its neck said “DRINK ME” in large letters.'),
      line('アリス|は|用[よう]心[じん]深[ぶか]く|、|「|毒[どく]|」|と|書[か]いていないか|調[しら]べた|。', 'Alice cautiously checked that it did not say “poison.”'),
      line('何[なに]も|警[けい]告[こく]|が|なく|、|甘[あま]い|香[かお]り|が|した|ので|試[ため]しに|一[ひと]口[くち]|飲[の]んだ|。', 'There was no warning, and it smelled sweet, so she tried one sip.'),
    ],
    [
      line('味[あじ]|は|チェリータルト|、|トースト|、|キャラメル|、|オレンジ|を|混[ま]ぜたようだった|。', 'It tasted like cherry tart, toast, caramel and orange mixed together.'),
      line('おいしさ|の|あまり|、|アリス|は|一[いっ]気[き]に|飲[の]み干[ほ]した|。', 'It was so delicious that Alice drank it all at once.'),
      line('すぐ|に|体[からだ]|が|縮[ちぢ]み始[はじ]めた|。', 'Her body immediately began to shrink.'),
      line('最[さい]後[ご]|に|は|人[にん]形[ぎょう]|ほど|の|背[せ]丈[たけ]|になった|。', 'At last, she was only as tall as a doll.'),
      line('「|これなら|庭[にわ]|へ|行[い]ける|」|と|喜[よろこ]んだ|。', '“At this size, I can reach the garden,” she rejoiced.'),
      line('しかし|、|テーブル|の|上[うえ]|の|鍵[かぎ]|を|取[と]る|に|は|手[て]|が|届[とど]かなくなっていた|。', 'But she could no longer reach the key on top of the table.'),
      line('脚[あし]|を|登[のぼ]ろうとした|が#but|、|ガラス|で|滑[すべ]って|何[なん]度[ど]|も|失[しっ]敗[ぱい]した|。', 'She tried to climb a leg but slipped on the glass again and again.'),
      line('床[ゆか]|に|座[すわ]り込[こ]んだ|。', 'She sat down on the floor.'),
    ],
    [
      line('「|泣[な]いても|仕[し]方[かた]がない|」|と|自[じ]分[ぶん]|に|言[い]い聞[き]かせた|。', '“Crying will not help,” she told herself firmly.'),
      line('それでも|泣[な]き続[つづ]けた|。', 'Even so, she kept crying.'),
      line('しばらくして|テーブル|の|下[した]|で|小[ちい]さな|ガラス箱[ばこ]|を|見[み]つけた|。', 'After a while, she found a small glass box under the table.'),
      line('中[なか]|に|小[ちい]さな|ケーキ|が|入[はい]っていた|。', 'Inside it was a little cake.'),
      line('「|食[た]べて|」|という|文[も]字[じ]|が|レーズン|で|並[なら]べられていた|。', 'The words “EAT ME” had been arranged in raisins.'),
      line('「|今[こん]度[ど]|は|大[おお]きくなるか|小[ちい]さくなるか|、|どちら|でも|都[つ]合[ごう]がいい|」|と|一[ひと]口[くち]|食[た]べた|。', '“Whether I grow or shrink this time, either would be useful,” she said, taking a bite.'),
      line('何[なに]も|起[お]こらなかった|ので|、|残[のこ]り|も|食[た]べた|。', 'Nothing happened, so she ate the rest.'),
      line('その|途[と]端[たん]|、|頭[あたま]|が|天[てん]井[じょう]|に|ぶつかった|。', 'At that instant, her head struck the ceiling.'),
    ],
    [
      line('首[くび]|が|伸[の]び|、|足[あし]元[もと]|が|遠[とお]く|へ|消[き]えていった|。', 'Her neck stretched, and her feet receded into the distance.'),
      line('望[ぼう]遠[えん]鏡[きょう]|が|逆[ぎゃく]向[む]き|に|開[ひら]いたようだった|。', 'It was as though a telescope had opened in reverse.'),
      line('今[いま]|なら|テーブル|の|鍵[かぎ]|は|簡[かん]単[たん]に|取[と]れた|。', 'Now she could easily take the key from the table.'),
      line('しかし|、|小[ちい]さな|ドア|を|通[とお]れない|こと|に|ひどく|腹[はら]を立[た]てた|。', 'But she was furious that she could not pass through the tiny door.'),
      line('片[かた]手[て]|に|鍵[かぎ]|を|握[にぎ]り|、|もう片[かた]方[ほう]|に|扇[せん]子[す]|が|欲[ほ]しい|と|つぶやいた|。', 'She gripped the key in one hand and muttered that she wished for a fan in the other.'),
      line('廊[ろう]下[か]|の|向[む]こう|から|足[あし]音[おと]|が|聞[き]こえた|。', 'Footsteps came from the far end of the corridor.'),
      line('白[しろ]ウサギ|が|戻[もど]ってきた|。', 'The White Rabbit had returned.'),
      line('白[しろ]い|手[て]袋[ぶくろ]|と|大[おお]きな|扇[せん]子[す]|を|抱[かか]えていた|。', 'He was carrying white gloves and a large fan.'),
    ],
    [
      line('「|公[こう]爵[しゃく]夫[ふ]人[じん]|を|お待[ま]たせしたら|、|何[なん]と言[い]われることか|」|と|ぶつぶつ言[い]っていた|。', '“What will the Duchess say if I keep her waiting?” he muttered.'),
      line('アリス|の|姿[すがた]|に|気[き]づくと|、|「|メアリー・アン|、|どうして|ここ|に|いる|」|と|命[めい]令[れい]した|。', 'Noticing Alice, he ordered, “Mary Ann, why are you here?”'),
      line('すぐ|に|驚[おどろ]き|、|手[て]袋[ぶくろ]|と|扇[せん]子[す]|を|落[お]として|逃[に]げた|。', 'Then he took fright, dropped the gloves and fan, and ran away.'),
      line('アリス|は|扇[せん]子[す]|を|拾[ひろ]った|。', 'Alice picked up the fan.'),
      line('暑[あつ]い|顔[かお]|を|あおぎ始[はじ]めた|。', 'She began fanning her hot face.'),
      line('「|私[わたし]|は|一[いっ]体[たい]|誰[だれ]なのだろう|。|朝[あさ]|起[お]きた|時[とき]|と|同[おな]じ|アリス|なの|か|」|と|考[かんが]えた|。', '“Who on earth am I? Am I the same Alice who woke this morning?” she wondered.'),
      line('確[たし]かめるため|、|覚[おぼ]えている|はず|の|詩[し]|を|暗[あん]唱[しょう]してみた|。', 'To check, she tried reciting a poem she ought to remember.'),
      line('ところが|、|全[まった]く|違[ちが]う|言[こと]葉[ば]|が|出[で]てきた|。', 'Instead, completely different words came out.'),
    ],
    [
      line('「|夢[ゆめ]|を|見[み]ているのかもしれない|」|と|思[おも]った|。', '“Perhaps I am dreaming,” she thought.'),
      line('扇[せん]子[す]|で|あおぐ|うち|に|、|体[からだ]|は|再[ふたた]び|縮[ちぢ]み始[はじ]めた|。', 'As she fanned herself, her body began shrinking again.'),
      line('危[あぶ]うく|消[き]えてしまう|前[まえ]|に|扇[せん]子[す]|を|投[な]げ捨[す]てた|。', 'Before she disappeared altogether, she threw the fan away.'),
      line('身[しん]長[ちょう]|は|二[に]十[じゅっ]センチ|ほど|で|落[お]ち着[つ]いた|。', 'Her height settled at about twenty centimetres.'),
      line('「|これで|庭[にわ]|へ|入[はい]れる|」|と|ドア|へ|駆[か]け寄[よ]った|。', '“Now I can enter the garden,” she said, rushing to the door.'),
      line('鍵[かぎ]|が|まだ|テーブル|の|上[うえ]|に|ある|こと|を|思[おも]い出[だ]した|。', 'She remembered that the key was still on the table.'),
      line('二[に]度[ど]目[め]|は|自[じ]分[ぶん]|の|愚[おろ]かさ|に|腹[はら]を立[た]てた|。', 'This time, she was angry at her own foolishness.'),
      line('涙[なみだ]|が|止[と]まらなくなった|。', 'Her tears would not stop.'),
    ],
    [
      line('大[おお]粒[つぶ]|の|涙[なみだ]|が|床[ゆか]|へ|落[お]ち|、|足[あし]首[くび]|ほど|の|深[ふか]さ|の|水[みず]たまり|に|広[ひろ]がった|。', 'Huge tears fell to the floor and spread into a pool as deep as her ankles.'),
      line('このまま|泣[な]けば|、|泳[およ]がなければならない|と|困[こま]った|。', 'She realised that if she kept crying, she would have to swim.'),
      line('数[すう]分[ふん]前[まえ]|に|大[おお]きかった|自[じ]分[ぶん]|が|、|涙[なみだ]|の|海[うみ]|を|作[つく]った|の|だった|。', 'Her larger self from a few minutes earlier had created a sea of tears.'),
      line('泣[な]きすぎた|こと|を|後[こう]悔[かい]しても|、|もう|遅[おそ]かった|。', 'Even if she regretted crying too much, it was already too late.'),
    ],
  ],
});

const wizardOfOz = expandStory({
  id: 'oz-no-mahoutsukai',
  title: { ja: 'オズの魔法使い', en: 'The Wonderful Wizard of Oz' },
  series: { id: 'wizard-of-oz', part: 1, of: 1, name: 'The Wonderful Wizard of Oz' },
  level: 'L6',
  gram: 'G6',
  blurb: 'A cyclone carries Dorothy from grey Kansas to Oz, where three unlikely companions join her road to the Emerald City.',
  source: SOL_SOURCE(
    'Public-domain novel by L. Frank Baum (The Wonderful Wizard of Oz, 1900), opening journey',
    'An original Japanese retelling and abridgement of Dorothy’s arrival and first meetings, not a translation of Baum’s prose or a later adaptation.',
    'Public domain (L. Frank Baum d. 1919). This retelling and its English translation are original to Kana Quest.',
  ),
  nw: ['ドロシー', 'カンザス', 'サイクロン', 'マンチキン', 'エメラルド'],
  lexicon: lexicon({
    'カンザス': ['Kansas', 'pn'],
    '果[は]てしない': ['endless, boundless', 'adj'],
    '草[そう]原[げん]': ['prairie, grassland', 'n'],
    'ドロシー': ['Dorothy', 'pn'],
    'エムおばさん': ['Aunt Em', 'pn'],
    'ヘンリーおじさん': ['Uncle Henry', 'pn'],
    '暮[く]らしていた': ['was living', 'v', { df: '暮らす', cf: 'plain past progressive' }],
    '黒[くろ]い': ['black', 'adj'],
    '子[こ]犬[いぬ]': ['little dog, puppy', 'n'],
    'トト': ['Toto', 'pn'],
    '親[しん]友[ゆう]': ['best friend', 'n'],
    '家[いえ]': ['house, home', 'n'],
    '部[へ]屋[や]': ['room', 'n'],
    '一[ひと]つ': ['one', 'num'],
    '小[ちい]さな': ['small', 'adj'],
    '木[もく]造[ぞう]': ['wooden', 'adj'],
    '窓[まど]': ['windows', 'n'],
    '壁[かべ]': ['walls', 'n'],
    '長[なが]年[ねん]': ['many years', 'n'],
    '日[ひ]差[ざ]し': ['sunlight', 'n'],
    '風[かぜ]': ['wind', 'n'],
    '灰[はい]色[いろ]に変[か]わっていた': ['had turned grey', 'v', { df: '灰色に変わる', cf: 'plain past perfect' }],
    '朝[あさ]': ['morning', 'n'],
    '空[そら]': ['sky', 'n'],
    '急[きゅう]に': ['suddenly', 'adv', { df: '急だ', cf: 'adverbial form' }],
    '暗[くら]くなった': ['grew dark', 'v', { df: '暗くなる', cf: 'plain past' }],
    '遠[とお]く': ['in the distance', 'adv'],
    '低[ひく]い': ['low', 'adj'],
    'うなり声[ごえ]': ['roar, moaning sound', 'n'],
    '聞[き]こえてきた': ['came rumbling towards them', 'v', { df: '聞こえる', cf: 'plain past 〜てくる form' }],
    'ヘンリーおじさん': ['Uncle Henry', 'pn'],
    '地[ち]平[へい]線[せん]': ['horizon', 'n'],
    '黒[くろ]い': ['black', 'adj'],
    '柱[はしら]': ['column, funnel', 'n'],
    '見[み]た': ['saw', 'v', { df: '見る', cf: 'plain past' }],
    'サイクロン': ['cyclone', 'n'],
    '叫[さけ]んだ': ['shouted', 'v', { df: '叫ぶ', cf: 'plain past' }],
    '牛[うし]': ['cattle', 'n'],
    '馬[うま]': ['horses', 'n'],
    '守[まも]るため': ['in order to protect', 'v', { df: '守る', cf: 'purpose form' }],
    '納[な]屋[や]': ['barn', 'n'],
    '走[はし]った': ['ran', 'v', { df: '走る', cf: 'plain past' }],
    'エムおばさん': ['Aunt Em', 'pn'],
    '床[ゆか]下[した]': ['underground, beneath the floor', 'n'],
    '避[ひ]難[なん]室[しつ]': ['storm cellar, shelter', 'n'],
    '扉[とびら]': ['door, hatch', 'n'],
    '開[あ]けた': ['opened', 'v', { df: '開ける', cf: 'plain past' }],
    'トト': ['Toto', 'pn'],
    'ベッド': ['bed', 'n'],
    '下[した]': ['underneath', 'n'],
    '逃[に]げ込[こ]んだ': ['darted under', 'v', { df: '逃げ込む', cf: 'plain past' }],
    'ドロシー': ['Dorothy', 'pn'],
    '捕[つか]まえようとした': ['tried to catch', 'v', { df: '捕まえる', cf: 'plain past "try to" form' }],
    '早[はや]く': ['quickly', 'adv'],
    '来[き]なさい': ['come!', 'v', { df: '来る', cf: 'plain imperative' }],
    'エムおばさん': ['Aunt Em', 'pn'],
    '階[かい]段[だん]': ['stairs', 'n'],
    '上[うえ]': ['top', 'n'],
    '呼[よ]んだ': ['called', 'v', { df: '呼ぶ', cf: 'plain past' }],
    '家[いえ]': ['house', 'n'],
    '床[ゆか]': ['floor', 'n'],
    '激[はげ]しく': ['violently', 'adv', { df: '激しい', cf: 'adverbial form' }],
    '揺[ゆ]れた': ['shook', 'v', { df: '揺れる', cf: 'plain past' }],
    '屋[や]根[ね]': ['roof', 'n'],
    '風[かぜ]': ['wind', 'n'],
    '引[ひ]っ張[ぱ]られる': ['being pulled', 'v', { df: '引っ張る', cf: 'plain present passive' }],
    '音[おと]': ['sound', 'n'],
    '直[ちょく]後[ご]': ['immediately after', 'n'],
    '家[いえ]全[ぜん]体[たい]': ['the whole house', 'n'],
    '地[じ]面[めん]': ['ground', 'n'],
    '持[も]ち上[あ]げられた': ['was lifted', 'v', { df: '持ち上げる', cf: 'plain past passive' }],
    'ドロシー': ['Dorothy', 'pn'],
    '転[ころ]んだ': ['fell over', 'v', { df: '転ぶ', cf: 'plain past' }],
    '壁[かべ]': ['wall', 'n'],
    '這[は]って': ['crawling; crawled and', 'v', { df: '這う', cf: 'te-form' }],
    '戻[もど]った': ['returned', 'v', { df: '戻る', cf: 'plain past' }],
    '不[ふ]思[し]議[ぎ]な': ['strange, mysterious', 'adj', { df: '不思議だ', cf: 'na-adjective form' }],
    '浮[う]かぶ': ['floating', 'v', { df: '浮かぶ', cf: 'plain present' }],
    '船[ふね]': ['ship', 'n'],
    '静[しず]かになった': ['became quiet', 'v', { df: '静かになる', cf: 'plain past' }],
    'トト': ['Toto', 'pn'],
    '耳[みみ]': ['ears', 'n'],
    '立[た]てて': ['pricking up; raised and', 'v', { df: '立てる', cf: 'te-form' }],
    '震[ふる]えていた': ['was trembling', 'v', { df: '震える', cf: 'plain past progressive' }],
    '抱[だ]き上[あ]げた': ['picked up and held', 'v', { df: '抱き上げる', cf: 'plain past' }],
    '何[なん]時[じ]間[かん]': ['many hours', 'n'],
    '空[そら]': ['air, sky', 'n'],
    '運[はこ]ばれた': ['was carried', 'v', { df: '運ぶ', cf: 'plain past passive' }],
    '初[はじ]め': ['at first', 'adv'],
    '怖[こわ]がっていた': ['was afraid', 'v', { df: '怖がる', cf: 'plain past progressive' }],
    '揺[ゆ]りかご': ['cradle', 'n'],
    '揺[ゆ]れ': ['rocking, sway', 'n'],
    '慣[な]れた': ['became used to', 'v', { df: '慣れる', cf: 'plain past' }],
    '床[ゆか]': ['floor', 'n'],
    '毛[もう]布[ふ]': ['blanket', 'n'],
    '敷[し]いた': ['spread out', 'v', { df: '敷く', cf: 'plain past' }],
    '眠[ねむ]り込[こ]んだ': ['fell asleep', 'v', { df: '眠り込む', cf: 'plain past' }],
    '大[おお]きな': ['large, loud', 'adj'],
    '衝[しょう]撃[げき]': ['impact', 'n'],
    '目[め]を覚[さ]ました': ['woke up', 'v', { df: '目を覚ます', cf: 'plain past' }],
    '家[いえ]': ['house', 'n'],
    '地[じ]面[めん]': ['ground', 'n'],
    '着[つ]いていた': ['had landed', 'v', { df: '着く', cf: 'plain past perfect' }],
    '窓[まど]': ['window', 'n'],
    '明[あか]るい': ['bright', 'adj'],
    '日[ひ]差[ざ]し': ['sunshine', 'n'],
    '差[さ]し込[こ]んでいた': ['was streaming in', 'v', { df: '差し込む', cf: 'plain past progressive' }],
    'ドア': ['door', 'n'],
    '開[あ]けた': ['opened', 'v', { df: '開ける', cf: 'plain past' }],
    '灰[はい]色[いろ]': ['grey', 'n'],
    '草[そう]原[げん]': ['prairie', 'n'],
    '代[か]わり': ['in place of', 'n'],
    '色[いろ]あざやかな': ['colourful, vivid', 'adj', { df: '色あざやかだ', cf: 'na-adjective form' }],
    '国[くに]': ['land, country', 'n'],
    '広[ひろ]がっていた': ['spread out', 'v', { df: '広がる', cf: 'plain past progressive' }],
    '丸[まる]い': ['round', 'adj'],
    '家[いえ]': ['houses', 'n'],
    '青[あお]い': ['blue', 'adj'],
    '屋[や]根[ね]': ['roofs', 'n'],
    '輝[かがや]く': ['shining', 'v', { df: '輝く', cf: 'plain present (modifying a noun)' }],
    '花[はな]': ['flowers', 'n'],
    '畑[はたけ]': ['fields', 'n'],
    '囲[かこ]まれていた': ['were surrounded', 'v', { df: '囲む', cf: 'plain past passive progressive' }],
    '背[せ]の低[ひく]い': ['short in stature', 'adj'],
    '人[ひと]たち': ['people', 'n'],
    '近[ちか]づいてきた': ['came approaching', 'v', { df: '近づく', cf: 'plain past 〜てくる form' }],
    'マンチキン': ['Munchkins', 'pn'],
    '皆[みな]': ['all, everyone', 'n'],
    '青[あお]い': ['blue', 'adj'],
    '帽[ぼう]子[し]': ['hats', 'n'],
    '服[ふく]': ['clothes', 'n'],
    '身[み]につけていた': ['were wearing', 'v', { df: '身につける', cf: 'plain past progressive' }],
    '一[いっ]緒[しょ]': ['together with them', 'n'],
    '白[しろ]い': ['white', 'adj'],
    'ドレス': ['dress', 'n'],
    '老[ろう]女[じょ]': ['old woman', 'n'],
    'いた': ['was there', 'v', { df: 'いる', cf: 'plain past' }],
    '北[きた]': ['North', 'n'],
    '良[よ]い魔[ま]女[じょ]': ['Good Witch', 'pn'],
    '自[じ]己[こ]紹[しょう]介[かい]した': ['introduced herself', 'v', { df: '自己紹介する', cf: 'plain past' }],
    '東[ひがし]': ['East', 'n'],
    '悪[わる]い魔[ま]女[じょ]': ['Wicked Witch', 'pn'],
    '倒[たお]してくださって': ['for defeating', 'v', { df: '倒す', cf: 'honorific te-form 〜てくださる form' }],
    'ありがとうございます': ['thank you very much', 'int'],
    '深[ふか]く': ['deeply', 'adv'],
    '頭[あたま]を下[さ]げた': ['bowed', 'v', { df: '頭を下げる', cf: 'plain past' }],
    '誰[だれ]も': ['no one', 'pn'],
    '倒[たお]していません': ['have not defeated', 'v', { df: '倒す', cf: 'polite perfect negative' }],
    '慌[あわ]てて': ['hurriedly, flustered', 'adv', { df: '慌てる', cf: 'te-form' }],
    '答[こた]えた': ['answered', 'v', { df: '答える', cf: 'plain past' }],
    '老[ろう]女[じょ]': ['old woman', 'n'],
    '家[いえ]': ['house', 'n'],
    '下[した]': ['beneath', 'n'],
    '指[ゆび]さした': ['pointed', 'v', { df: '指さす', cf: 'plain past' }],
    '赤[あか]い': ['red', 'adj'],
    '靴[くつ]下[した]': ['stockings', 'n'],
    '二[に]本[ほん]': ['two', 'num'],
    '足[あし]': ['feet', 'n'],
    '出[で]ていた': ['were sticking out', 'v', { df: '出る', cf: 'plain past progressive' }],
    '家[いえ]': ['house', 'n'],
    '落[お]ちた': ['fell', 'v', { df: '落ちる', cf: 'plain past' }],
    '偶[ぐう]然[ぜん]': ['by accident', 'adv'],
    '押[お]しつぶした': ['crushed', 'v', { df: '押しつぶす', cf: 'plain past' }],
    '銀[ぎん]色[いろ]': ['silver', 'adj'],
    '靴[くつ]': ['shoes', 'n'],
    '残[のこ]っていた': ['remained', 'v', { df: '残る', cf: 'plain past progressive' }],
    '北[きた]': ['North', 'n'],
    '魔[ま]女[じょ]': ['witch', 'n'],
    'ドロシー': ['Dorothy', 'pn'],
    '渡[わた]した': ['gave, handed', 'v', { df: '渡す', cf: 'plain past' }],
    '東[ひがし]': ['East', 'n'],
    '魔[ま]女[じょ]': ['Witch', 'n'],
    'マンチキン': ['Munchkins', 'pn'],
    '長[なが]い間[あいだ]': ['for a long time', 'n'],
    '働[はたら]かせていた': ['had forced to work', 'v', { df: '働く', cf: 'plain past causative progressive' }],
    'いなくなり': ['being gone; disappeared and', 'v', { df: 'いなくなる', cf: 'continuative form' }],
    '自[じ]由[ゆう]になった': ['became free', 'v', { df: '自由になる', cf: 'plain past' }],
    '靴[くつ]': ['shoes', 'n'],
    '強[つよ]い': ['powerful, strong', 'adj'],
    '魔[ま]法[ほう]': ['magic', 'n'],
    '秘[ひ]められている': ['is hidden within', 'v', { df: '秘める', cf: 'plain present passive progressive' }],
    '使[つか]い方[かた]': ['way to use', 'n'],
    '知[し]らない': ['does not know', 'v', { df: '知る', cf: 'plain negative' }],
    '説[せつ]明[めい]した': ['explained', 'v', { df: '説明する', cf: 'plain past' }],
    'カンザス': ['Kansas', 'pn'],
    '帰[かえ]りたい': ['want to return', 'v', { df: '帰る', cf: 'desiderative form' }],
    '言[い]うと': ['when she said', 'v', { df: '言う', cf: 'conditional 〜と form' }],
    '困[こま]った': ['troubled, perplexed', 'adj', { df: '困る', cf: 'plain past (modifying a noun)' }],
    '顔[かお]': ['face', 'n'],
    '西[にし]': ['West', 'n'],
    '魔[ま]女[じょ]': ['witch', 'n'],
    '東[ひがし]': ['East', 'n'],
    '国[くに]': ['land', 'n'],
    '外[そと]': ['outside, beyond', 'n'],
    '知[し]らない': ['does not know', 'v', { df: '知る', cf: 'plain negative' }],
    '答[こた]えた': ['answered', 'v', { df: '答える', cf: 'plain past' }],
    'エメラルドの都[みやこ]': ['Emerald City', 'pn'],
    '偉[い]大[だい]な': ['great, mighty', 'adj', { df: '偉大だ', cf: 'na-adjective form' }],
    'オズ': ['Oz', 'pn'],
    '魔[ま]法[ほう]使[つか]い': ['wizard', 'n'],
    '住[す]んでいる': ['lives', 'v', { df: '住む', cf: 'plain present progressive' }],
    '彼[かれ]': ['he', 'pn'],
    '助[たす]けられるかもしれない': ['might be able to help', 'v', { df: '助ける', cf: 'potential possibility form' }],
    '教[おし]えた': ['told', 'v', { df: '教える', cf: 'plain past' }],
    '都[みやこ]': ['city, capital', 'n'],
    '黄[き]色[いろ]い': ['yellow', 'adj'],
    'レンガ': ['brick', 'n'],
    '道[みち]': ['road', 'n'],
    'たどれば': ['if you follow', 'v', { df: 'たどる', cf: 'conditional 〜ば form' }],
    '着[つ]く': ['will arrive', 'v', { df: '着く', cf: 'plain present/future' }],
    'ドロシー': ['Dorothy', 'pn'],
    '額[ひたい]': ['forehead', 'n'],
    '口[くち]づけ': ['kiss', 'n'],
    '与[あた]えた': ['gave', 'v', { df: '与える', cf: 'plain past' }],
    '印[しるし]': ['mark, sign', 'n'],
    '悪[わる]い': ['wicked, evil', 'adj'],
    '者[もの]': ['being, person', 'n'],
    '手[て]を出[だ]せない': ['cannot harm or touch', 'v', { df: '手を出す', cf: 'potential negative form' }],
    '光[ひかり]': ['flash of light', 'n'],
    '中[なか]': ['within', 'n'],
    '消[き]えた': ['vanished', 'v', { df: '消える', cf: 'plain past' }],
    'マンチキン': ['Munchkins', 'pn'],
    '歌[うた]': ['songs', 'n'],
    '踊[おど]り': ['dancing', 'n'],
    '祝[いわ]った': ['celebrated', 'v', { df: '祝う', cf: 'plain past' }],
    'ドロシー': ['Dorothy', 'pn'],
    '家[いえ]': ['house', 'n'],
    '残[のこ]っていた': ['remaining', 'adj', { df: '残る', cf: 'plain past (modifying a noun)' }],
    'パン': ['bread', 'n'],
    '食[た]べた': ['ate', 'v', { df: '食べる', cf: 'plain past' }],
    '青[あお]': ['blue', 'n'],
    '白[しろ]': ['white', 'n'],
    'チェック': ['checked pattern', 'n'],
    'ワンピース': ['dress', 'n'],
    '着[き]替[が]えた': ['changed into', 'v', { df: '着替える', cf: 'plain past' }],
    'バスケット': ['basket', 'n'],
    'パン': ['bread', 'n'],
    '水[みず]': ['water', 'n'],
    '入[い]れた': ['put inside', 'v', { df: '入れる', cf: 'plain past' }],
    'トト': ['Toto', 'pn'],
    '一[いっ]緒[しょ]に': ['together', 'adv'],
    '黄[き]色[いろ]い': ['yellow', 'adj'],
    '道[みち]': ['road', 'n'],
    '歩[ある]き始[はじ]めた': ['began walking', 'v', { df: '歩き始める', cf: 'plain past' }],
    '日[ひ]差[ざ]し': ['sunlight', 'n'],
    '金[きん]色[いろ]': ['golden', 'adj'],
    '帯[おび]': ['ribbon, band', 'n'],
    '輝[かがや]いていた': ['was shining', 'v', { df: '輝く', cf: 'plain past progressive' }],
    '両[りょう]側[がわ]': ['both sides', 'n'],
    '畑[はたけ]': ['fields', 'n'],
    '柵[さく]': ['fences', 'n'],
    '続[つづ]いていた': ['continued', 'v', { df: '続く', cf: 'plain past progressive' }],
    '農[のう]夫[ふ]': ['farmers', 'n'],
    '青[あお]い': ['blue', 'adj'],
    '服[ふく]': ['clothes', 'n'],
    'かぶり': ['wearing; wore and', 'v', { df: 'かぶる', cf: 'continuative form' }],
    '感[かん]謝[しゃ]を伝[つた]えた': ['expressed thanks', 'v', { df: '感謝を伝える', cf: 'plain past' }],
    '昼[ひる]過[す]ぎ': ['early afternoon', 'n'],
    '柵[さく]': ['fence', 'n'],
    'そば': ['beside', 'n'],
    '休[やす]んだ': ['rested', 'v', { df: '休む', cf: 'plain past' }],
    'トト': ['Toto', 'pn'],
    '突[とつ]然[ぜん]': ['suddenly', 'adv'],
    '吠[ほ]え始[はじ]めた': ['began barking', 'v', { df: '吠え始める', cf: 'plain past' }],
    'トウモロコシ畑[ばたけ]': ['cornfield', 'n'],
    '中[なか]': ['inside', 'n'],
    '棒[ぼう]': ['pole', 'n'],
    '古[ふる]い': ['old', 'adj'],
    '服[ふく]': ['clothes', 'n'],
    '着[き]せられた': ['had been dressed', 'v', { df: '着せる', cf: 'plain past passive' }],
    'カカシ': ['Scarecrow', 'pn'],
    '立[た]っていた': ['was standing', 'v', { df: '立つ', cf: 'plain past progressive' }],
    '顔[かお]': ['face', 'n'],
    '布[ぬの]': ['cloth', 'n'],
    '目[め]': ['eyes', 'n'],
    '口[くち]': ['mouth', 'n'],
    '描[えが]かれていた': ['had been painted', 'v', { df: '描く', cf: 'plain past passive progressive' }],
    'ドロシー': ['Dorothy', 'pn'],
    '片[かた]目[め]': ['one eye', 'n'],
    'ウインクした': ['winked', 'v', { df: 'ウインクする', cf: 'plain past' }],
    '驚[おどろ]いて': ['being surprised; startled and', 'v', { df: '驚く', cf: 'te-form' }],
    '近[ちか]づいた': ['approached', 'v', { df: '近づく', cf: 'plain past' }],
    '棒[ぼう]': ['pole', 'n'],
    '降[お]ろしてください': ['please take me down', 'v', { df: '降ろす', cf: 'polite request form' }],
    'カカシ': ['Scarecrow', 'pn'],
    '頼[たの]んだ': ['asked, requested', 'v', { df: '頼む', cf: 'plain past' }],
    '結[むす]び目[め]': ['knot', 'n'],
    'ほどいて': ['untying; untied and', 'v', { df: 'ほどく', cf: 'te-form' }],
    '地[じ]面[めん]': ['ground', 'n'],
    '降[お]ろした': ['lowered', 'v', { df: '降ろす', cf: 'plain past' }],
    'カカシ': ['Scarecrow', 'pn'],
    '何[なん]度[ど]': ['many times', 'n'],
    '頭[あたま]を下[さ]げた': ['bowed', 'v', { df: '頭を下げる', cf: 'plain past' }],
    '脳[のう]': ['brain', 'n'],
    '入[はい]っていない': ['does not contain', 'v', { df: '入る', cf: 'plain present negative progressive' }],
    '告[こく]白[はく]した': ['confessed', 'v', { df: '告白する', cf: 'plain past' }],
    'オズ': ['Oz', 'pn'],
    '脳[のう]': ['brain', 'n'],
    '願[ねが]う': ['ask for, wish for', 'v', { df: '願う', cf: 'plain present' }],
    '決[き]め': ['deciding; decided and', 'v', { df: '決める', cf: 'continuative form' }],
    '旅[たび]': ['journey', 'n'],
    '加[くわ]わった': ['joined', 'v', { df: '加わる', cf: 'plain past' }],
    'カカシ': ['Scarecrow', 'pn'],
    '足[あし]': ['feet', 'n'],
    'わら': ['straw', 'n'],
    '詰[つ]まっている': ['are stuffed', 'v', { df: '詰まる', cf: 'plain present progressive' }],
    '何[なん]度[ど]': ['many times', 'n'],
    '転[ころ]んだ': ['fell over', 'v', { df: '転ぶ', cf: 'plain past' }],
    '痛[いた]み': ['pain', 'n'],
    '感[かん]じない': ['does not feel', 'v', { df: '感じる', cf: 'plain negative' }],
    'すぐ': ['immediately', 'adv'],
    '立[た]ち上[あ]がった': ['stood up', 'v', { df: '立ち上がる', cf: 'plain past' }],
    'ドロシー': ['Dorothy', 'pn'],
    'カンザス': ['Kansas', 'pn'],
    '家[いえ]': ['home', 'n'],
    '話[はなし]': ['story, account', 'n'],
    'カカシ': ['Scarecrow', 'pn'],
    '「|家[いえ]|」|という': ['the word “home”', 'n'],
    '気[き]持[も]ち': ['feeling, emotion', 'n'],
    '理[り]解[かい]できなかった': ['could not understand', 'v', { df: '理解する', cf: 'plain potential past negative' }],
    '脳[のう]': ['brain', 'n'],
    'ない': ['does not have', 'adj'],
    '思[おも]った': ['thought', 'v', { df: '思う', cf: 'plain past' }],
    '昼[ひる]': ['noon, lunch', 'n'],
    'ドロシー': ['Dorothy', 'pn'],
    'パン': ['bread', 'n'],
    '分[わ]けた': ['shared', 'v', { df: '分ける', cf: 'plain past' }],
    'カカシ': ['Scarecrow', 'pn'],
    '食[た]べる': ['eat', 'v', { df: '食べる', cf: 'plain present' }],
    '必[ひつ]要[よう]': ['need', 'n'],
    'なかった': ['did not have', 'v', { df: 'ある', cf: 'plain past negative' }],
    '自[じ]分[ぶん]': ['himself', 'pn'],
    '作[つく]った': ['made', 'v', { df: '作る', cf: 'plain past (modifying a noun)' }],
    '農[のう]夫[ふ]': ['farmer', 'n'],
    '最[さい]後[ご]': ['at the end', 'n'],
    '脳[のう]': ['brain', 'n'],
    '入[い]れ忘[わす]れたらしい': ['seems to have forgotten to put in', 'v', { df: '入れ忘れる', cf: 'plain past hearsay form' }],
    '話[はな]した': ['said, told', 'v', { df: '話す', cf: 'plain past' }],
    '考[かんが]え': ['thoughts, ideas', 'n'],
    'わら': ['straw', 'n'],
    '欲[ほ]しい': ['want', 'adj'],
    '言[い]った': ['said', 'v', { df: '言う', cf: 'plain past' }],
    '午[ご]後[ご]': ['afternoon', 'n'],
    '道[みち]': ['road', 'n'],
    '暗[くら]い': ['dark', 'adj'],
    '森[もり]': ['forest', 'n'],
    '入[はい]った': ['entered', 'v', { df: '入る', cf: 'plain past' }],
    '木[き]': ['trees', 'n'],
    '間[あいだ]': ['between', 'n'],
    '助[たす]けて': ['help me', 'v', { df: '助ける', cf: 'te-form request' }],
    '弱[よわ]い': ['faint', 'adj'],
    '声[こえ]': ['voice', 'n'],
    '聞[き]こえた': ['could be heard', 'v', { df: '聞こえる', cf: 'plain past' }],
    '道[みち]端[ばた]': ['roadside', 'n'],
    '小[ちい]さな': ['small', 'adj'],
    '小[こ]屋[や]': ['cottage, hut', 'n'],
    'あった': ['there was', 'v', { df: 'ある', cf: 'plain past' }],
    'テーブル': ['table', 'n'],
    '上[うえ]': ['on top', 'n'],
    'オイル缶[かん]': ['oilcan', 'n'],
    '置[お]かれていた': ['had been placed', 'v', { df: '置く', cf: 'plain past passive progressive' }],
    '近[ちか]く': ['nearby', 'adv'],
    'ブリキ': ['tin', 'n'],
    '木[き]こり': ['woodcutter', 'n'],
    '斧[おの]': ['axe', 'n'],
    '持[も]ったまま': ['still holding', 'v', { df: '持つ', cf: 'plain past 〜たまま form' }],
    '立[た]ち尽[つ]くしていた': ['was standing frozen in place', 'v', { df: '立ち尽くす', cf: 'plain past progressive' }],
    '一[いち]年[ねん]近[ちか]く': ['for nearly a year', 'n'],
    '雨[あめ]': ['rain', 'n'],
    '関[かん]節[せつ]': ['joints', 'n'],
    'さびついて': ['rusting; rusted and', 'v', { df: 'さびつく', cf: 'te-form' }],
    '動[うご]けなくなっていた': ['had become unable to move', 'v', { df: '動く', cf: 'plain potential negative 〜なる form' }],
    'ドロシー': ['Dorothy', 'pn'],
    'オイル': ['oil', 'n'],
    '差[さ]してください': ['please apply', 'v', { df: '差す', cf: 'polite request form' }],
    'ブリキの木[き]こり': ['Tin Woodman', 'pn'],
    '頼[たの]んだ': ['asked, pleaded', 'v', { df: '頼む', cf: 'plain past' }],
    '首[くび]': ['neck', 'n'],
    '腕[うで]': ['arms', 'n'],
    '脚[あし]': ['legs', 'n'],
    '順[じゅん]番[ばん]に': ['in order', 'adv'],
    '油[あぶら]を差[さ]した': ['oiled', 'v', { df: '油を差す', cf: 'plain past' }],
    'ブリキの木[き]こり': ['Tin Woodman', 'pn'],
    '少[すこ]しずつ': ['little by little', 'adv'],
    '動[うご]けるようになった': ['became able to move', 'v', { df: '動く', cf: 'plain potential 〜ようになる form' }],
    '斧[おの]': ['axe', 'n'],
    '下[お]ろし': ['lowering; lowered and', 'v', { df: '下ろす', cf: 'continuative form' }],
    '深[ふか]い': ['deep', 'adj'],
    '息[いき]': ['breath, sigh', 'n'],
    '元[もと]': ['originally, former', 'n'],
    '人[にん]間[げん]': ['human', 'n'],
    '木[き]こり': ['woodcutter', 'n'],
    '話[はな]し始[はじ]めた': ['began to tell', 'v', { df: '話し始める', cf: 'plain past' }],
    '悪[わる]い': ['wicked', 'adj'],
    '魔[ま]女[じょ]': ['witch', 'n'],
    '魔[ま]法[ほう]': ['magic', 'n'],
    '斧[おの]': ['axe', 'n'],
    '滑[すべ]らされ': ['was made to slip', 'v', { df: '滑る', cf: 'continuative causative-passive' }],
    '手[て]足[あし]': ['limbs', 'n'],
    '失[うしな]った': ['lost', 'v', { df: '失う', cf: 'plain past' }],
    '鍛[か]冶[じ]屋[や]': ['tinsmith', 'n'],
    '新[あたら]しい': ['new', 'adj'],
    'ブリキ': ['tin', 'n'],
    '体[からだ]': ['body', 'n'],
    '作[つく]ってくれた': ['made for him', 'v', { df: '作る', cf: 'plain past 〜てくれる form' }],
    '心[しん]臓[ぞう]': ['heart', 'n'],
    '入[い]れる': ['put in', 'v', { df: '入れる', cf: 'plain present' }],
    '忘[わす]れられた': ['was forgotten', 'v', { df: '忘れる', cf: 'plain past passive' }],
    '悲[かな]しそうに': ['sadly; looking sad', 'adv', { df: '悲しそうだ', cf: 'adverbial form' }],
    'オズ': ['Oz', 'pn'],
    '心[しん]臓[ぞう]': ['heart', 'n'],
    '頼[たの]みたい': ['want to ask for', 'v', { df: '頼む', cf: 'desiderative form' }],
    '旅[たび]': ['journey', 'n'],
    '加[くわ]わった': ['joined', 'v', { df: '加わる', cf: 'plain past' }],
    '三[さん]人[にん]': ['three people', 'num'],
    '一[いっ]匹[ぴき]': ['one animal', 'num'],
    '奥[おく]': ['deeper inside', 'n'],
    '進[すす]んだ': ['advanced, went', 'v', { df: '進む', cf: 'plain past' }],
    '木[こ]陰[かげ]': ['shade under the trees', 'n'],
    '暗[くら]くなり': ['growing dark; darkened and', 'v', { df: '暗くなる', cf: 'continuative form' }],
    '黄[き]色[いろ]い': ['yellow', 'adj'],
    'レンガ': ['bricks', 'n'],
    '見[み]えにくくなった': ['became difficult to see', 'v', { df: '見える', cf: 'plain potential 〜にくくなる form' }],
    '突[とつ]然[ぜん]': ['suddenly', 'adv'],
    '大[おお]きな': ['loud, large', 'adj'],
    'ほえ声[ごえ]': ['roar', 'n'],
    '響[ひび]いた': ['echoed', 'v', { df: '響く', cf: 'plain past' }],
    '森[もり]': ['forest', 'n'],
    '王[おう]様[さま]': ['king', 'n'],
    '呼[よ]ばれる': ['called, known as', 'v', { df: '呼ぶ', cf: 'plain present passive' }],
    '大[おお]きな': ['large', 'adj'],
    'ライオン': ['Lion', 'pn'],
    '飛[と]び出[だ]した': ['leapt out', 'v', { df: '飛び出す', cf: 'plain past' }],
    'トト': ['Toto', 'pn'],
    '向[む]かって': ['towards', 'v', { df: '向かう', cf: 'te-form' }],
    '前[まえ]足[あし]': ['front paw', 'n'],
    '振[ふ]り上[あ]げた': ['raised', 'v', { df: '振り上げる', cf: 'plain past' }],
    'ドロシー': ['Dorothy', 'pn'],
    '考[かんが]える': ['thinking', 'v', { df: '考える', cf: 'plain present' }],
    '暇[ひま]': ['time, leisure', 'n'],
    '鼻[はな]': ['nose', 'n'],
    '平[ひら]手[て]で打[う]った': ['slapped with an open hand', 'v', { df: '平手で打つ', cf: 'plain past' }],
    '小[ちい]さな': ['small', 'adj'],
    '犬[いぬ]': ['dog', 'n'],
    'いじめる': ['bully, attack', 'v', { df: 'いじめる', cf: 'plain present' }],
    'なんて': ['such a thing as', 'part'],
    '臆[おく]病[びょう]者[もの]だ': ['are a coward', 'adj'],
    '叱[しか]った': ['scolded', 'v', { df: '叱る', cf: 'plain past' }],
    'ライオン': ['Lion', 'pn'],
    'うなだれ': ['hanging his head; bowed and', 'v', { df: 'うなだれる', cf: 'continuative form' }],
    '実[じつ]は': ['in truth', 'adv'],
    '認[みと]めた': ['admitted', 'v', { df: '認める', cf: 'plain past' }],
    '他[ほか]': ['other', 'adj'],
    '動[どう]物[ぶつ]': ['animals', 'n'],
    '逃[に]げる': ['flee', 'v', { df: '逃げる', cf: 'plain present' }],
    '勇[ゆう]気[き]': ['courage', 'n'],
    'ない': ['does not have', 'adj'],
    'オズ': ['Oz', 'pn'],
    '勇[ゆう]気[き]': ['courage', 'n'],
    'もらえるなら': ['if he can receive', 'v', { df: 'もらう', cf: 'potential conditional 〜なら form' }],
    '行[い]きたい': ['want to go', 'v', { df: '行く', cf: 'desiderative form' }],
    '申[もう]し出[で]た': ['offered, proposed', 'v', { df: '申し出る', cf: 'plain past' }],
    '一[いっ]行[こう]': ['party, group of travellers', 'n'],
    '四[よ]人[にん]': ['four people; group of four', 'num'],
    '一[いっ]匹[ぴき]': ['one animal', 'num'],
    'なった': ['became', 'v', { df: 'なる', cf: 'plain past' }],
    'カカシ': ['Scarecrow', 'pn'],
    '正[ただ]しい': ['correct', 'adj'],
    '道[みち]': ['road', 'n'],
    '見[み]分[わ]け': ['distinguishing; picked out', 'v', { df: '見分ける', cf: 'continuative form' }],
    'ブリキの木[き]こり': ['Tin Woodman', 'pn'],
    '斧[おの]': ['axe', 'n'],
    '枝[えだ]': ['branches', 'n'],
    '払[はら]った': ['cleared away', 'v', { df: '払う', cf: 'plain past' }],
    'ライオン': ['Lion', 'pn'],
    '後[うし]ろ': ['rear, behind', 'n'],
    '歩[ある]き': ['walking; walked and', 'v', { df: '歩く', cf: 'continuative form' }],
    '皆[みな]': ['everyone', 'n'],
    '守[まも]った': ['protected', 'v', { df: '守る', cf: 'plain past' }],
    'ドロシー': ['Dorothy', 'pn'],
    'トト': ['Toto', 'pn'],
    '真[ま]ん中[なか]': ['middle', 'n'],
    '歩[ある]いた': ['walked', 'v', { df: '歩く', cf: 'plain past' }],
    'エメラルドの都[みやこ]': ['Emerald City', 'pn'],
    'まだ': ['still', 'adv'],
    '遠[とお]かった': ['was far away', 'adj', { df: '遠い', cf: 'plain past' }],
    '黄[き]色[いろ]い': ['yellow', 'adj'],
    'レンガ': ['bricks', 'n'],
    '一[ひと]つずつ': ['one at a time', 'adv'],
    '踏[ふ]みしめた': ['stepped firmly upon', 'v', { df: '踏みしめる', cf: 'plain past' }],
    '家[いえ]': ['home', 'n'],
    '帰[かえ]る': ['return', 'v', { df: '帰る', cf: 'plain present' }],
    '脳[のう]': ['brain', 'n'],
    '心[しん]臓[ぞう]': ['heart', 'n'],
    '勇[ゆう]気[き]': ['courage', 'n'],
    '願[ねが]い': ['wishes', 'n'],
    '同[おな]じ': ['same', 'adj'],
    '道[みち]': ['road', 'n'],
    '結[むす]びつけていた': ['bound together', 'v', { df: '結びつける', cf: 'plain past progressive' }],
    'が#but': ['but, although', 'part'],
    'ある': ['a certain; existing', 'adj'],
    'できる': ['can do; possible', 'v'],
    '日[ひ]': ['day', 'n'],
    'し': ['doing; and', 'v', { df: 'する', cf: 'continuative form' }],
    '帽[ぼう]子[し]': ['hat', 'n'],
    '先[さき]': ['ahead, destination', 'n'],
    '後[あと]': ['after, behind', 'n'],
    '一[いち]番[ばん]': ['best, number one, most', 'adv'],
    'した': ['did; gave off', 'v', { df: 'する', cf: 'plain past' }],
    '抱[だ]いたまま': ['while still holding', 'v', { df: '抱く', cf: 'plain past + まま (remaining as)' }],
    'はいた': ['wore, put on (feet or legs)', 'v', { df: 'はく', cf: 'plain past' }],
    '消[き]え': ['vanished, disappeared', 'v', { df: '消える', cf: 'continuative (~, and) form' }],
    'あれば': ['if there is', 'v', { df: 'ある', cf: 'conditional (~ば) form' }],
    '出[で]会[あ]った': ['met, encountered', 'v', { df: '出会う', cf: 'plain past' }],
    '見[み]ていると': ['as (she) was watching', 'v', { df: '見る', cf: 'plain present progressive + と (as, when)' }],
    'ついた': ['drew (a breath), heaved (a sigh)', 'v', { df: '息をつく', cf: 'plain past' }],
    'なければ': ['if there is not, without', 'aux', { df: 'ない', cf: 'conditional negative (~なければ) form' }],
    '愛[あい]': ['love', 'n'],
    'する': ['to do', 'v'],
    'できない': ['cannot, is not possible', 'v', { df: 'できる', cf: 'plain negative' }],
    '通[とお]りだ': ['is true, is as said', 'exp', { df: '通り', cf: '～だ (is)' }],
    'こうして': ['thus, in this way', 'adv'],
    '四[よっ]つ': ['four (things)', 'num'],
    '前[まえ]': ['front, before', 'n'],
    '誰[だれ]も': ['no one', 'pn'],
    '誰[だれ]': ['who; anyone (with a negative: no one)', 'pn'],
    '頭[あたま]': ['head', 'n'],
    '自[じ]由[ゆう]': ['freedom', 'n'],
    'なく': ['without, and not', 'v', { df: 'ない', cf: 'continuative negative (~なく) form' }],
    'になった': ['became', 'v', { df: 'になる', cf: 'plain past' }],
  }),
  body: [
    [
      line('カンザス|の|果[は]てしない|草[そう]原[げん]|で|、|ドロシー|は|エムおばさん|と|ヘンリーおじさん|と|暮[く]らしていた|。', 'On the endless Kansas prairie, Dorothy lived with Aunt Em and Uncle Henry.'),
      line('黒[くろ]い|子[こ]犬[いぬ]|の|トト|が|一[いち]番[ばん]|の|親[しん]友[ゆう]|だった|。', 'A little black dog named Toto was her best friend.'),
      line('家[いえ]|は|部[へ]屋[や]|が|一[ひと]つ|だけ|の|小[ちい]さな|木[もく]造[ぞう]|だった|。', 'Their home was a small wooden house with just one room.'),
      line('窓[まど]|も|壁[かべ]|も|長[なが]年[ねん]|の|日[ひ]差[ざ]し|と|風[かぜ]|で|灰[はい]色[いろ]に変[か]わっていた|。', 'Years of sun and wind had turned its windows and walls grey.'),
      line('ある|朝[あさ]|、|空[そら]|が|急[きゅう]に|暗[くら]くなった|。', 'One morning, the sky suddenly darkened.'),
      line('遠[とお]く|から|低[ひく]い|うなり声[ごえ]|が|聞[き]こえてきた|。', 'A low roar came from the distance.'),
      line('ヘンリーおじさん|は|地[ち]平[へい]線[せん]|の|黒[くろ]い|柱[はしら]|を|見[み]た|。', 'Uncle Henry saw a black column on the horizon.'),
      line('「|サイクロン|だ|」|と|叫[さけ]んだ|。', '“A cyclone!” he shouted.'),
    ],
    [
      line('ヘンリーおじさん|は|牛[うし]|と|馬[うま]|を|守[まも]るため|、|納[な]屋[や]|へ|走[はし]った|。', 'Uncle Henry ran to the barn to protect the cattle and horses.'),
      line('エムおばさん|は|床[ゆか]下[した]|の|避[ひ]難[なん]室[しつ]|の|扉[とびら]|を|開[あ]けた|。', 'Aunt Em opened the storm cellar beneath the floor.'),
      line('その|時[とき]|、|トト|が|ベッド|の|下[した]|へ|逃[に]げ込[こ]んだ|。', 'At that moment, Toto darted under the bed.'),
      line('ドロシー|は|トト|を|捕[つか]まえようとした|。', 'Dorothy tried to catch Toto.'),
      line('「|早[はや]く|来[き]なさい|」|と|エムおばさん|が|階[かい]段[だん]|の|上[うえ]|から|呼[よ]んだ|。', '“Come quickly!” Aunt Em called from the top of the stairs.'),
      line('家[いえ]|の|床[ゆか]|が|激[はげ]しく|揺[ゆ]れた|。', 'The floor of the house shook violently.'),
      line('屋[や]根[ね]|が|風[かぜ]|に|引[ひ]っ張[ぱ]られる|音[おと]|が|した|。', 'The roof sounded as though the wind were pulling at it.'),
      line('直[ちょく]後[ご]|、|家[いえ]全[ぜん]体[たい]|が|地[じ]面[めん]|から|持[も]ち上[あ]げられた|。', 'A moment later, the whole house was lifted from the ground.'),
    ],
    [
      line('ドロシー|は|転[ころ]んだ|が#but|、|壁[かべ]|まで|這[は]って|ベッド|へ|戻[もど]った|。', 'Dorothy fell, but crawled to the wall and returned to the bed.'),
      line('家[いえ]|は|不[ふ]思[し]議[ぎ]な|浮[う]かぶ|船[ふね]|のように|静[しず]かになった|。', 'The house became quiet, like a strange floating ship.'),
      line('トト|は|耳[みみ]|を|立[た]てて|震[ふる]えていた|。', 'Toto trembled with his ears pricked.'),
      line('ドロシー|は|トト|を|抱[だ]き上[あ]げた|。', 'Dorothy picked Toto up.'),
      line('家[いえ]|は|何[なん]時[じ]間[かん]|も|空[そら]|を|運[はこ]ばれた|。', 'The house was carried through the air for many hours.'),
      line('初[はじ]め|は|怖[こわ]がっていた|ドロシー|も|、|揺[ゆ]りかご|のような|揺[ゆ]れ|に|慣[な]れた|。', 'At first Dorothy was frightened, but she grew used to the cradle-like motion.'),
      line('床[ゆか]|に|毛[もう]布[ふ]|を|敷[し]いた|。', 'She spread a blanket on the floor.'),
      line('トト|を|抱[だ]いたまま|眠[ねむ]り込[こ]んだ|。', 'Holding Toto, she fell asleep.'),
    ],
    [
      line('大[おお]きな|衝[しょう]撃[げき]|で|目[め]を覚[さ]ました|。', 'A great impact woke her.'),
      line('家[いえ]|は|地[じ]面[めん]|に|着[つ]いていた|。', 'The house had landed on the ground.'),
      line('窓[まど]|から|明[あか]るい|日[ひ]差[ざ]し|が|差[さ]し込[こ]んでいた|。', 'Bright sunlight streamed through the window.'),
      line('ドア|を|開[あ]けた|ドロシー|の|前[まえ]|に|、|灰[はい]色[いろ]|の|草[そう]原[げん]|の|代[か]わり|に|色[いろ]あざやかな|国[くに]|が|広[ひろ]がっていた|。', 'When Dorothy opened the door, a colourful land spread before her instead of the grey prairie.'),
      line('丸[まる]い|家[いえ]|は|青[あお]い|屋[や]根[ね]|と|輝[かがや]く|花[はな]|の|畑[はたけ]|に|囲[かこ]まれていた|。', 'Round houses were surrounded by blue roofs and fields of shining flowers.'),
      line('背[せ]の低[ひく]い|人[ひと]たち|が|近[ちか]づいてきた|。', 'Short people came approaching.'),
      line('マンチキン|と|呼[よ]ばれる|人[ひと]たち|で|、|皆[みな]|青[あお]い|帽[ぼう]子[し]|と|服[ふく]|を|身[み]につけていた|。', 'They were called Munchkins, and all wore blue hats and clothes.'),
      line('一[いっ]緒[しょ]|に|白[しろ]い|ドレス|の|老[ろう]女[じょ]|が|いた|。', 'An old woman in a white dress was with them.'),
    ],
    [
      line('老[ろう]女[じょ]|は|北[きた]|の|良[よ]い魔[ま]女[じょ]|だ|と|自[じ]己[こ]紹[しょう]介[かい]した|。', 'The old woman introduced herself as the Good Witch of the North.'),
      line('「|東[ひがし]|の|悪[わる]い魔[ま]女[じょ]|を|倒[たお]してくださって|、|ありがとうございます|」|と|深[ふか]く|頭[あたま]を下[さ]げた|。', '“Thank you for defeating the Wicked Witch of the East,” she said with a deep bow.'),
      line('「|私[わたし]|は|誰[だれ]も|倒[たお]していません|」|と|ドロシー|は|慌[あわ]てて|答[こた]えた|。', '“I have not defeated anyone,” Dorothy replied hurriedly.'),
      line('老[ろう]女[じょ]|は|家[いえ]|の|下[した]|を|指[ゆび]さした|。', 'The old woman pointed beneath the house.'),
      line('赤[あか]い|靴[くつ]下[した]|を|はいた|二[に]本[ほん]|の|足[あし]|が|出[で]ていた|。', 'Two feet in red stockings stuck out.'),
      line('家[いえ]|が|落[お]ちた|時[とき]|、|偶[ぐう]然[ぜん]|に|魔[ま]女[じょ]|を|押[お]しつぶした|の|だった|。', 'When the house fell, it had accidentally crushed the witch.'),
      line('やがて|足[あし]|は|消[き]え|、|銀[ぎん]色[いろ]|の|靴[くつ]|だけ|が|残[のこ]っていた|。', 'Soon the feet vanished, leaving only silver shoes.'),
      line('北[きた]|の|魔[ま]女[じょ]|は|その|靴[くつ]|を|ドロシー|に|渡[わた]した|。', 'The Witch of the North gave the shoes to Dorothy.'),
    ],
    [
      line('東[ひがし]|の|魔[ま]女[じょ]|は|マンチキン|を|長[なが]い間[あいだ]|働[はたら]かせていた|。', 'The Witch of the East had forced the Munchkins to work for a long time.'),
      line('魔[ま]女[じょ]|が|いなくなり|、|皆[みな]|は|自[じ]由[ゆう]になった|。', 'With the witch gone, everyone was free.'),
      line('「|靴[くつ]|に|は|強[つよ]い|魔[ま]法[ほう]|が|秘[ひ]められている|が#but|、|使[つか]い方[かた]|は|誰[だれ]|も|知[し]らない|」|と|老[ろう]女[じょ]|は|説[せつ]明[めい]した|。', '“Powerful magic lies in the shoes, but no one knows how to use it,” the old woman explained.'),
      line('ドロシー|が|カンザス|へ|帰[かえ]りたい|と|言[い]うと|、|老[ろう]女[じょ]|は|困[こま]った|顔[かお]|を|した|。', 'When Dorothy said she wanted to return to Kansas, the old woman looked troubled.'),
      line('北[きた]|の|魔[ま]女[じょ]|も|西[にし]|の|魔[ま]女[じょ]|も|、|東[ひがし]|の|国[くに]|の|外[そと]|は|よく|知[し]らない|と|答[こた]えた|。', 'She said that neither the Witch of the North nor the Witch of the West knew much beyond the eastern land.'),
      line('「|エメラルドの都[みやこ]|に|偉[い]大[だい]な|オズ|という|魔[ま]法[ほう]使[つか]い|が|住[す]んでいる|」|と|教[おし]えた|。', '“A great wizard called Oz lives in the Emerald City,” she told her.'),
      line('「|彼[かれ]|なら|助[たす]けられるかもしれない|」|。', '“He may be able to help you.”'),
      line('都[みやこ]|へ|は|黄[き]色[いろ]い|レンガ|の|道[みち]|を|たどれば|着[つ]く|。', 'The yellow brick road would lead to the city.'),
    ],
    [
      line('北[きた]|の|魔[ま]女[じょ]|は|ドロシー|の|額[ひたい]|に|口[くち]づけ|を|与[あた]えた|。', 'The Witch of the North kissed Dorothy’s forehead.'),
      line('「|この|印[しるし]|が|あれば|、|悪[わる]い|者[もの]|も|あなた|に|手[て]を出[だ]せない|」|と|言[い]った|。', '“With this mark, wicked beings cannot harm you,” she said.'),
      line('そして|光[ひかり]|の|中[なか]|へ|消[き]えた|。', 'Then she vanished in a flash of light.'),
      line('マンチキン|たち|は|歌[うた]|と|踊[おど]り|で|自[じ]由[ゆう]|を|祝[いわ]った|。', 'The Munchkins celebrated their freedom with songs and dancing.'),
      line('ドロシー|は|家[いえ]|に|残[のこ]っていた|パン|を|食[た]べた|。', 'Dorothy ate some bread left in the house.'),
      line('青[あお]|と|白[しろ]|の|チェック|の|ワンピース|に|着[き]替[が]えた|。', 'She changed into a blue-and-white checked dress.'),
      line('バスケット|に|パン|と|水[みず]|を|入[い]れた|。', 'She put bread and water into a basket.'),
      line('トト|と|一[いっ]緒[しょ]に|黄[き]色[いろ]い|道[みち]|を|歩[ある]き始[はじ]めた|。', 'With Toto, she began walking along the yellow road.'),
    ],
    [
      line('道[みち]|は|日[ひ]差[ざ]し|の|中[なか]|で|金[きん]色[いろ]|の|帯[おび]|のように|輝[かがや]いていた|。', 'The road shone like a golden ribbon in the sunlight.'),
      line('両[りょう]側[がわ]|に|は|畑[はたけ]|と|青[あお]い|柵[さく]|が|続[つづ]いていた|。', 'Fields and blue fences continued on either side.'),
      line('出[で]会[あ]った|農[のう]夫[ふ]|は|皆[みな]|青[あお]い|服[ふく]|と|帽[ぼう]子[し]|を|かぶり|、|ドロシー|に|感[かん]謝[しゃ]を伝[つた]えた|。', 'Every farmer she met wore blue clothes and a hat and thanked Dorothy.'),
      line('昼[ひる]過[す]ぎ|、|ドロシー|は|柵[さく]|の|そば|で|休[やす]んだ|。', 'In the early afternoon, Dorothy rested beside a fence.'),
      line('トト|が|突[とつ]然[ぜん]|吠[ほ]え始[はじ]めた|。', 'Toto suddenly began barking.'),
      line('トウモロコシ畑[ばたけ]|の|中[なか]|で|、|棒[ぼう]|に|古[ふる]い|服[ふく]|を|着[き]せられた|カカシ|が|立[た]っていた|。', 'In the cornfield stood a Scarecrow in old clothes, fastened to a pole.'),
      line('顔[かお]|は|布[ぬの]|で|、|目[め]|と|口[くち]|が|描[えが]かれていた|。', 'His face was cloth, with eyes and a mouth painted upon it.'),
      line('ドロシー|が|見[み]ていると|、|カカシ|は|片[かた]目[め]|で|ウインクした|。', 'As Dorothy watched, the Scarecrow winked one eye.'),
    ],
    [
      line('ドロシー|は|驚[おどろ]いて|近[ちか]づいた|。', 'Dorothy approached in surprise.'),
      line('「|棒[ぼう]|から|降[お]ろしてください|」|と|カカシ|は|頼[たの]んだ|。', '“Please take me down from this pole,” the Scarecrow asked.'),
      line('ドロシー|は|結[むす]び目[め]|を|ほどいて|、|カカシ|を|地[じ]面[めん]|へ|降[お]ろした|。', 'Dorothy untied the knot and lowered the Scarecrow to the ground.'),
      line('カカシ|は|何[なん]度[ど]|も|頭[あたま]を下[さ]げた|。', 'The Scarecrow bowed again and again.'),
      line('頭[あたま]|に|脳[のう]|が|入[はい]っていない|と|告[こく]白[はく]した|。', 'He confessed that there was no brain in his head.'),
      line('オズ|に|脳[のう]|を|願[ねが]う|と|決[き]め|、|ドロシー|の|旅[たび]|に|加[くわ]わった|。', 'He decided to ask Oz for a brain and joined Dorothy’s journey.'),
      line('カカシ|は|足[あし]|に|わら|が|詰[つ]まっている|ので|何[なん]度[ど]|も|転[ころ]んだ|。', 'Because his feet were stuffed with straw, the Scarecrow often fell.'),
      line('それでも|痛[いた]み|を|感[かん]じない|ので|、|すぐ|立[た]ち上[あ]がった|。', 'But because he felt no pain, he immediately stood again.'),
    ],
    [
      line('ドロシー|は|カンザス|の|家[いえ]|の|話[はなし]|を|した|。', 'Dorothy told him about her home in Kansas.'),
      line('カカシ|は|「|家[いえ]|」|という|気[き]持[も]ち|を|理[り]解[かい]できなかった|。', 'The Scarecrow could not understand the feeling of “home.”'),
      line('脳[のう]|が|ない|から|だ|と|思[おも]った|。', 'He thought it was because he had no brain.'),
      line('昼[ひる]|に|ドロシー|は|パン|を|トト|と|分[わ]けた|。', 'At lunch, Dorothy shared bread with Toto.'),
      line('カカシ|は|食[た]べる|必[ひつ]要[よう]|が|なかった|。', 'The Scarecrow had no need to eat.'),
      line('自[じ]分[ぶん]|を|作[つく]った|農[のう]夫[ふ]|が|最[さい]後[ご]|に|脳[のう]|を|入[い]れ忘[わす]れたらしい|と|話[はな]した|。', 'He said that the farmer who made him seemed to have forgotten to put in a brain.'),
      line('「|わら|より|考[かんが]え|が|欲[ほ]しい|」|と|言[い]った|。', '“I want thoughts more than straw,” he said.'),
      line('午[ご]後[ご]|、|黄[き]色[いろ]い|道[みち]|は|暗[くら]い|森[もり]|へ|入[はい]った|。', 'In the afternoon, the yellow road entered a dark forest.'),
    ],
    [
      line('木[き]|の|間[あいだ]|から|「|助[たす]けて|」|という|弱[よわ]い|声[こえ]|が|聞[き]こえた|。', 'A faint voice saying “Help” came from between the trees.'),
      line('道[みち]端[ばた]|に|小[ちい]さな|小[こ]屋[や]|が|あった|。', 'A small cottage stood beside the road.'),
      line('テーブル|の|上[うえ]|に|オイル缶[かん]|が|置[お]かれていた|。', 'An oilcan sat on the table.'),
      line('近[ちか]く|に|ブリキ|の|木[き]こり|が|斧[おの]|を|持[も]ったまま|立[た]ち尽[つ]くしていた|。', 'Nearby, a Tin Woodman stood frozen while holding an axe.'),
      line('一[いち]年[ねん]近[ちか]く|、|雨[あめ]|で|関[かん]節[せつ]|が|さびついて|動[うご]けなくなっていた|。', 'Rain had rusted his joints, leaving him unable to move for nearly a year.'),
      line('「|オイル|を|差[さ]してください|」|と|ブリキの木[き]こり|が|頼[たの]んだ|。', '“Please apply some oil,” the Tin Woodman asked.'),
      line('ドロシー|は|首[くび]|、|腕[うで]|、|脚[あし]|の|順[じゅん]番[ばん]に|油[あぶら]を差[さ]した|。', 'Dorothy oiled his neck, arms and legs in order.'),
      line('ブリキの木[き]こり|は|少[すこ]しずつ|動[うご]けるようになった|。', 'Little by little, the Tin Woodman could move again.'),
    ],
    [
      line('斧[おの]|を|下[お]ろし|、|深[ふか]い|息[いき]|を|ついた|。', 'He lowered his axe and drew a deep breath.'),
      line('元[もと]|は|人[にん]間[げん]|の|木[き]こり|だった|と|話[はな]し始[はじ]めた|。', 'He began to explain that he had once been a human woodcutter.'),
      line('悪[わる]い|魔[ま]女[じょ]|の|魔[ま]法[ほう]|で|斧[おの]|を|滑[すべ]らされ|、|手[て]足[あし]|を|失[うしな]った|。', 'A wicked witch’s magic made his axe slip, and he lost his limbs.'),
      line('鍛[か]冶[じ]屋[や]|が|新[あたら]しい|ブリキ|の|体[からだ]|を|作[つく]ってくれた|。', 'A tinsmith made him a new body of tin.'),
      line('しかし|、|心[しん]臓[ぞう]|を|入[い]れる|こと|は|忘[わす]れられた|。', 'But everyone forgot to put in a heart.'),
      line('「|心[しん]臓[ぞう]|が|なければ|、|愛[あい]|する|こと|も|できない|」|と|悲[かな]しそうに|言[い]った|。', '“Without a heart, I cannot love,” he said sadly.'),
      line('オズ|に|心[しん]臓[ぞう]|を|頼[たの]みたい|と|、|彼[かれ]|も|旅[たび]|に|加[くわ]わった|。', 'He too joined the journey, hoping to ask Oz for a heart.'),
      line('三[さん]人[にん]|と|一[いっ]匹[ぴき]|は|森[もり]|の|奥[おく]|へ|進[すす]んだ|。', 'The three travellers and one dog went deeper into the forest.'),
    ],
    [
      line('木[こ]陰[かげ]|が|暗[くら]くなり|、|黄[き]色[いろ]い|レンガ|も|見[み]えにくくなった|。', 'The shade deepened, and even the yellow bricks became difficult to see.'),
      line('突[とつ]然[ぜん]|、|大[おお]きな|ほえ声[ごえ]|が|響[ひび]いた|。', 'Suddenly, a mighty roar echoed.'),
      line('森[もり]|の|王[おう]様[さま]|と|呼[よ]ばれる|大[おお]きな|ライオン|が|飛[と]び出[だ]した|。', 'A great Lion, called the king of the forest, leapt out.'),
      line('トト|に|向[む]かって|前[まえ]足[あし]|を|振[ふ]り上[あ]げた|。', 'He raised a front paw towards Toto.'),
      line('ドロシー|は|考[かんが]える|暇[ひま]|も|なく|、|ライオン|の|鼻[はな]|を|平[ひら]手[て]で打[う]った|。', 'Without time to think, Dorothy slapped the Lion’s nose.'),
      line('「|小[ちい]さな|犬[いぬ]|を|いじめる|なんて|、|臆[おく]病[びょう]者[もの]だ|」|と|叱[しか]った|。', '“Only a coward would bully a little dog,” she scolded.'),
      line('ライオン|は|うなだれ|、|「|実[じつ]は|その|通[とお]りだ|」|と|認[みと]めた|。', 'The Lion hung his head and admitted, “It is true.”'),
      line('他[ほか]|の|動[どう]物[ぶつ]|は|ほえ声[ごえ]|から|逃[に]げる|が#but|、|自[じ]分[ぶん]|に|は|勇[ゆう]気[き]|が|ない|と|言[い]った|。', 'He said that other animals fled from his roar, but he had no courage.'),
    ],
    [
      line('オズ|から|勇[ゆう]気[き]|を|もらえるなら|一[いっ]緒[しょ]に|行[い]きたい|と|申[もう]し出[で]た|。', 'He offered to come if Oz might give him courage.'),
      line('こうして|一[いっ]行[こう]|は|四[よ]人[にん]|と|一[いっ]匹[ぴき]|になった|。', 'And so the party became four travellers and one dog.'),
      line('カカシ|は|正[ただ]しい|道[みち]|を|見[み]分[わ]け|、|ブリキの木[き]こり|は|斧[おの]|で|枝[えだ]|を|払[はら]った|。', 'The Scarecrow picked out the road, and the Tin Woodman cleared branches with his axe.'),
      line('ライオン|は|後[うし]ろ|を|歩[ある]き|、|皆[みな]|を|守[まも]った|。', 'The Lion walked behind and guarded everyone.'),
      line('ドロシー|と|トト|は|真[ま]ん中[なか]|を|歩[ある]いた|。', 'Dorothy and Toto walked in the middle.'),
      line('エメラルドの都[みやこ]|は|まだ|遠[とお]かった|。', 'The Emerald City was still far away.'),
      line('それでも|一[いっ]行[こう]|は|黄[き]色[いろ]い|レンガ|を|一[ひと]つずつ|踏[ふ]みしめた|。', 'Even so, the party stepped firmly on the yellow bricks one by one.'),
      line('家[いえ]|へ|帰[かえ]る|こと|、|脳[のう]|、|心[しん]臓[ぞう]|、|勇[ゆう]気[き]|という|四[よっ]つ|の|願[ねが]い|が|、|皆[みな]|を|同[おな]じ|道[みち]|に|結[むす]びつけていた|。', 'Four wishes—a way home, a brain, a heart and courage—bound them to the same road.'),
    ],
  ],
});

export const STORY_SOURCES = [alice, wizardOfOz];
