"""Build src/stroke-data.js from KanjiVG SVGs.

Extracts, per character, the ordered list of stroke path outlines (SVG path
`d` strings, one per stroke, in writing order — that ordering is exactly what
KanjiVG's file format encodes and is the entire reason to use it rather than
draw stroke diagrams by hand) plus the source viewBox. Stroke *numbers* are
not extracted here: the app derives a stroke's start point at render time via
the browser's own SVG geometry (`path.getPointAtLength(0)`), which is more
robust than parsing the number labels' text-transform coordinates out of the
SVG and keeps this script simpler.

Keyed by single character, never by a multi-character string — a yōon
compound like きゃ is two lookups (き, then ゃ) composed by the app, not one.
Both halves have their own KanjiVG entry, so nothing needs mapping to a
full-size substitute.

Only the exact characters this app teaches are included (kana + the 1026
kyoiku kanji already in src/kanji-data.js), not KanjiVG's full ~6,700-glyph
set, the same scoping rule build_kanji_data.py applies to KANJIDIC/JMdict.

Source data (CC BY-SA 3.0, KanjiVG by Ulrich Apel, http://kanjivg.tagaini.net)
is downloaded by fetch_kanjivg.sh into tools/data_src/kanjivg/ and is NOT
committed — this script is meant to be re-run rather than the ~6,700 SVG
files kept in git.

Usage:
    python3 tools/build_stroke_data.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
KANJIVG_DIR = ROOT / "tools" / "data_src" / "kanjivg" / "kanji"
KANJI_DATA = ROOT / "src" / "kanji-data.js"
OUT = ROOT / "src" / "stroke-data.js"

# Mirrors the tables in src/kana.js. Kept independent rather than imported —
# this is a Python build script and kana.js is an ES module — the same
# arrangement build_kanji_data.py already has with kanji.js.
HIRAGANA_ROWS = [
    'あいうえお', 'かきくけこ', 'さしすせそ', 'たちつてと', 'なにぬねの',
    'はひふへほ', 'まみむめも', 'やゆよ', 'らりるれろ', 'わをん',
    'がぎぐげご', 'ざじずぜぞ', 'だぢづでど', 'ばびぶべぼ', 'ぱぴぷぺぽ',
]
# Small kana used only as the second half of a yōon compound (きゃ, etc.).
SMALL_HIRAGANA = 'ゃゅょ'


def to_katakana(hira_char):
    # Hiragana and katakana occupy parallel Unicode blocks at a fixed offset
    # for every character this app uses (kana.js relies on wanakana for this
    # at runtime; this script only needs the single-character shift).
    return chr(ord(hira_char) + 0x60)


def characters_to_extract():
    hiragana = set(''.join(HIRAGANA_ROWS)) | set(SMALL_HIRAGANA)
    katakana = {to_katakana(c) for c in hiragana}

    kanji_text = KANJI_DATA.read_text(encoding="utf-8")
    kanji_data = json.loads(re.search(r'= (\{.*\});', kanji_text, re.S).group(1))
    kanji = {e["kanji"] for grade in kanji_data.values() for e in grade}

    return sorted(hiragana | katakana | kanji)


def parse_svg(path):
    text = path.read_text(encoding="utf-8")
    view_box = re.search(r'<svg[^>]*\bviewBox="([^"]+)"', text)
    # Order matters and is exactly document order — KanjiVG numbers its path
    # ids ...-s1, -s2, -s3 in writing sequence, which is also the sequence
    # they appear in the file.
    strokes = re.findall(r'<path\b[^>]*\bd="([^"]+)"', text)
    if not view_box or not strokes:
        return None
    return {"viewBox": view_box.group(1), "strokes": strokes}


def main():
    if not KANJIVG_DIR.exists():
        raise SystemExit(
            f"Missing source data. Run tools/fetch_kanjivg.sh first (expects {KANJIVG_DIR})."
        )

    characters = characters_to_extract()
    print(f"looking up {len(characters)} characters")

    out = {}
    missing = []
    for ch in characters:
        svg_path = KANJIVG_DIR / f"{ord(ch):05x}.svg"
        if not svg_path.exists():
            missing.append(ch)
            continue
        parsed = parse_svg(svg_path)
        if parsed is None:
            missing.append(ch)
            continue
        out[ch] = parsed

    if missing:
        print(f"  warning: no stroke data for {len(missing)} character(s): {''.join(missing)}")
    stroke_counts = [len(v["strokes"]) for v in out.values()]
    print(f"found {len(out)} characters, {sum(stroke_counts)} strokes total "
          f"(avg {sum(stroke_counts) / len(out):.1f} per character)")

    js = [
        "// Generated by tools/build_stroke_data.py — do not hand-edit.",
        "// Source: KanjiVG (c) Ulrich Apel, CC BY-SA 3.0 — http://kanjivg.tagaini.net",
        "",
        "export const STROKES = " + json.dumps(out, ensure_ascii=False, separators=(",", ":")) + ";",
        "",
    ]
    OUT.write_text("\n".join(js), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
