"""Build src/data/stroke-kana.js and src/data/stroke-grade-*.js from KanjiVG
SVGs.

Extracts, per character, the ordered list of stroke path outlines (SVG path
`d` strings, one per stroke, in writing order — that ordering is exactly what
KanjiVG's file format encodes and is the entire reason to use it rather than
draw stroke diagrams by hand) plus the source viewBox. Stroke *numbers* are
not extracted here: the app derives a stroke's start point at render time via
the browser's own SVG geometry (`path.getPointAtLength(0)`), which is more
robust than parsing the number labels' text-transform coordinates out of the
SVG and keeps this script simpler.

Keyed by single character, never by a multi-character string — a yōon
compound like きゃ is two lookups (き, then ゃ) composed by the app, not one.
Both halves have their own KanjiVG entry, so nothing needs mapping to a
full-size substitute.

Split the same way build_kanji_data.py splits kanji-data: kana strokes (used
on every screen that can show writing practice, kana or kanji) go in one
always-loaded `stroke-kana.js`; each grade's kanji strokes go in their own
`stroke-grade-<unit>.js`, loaded lazily alongside that grade's kanji data —
see kanji-expansion-plan.md §4. Only the exact characters this app teaches
are included, not KanjiVG's full ~6,700-glyph set, the same scoping rule
build_kanji_data.py applies to KANJIDIC/JMdict.

Source data (CC BY-SA 3.0, KanjiVG by Ulrich Apel, http://kanjivg.tagaini.net)
is downloaded by fetch_kanjivg.sh into tools/data_src/kanjivg/ and is NOT
committed — this script is meant to be re-run rather than the ~6,700 SVG
files kept in git.

Usage:
    python3 tools/build_stroke_data.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
KANJIVG_DIR = ROOT / "tools" / "data_src" / "kanjivg" / "kanji"
MANIFEST = ROOT / "src" / "data" / "kanji-manifest.js"
DATA_DIR = ROOT / "src" / "data"

# Mirrors the tables in src/kana.js. Kept independent rather than imported —
# this is a Python build script and kana.js is an ES module — the same
# arrangement build_kanji_data.py already has with kanji.js.
HIRAGANA_ROWS = [
    'あいうえお', 'かきくけこ', 'さしすせそ', 'たちつてと', 'なにぬねの',
    'はひふへほ', 'まみむめも', 'やゆよ', 'らりるれろ', 'わをん',
    'がぎぐげご', 'ざじずぜぞ', 'だぢづでど', 'ばびぶべぼ', 'ぱぴぷぺぽ',
]
# Small kana used only as the second half of a yōon compound (きゃ, etc.).
SMALL_HIRAGANA = 'ゃゅょ'


def to_katakana(hira_char):
    # Hiragana and katakana occupy parallel Unicode blocks at a fixed offset
    # for every character this app uses (kana.js relies on wanakana for this
    # at runtime; this script only needs the single-character shift).
    return chr(ord(hira_char) + 0x60)


def kana_characters():
    hiragana = set(''.join(HIRAGANA_ROWS)) | set(SMALL_HIRAGANA)
    katakana = {to_katakana(c) for c in hiragana}
    return hiragana | katakana


def kanji_units():
    """{unit: [chars...]} from the manifest build_kanji_data.py just wrote —
    same units, same order, so each grade's stroke chunk lines up with its
    kanji-data chunk."""
    manifest_text = MANIFEST.read_text(encoding="utf-8")
    return json.loads(re.search(r'KANJI_UNITS = (\{.*?\});', manifest_text, re.S).group(1))


def parse_svg(path):
    text = path.read_text(encoding="utf-8")
    view_box = re.search(r'<svg[^>]*\bviewBox="([^"]+)"', text)
    # Order matters and is exactly document order — KanjiVG numbers its path
    # ids ...-s1, -s2, -s3 in writing sequence, which is also the sequence
    # they appear in the file.
    strokes = re.findall(r'<path\b[^>]*\bd="([^"]+)"', text)
    if not view_box or not strokes:
        return None
    return {"viewBox": view_box.group(1), "strokes": strokes}


def lookup(characters, missing):
    out = {}
    for ch in sorted(characters):
        svg_path = KANJIVG_DIR / f"{ord(ch):05x}.svg"
        parsed = parse_svg(svg_path) if svg_path.exists() else None
        if parsed is None:
            missing.append(ch)
            continue
        out[ch] = parsed
    return out


def write_chunk(path, header, data):
    js = header + [
        "export const STROKES = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";",
        "",
    ]
    path.write_text("\n".join(js), encoding="utf-8")
    print(f"wrote {path} ({path.stat().st_size} bytes)")


def main():
    if not KANJIVG_DIR.exists():
        raise SystemExit(
            f"Missing source data. Run tools/fetch_kanjivg.sh first (expects {KANJIVG_DIR})."
        )
    if not MANIFEST.exists():
        raise SystemExit(f"Missing {MANIFEST}. Run tools/build_kanji_data.py first.")

    header = [
        "// Generated by tools/build_stroke_data.py — do not hand-edit.",
        "// Source: KanjiVG (c) Ulrich Apel, CC BY-SA 3.0 — http://kanjivg.tagaini.net",
        "",
    ]
    missing = []

    kana = kana_characters()
    print(f"looking up {len(kana)} kana characters")
    kana_out = lookup(kana, missing)
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    write_chunk(DATA_DIR / "stroke-kana.js", header, kana_out)

    units = kanji_units()
    total_found = len(kana_out)
    total_strokes = sum(len(v["strokes"]) for v in kana_out.values())
    for unit, chars in units.items():
        unit_out = lookup(set(chars), missing)
        write_chunk(DATA_DIR / f"stroke-grade-{unit}.js", header, unit_out)
        total_found += len(unit_out)
        total_strokes += sum(len(v["strokes"]) for v in unit_out.values())

    if missing:
        print(f"  warning: no stroke data for {len(missing)} character(s): {''.join(sorted(set(missing)))}")
    print(f"found {total_found} characters, {total_strokes} strokes total "
          f"(avg {total_strokes / total_found:.1f} per character)")


if __name__ == "__main__":
    main()
