// Generated by tools/build_kanji_data.py — do not hand-edit.
// Source: KANJIDIC2 and JMdict (c) EDRDG, CC BY-SA 4.0.
// https://www.edrdg.org/wiki/index.php/KANJIDIC_Project

export const KANJI_BY_GRADE = {
  "1": [
    {
      "kanji": "一",
      "on": [
        "イチ",
        "イツ"
      ],
      "kun": [
        "ひと-",
        "ひと.つ"
      ],
      "meanings": [
        "one",
        "one radical (no.1)"
      ],
      "words": [
        {
          "kanji": "一",
          "kana": "いち",
          "en": "one"
        },
        {
          "kanji": "一",
          "kana": "ひと",
          "en": "one"
        },
        {
          "kanji": "一つ",
          "kana": "ひとつ",
          "en": "one"
        },
        {
          "kanji": "一に",
          "kana": "いつに",
          "en": "solely"
        }
      ]
    },
    {
      "kanji": "七",
      "on": [
        "シチ"
      ],
      "kun": [
        "なな",
        "なな.つ",
        "なの"
      ],
      "meanings": [
        "seven"
      ],
      "words": [
        {
          "kanji": "七",
          "kana": "しち",
          "en": "seven"
        },
        {
          "kanji": "七つ",
          "kana": "ななつ",
          "en": "seven"
        },
        {
          "kanji": "七草",
          "kana": "ななくさ",
          "en": "the seven spring flowers"
        },
        {
          "kanji": "七夕",
          "kana": "たなばた",
          "en": "Star Festival (held in July or August)"
        }
      ]
    },
    {
      "kanji": "三",
      "on": [
        "サン",
        "ゾウ"
      ],
      "kun": [
        "み",
        "み.つ",
        "みっ.つ"
      ],
      "meanings": [
        "three"
      ],
      "words": [
        {
          "kanji": "三",
          "kana": "さん",
          "en": "three"
        },
        {
          "kanji": "三つ",
          "kana": "みっつ",
          "en": "three"
        },
        {
          "kanji": "二三",
          "kana": "にさん",
          "en": "two or three"
        },
        {
          "kanji": "三校",
          "kana": "さんこう",
          "en": "third proof"
        }
      ]
    },
    {
      "kanji": "上",
      "on": [
        "ジョウ",
        "ショウ",
        "シャン"
      ],
      "kun": [
        "うえ",
        "-うえ",
        "うわ-",
        "かみ",
        "あ.げる",
        "-あ.げる",
        "あ.がる",
        "-あ.がる",
        "あ.がり",
        "-あ.がり",
        "のぼ.る",
        "のぼ.り",
        "のぼ.せる",
        "のぼ.す",
        "たてまつ.る"
      ],
      "meanings": [
        "above",
        "up"
      ],
      "words": [
        {
          "kanji": "上",
          "kana": "うえ",
          "en": "above"
        },
        {
          "kanji": "上",
          "kana": "かみ",
          "en": "upper reaches (of a river)"
        },
        {
          "kanji": "上げ",
          "kana": "あげ",
          "en": "tuck (e.g. in a dress)"
        },
        {
          "kanji": "上手い",
          "kana": "うまい",
          "en": "skillful"
        }
      ]
    },
    {
      "kanji": "下",
      "on": [
        "カ",
        "ゲ"
      ],
      "kun": [
        "した",
        "しも",
        "もと",
        "さ.げる",
        "さ.がる",
        "くだ.る",
        "くだ.り",
        "くだ.す",
        "-くだ.す",
        "くだ.さる",
        "お.ろす",
        "お.りる"
      ],
      "meanings": [
        "below",
        "down",
        "descend",
        "give"
      ],
      "words": [
        {
          "kanji": "下",
          "kana": "した",
          "en": "below"
        },
        {
          "kanji": "下手",
          "kana": "へた",
          "en": "unskillful"
        },
        {
          "kanji": "下",
          "kana": "もと",
          "en": "under (guidance, supervision, rules, the law, etc.)"
        },
        {
          "kanji": "下がる",
          "kana": "さがる",
          "en": "to come down"
        }
      ]
    },
    {
      "kanji": "中",
      "on": [
        "チュウ"
      ],
      "kun": [
        "なか",
        "うち",
        "あた.る"
      ],
      "meanings": [
        "in",
        "inside",
        "middle",
        "mean"
      ],
      "words": [
        {
          "kanji": "中",
          "kana": "なか",
          "en": "inside"
        },
        {
          "kanji": "中",
          "kana": "ちゅう",
          "en": "medium (size)"
        },
        {
          "kanji": "中",
          "kana": "じゅう",
          "en": "(all) through (e.g. the night)"
        },
        {
          "kanji": "雨中",
          "kana": "うちゅう",
          "en": "in the rain"
        }
      ]
    },
    {
      "kanji": "九",
      "on": [
        "キュウ",
        "ク"
      ],
      "kun": [
        "ここの",
        "ここの.つ"
      ],
      "meanings": [
        "nine"
      ],
      "words": [
        {
          "kanji": "九九",
          "kana": "くく",
          "en": "multiplication table"
        },
        {
          "kanji": "九",
          "kana": "きゅう",
          "en": "nine"
        },
        {
          "kanji": "九つ",
          "kana": "ここのつ",
          "en": "nine"
        },
        {
          "kanji": "十九",
          "kana": "じゅうきゅう",
          "en": "nineteen"
        }
      ]
    },
    {
      "kanji": "二",
      "on": [
        "ニ",
        "ジ"
      ],
      "kun": [
        "ふた",
        "ふた.つ",
        "ふたたび"
      ],
      "meanings": [
        "two",
        "two radical (no. 7)"
      ],
      "words": [
        {
          "kanji": "二",
          "kana": "に",
          "en": "two"
        },
        {
          "kanji": "二つ",
          "kana": "ふたつ",
          "en": "two"
        },
        {
          "kanji": "二三",
          "kana": "にさん",
          "en": "two or three"
        },
        {
          "kanji": "二手",
          "kana": "ふたて",
          "en": "two groups"
        }
      ]
    },
    {
      "kanji": "五",
      "on": [
        "ゴ"
      ],
      "kun": [
        "いつ",
        "いつ.つ"
      ],
      "meanings": [
        "five"
      ],
      "words": [
        {
          "kanji": "五",
          "kana": "ご",
          "en": "five"
        },
        {
          "kanji": "五つ",
          "kana": "いつつ",
          "en": "five"
        },
        {
          "kanji": "五目",
          "kana": "ごもく",
          "en": "mixture of ingredients (originally five)"
        },
        {
          "kanji": "十五",
          "kana": "じゅうご",
          "en": "fifteen"
        }
      ]
    },
    {
      "kanji": "人",
      "on": [
        "ジン",
        "ニン"
      ],
      "kun": [
        "ひと",
        "-り",
        "-と"
      ],
      "meanings": [
        "person"
      ],
      "words": [
        {
          "kanji": "人",
          "kana": "じん",
          "en": "-ian (e.g. Italian)"
        },
        {
          "kanji": "人",
          "kana": "ひと",
          "en": "person"
        },
        {
          "kanji": "人",
          "kana": "にん",
          "en": "counter for people"
        },
        {
          "kanji": "人気",
          "kana": "にんき",
          "en": "popularity"
        }
      ]
    },
    {
      "kanji": "休",
      "on": [
        "キュウ"
      ],
      "kun": [
        "やす.む",
        "やす.まる",
        "やす.める"
      ],
      "meanings": [
        "rest",
        "day off",
        "retire",
        "sleep"
      ],
      "words": [
        {
          "kanji": "休み",
          "kana": "やすみ",
          "en": "rest"
        },
        {
          "kanji": "休む",
          "kana": "やすむ",
          "en": "to be absent"
        },
        {
          "kanji": "休まる",
          "kana": "やすまる",
          "en": "to be rested"
        },
        {
          "kanji": "休める",
          "kana": "やすめる",
          "en": "to rest"
        }
      ]
    },
    {
      "kanji": "先",
      "on": [
        "セン"
      ],
      "kun": [
        "さき",
        "ま.ず"
      ],
      "meanings": [
        "before",
        "ahead",
        "previous",
        "future"
      ],
      "words": [
        {
          "kanji": "先",
          "kana": "さき",
          "en": "point"
        },
        {
          "kanji": "先ず",
          "kana": "まず",
          "en": "first (of all)"
        },
        {
          "kanji": "先",
          "kana": "さっき",
          "en": "a short while ago"
        },
        {
          "kanji": "手先",
          "kana": "てさき",
          "en": "fingers"
        }
      ]
    },
    {
      "kanji": "入",
      "on": [
        "ニュウ",
        "ジュ"
      ],
      "kun": [
        "い.る",
        "-い.る",
        "-い.り",
        "い.れる",
        "-い.れ",
        "はい.る"
      ],
      "meanings": [
        "enter",
        "insert"
      ],
      "words": [
        {
          "kanji": "入り",
          "kana": "いり",
          "en": "entering"
        },
        {
          "kanji": "入る",
          "kana": "いる",
          "en": "to enter"
        },
        {
          "kanji": "手入れ",
          "kana": "ていれ",
          "en": "care"
        },
        {
          "kanji": "出入り",
          "kana": "でいり",
          "en": "going in and out"
        }
      ]
    },
    {
      "kanji": "八",
      "on": [
        "ハチ",
        "ハツ"
      ],
      "kun": [
        "や",
        "や.つ",
        "やっ.つ",
        "よう"
      ],
      "meanings": [
        "eight",
        "eight radical (no. 12)"
      ],
      "words": [
        {
          "kanji": "八",
          "kana": "はち",
          "en": "eight"
        },
        {
          "kanji": "八つ",
          "kana": "やっつ",
          "en": "eight"
        },
        {
          "kanji": "お八つ",
          "kana": "おやつ",
          "en": "between-meal snack"
        },
        {
          "kanji": "八本",
          "kana": "はちほん",
          "en": "eight (long cylindrical things)"
        }
      ]
    },
    {
      "kanji": "六",
      "on": [
        "ロク",
        "リク"
      ],
      "kun": [
        "む",
        "む.つ",
        "むっ.つ",
        "むい"
      ],
      "meanings": [
        "six"
      ],
      "words": [
        {
          "kanji": "六",
          "kana": "ろく",
          "en": "six"
        },
        {
          "kanji": "六つ",
          "kana": "むっつ",
          "en": "six"
        },
        {
          "kanji": "十六",
          "kana": "じゅうろく",
          "en": "sixteen"
        }
      ]
    },
    {
      "kanji": "円",
      "on": [
        "エン"
      ],
      "kun": [
        "まる.い",
        "まる",
        "まど",
        "まど.か",
        "まろ.やか"
      ],
      "meanings": [
        "circle",
        "yen",
        "round"
      ],
      "words": [
        {
          "kanji": "円",
          "kana": "えん",
          "en": "yen (currency of Japan)"
        },
        {
          "kanji": "一円",
          "kana": "いちえん",
          "en": "one yen"
        },
        {
          "kanji": "１０００円",
          "kana": "せんえん",
          "en": "1000 yen"
        },
        {
          "kanji": "１００円ショップ",
          "kana": "ひゃくえんショップ",
          "en": "hundred-yen store"
        }
      ]
    },
    {
      "kanji": "出",
      "on": [
        "シュツ",
        "スイ"
      ],
      "kun": [
        "で.る",
        "-で",
        "だ.す",
        "-だ.す",
        "い.でる",
        "い.だす"
      ],
      "meanings": [
        "exit",
        "leave",
        "go out",
        "come out"
      ],
      "words": [
        {
          "kanji": "出",
          "kana": "で",
          "en": "coming out"
        },
        {
          "kanji": "出す",
          "kana": "だす",
          "en": "to take out"
        },
        {
          "kanji": "出る",
          "kana": "でる",
          "en": "to leave"
        },
        {
          "kanji": "出し",
          "kana": "だし",
          "en": "dashi"
        }
      ]
    },
    {
      "kanji": "力",
      "on": [
        "リョク",
        "リキ",
        "リイ"
      ],
      "kun": [
        "ちから"
      ],
      "meanings": [
        "power",
        "strength",
        "strong",
        "strain"
      ],
      "words": [
        {
          "kanji": "力",
          "kana": "ちから",
          "en": "force"
        },
        {
          "kanji": "力",
          "kana": "りょく",
          "en": "strength"
        },
        {
          "kanji": "力む",
          "kana": "りきむ",
          "en": "to strain (oneself)"
        },
        {
          "kanji": "火力",
          "kana": "かりょく",
          "en": "heating power"
        }
      ]
    },
    {
      "kanji": "十",
      "on": [
        "ジュウ",
        "ジッ",
        "ジュッ"
      ],
      "kun": [
        "とお",
        "と",
        "そ"
      ],
      "meanings": [
        "ten"
      ],
      "words": [
        {
          "kanji": "十",
          "kana": "じゅう",
          "en": "ten"
        },
        {
          "kanji": "十五",
          "kana": "じゅうご",
          "en": "fifteen"
        },
        {
          "kanji": "十字",
          "kana": "じゅうじ",
          "en": "cross"
        },
        {
          "kanji": "十二",
          "kana": "じゅうに",
          "en": "twelve"
        }
      ]
    },
    {
      "kanji": "千",
      "on": [
        "セン"
      ],
      "kun": [
        "ち"
      ],
      "meanings": [
        "thousand"
      ],
      "words": [
        {
          "kanji": "千",
          "kana": "せん",
          "en": "thousand"
        },
        {
          "kanji": "千草",
          "kana": "ちぐさ",
          "en": "great variety of flowering plants"
        }
      ]
    },
    {
      "kanji": "口",
      "on": [
        "コウ",
        "ク"
      ],
      "kun": [
        "くち"
      ],
      "meanings": [
        "mouth"
      ],
      "words": [
        {
          "kanji": "口",
          "kana": "くち",
          "en": "mouth"
        },
        {
          "kanji": "口火",
          "kana": "くちび",
          "en": "fuse"
        },
        {
          "kanji": "手口",
          "kana": "てぐち",
          "en": "modus operandi"
        },
        {
          "kanji": "出口",
          "kana": "でぐち",
          "en": "exit"
        }
      ]
    },
    {
      "kanji": "右",
      "on": [
        "ウ",
        "ユウ"
      ],
      "kun": [
        "みぎ"
      ],
      "meanings": [
        "right"
      ],
      "words": [
        {
          "kanji": "右",
          "kana": "みぎ",
          "en": "right"
        },
        {
          "kanji": "右手",
          "kana": "みぎて",
          "en": "right hand"
        },
        {
          "kanji": "左右",
          "kana": "さゆう",
          "en": "left and right"
        },
        {
          "kanji": "右下",
          "kana": "みぎした",
          "en": "lower right"
        }
      ]
    },
    {
      "kanji": "名",
      "on": [
        "メイ",
        "ミョウ"
      ],
      "kun": [
        "な",
        "-な"
      ],
      "meanings": [
        "name",
        "noted",
        "distinguished",
        "reputation"
      ],
      "words": [
        {
          "kanji": "名",
          "kana": "な",
          "en": "name"
        },
        {
          "kanji": "あだ名",
          "kana": "あだな",
          "en": "nickname"
        },
        {
          "kanji": "学名",
          "kana": "がくめい",
          "en": "scientific name (of a species)"
        },
        {
          "kanji": "人名",
          "kana": "じんめい",
          "en": "person's name"
        }
      ]
    },
    {
      "kanji": "四",
      "on": [
        "シ"
      ],
      "kun": [
        "よ",
        "よ.つ",
        "よっ.つ",
        "よん"
      ],
      "meanings": [
        "four"
      ],
      "words": [
        {
          "kanji": "四",
          "kana": "し",
          "en": "four"
        },
        {
          "kanji": "四手",
          "kana": "しで",
          "en": "zigzag-shaped paper streamer often used to adorn Shinto-related objects"
        },
        {
          "kanji": "四つ",
          "kana": "よっつ",
          "en": "four"
        },
        {
          "kanji": "四川",
          "kana": "しせん",
          "en": "Sichuan (China)"
        }
      ]
    },
    {
      "kanji": "土",
      "on": [
        "ド",
        "ト"
      ],
      "kun": [
        "つち"
      ],
      "meanings": [
        "soil",
        "earth",
        "ground",
        "Turkey"
      ],
      "words": [
        {
          "kanji": "土",
          "kana": "つち",
          "en": "earth"
        },
        {
          "kanji": "土手",
          "kana": "どて",
          "en": "embankment"
        },
        {
          "kanji": "土人",
          "kana": "どじん",
          "en": "native"
        },
        {
          "kanji": "土石",
          "kana": "どせき",
          "en": "earth and stones"
        }
      ]
    },
    {
      "kanji": "夕",
      "on": [
        "セキ"
      ],
      "kun": [
        "ゆう"
      ],
      "meanings": [
        "evening"
      ],
      "words": [
        {
          "kanji": "夕",
          "kana": "ゆう",
          "en": "evening"
        },
        {
          "kanji": "夕日",
          "kana": "ゆうひ",
          "en": "evening sun"
        },
        {
          "kanji": "夕立",
          "kana": "ゆうだち",
          "en": "(sudden, heavy) shower (on a summer afternoon or evening)"
        },
        {
          "kanji": "七夕",
          "kana": "たなばた",
          "en": "Star Festival (held in July or August)"
        }
      ]
    },
    {
      "kanji": "大",
      "on": [
        "ダイ",
        "タイ"
      ],
      "kun": [
        "おお-",
        "おお.きい",
        "-おお.いに"
      ],
      "meanings": [
        "large",
        "big"
      ],
      "words": [
        {
          "kanji": "大",
          "kana": "おお",
          "en": "large"
        },
        {
          "kanji": "大",
          "kana": "だい",
          "en": "large"
        },
        {
          "kanji": "大火",
          "kana": "たいか",
          "en": "large fire"
        },
        {
          "kanji": "大気",
          "kana": "たいき",
          "en": "atmosphere"
        }
      ]
    },
    {
      "kanji": "天",
      "on": [
        "テン"
      ],
      "kun": [
        "あまつ",
        "あめ",
        "あま-"
      ],
      "meanings": [
        "heavens",
        "sky",
        "imperial"
      ],
      "words": [
        {
          "kanji": "天",
          "kana": "てん",
          "en": "sky"
        },
        {
          "kanji": "雨天",
          "kana": "うてん",
          "en": "rainy weather"
        },
        {
          "kanji": "天下",
          "kana": "てんか",
          "en": "the whole world"
        },
        {
          "kanji": "天気",
          "kana": "てんき",
          "en": "weather"
        }
      ]
    },
    {
      "kanji": "女",
      "on": [
        "ジョ",
        "ニョ",
        "ニョウ"
      ],
      "kun": [
        "おんな",
        "め"
      ],
      "meanings": [
        "woman",
        "female"
      ],
      "words": [
        {
          "kanji": "子女",
          "kana": "しじょ",
          "en": "sons and daughters"
        },
        {
          "kanji": "女",
          "kana": "おんな",
          "en": "woman"
        },
        {
          "kanji": "女子",
          "kana": "じょし",
          "en": "woman"
        },
        {
          "kanji": "王女",
          "kana": "おうじょ",
          "en": "princess"
        }
      ]
    },
    {
      "kanji": "子",
      "on": [
        "シ",
        "ス",
        "ツ"
      ],
      "kun": [
        "こ",
        "-こ",
        "ね"
      ],
      "meanings": [
        "child",
        "sign of the rat",
        "11PM-1AM",
        "first sign of Chinese zodiac"
      ],
      "words": [
        {
          "kanji": "子",
          "kana": "こ",
          "en": "child"
        },
        {
          "kanji": "子",
          "kana": "ね",
          "en": "the Rat (first sign of the Chinese zodiac)"
        },
        {
          "kanji": "王子",
          "kana": "おうじ",
          "en": "prince"
        },
        {
          "kanji": "子音",
          "kana": "しいん",
          "en": "consonant"
        }
      ]
    },
    {
      "kanji": "字",
      "on": [
        "ジ"
      ],
      "kun": [
        "あざ",
        "あざな",
        "-な"
      ],
      "meanings": [
        "character",
        "letter",
        "word",
        "section of village"
      ],
      "words": [
        {
          "kanji": "字",
          "kana": "じ",
          "en": "character (esp. kanji)"
        },
        {
          "kanji": "字",
          "kana": "あざ",
          "en": "section of village"
        },
        {
          "kanji": "文字",
          "kana": "もじ",
          "en": "letter (of an alphabet)"
        },
        {
          "kanji": "一字",
          "kana": "いちじ",
          "en": "(one) letter"
        }
      ]
    },
    {
      "kanji": "学",
      "on": [
        "ガク"
      ],
      "kun": [
        "まな.ぶ"
      ],
      "meanings": [
        "study",
        "learning",
        "science"
      ],
      "words": [
        {
          "kanji": "学",
          "kana": "がく",
          "en": "learning"
        },
        {
          "kanji": "学ぶ",
          "kana": "まなぶ",
          "en": "to learn"
        },
        {
          "kanji": "学び",
          "kana": "まなび",
          "en": "learning"
        },
        {
          "kanji": "学校",
          "kana": "がっこう",
          "en": "school"
        }
      ]
    },
    {
      "kanji": "小",
      "on": [
        "ショウ"
      ],
      "kun": [
        "ちい.さい",
        "こ-",
        "お-",
        "さ-"
      ],
      "meanings": [
        "little",
        "small"
      ],
      "words": [
        {
          "kanji": "小",
          "kana": "こ",
          "en": "small"
        },
        {
          "kanji": "小火",
          "kana": "ボヤ",
          "en": "small fire"
        },
        {
          "kanji": "小手",
          "kana": "こて",
          "en": "forearm"
        },
        {
          "kanji": "小雨",
          "kana": "こさめ",
          "en": "light rain"
        }
      ]
    },
    {
      "kanji": "山",
      "on": [
        "サン",
        "セン"
      ],
      "kun": [
        "やま"
      ],
      "meanings": [
        "mountain"
      ],
      "words": [
        {
          "kanji": "山",
          "kana": "やま",
          "en": "mountain"
        },
        {
          "kanji": "山車",
          "kana": "だし",
          "en": "parade float"
        },
        {
          "kanji": "下山",
          "kana": "げざん",
          "en": "descending a mountain"
        },
        {
          "kanji": "火山",
          "kana": "かざん",
          "en": "volcano"
        }
      ]
    },
    {
      "kanji": "川",
      "on": [
        "セン"
      ],
      "kun": [
        "かわ"
      ],
      "meanings": [
        "stream",
        "river",
        "river or three-stroke river radical (no. 47)"
      ],
      "words": [
        {
          "kanji": "川",
          "kana": "かわ",
          "en": "river"
        },
        {
          "kanji": "四川",
          "kana": "しせん",
          "en": "Sichuan (China)"
        },
        {
          "kanji": "小川",
          "kana": "おがわ",
          "en": "stream"
        },
        {
          "kanji": "山川",
          "kana": "さんせん",
          "en": "mountains and rivers"
        }
      ]
    },
    {
      "kanji": "左",
      "on": [
        "サ",
        "シャ"
      ],
      "kun": [
        "ひだり"
      ],
      "meanings": [
        "left"
      ],
      "words": [
        {
          "kanji": "左",
          "kana": "ひだり",
          "en": "left"
        },
        {
          "kanji": "左右",
          "kana": "さゆう",
          "en": "left and right"
        },
        {
          "kanji": "左手",
          "kana": "ひだりて",
          "en": "left hand"
        },
        {
          "kanji": "左上",
          "kana": "ひだりうえ",
          "en": "upper left"
        }
      ]
    },
    {
      "kanji": "年",
      "on": [
        "ネン"
      ],
      "kun": [
        "とし"
      ],
      "meanings": [
        "year",
        "counter for years"
      ],
      "words": [
        {
          "kanji": "年",
          "kana": "とし",
          "en": "year"
        },
        {
          "kanji": "年",
          "kana": "ねん",
          "en": "year"
        },
        {
          "kanji": "学年",
          "kana": "がくねん",
          "en": "academic year"
        },
        {
          "kanji": "青年",
          "kana": "せいねん",
          "en": "youth"
        }
      ]
    },
    {
      "kanji": "手",
      "on": [
        "シュ",
        "ズ"
      ],
      "kun": [
        "て",
        "て-",
        "-て",
        "た-"
      ],
      "meanings": [
        "hand"
      ],
      "words": [
        {
          "kanji": "手",
          "kana": "て",
          "en": "hand"
        },
        {
          "kanji": "下手",
          "kana": "へた",
          "en": "unskillful"
        },
        {
          "kanji": "土手",
          "kana": "どて",
          "en": "embankment"
        },
        {
          "kanji": "小手",
          "kana": "こて",
          "en": "forearm"
        }
      ]
    },
    {
      "kanji": "文",
      "on": [
        "ブン",
        "モン"
      ],
      "kun": [
        "ふみ",
        "あや"
      ],
      "meanings": [
        "sentence",
        "literature",
        "style",
        "art"
      ],
      "words": [
        {
          "kanji": "文",
          "kana": "ふみ",
          "en": "letter"
        },
        {
          "kanji": "文",
          "kana": "ぶん",
          "en": "sentence"
        },
        {
          "kanji": "文字",
          "kana": "もじ",
          "en": "letter (of an alphabet)"
        },
        {
          "kanji": "一文",
          "kana": "いちもん",
          "en": "tiny amount of money"
        }
      ]
    },
    {
      "kanji": "日",
      "on": [
        "ニチ",
        "ジツ"
      ],
      "kun": [
        "ひ",
        "-び",
        "-か"
      ],
      "meanings": [
        "day",
        "sun",
        "Japan",
        "counter for days"
      ],
      "words": [
        {
          "kanji": "日",
          "kana": "ひ",
          "en": "day"
        },
        {
          "kanji": "日々",
          "kana": "ひび",
          "en": "daily"
        },
        {
          "kanji": "日",
          "kana": "にち",
          "en": "Sunday"
        },
        {
          "kanji": "月日",
          "kana": "つきひ",
          "en": "time"
        }
      ]
    },
    {
      "kanji": "早",
      "on": [
        "ソウ",
        "サッ"
      ],
      "kun": [
        "はや.い",
        "はや",
        "はや-",
        "はや.まる",
        "はや.める",
        "さ-"
      ],
      "meanings": [
        "early",
        "fast"
      ],
      "words": [
        {
          "kanji": "早",
          "kana": "はや",
          "en": "already"
        },
        {
          "kanji": "早く",
          "kana": "はやく",
          "en": "early"
        },
        {
          "kanji": "早い",
          "kana": "はやい",
          "en": "fast"
        },
        {
          "kanji": "早出",
          "kana": "はやで",
          "en": "leaving early (for work)"
        }
      ]
    },
    {
      "kanji": "月",
      "on": [
        "ゲツ",
        "ガツ"
      ],
      "kun": [
        "つき"
      ],
      "meanings": [
        "month",
        "moon"
      ],
      "words": [
        {
          "kanji": "月",
          "kana": "つき",
          "en": "Moon"
        },
        {
          "kanji": "月",
          "kana": "がつ",
          "en": "month (of the year)"
        },
        {
          "kanji": "ヶ月",
          "kana": "かげつ",
          "en": "counter for months"
        },
        {
          "kanji": "９月",
          "kana": "くがつ",
          "en": "September"
        }
      ]
    },
    {
      "kanji": "木",
      "on": [
        "ボク",
        "モク"
      ],
      "kun": [
        "き",
        "こ-"
      ],
      "meanings": [
        "tree",
        "wood"
      ],
      "words": [
        {
          "kanji": "木",
          "kana": "き",
          "en": "tree"
        },
        {
          "kanji": "木々",
          "kana": "きぎ",
          "en": "(many) trees"
        },
        {
          "kanji": "土木",
          "kana": "どぼく",
          "en": "engineering works"
        },
        {
          "kanji": "白木",
          "kana": "しらき",
          "en": "plain wood"
        }
      ]
    },
    {
      "kanji": "本",
      "on": [
        "ホン"
      ],
      "kun": [
        "もと"
      ],
      "meanings": [
        "book",
        "present",
        "main",
        "origin"
      ],
      "words": [
        {
          "kanji": "本",
          "kana": "ほん",
          "en": "book"
        },
        {
          "kanji": "本の",
          "kana": "ほんの",
          "en": "mere"
        },
        {
          "kanji": "見本",
          "kana": "みほん",
          "en": "sample"
        },
        {
          "kanji": "手本",
          "kana": "てほん",
          "en": "model"
        }
      ]
    },
    {
      "kanji": "村",
      "on": [
        "ソン"
      ],
      "kun": [
        "むら"
      ],
      "meanings": [
        "village",
        "town"
      ],
      "words": [
        {
          "kanji": "村",
          "kana": "むら",
          "en": "village"
        },
        {
          "kanji": "村人",
          "kana": "むらびと",
          "en": "villager"
        },
        {
          "kanji": "村立",
          "kana": "そんりつ",
          "en": "established by a village"
        },
        {
          "kanji": "山村",
          "kana": "さんそん",
          "en": "mountain village"
        }
      ]
    },
    {
      "kanji": "林",
      "on": [
        "リン"
      ],
      "kun": [
        "はやし"
      ],
      "meanings": [
        "grove",
        "forest"
      ],
      "words": [
        {
          "kanji": "林",
          "kana": "はやし",
          "en": "wood"
        },
        {
          "kanji": "山林",
          "kana": "さんりん",
          "en": "mountain forest"
        },
        {
          "kanji": "森林",
          "kana": "しんりん",
          "en": "forest"
        },
        {
          "kanji": "竹林",
          "kana": "ちくりん",
          "en": "bamboo thicket"
        }
      ]
    },
    {
      "kanji": "校",
      "on": [
        "コウ",
        "キョウ"
      ],
      "kun": [],
      "meanings": [
        "exam",
        "school",
        "printing",
        "proof"
      ],
      "words": [
        {
          "kanji": "下校",
          "kana": "げこう",
          "en": "leaving school (at the end of the day)"
        },
        {
          "kanji": "学校",
          "kana": "がっこう",
          "en": "school"
        },
        {
          "kanji": "校正",
          "kana": "こうせい",
          "en": "proofreading"
        },
        {
          "kanji": "三校",
          "kana": "さんこう",
          "en": "third proof"
        }
      ]
    },
    {
      "kanji": "森",
      "on": [
        "シン"
      ],
      "kun": [
        "もり"
      ],
      "meanings": [
        "forest",
        "woods"
      ],
      "words": [
        {
          "kanji": "森",
          "kana": "もり",
          "en": "forest"
        },
        {
          "kanji": "森林",
          "kana": "しんりん",
          "en": "forest"
        }
      ]
    },
    {
      "kanji": "正",
      "on": [
        "セイ",
        "ショウ"
      ],
      "kun": [
        "ただ.しい",
        "ただ.す",
        "まさ",
        "まさ.に"
      ],
      "meanings": [
        "correct",
        "justice",
        "righteous",
        "10**40"
      ],
      "words": [
        {
          "kanji": "正",
          "kana": "せい",
          "en": "(logical) true"
        },
        {
          "kanji": "正す",
          "kana": "ただす",
          "en": "to correct"
        },
        {
          "kanji": "正に",
          "kana": "まさに",
          "en": "exactly"
        },
        {
          "kanji": "校正",
          "kana": "こうせい",
          "en": "proofreading"
        }
      ]
    },
    {
      "kanji": "気",
      "on": [
        "キ",
        "ケ"
      ],
      "kun": [
        "いき",
        "き"
      ],
      "meanings": [
        "spirit",
        "mind",
        "air",
        "atmosphere"
      ],
      "words": [
        {
          "kanji": "気",
          "kana": "き",
          "en": "spirit"
        },
        {
          "kanji": "火気",
          "kana": "かき",
          "en": "fire"
        },
        {
          "kanji": "一気",
          "kana": "いっき",
          "en": "one breath"
        },
        {
          "kanji": "火の気",
          "kana": "ひのけ",
          "en": "source of fire"
        }
      ]
    },
    {
      "kanji": "水",
      "on": [
        "スイ"
      ],
      "kun": [
        "みず",
        "みず-"
      ],
      "meanings": [
        "water"
      ],
      "words": [
        {
          "kanji": "水",
          "kana": "みず",
          "en": "water (esp. cool or cold)"
        },
        {
          "kanji": "下水",
          "kana": "げすい",
          "en": "drainage"
        },
        {
          "kanji": "水気",
          "kana": "みずけ",
          "en": "water content"
        },
        {
          "kanji": "水木",
          "kana": "みずき",
          "en": "dogwood (Cornus controversa)"
        }
      ]
    },
    {
      "kanji": "火",
      "on": [
        "カ"
      ],
      "kun": [
        "ひ",
        "-び",
        "ほ-"
      ],
      "meanings": [
        "fire"
      ],
      "words": [
        {
          "kanji": "火",
          "kana": "ひ",
          "en": "fire"
        },
        {
          "kanji": "火気",
          "kana": "かき",
          "en": "fire"
        },
        {
          "kanji": "小火",
          "kana": "ボヤ",
          "en": "small fire"
        },
        {
          "kanji": "下火",
          "kana": "したび",
          "en": "dying down (of a fire)"
        }
      ]
    },
    {
      "kanji": "犬",
      "on": [
        "ケン"
      ],
      "kun": [
        "いぬ",
        "いぬ-"
      ],
      "meanings": [
        "dog"
      ],
      "words": [
        {
          "kanji": "犬",
          "kana": "いぬ",
          "en": "dog (Canis (lupus) familiaris)"
        },
        {
          "kanji": "子犬",
          "kana": "こいぬ",
          "en": "puppy"
        }
      ]
    },
    {
      "kanji": "玉",
      "on": [
        "ギョク"
      ],
      "kun": [
        "たま",
        "たま-",
        "-だま"
      ],
      "meanings": [
        "jewel",
        "ball"
      ],
      "words": [
        {
          "kanji": "玉",
          "kana": "たま",
          "en": "ball"
        },
        {
          "kanji": "目玉",
          "kana": "めだま",
          "en": "eyeball"
        },
        {
          "kanji": "手玉",
          "kana": "てだま",
          "en": "beanbags"
        },
        {
          "kanji": "火の玉",
          "kana": "ひのたま",
          "en": "fireball"
        }
      ]
    },
    {
      "kanji": "王",
      "on": [
        "オウ",
        "-ノウ"
      ],
      "kun": [],
      "meanings": [
        "king",
        "rule",
        "magnate"
      ],
      "words": [
        {
          "kanji": "王",
          "kana": "おう",
          "en": "king"
        },
        {
          "kanji": "王子",
          "kana": "おうじ",
          "en": "prince"
        },
        {
          "kanji": "王手",
          "kana": "おうて",
          "en": "check"
        },
        {
          "kanji": "王女",
          "kana": "おうじょ",
          "en": "princess"
        }
      ]
    },
    {
      "kanji": "生",
      "on": [
        "セイ",
        "ショウ"
      ],
      "kun": [
        "い.きる",
        "い.かす",
        "い.ける",
        "う.まれる",
        "うま.れる",
        "う.まれ",
        "うまれ",
        "う.む",
        "お.う",
        "は.える",
        "は.やす",
        "き",
        "なま",
        "なま-",
        "な.る",
        "な.す",
        "む.す",
        "-う"
      ],
      "meanings": [
        "life",
        "genuine",
        "birth"
      ],
      "words": [
        {
          "kanji": "生",
          "kana": "なま",
          "en": "raw"
        },
        {
          "kanji": "生き",
          "kana": "いき",
          "en": "living"
        },
        {
          "kanji": "生む",
          "kana": "うむ",
          "en": "to give birth"
        },
        {
          "kanji": "生る",
          "kana": "なる",
          "en": "to bear fruit"
        }
      ]
    },
    {
      "kanji": "田",
      "on": [
        "デン"
      ],
      "kun": [
        "た"
      ],
      "meanings": [
        "rice field",
        "rice paddy"
      ],
      "words": [
        {
          "kanji": "田",
          "kana": "た",
          "en": "rice field"
        },
        {
          "kanji": "下田",
          "kana": "げでん",
          "en": "worn-out rice land"
        },
        {
          "kanji": "田んぼ",
          "kana": "たんぼ",
          "en": "rice field"
        },
        {
          "kanji": "青田",
          "kana": "あおた",
          "en": "green paddy"
        }
      ]
    },
    {
      "kanji": "男",
      "on": [
        "ダン",
        "ナン"
      ],
      "kun": [
        "おとこ",
        "お"
      ],
      "meanings": [
        "male"
      ],
      "words": [
        {
          "kanji": "男",
          "kana": "おとこ",
          "en": "man"
        },
        {
          "kanji": "男子",
          "kana": "だんし",
          "en": "boy"
        },
        {
          "kanji": "一男",
          "kana": "いちなん",
          "en": "boy"
        },
        {
          "kanji": "三男",
          "kana": "さんなん",
          "en": "three sons"
        }
      ]
    },
    {
      "kanji": "町",
      "on": [
        "チョウ"
      ],
      "kun": [
        "まち"
      ],
      "meanings": [
        "town",
        "village",
        "block",
        "street"
      ],
      "words": [
        {
          "kanji": "町",
          "kana": "まち",
          "en": "town"
        },
        {
          "kanji": "小町",
          "kana": "こまち",
          "en": "belle"
        },
        {
          "kanji": "下町",
          "kana": "したまち",
          "en": "low-lying part of a city (usu. containing shops, factories, etc.)"
        },
        {
          "kanji": "町中",
          "kana": "まちなか",
          "en": "downtown"
        }
      ]
    },
    {
      "kanji": "白",
      "on": [
        "ハク",
        "ビャク"
      ],
      "kun": [
        "しろ",
        "しら-",
        "しろ.い"
      ],
      "meanings": [
        "white"
      ],
      "words": [
        {
          "kanji": "白",
          "kana": "しろ",
          "en": "white"
        },
        {
          "kanji": "白い",
          "kana": "しろい",
          "en": "white"
        },
        {
          "kanji": "白む",
          "kana": "しらむ",
          "en": "to whiten"
        },
        {
          "kanji": "白子",
          "kana": "しらこ",
          "en": "soft roe"
        }
      ]
    },
    {
      "kanji": "百",
      "on": [
        "ヒャク",
        "ビャク"
      ],
      "kun": [
        "もも"
      ],
      "meanings": [
        "hundred"
      ],
      "words": [
        {
          "kanji": "百",
          "kana": "ひゃく",
          "en": "hundred"
        }
      ]
    },
    {
      "kanji": "目",
      "on": [
        "モク",
        "ボク"
      ],
      "kun": [
        "め",
        "-め",
        "ま-"
      ],
      "meanings": [
        "eye",
        "class",
        "look",
        "insight"
      ],
      "words": [
        {
          "kanji": "目",
          "kana": "め",
          "en": "eye"
        },
        {
          "kanji": "一目",
          "kana": "ひとめ",
          "en": "glance"
        },
        {
          "kanji": "金目",
          "kana": "かねめ",
          "en": "valuable"
        },
        {
          "kanji": "五目",
          "kana": "ごもく",
          "en": "mixture of ingredients (originally five)"
        }
      ]
    },
    {
      "kanji": "石",
      "on": [
        "セキ",
        "シャク",
        "コク"
      ],
      "kun": [
        "いし"
      ],
      "meanings": [
        "stone"
      ],
      "words": [
        {
          "kanji": "石",
          "kana": "いし",
          "en": "stone"
        },
        {
          "kanji": "石",
          "kana": "こく",
          "en": "koku"
        },
        {
          "kanji": "小石",
          "kana": "こいし",
          "en": "pebble"
        },
        {
          "kanji": "土石",
          "kana": "どせき",
          "en": "earth and stones"
        }
      ]
    },
    {
      "kanji": "空",
      "on": [
        "クウ"
      ],
      "kun": [
        "そら",
        "あ.く",
        "あ.き",
        "あ.ける",
        "から",
        "す.く",
        "す.かす",
        "むな.しい"
      ],
      "meanings": [
        "empty",
        "sky",
        "void",
        "vacant"
      ],
      "words": [
        {
          "kanji": "空",
          "kana": "から",
          "en": "emptiness"
        },
        {
          "kanji": "空",
          "kana": "そら",
          "en": "sky"
        },
        {
          "kanji": "空く",
          "kana": "すく",
          "en": "to become less crowded"
        },
        {
          "kanji": "空き",
          "kana": "あき",
          "en": "space"
        }
      ]
    },
    {
      "kanji": "立",
      "on": [
        "リツ",
        "リュウ",
        "リットル"
      ],
      "kun": [
        "た.つ",
        "-た.つ",
        "た.ち-",
        "た.てる",
        "-た.てる",
        "た.て-",
        "たて-",
        "-た.て",
        "-だ.て",
        "-だ.てる"
      ],
      "meanings": [
        "stand up",
        "rise",
        "set up",
        "erect"
      ],
      "words": [
        {
          "kanji": "立ち",
          "kana": "たち",
          "en": "departure"
        },
        {
          "kanji": "立つ",
          "kana": "たつ",
          "en": "to stand (up)"
        },
        {
          "kanji": "手立て",
          "kana": "てだて",
          "en": "means"
        },
        {
          "kanji": "目立つ",
          "kana": "めだつ",
          "en": "to be conspicuous"
        }
      ]
    },
    {
      "kanji": "竹",
      "on": [
        "チク"
      ],
      "kun": [
        "たけ"
      ],
      "meanings": [
        "bamboo"
      ],
      "words": [
        {
          "kanji": "竹",
          "kana": "たけ",
          "en": "bamboo (any grass of subfamily Bambusoideae)"
        },
        {
          "kanji": "竹林",
          "kana": "ちくりん",
          "en": "bamboo thicket"
        },
        {
          "kanji": "青竹",
          "kana": "あおだけ",
          "en": "green bamboo"
        }
      ]
    },
    {
      "kanji": "糸",
      "on": [
        "シ"
      ],
      "kun": [
        "いと"
      ],
      "meanings": [
        "thread"
      ],
      "words": [
        {
          "kanji": "糸",
          "kana": "いと",
          "en": "thread"
        },
        {
          "kanji": "生糸",
          "kana": "きいと",
          "en": "raw silk thread"
        },
        {
          "kanji": "金糸",
          "kana": "きんし",
          "en": "gold thread"
        },
        {
          "kanji": "糸口",
          "kana": "いとぐち",
          "en": "beginning"
        }
      ]
    },
    {
      "kanji": "耳",
      "on": [
        "ジ"
      ],
      "kun": [
        "みみ"
      ],
      "meanings": [
        "ear"
      ],
      "words": [
        {
          "kanji": "耳",
          "kana": "みみ",
          "en": "ear"
        },
        {
          "kanji": "耳目",
          "kana": "じもく",
          "en": "eyes and ears"
        },
        {
          "kanji": "中耳",
          "kana": "ちゅうじ",
          "en": "middle ear"
        },
        {
          "kanji": "耳より",
          "kana": "みみより",
          "en": "welcome (news)"
        }
      ]
    },
    {
      "kanji": "花",
      "on": [
        "カ",
        "ケ"
      ],
      "kun": [
        "はな"
      ],
      "meanings": [
        "flower"
      ],
      "words": [
        {
          "kanji": "花",
          "kana": "はな",
          "en": "flower"
        },
        {
          "kanji": "火花",
          "kana": "ひばな",
          "en": "spark"
        },
        {
          "kanji": "花火",
          "kana": "はなび",
          "en": "fireworks"
        },
        {
          "kanji": "花見",
          "kana": "はなみ",
          "en": "cherry blossom viewing"
        }
      ]
    },
    {
      "kanji": "草",
      "on": [
        "ソウ"
      ],
      "kun": [
        "くさ",
        "くさ-",
        "-ぐさ"
      ],
      "meanings": [
        "grass",
        "weeds",
        "herbs",
        "pasture"
      ],
      "words": [
        {
          "kanji": "草",
          "kana": "くさ",
          "en": "grass"
        },
        {
          "kanji": "千草",
          "kana": "ちぐさ",
          "en": "great variety of flowering plants"
        },
        {
          "kanji": "草木",
          "kana": "くさき",
          "en": "plants"
        },
        {
          "kanji": "下草",
          "kana": "したくさ",
          "en": "undergrowth"
        }
      ]
    },
    {
      "kanji": "虫",
      "on": [
        "チュウ",
        "キ"
      ],
      "kun": [
        "むし"
      ],
      "meanings": [
        "insect",
        "bug",
        "temper"
      ],
      "words": [
        {
          "kanji": "虫",
          "kana": "むし",
          "en": "insect"
        },
        {
          "kanji": "水虫",
          "kana": "みずむし",
          "en": "athlete's foot"
        }
      ]
    },
    {
      "kanji": "見",
      "on": [
        "ケン"
      ],
      "kun": [
        "み.る",
        "み.える",
        "み.せる"
      ],
      "meanings": [
        "see",
        "hopes",
        "chances",
        "idea"
      ],
      "words": [
        {
          "kanji": "見る",
          "kana": "みる",
          "en": "to see"
        },
        {
          "kanji": "下見",
          "kana": "したみ",
          "en": "preliminary inspection"
        },
        {
          "kanji": "花見",
          "kana": "はなみ",
          "en": "cherry blossom viewing"
        },
        {
          "kanji": "月見",
          "kana": "つきみ",
          "en": "moon viewing (esp. during the eight month of the lunar calendar)"
        }
      ]
    },
    {
      "kanji": "貝",
      "on": [
        "バイ"
      ],
      "kun": [
        "かい"
      ],
      "meanings": [
        "shellfish"
      ],
      "words": [
        {
          "kanji": "貝",
          "kana": "かい",
          "en": "shellfish"
        }
      ]
    },
    {
      "kanji": "赤",
      "on": [
        "セキ",
        "シャク"
      ],
      "kun": [
        "あか",
        "あか-",
        "あか.い",
        "あか.らむ",
        "あか.らめる"
      ],
      "meanings": [
        "red"
      ],
      "words": [
        {
          "kanji": "赤",
          "kana": "あか",
          "en": "red"
        },
        {
          "kanji": "赤い",
          "kana": "あかい",
          "en": "red"
        },
        {
          "kanji": "赤字",
          "kana": "あかじ",
          "en": "(being in) the red"
        },
        {
          "kanji": "赤子",
          "kana": "あかご",
          "en": "baby"
        }
      ]
    },
    {
      "kanji": "足",
      "on": [
        "ソク"
      ],
      "kun": [
        "あし",
        "た.りる",
        "た.る",
        "た.す"
      ],
      "meanings": [
        "leg",
        "foot",
        "be sufficient",
        "counter for pairs of footwear"
      ],
      "words": [
        {
          "kanji": "足",
          "kana": "あし",
          "en": "foot"
        },
        {
          "kanji": "足す",
          "kana": "たす",
          "en": "to add (numbers)"
        },
        {
          "kanji": "足る",
          "kana": "たる",
          "en": "to be sufficient"
        },
        {
          "kanji": "手足",
          "kana": "てあし",
          "en": "hands and feet"
        }
      ]
    },
    {
      "kanji": "車",
      "on": [
        "シャ"
      ],
      "kun": [
        "くるま"
      ],
      "meanings": [
        "car"
      ],
      "words": [
        {
          "kanji": "山車",
          "kana": "だし",
          "en": "parade float"
        },
        {
          "kanji": "下車",
          "kana": "げしゃ",
          "en": "alighting (from a train, bus, etc.)"
        },
        {
          "kanji": "車",
          "kana": "くるま",
          "en": "car"
        },
        {
          "kanji": "空車",
          "kana": "くうしゃ",
          "en": "empty conveyance"
        }
      ]
    },
    {
      "kanji": "金",
      "on": [
        "キン",
        "コン",
        "ゴン"
      ],
      "kun": [
        "かね",
        "かな-",
        "-がね"
      ],
      "meanings": [
        "gold"
      ],
      "words": [
        {
          "kanji": "金",
          "kana": "かね",
          "en": "money"
        },
        {
          "kanji": "金",
          "kana": "きん",
          "en": "gold (metal)"
        },
        {
          "kanji": "お金",
          "kana": "おかね",
          "en": "money"
        },
        {
          "kanji": "金目",
          "kana": "かねめ",
          "en": "valuable"
        }
      ]
    },
    {
      "kanji": "雨",
      "on": [
        "ウ"
      ],
      "kun": [
        "あめ",
        "あま-",
        "-さめ"
      ],
      "meanings": [
        "rain"
      ],
      "words": [
        {
          "kanji": "雨",
          "kana": "あめ",
          "en": "rain"
        },
        {
          "kanji": "雨天",
          "kana": "うてん",
          "en": "rainy weather"
        },
        {
          "kanji": "小雨",
          "kana": "こさめ",
          "en": "light rain"
        },
        {
          "kanji": "雨中",
          "kana": "うちゅう",
          "en": "in the rain"
        }
      ]
    },
    {
      "kanji": "青",
      "on": [
        "セイ",
        "ショウ"
      ],
      "kun": [
        "あお",
        "あお-",
        "あお.い"
      ],
      "meanings": [
        "blue",
        "green"
      ],
      "words": [
        {
          "kanji": "青",
          "kana": "あお",
          "en": "blue"
        },
        {
          "kanji": "青い",
          "kana": "あおい",
          "en": "blue"
        },
        {
          "kanji": "青木",
          "kana": "あおき",
          "en": "Japanese laurel (Aucuba japonica)"
        },
        {
          "kanji": "青田",
          "kana": "あおた",
          "en": "green paddy"
        }
      ]
    },
    {
      "kanji": "音",
      "on": [
        "オン",
        "イン",
        "-ノン"
      ],
      "kun": [
        "おと",
        "ね"
      ],
      "meanings": [
        "sound",
        "noise"
      ],
      "words": [
        {
          "kanji": "音",
          "kana": "ね",
          "en": "sound"
        },
        {
          "kanji": "音",
          "kana": "おと",
          "en": "sound"
        },
        {
          "kanji": "音",
          "kana": "おん",
          "en": "sound"
        },
        {
          "kanji": "子音",
          "kana": "しいん",
          "en": "consonant"
        }
      ]
    }
  ]
};

